# -*- coding: utf-8 -*-
"""
© Roberto Spíndola Barrón, 2026.
Todos los derechos reservados.

Sistema estructural de análisis lingüístico Náhuatl ↔ Español.
Módulo: [ADVERBS_SP_NTL]
Versión: v1.0
Fecha: [23-05-2026]

Prohibida la reproducción, redistribución, extracción estructural,
ingeniería inversa, entrenamiento de modelos de inteligencia artificial
o reutilización no autorizada.
"""
ADVERBS_SP_NTL = {
	"abajo":'tzintlan',
	"abandonadamente":'kauakan',
	"abarcadamente":'pachokan',
	"abiertamente":'tlapokan',
	"abominadamente": ['amokualteilchiukan', 'amokualteilchiuakan'],
	"abrazadamente": ['pachoakan', 'pachoatikan', 'pachokan'],
	"abrigadamente":'ehekatzaukan',
	"abundadamente":'achpanikan',
	"abundativamente":'achpaniliztikan',
	"abundosamente":'achpanikan',
	"abusadamente":'achpanikan',
	"abusivamente":'achpanitikan',
	"acaloradamente":'tonakan',
	"acaparadamente":'pachokan',
	"acaso":'koch',
	"aceleradamente":'olyokan',
	"aceptadamente":'zeliakan',
	"acertadamente": ['xihiakan', 'xihmakakan'],
	"achicadamente": ['tzinuakan', 'tzinuatikan'],
	"aclaradamente": ['chipauakan', 'chipauatikan'],
	"aclarosamente":'chipauatikan',
	"acomodadamente":'nepanpatikan',
	"acomodatoriamente":'nepanpatikan',
	"acondicionadamente":'yektlaliakan',
	"acongojadamente": ['achikopalakan', 'achikopalatikan'],
	"acontecidamente":'panoyokan',
	"acostumbradamente": ['matichiuakan', 'matichiuatikan'],
	"activadamente":'tlaueliakan',
	"activamente":'chiuakan',
	"activosamente":'chiuakan',
	"actualizádamente":'axkanchiuayokan',
	"actualmente": ['axpan', 'axkan'],
	"acumuladamente": ['achpanikan', 'uaniakan'],
	"acumulativamente":'achpaniliztikan',
	"acumulatoriamente":'achpaniliztikan',
	"acumulivamente":'achpanikan',
	"acuosamente": ['atikan', 'ayokan'],
	"acuáticamente":'atikan',
	"adaptadamente": ['matichiuakan', 'matichiuatikan'],
	"adecuadamente":'kualtikan',
	"adelante": ['ixkan', 'ixko', 'ixman', 'ixpan'],
	"además":'achiokze',
	"adentradamente": ['itekiakan', 'kalakiakan', 'ni itakan'],
	"adentramente":'itekiakan',
	"adentrativamente":'itekializtikan',
	"adentro":'itik',
	"adentro":'itek',
	"adentros":'itik',
	"adentros":'itek',
	"adeudadamente": ['kiliakan', 'kilikan', 'uihkilikan', 'uihkilitikan'],
	"adecuadamente":'kualchiuatikan',
	"adicionadamente":'iuanyokan',
	"adicionalmente":'achtlanapan',
	"administradamente":'nepanpatikan',
	"admitidamente":'zeliakan',
	"adquiridamente":'tlaniakan',
	"adulteradamente": ['akauikan', 'akauiliztikan', 'makauikan'],
	"advertidamente":'matizmakakan',
	"afirmadamente": ['kematiakan', 'kemihtokan', 'kemiliakan', 'kemilikan', 'neltokaihtokan'],
	"afirmatoriamente":'neltokaihtokan',
	"aflojádamente":'auikan',
	"afuera":'kiauak',
	"fuera":'kiauak',
	"agarradamente":'kuikan',
	"agradable":'kualtzin',
	"agradablemente":'kualtzin',
	"agrandadamente": ['ixkaltiakan', 'ixpankuikan', 'izkaliakan', 'izkaltiakan', 'ueyikchiuakan'],
	"agraviadamente": ['amokualtlahtokan', 'ihtlakokan'],
	"agriadamente":'xokokan',
	"aguadámente":'ayotiyokan',
	"aguantadamente":'chikoukan',
	"aguantamente":'chikoukan',
	"aguádamente":'auakan',
	"ahogadamente": ['amikuyokan', 'amikyotikan'],
	"ahora":'axkan',
	"airosamente":'ehekatikpan',
	"ajustadamente": ['mekajustikan', 'melakiakan'],
	"alborotadamente":'etzonitikan',
	"alcanzante":'azihtokan',
	"alcanzantemente":'azihtokan',
	"alcanzámente":'aziyokan',
	"alejadamente": ['tlauehkakan', 'uehkakan'],
	"alguienmente":'tekan',
	"alimentadamente":'tlakuakan',
	"allá":'ne',
	"allá":'ompa',
	"allí":'ompa',
	"altamente":'uehkapa',
	"alteradamente":'makaukan',
	"amable":'ikniuhtikan',
	"amablemente":'ikniuhtikan',
	"amables":'ikniuhtikan',
	"amadamente":'tlazohtiakan',
	"amenazadamente":'ouiyoihtokan',
	"aminoradamente": ['tziniakan', 'tzinuakan', 'tzinuatikan', 'tzitziniakan', 'tzitziniatikan'],
	"analizadamente":'ihitztlikokan',
	"anaranjadamente": ['alaxtikan', 'laxtikan'],
	"anchamente":'patlauakan',
	"animadamente": ['nemikan', 'nemitikan'],
	"animatoriamente":'nemiliztikan',
	"anoche":'youalpan yalhua',
	"anteriormente":'achtopan',
	"anteriormente":'achtopan',
	"antes":'achto',
	"anticipadamente": ['achpanikan', 'achtokchiuakan'],
	"anticipativamente": ['achpanitikan', 'achtokchiutikan'],
	"antier":'achtoyalhua',
	"antiguamente":'achtopakan',
	"aparente": ['amonelikan', 'amoneltokan'],
	"aparentemente": ['amonelikan', 'amoneltokan'],
	"apelmazádamente":'chichiuayokan',
	"apestosamente": ['amokual ahuiakan', 'ihyakan', 'ihyaktikan', 'tzolyakan', 'tzolyaktikan'],
	"aplausivamente":'tlaxtlaxkalouayokan',
	"aplicadamente":'paniakan',
	"apoyadamente": ['mamauakan', 'mamauatikan'],
	"aprendidamente":'tzalokan',
	"apretadamente":'papachokan',
	"aproximador":'azihtekatl',
	"aproximadormente":'azihtekatl',
	"aproximante":'azihtokan',
	"aproximantemente":'azihtokan',
	"apuntadamente": ['axiltiakan', 'axiltiayotl'],
	"apáticamente": ['amoyoki', 'nekayoki'],
	"aquí": ['ni kan', 'nikan'],
	"aquímente": ['ni kan', 'nikan'],
	"ardidamente":'tlaniakan',
	"ardiente":'tlatlauhki',
	"ardientemente":'tlatlauhki',
	"aromatizadamente":'ahuikaukan',
	"aromáticamente":'ahuikauliztikan',
	"arrancadamente":'peuakan',
	"arribamente":'tlakpakan',
	"asemejantemente":'neneuakan',
	"asemejatoriamente":'neneuakan',
	"asentadamente":'tlaliakan',
	"asesinadamente":'mikmakakan',
	"asesinatoriamente":'miktikan',
	"asidamente":'kuikan',
	"asimiladamente": ['ontlamatikan', 'yolpachokan'],
	"asociadamente": ['mekakan', 'mekatikan', 'mekauakan', 'mekauatikan'],
	"asombradamente":'izakan',
	"astutamente":'matiazikan',
	"astutosamente":'matiazikan',
	"así":'ihkin',
	"asímente":'ihkin',
	"atacadamente":'yaokan',
	"atadamente": ['mekakan', 'mekatikan', 'mekauakan', 'mekauatikan'],
	"aterrizadamente":'tlaliakan',
	"atinadamente":'xihiakan',
	"atisbadamente":'nezikan',
	"atisbatoriamente":'nezikan',
	"atrapadamente":'pachokuikan',
	"atravesadamente":'ipalikan',
	"atrámente":'ihkampa',
	"atrás":'ihkampa',
	"atuendadamente":'tlakemiakan',
	"aumentadamente": ['ixkaltiakan', 'ixpankuikan', 'izkaltiakan'],
	"ausentadamente": ['poliuikan', 'amitlakan'],
	"ausentadamente":'poliuikan',
	"autodestruidamente":'tlakapexikan',
	"auxiliadamente":'paleuikan',
	"avanzadamente": ['ipainakan', 'ixyauikan', 'nehnemikan'],
	"aventadamente":'tlazakan',
	"averiguadamente":'temokan',
	"averiguatoriamente":'temokan',
	"avisadamente":'notzakan',
	"avisatoriamente":'notzakan',
	"avistadamente":'nezikan',
	"avistatoriamente":'nezikan',
	"avizoradamente":'nezikan',
	"avizoratoriamente":'nezikan',
	"ayer":'yalhua',
	"ayermente":'yalhua',
	"ayudadamente":'paleuikan',
	"ayudámente":'paleuikan',
	"azul":'xiuhtikan',
	"azulmente":'xiuhtikan',
	"bailable":'ihtotikan',
	"bailablemente":'ihtotikan',
	"bailadamente": ['ihtotikan', 'ihtotitikan'],
	"bajadamente":'temokan',
	"bajamente":'tzinkapa',
	"bajariamente":'temokan',
	"baratamente": ['amopatiyokan', 'amopatiyotikan', 'chotikan'],
	"bañadamente": ['altiakan', 'altikan', 'maltiakan', 'maltikan'],
	"bebidamente":'koniakan',
	"bien":'kualli',
	"bienmente":'kualli',
	"biscosamente":'kuekuetlaxtikan',
	"blancamente":'iztakan',
	"bloqueadamente": ['amokauakan', 'amokaualtikan', 'kehtzakan'],
	"bondadosamente":'kualtiyokan',
	"bonitamente": ['kualtzin', 'yekyokan', 'yekyoltzin', 'yekyotzin'],
	"borradamente":'popolokan',
	"brevemente": ['achikan', 'achitikan', 'achtzinman'],
	"brevemente":'achikan',
	"brevemente":'achitikan',
	"brevemente":'achtzinman',
	"brilladamente": ['momochkakan', 'petlanikan'],
	"brillante": ['motlanextikan', 'petlanikan'],
	"brillantemente": ['motlanextikan', 'petlanikan'],
	"brillatoriamente":'momochkakan',
	"brillosamente": ['motlanextikan', 'petlanikan'],
	"brincadamente":'tzikuinikan',
	"bromeadamente":'chunkaukan',
	"brotadamente":'kueponiakan',
	"buceádamente":'atzinnehnemikan',
	"buenamente":'kualli',
	"burladamente": ['chunkaukan', 'kamanakan'],
	"buscadamente":'temoakan',
	"buscariamente":'temoakan',
	"cagadamente":'kuitlauikan',
	"caidamente":'uetzkakan',
	"caladamente":'itzminakan',
	"caliente":'tonakan',
	"calientemente":'tonakan',
	"calmadamente":'mantikan',
	"caloradamente":'tonakan',
	"cambiadamente":'palakan',
	"caminadamente":'nehnemikan',
	"caminamente":'nehnemikan',
	"cansadamente":'zauikan',
	"cantadamente":'kuikakan',
	"capaces":'ueltikan',
	"capacitadamente":'yekmachiliakan',
	"capaz":'ueltikan',
	"capazmente":'ueltikan',
	"característicamente":'iuhkayotikan',
	"caramente":'patiyotikan',
	"carente": ['inayaki', 'inayatokan', 'mayanakan'],
	"carentemente": ['inayaki', 'inayatokan', 'mayanakan'],
	"cargadamente": ['mamauakan', 'mamauatikan'],
	"cargante":'mamahtokan',
	"cargantemente":'mamahtokan',
	"casi":'iuhki',
	"categóricamente":'tlamikan',
	"causadamente": ['ikchiuakan', 'ixchiuakan'],
	"caóticamente":'makauitikan',
	"cegadamente":'ixpopoyokan',
	"celádamente":'chauakan',
	"cerca":'nauak',
	"cercamente":'nauakan',
	"cerradamente": ['tzakualtikan', 'tzakuatikan', 'tzatikan'],
	"cesadamente": ['nakauakan', 'nekauakan'],
	"cesatoriamente": ['nakauakan', 'nekauakan'],
	"charladamente":'nonotzakan',
	"charlatoriamente":'nonotzakan',
	"chingadamente":'ihtlakokan',
	"chupante":'chupitokan',
	"chupantemente":'chupitokan',
	"chupeteadamente":'chupitikan',
	"chupádamente":'chichinakan',
	"cierradamente":'tzakuakan',
	"ciertamente": ['mela', 'melakan', 'melauakan', 'melli', 'nelli'],
	"ciervamente":'mazatl',
	"cilíndricamente": ['kokotikan', 'mimilkonikan'],
	"circuladamente": ['maliakan', 'maliatikan'],
	"claramente": ['amote yayauaktikan', 'amoteyauaktikan', 'chipauakan', 'iztakan'],
	"cobradamente":'ihtlanikan',
	"cogidamente":'pehpechikan',
	"cohibidamente":'amokauakan',
	"coladamente": ['amiminakan', 'amiminatikan', 'miminakan'],
	"colatoriamente":'miminakan',
	"coleadamente": ['kuitlapiluakan', 'piluakan'],
	"colocadamente":'kaniakan',
	"coloreadamente":'tlapaliakan',
	"comadamente":'tlakuakan',
	"comandadamente":'nauatikan',
	"comandatoriamente":'nauatikan',
	"comenzadamente":'peuakan',
	"comerciadamente":'namakokan',
	"comerciatoriamente":'namakokan',
	"comidamente":'tlakuakan',
#	"como":'kenin',
	"cómo":'kenin',
	"comparadamente": ['neneuhtlachiakan', 'zezeltlachiakan'],
	"comparatoriamente":'neneuhtlachiakan',
	"complejamente":'youikan',
	"complejas":'youikan',
	"complejosamente":'youikan',
	"complementadamente":'temikan',
	"complementariamente":'temikan',
	"completadamente":'temikan',
	"completamente":'temikan',
	"compradamente": ['kouakan', 'kouikan', 'kouitikan'],
	"comprobadamente":'itachiuakan',
	"comprobamente":'itachiuakan',
	"compuestamente":'melakiyokan',
	"común":'mantik',
	"común":'nochipak',
	"concatenadamente": ['mekakan', 'mekatikan', 'mekauakan', 'mekauatikan'],
	"concluyentemente":'tlamikan',
	"conectadamente": ['mekakan', 'mekauakan', 'mekconectikan'],
	"confesadamente":'mokuitiliakan',
	"confesatoriamente":'mokuitiliakan',
	"configuradamente":'tokakan',
	"conflictivamente":'ouiyokan',
	"conforme":'ixmatipan',
	"conformemente":'ixmatipan',
	"confrontatoriamente":'yaolizko',
	"confundidamente": ['amoixmatiuakan', 'tlalpolokan', 'tlapolokan'],
	"confusamente":'youikan',
	"confusas":'youikan',
	"confusosamente":'youikan',
	"congeladamente":'zekuikan',
	"congruente":'kayotokan',
	"congruentemente":'kayotokan',
	"conocidamente":'ontlamatiyokan',
	"conseguidamente":'tlaniakan',
	"consentidamente":'kemiyoakan',
	"consoladamente": ['ikamakixtiatikan', 'ikpaleuikan', 'yolpachokan'],
	"consolan":'ikamakixtiakan',
	"conspiradamente":'tlakuepaihtokan',
	"constante": ['totokakan', 'totokatikan'],
	"constantemente": ['totokakan', 'totokatikan'],
	"constantes":'totokakan',
	"constituidamente":'chichiuayokan',
	"contadamente": ['pouakan', 'pouatikan'],
	"contaminadamente": ['akauikan', 'amokualyokan', 'makauikan'],
	"contentamente":'pakiliztikan',
	"contestadamente":'nankiliakan',
	"contestatoriamente":'nankiliakan',
	"controládamente":'chikauayokan',
	"contundentemente":'ipanmelauak',
	"contundentemente":'ipantlamikan',
	"convencidamente":'neltokachiuakan',
	"conversadamente":'nonotzakan',
	"conversatoriamente":'nonotzakan',
	"copiadamente": ['kilikan', 'kixtiakan', 'momoakan'],
	"copiatoriamente":'momoakan',
	"copuladamente":'pehpechikan',
	"coqueteadamente":'yolchiuiliakan',
	"correctamente":'melauakan',
	"cortadamente":'tekikan',
	"cortamente":'achikan',
	"cortamente":'achikan',
	"cosamente":'tla',
	"costadamente": ['kemilikan', 'kexkiakan'],
	"cotidianamente":'momoztlapan',
	"creidamente":'neltokayokan',
	"creádamente":'chichiuakan',
	"cruzadamente":'ipalikan',
	"cuajádamente":'chichiuayokan',
	"cuanto":'kexki',
	"cuantos":'kexki',
	"cubiertamente":'pachoyokan',
	"cuchicheadamente":'ixtetlapouakan',
	"culpadamente":'tetlakolchiuakan',
	"curvadamente":'koliakan',
	"dadamente": ['makakan', 'makatikan'],
	"danzadamente": ['ihtotikan', 'ihtotitikan'],
	"dañadamente":'ihtlakokan',
	"deacuerdo":'monamiki',
	"debidamente": ['uihkilikan', 'kualkan'],
	"debilidad": ['amokueltikyotl', 'ayolotl'],
	"debilitadamente": ['amokueltikyotl', 'ayolotl'],
	"debilmente":'amotlaueltikpan',
	"debilmente":'amoueltikpan',
	"decapitadamente":'tzontekontekikan',
	"decididamente":'tlamikan',
	"decisivamente":'iliayokan',
	"deductivamente":'neltokayokan',
	"defecadamente":'kuitlauikan',
	"defendidamente":'manailhuakan',
	"definidamente": ['machiliakan', 'tlamachiliakan'],
	"definitivamente":'tlamikan',
	"degradadamente": ['tziniakan', 'tzinuakan', 'tzinuatikan', 'tzitziniakan', 'tzitziniatikan'],
	"dejadamente":'kauakan',
	"delgadamente":'pitzauakan',
	"demandadamente":'teiliakan',
	"demostradamente":'panititikan',
	"deponidamente":'notzoyokan',
	"derechamente": ['mayekpa', 'yekamikan', 'yekan'],
	"derretidamente": ['auakan', 'axolohtiakan'],
	"derribadamente": ['kantlazakan', 'kotlazakan'],
	"desafiadamente":'ixiuiliakan',
	"desafiádamente":'chikauilikan',
	"desagradable":'amokualtzin',
	"desagradablemente":'amokualtzin',
	"desagradadamente": ['amokualpakikan', 'amopaktokan'],
	"desaparecidamente":'poliuikan',
	"desbocadamente":'ikchiuakan',
	"descansadamente":'zeuikan',
	"descargadamente":'mamazkauakan',
	"descendidamente":'temokan',
	"descompuestamente":'makauikan',
	"desconciertadamente":'tzontekontlaukan',
	"desconfiadamente":'amo neltokakan',
	"descorteses":'amotzinyokan',
	"descortesmente":'amotzinyokan',
	"descortés":'amotzinyokan',
	"descubiertamente": ['nechtiayokan', 'nenelouayokan'],
	"descuidadamente": ['ilkauakan', 'ilkaukan'],
	"desde":'ixkipa',
	"desdemente":'ixkipa',
	"desdobladamente":'itztlakoliuakan',
	"deseadamente": ['onnekikan', 'yolnekikan'],
	"desenbocadamente":'ikpanchiuakan',
	"deshonradamente": ['mauizokuitlakan', 'mauizokuitlatikan'],
	"desistidamente":'kauakan',
	"deslizadamente": ['alauakan', 'alauayotikan'],
	"despegadamente": ['kopeuikan', 'moleuakan'],
	"despegatoriamente":'moleuakan',
	"despertadamente":'izakan',
	"desplazadamente":'olikan',
	"desplazatoriamente":'olikan',
	"desplomadamente":'uetzkakan',
	"despuémente":'niman',
	"después de mañana":'nimanmoztla',
	"después":'niman',
	"destapadamente":'tlapokan',
	"destituyamente":'panpalayokan',
	"destruidamente":'tzominiakan',
	"desunidamente":'notzoyokan',
	"desviadamente": ['okzenehnemkuikan', 'palkuikan'],
	"desviatoriamente":'okzenehnemkuikan',
	"desvirtuadamente":'akauikan',
	"determinadamente":'itlakuikan',
	"detrámente":'kuitlapa',
	"detrás":'kuitlapa',
	"devolutivamente":'tlakuepayotl',
	"devolver":'tlakuepa',
	"devolvermente":'tlakuepa',
	"devueltamente":'tlakuepayotl',
	"diariamente":'momoztlapan',
	"diariamente":['axkanman', 'axkanpan'],
	"dichamente":'ihtokan',
	"diferidamente": ['amonamiktiakan', 'zezekiakan'],
	"dificultadamente":'youiakan',
	"difícil":'youikan',
	"difícilemente":'youikan',
	"difíciles":'youikan',
	"difícilmente":'youikan',
	"dignamente":'mauizokpan',
	"dignamente":'mauizopan',
	"diludidamente":'tzitziniakan',
	"diluidamente":'auaxpeuikan',
	"dinámicamente":'olinikan',
	"dinámicas":'olinikan',
	"dinámicosamente":'olinikan',
	"dirigidamente":'tekuhuayokan',
	"discutidamente":'tekuaniliayokan',
	"disponible":'nepanpatikan',
	"disponiblemente":'nepanpatikan',
	"distanciadamente": ['tlauehkakan', 'uehkakan'],
	"distante":'uehka',
	"distantemente":'uehka',
	"distribuidamente":'auipaloliakan',
	"disyuntadamente": ['notzokan', 'tekikan'],
	"disyuntatoriamente":'notzokan',
	"divertidamente":'auiltiakan',
	"divididamente":'zezekiakan',
	"dobladamente":'koliuikan',
	"dormidamente":'kochikan',
	"dosamente":'makatikan',
	"dramáticamente":'achokzepakan',
	"dudadamente":'nelyanakan',
	"dudatoriamente":'nelyanakan',
	"dudosamente":'tzontekontlaukan',
	"duramente":'chikauakan',
	"educadamente":'temachiltikan',
	"educadosamente":'temachiltikan',
	"efectivamente":'melauakan',
	"egoístamente":'chautilki',
	"ejecutadamente":'chiuakan',
	"ejecutosamente":'chiuatikan',
	"elaborádamente":'chichiuakan',
	"electamente":'pehpenayokan',
	"electrónicamente":'ekehtzatikan',
	"elegante":'uelueyikan',
	"elegantemente":'uelueyikan',
	"elevadamente":'euakan',
	"ellamente": ['yeh', 'yehua', 'yehuan', 'yehuantin', 'yehuatl'],
	"ellas": ['yehuan', 'yehuantin'],
	"ellosamente": ['yehuan', 'yehuantin'],
	"elásticamente":'kuekuetlaxtikan',
	"embarcadamente": ['akalkokan', 'akalkoyotikan'],
	"embarradamente":'ixpanmoliakan',
	"emborrachodamente":'huintikan',
	"empequeñecidamente":'tzinuakan',
	"emprendamente":'pehpechikan',
	"en medio de":'nepantla',
	"en medio demente":'nepantla',
	"encabronadamente":'tekuanikan',
	"encajadamente":'kalakiakan',
	"encantadamente": ['mauizokan', 'mauizotikan'],
	"encogidamente":'tzinuikan',
	"encontradamente":'namikiatikan',
	"encorbaradamente":'ahkolkukan',
	"encuadernadamente": ['amatzomayokan', 'amatzomayotikan'],
	"encuadradamente":'nauhkampakan',
	"encuadratoriamente":'nauhkampakan',
	"encuentran":'namikiakan',
	"enderezadamente": ['mekenderezikan', 'melakiakan'],
	"endeudadamente":'ikilikan',
	"energizadamente":'tlaueliakan',
	"enfermadamente":'kokoiliakan',
	"enfrentadamente": ['ixchiuakan', 'yaokan'],
	"enfrentativamente":'yaoliztikan',
	"enfriadamente":'zekuikan',
	"enfurecidamente":'tekuanikan',
	"enganchadamente": ['kokouhkuikan', 'kuauhkuikan'],
	"engañadamente": ['itztlakoliukan', 'kahkayauakan'],
	"engranadamente":'teponiakan',
	"enjuagadamente":'amouikan',
	"enlazadamente": ['mekakan', 'mekatikan', 'mekauakan', 'mekauatikan'],
	"enojadamente": ['tekuanikan', 'tekuantikan'],
	"enrojádamente":'chichilinakan',
	"enseñadamente": ['machiliakan', 'machiliatikan', 'machtiakan', 'machtiatikan'],
	"ensuciadamente": ['tzoyokan', 'tzoyotikan'],
	"entoncemente": ['ikuakan', 'inikan', 'kuakan'],
	"entonces": ['ikuakan', 'inikan', 'kuakan'],
	"entradamente": ['kalakiakan', 'ni itakan'],
	"entramente":'itekiakan',
	"entrativamente":'itekializtikan',
	"entrañadamente":'ni itakan',
	"entrañamente":'itekiakan',
	"entrañativamente":'itekializtikan',
	"entre":'nepantla',
	"entremente":'nepantla',
	"entrenaradamente":'moltiakan',
	"entrenaratoriamente":'moltiakan',
	"entristecidamente":'tlakolokan',
	"enumeradamente":'poualmachiyouakan',
	"envenenadamente":'mikpahtiakan',
	"envenenatoriamente":'mikpahtiakan',
	"enviadamente":'titlanikan',
	"equilibradamente": ['olinxihtiakan', 'olinyolokan'],
	"equivocadamente": ['ouilyokan', 'ouiyokan'],
	"equivocádamente":'auiyokan',
	"erigidamente":'euakan',
	"erradamente":'ouilyokan',
	"errádamente":'auiyokan',
	"erróneamente":'ouiyokan',
	"escapadamente":'kizoliuikan',
	"escarbadamente":'xexelokan',
	"escogidamente":'pehpenayokan',
	"escurridamente":'achiutetemotokan',
	"esenciamente":'yo',
	"esféricamente":'koyolikan',
	"esmeradamente":'mochikauakan',
	"esmeratoriamente":'mochikauakan',
	"espaciadamente": ['ikauakan', 'ikaukan'],
	"específicamente":'tlachiuhyotikan',
	"esperadamente":'tepitikan',
	"esperanzadamente":'neltokaztepitikan',
	"esperádamente":'chiakan',
	"espinadamente": ['uitziakan', 'uitzpaniakan'],
	"espinádamente":'uitzikan',
	"estabilidad":'kayotl',
	"estabilidadmente":'kayotl',
	"estabilización":'kayotl',
	"estabilizaciónmente":'kayotl',
	"estable":'katikan',
	"establecidamente": ['tlaliakan', 'tokakan'],
	"establemente":'katikan',
	"estrechamente":'achihko',
	"estructuradamente": ['mekakan', 'mekauakan', 'mekestructurikan'],
	"estrujadamente":'papachokan',
	"estudiadamente":'momachtikan',
	"estáticamente":'katikan',
	"estáticas":'katikan',
	"estáticosamente":'katikan',
	"eternamente": ['nochipakan', 'nochipa'],
	"evaluadamente":'patiyokan',
	"evidentemente":'itayokan',
	"evitadamente":'tzikuinikan',
	"exactamente":'kualtlamikan',
	"exactosamente":'kualtlamikan',
	"exajeradamente": ['achtokzepalakan', 'achtokzepalatikan', 'ueyikchiuakan', 'ueyikchiutikan'],
	"exajerativamente":'ueyikchiualiztikan',
	"excelente": ['miak kualtikan', 'miakkualtikan'],
	"excelentemente": ['miak kualtikan', 'miakkualtikan'],
	"exhibidamente":'ititikan',
	"exhortadamente": ['ahuinikan', 'ahuiniliztikan', 'notzakan'],
	"exhortatoriamente":'notzakan',
	"exigidamente":'teiliayokan',
	"existidamente":'kakan',
	"expeditamente": ['makix', 'makixtilli'],
	"expididamente":'titlaniyokan',
	"explicadamente":'tlamachiliakan',
	"explicativamente":'tlamachiliyokan',
	"expresadamente": ['ihtokan', 'ihtotikan'],
	"expresante":'ihtoki',
	"expresantemente":'ihtoki',
	"extornudadamente": ['alauakan', 'alaualiztikan'],
	"facilitación":'amoyouitiyotl',
	"facilitaciónmente":'amoyouitiyotl',
	"facilitámente":'ayouiyokan',
	"falládamente":'auiyokan',
	"familiarizámente":'chantiliyokan',
	"fascinadamente": ['mauizokan', 'mauizotikan'],
	"fastidiadamente":'kuetziakan',
	"feamente":'amokualtzin',
	"feamente":'amokualtzintikpan',
	"feliz":'pakiliztikan',
	"felizmente":'pakiliztikan',
	"festejadamente":'ilhuikan',
	"festejatoriamente":'ilhuikan',
	"fijadamente":'pehpechouakan',
	"filtradamente": ['amiminakan', 'amiminatikan'],
	"finalizadamente": ['tlamiakan', 'tlamikan'],
	"finalmente": ['tlamiakan', 'tlamikan'],
	"finamente":'pitzauakan',
	"finiquitadamente": ['tlamiakan', 'tlamikan'],
	"finiquitadamente":'tlamikan',
	"firme":'chikauakan',
	"firmemente":'chikauakan',
	"flemosamente": ['alauahtikan', 'alauakan'],
	"fletación":'akaleuyotikan',
	"fletaciónmente":'akaleuyotikan',
	"fletadamente": ['akaleukan', 'ehekaleukan'],
	"fortalezamente":'chikauayotl',
	"forzar":'chikaua',
	"forzarmente":'chikaua',
	"forzádamente":'chikauayokan',
	"fracturadamente": ['tzomonikan', 'tzomonitikan'],
	"fraternadamente":'ikniukan',
	"frecuente":'totokatikan',
	"frecuentemente":'achtzinkan',
	"frecuentemente":'achtzinpa',
	"frecuentemente":'totokatikan',
	"frecuentes":'totokatikan',
	"frenadamente":'kehtzakan',
	"frenadamente":'nekauakan',
	"frente":'ixpan',
	"frentemente":'ixpan',
	"friamente":'itztikpan',
	"frágil":'tzomonikan',
	"frágilmente":'tzomonikan',
	"fríamente":'zezekan',
	"fuerte":'chikauakan',
	"fuertemente":'chikauakan',
	"fuertementemente":'chikauakan',
	"fuerzamente":'chikauaktli',
	"funcionadamente":'tekitikan',
	"fácil":'ayouikan',
	"fácilemente":'ayouikan',
	"fáciles":'ayouikan',
	"fácilmente":'ayouikan',
	"galopadamente":'choloeuakan',
	"galopatoriamente":'choloeuakan',
	"ganadamente":'tlaniakan',
	"giradamente": ['maliakan', 'maliatikan'],
	"golpeadamente":'tekpanakan',
	"gran":'uey',
	"grande":'ueyikan',
	"grandemente":'ueyikan',
	"granmente":'uey',
	"groseramente":'kamapitokan',
	"groserosamente":'kamapitokan',
	"gruesamente":'tomauakan',
	"guardadamente":'tlatiakan',
	"guiñadamente": ['ikopiakan', 'ikopikan', 'zeixtelolotzakan'],
	"gustadamente":'pakikan',
	"gustosamente":'pakitikan',
	"guíadamente":'tekuanikan',
	"habiente":'onkayotokan',
	"habientemente":'onkayotokan',
	"habituadamente": ['matichiuakan', 'matichiuatikan'],
	"habitámente":'chantiyokan',
	"habladamente":'tlahtokan',
	"haciamente":'ixkikan',
	"hastamente":'ixkikan',
	"hechamente":'chiuayotl',
	"hermosamente": ['katzalli', 'ketzalikan', 'ketzalli', 'ketzaltzin'],
	"hervidamente":'amanakan',
	"hidráulicamente": ['aolinikan', 'atl olinikan'],
	"holgadamente":'auixpan',
	"holgádamente":'auikan',
	"honestamente":'temelauakan',
	"honestosamente":'temelauakan',
	"honradamente": ['mauizokan', 'mauizotikan'],
	"honrrosamente":'mauizokpan',
	"honrrosamente":'mauizopan',
	"horrible": ['amoketzalyotl', 'miakamoketzalli'],
	"horriblemente": ['amoketzalyotl', 'miakamoketzalli'],
	"horriblemente":'amokualtzintikpan',
	"hostigadamente":'kuetziakan',
	"hoy":'axkan',
	"huidamente":'kizoliuikan',
	"humedamente":'atiakan',
	"humilde":'iknotekatikan',
	"humildemente":'iknotekatikan',
	"humildes":'iknotekatikan',
	"hundidamente":'akalakiakan',
	"húmedamente":'apachiuaki',
	"idamente":'yaukan',
	"ideadamente": ['izpanilyokan', 'tlalnamikikan'],
	"identicamente":'neneutikan',
	"idiomáticamente":'ihtoltikan',
	"idiotamente": ['kiuaxoko', 'koaxoko', 'kouaxoko'],
	"ignoradamente":'tzikuinikan',
	"ignorante": ['amoixmatiki', 'amotlamatiki'],
	"ignorantemente": ['amoixmatiki', 'amotlamatiki'],
	"ignorantes":'amotlamatiki',
	"igual": ['iuhpantikan', 'iuhpechtikan', 'neneuaki'],
	"igualantemente":'neneuakiakan',
	"igualatoriamente":'neneuakiakan',
	"igualmente": ['iuhpantikan', 'iuhpechtikan', 'neneuaki'],
	"igualmente":'neneuhpan',
	"iluminadamente": ['tlanezikan', 'tlauelikan'],
	"ilícitamente": ['amochikualli', 'amochiualiz', 'amochiualoki'],
	"imaginadamente": ['izpanamikiliakan', 'izpanilyokan'],
	"impedidamente":'amokauakan',
	"importante":'ihuanikan',
	"importantemente":'ihuanikan',
	"imprecisamente":'amomelauakan',
	"imprecisosamente":'amomelauakan',
	"imprimidamente": ['kuenchiuakan', 'kuenkauakan'],
	"inadecuadamente":'amokualtikan',
	"incapacemente":'amoueltikan',
	"incapaces":'amoueltikan',
	"incapaz":'amoueltikan',
	"incapazmente":'amoueltikan',
	"incitadamente":'izpanotzakan',
	"inclinadamente":'tekakan',
	"incompletamente":'amotemikan',
	"incorporadamente":'kalakiakan',
	"incorrectamente":'amomelauakan',
	"incrementadamente": ['iuanyokan', 'iuanyouakan', 'ixkaltiakan', 'izkaltiakan'],
	"incrustadamente":'pachokalakiakan',
	"indisponible":'amonepanpatikan',
	"indisponiblemente":'amonepanpatikan',
	"indudablemente":'amotlanelyanalikan',
	"inesperadamente":'amotepitipan',
	"inestable":'amokatikan',
	"inestablemente":'amokatikan',
	"inexactamente":'amokualtlamikan',
	"inexactosamente":'amokualtlamikan',
	"inferente":'neltokayokan',
	"inferentemente":'neltokayokan',
	"infinitamente": ['amopoualyotl', 'amotlamikyan', 'amotlamyotl'],
	"informadamente": ['matizmakakan', 'matizmakatikan'],
	"ingeniadamente":'tlalnamikikan',
	"ingenuamente":'amotetlamatiki',
	"ingenuas":'amotetlamatiki',
	"ingenuosamente":'amotetlamatiki',
	"ingeridamente":'tlakuakan',
	"iniciadamente":'peuakan',
	"injuriadamente":'amokualtlahtokan',
	"inmaculadamente": ['chipauakan', 'iztakan'],
	"innecesariamente":'amoihuanikan',
	"inquietadamente":'amo yolpachokan',
	"inquietamente": ['amo yolpachokan', 'makaukan'],
	"inseguramente":'amochimalikan',
	"insinuadamente":'chiuiliakan',
	"inspiradamente":'yolnotzakan',
	"instantáneamente":'imanpan',
	"instruidamente":'machtiakan',
	"instrumentádamente":'aztiakan',
	"insultadamente":'amokualtlahtokan',
	"integradamente":'uaniakan',
	"inteligente":'tlamatiki',
	"inteligentemente":'tlamatiki',
	"inteligentes":'tlamatiki',
	"intensamente":'yayauhtikan',
	"interpeladamente":'teiliakan',
	"interpretadamente":'tlalnamikyopalakan',
	"interrumpidamente": ['kehtzakan', 'nakauayokan'],
	"intranquilizadamente":'amouikan',
	"intrigosamente": ['amokualtzaihtoka', 'amokualtzailihka'],
	"introducvamente":'kalakiayokan',
	"invadidamente":'iteknehnemikan',
	"inventádamente":'aztiakan',
	"invitadamente":'izpanotzakan',
	"involucradamente":'kankuikan',
	"inútil": ['amotzalikan', 'amotzatzalikan', 'ontemikan'],
	"inútilmente": ['amotzalikan', 'amotzatzalikan', 'ontemikan'],
	"irrelevante":'amoihuanikan',
	"irrelevantemente":'amoihuanikan',
	"irrespetuosamente":'amotzinyokan',
	"irrespetuososamente":'amotzinyokan',
	"jaladamente": ['tilanakan', 'tilantikan'],
	"jamámente":'aikan',
	"jamás":'aikan',
	"joven":'telpochtikan',
	"jovenmente":'telpochtikan',
	"jugádamente":'auikan',
	"juntadamente":'uaniakan',
	"jurídicamente": ['melauakzeliltikan', 'melazeliltikan', 'yekuakzeliltikan', 'yekzeliltikan'],
	"justamente":'azitok',
	"justamente":'melauakan',
	"justamentemente":'melauakan',
	"labradamente":'tetekikan',
	"labratoriamente":'tetekikan',
	"lanzadamente":'tlazakan',
	"largamente":'ueyakan',
	"lastradamente":'akaltetemokan',
	"lavadamente":'tlapakakan',
	"leidamente":'tlatlachiakan',
	"lejosamente":'uehka',
	"lemente": ['an mech', 'ki', 'kin'],
	"lentamente": ['kuechauakan', 'tzinuhtikan', 'ziuhtikan'],
	"liberadamente":'makixtiakan',
	"libradamente":'makixtiakan',
	"libre": ['ma kixtikan', 'makixtikan'],
	"libremente": ['ma kixtikan', 'makixtikan'],
	"ligeramente":'amoetikan',
	"limitadamente": ['amokauakan', 'amokauatikan'],
	"lisamente":'alaxtikan',
	"listamente":'kuayamanki',
	"listas":'kuayamanki',
	"listosamente":'kuayamanki',
	"llamadamente":'notzakan',
	"llamatoriamente":'notzakan',
	"llegadamente": ['ehkokan', 'ehkotikan'],
	"llenamente":'temikan',
	"llevadamente": ['mamayauikan', 'mamayauitikan', 'tlauihkakan', 'uihkakan'],
	"lloradamente":'chokakan',
	"luego":'niman',
	"luminosamente":'tlanezikan',
	"lumínicamente":'tlanezikan',
	"lunáticamente": ['koaxoko', 'kouaxoko'],
	"maduramente":'ikoxikan',
	"mal":'amokualli',
	"malamente":'amokualli',
	"malmente":'amokualli',
	"mamádamente": ['chichileuakan', 'chichinakan', 'chichipiakan', 'chichitilanakan'],
	"manifestadamente": ['ihtokan', 'ihtotikan', 'notzakan'],
	"manifestatoriamente":'notzakan',
	"manipulable":'ketzauekan',
	"manipulablemente":'ketzauekan',
	"maniáticamente": ['kiuaxoko', 'koaxoko'],
	"maníacamente": ['kiuaxoko', 'koaxoko'],
	"maravilladamente": ['mauizokan', 'mauizotikan'],
	"masturbadamente":'tepiltilanakan',
	"matadamente":'mikikan',
	"matizádamente":'auaxpeuikan',
	"mayoritariamente":'okzenka',
	"mayoritariamentemente":'okzenka',
	"mayormente":'okzenka',
	"mayormentemente":'okzenka',
	"mañana":'moztla',
	"mediadamente":'ipalikan',
	"medidamente":'neneuihkiayokan',
	"mejor":'achikualtikan',
	"mejormente":'achikualtikan',
	"memente":'nech',
	"menosamente":'nenkan',
	"mentalizadamente":'tlalnamikikan',
	"mentirosamente": ['itztlakoliuyokan', 'teamoneloakan'],
	"mentirososamente":'teamoneloakan',
	"mercadeadamente":'namakokan',
	"mercadeatoriamente":'namakokan',
	"merecidamente":'mazeuikan',
	"meritadamente":'tlaniakan',
	"metamorfoseadamente":'itztlakoliuikan',
	"modernamente":'axkantikan',
	"mojádamente":'atiakan',
	"molestadamente": ['kuehtziakan', 'kuetziakan'],
	"mortal":'mikiyokan',
	"mortalmente":'mikiyokan',
	"mortoriamente":'miktikan',
	"mostradamente":'ititikan',
	"moviblemente":'oltikan',
	"mucha":'miak',
	"muchas":'miak',
	"mucho":'miak',
	"muchos":'miak',
	"más":'achi',
	"nacidamente":['ixuakan', 'ixuhtokan'],
	"nacientemente":['ixuakan', 'ixuhtokan'],
	"nada":'amitla',
	"nadadamente": ['manelokan', 'manelotikan'],
	"nadie": ['ayak', 'amoyak'],
	"naranjamente": ['alaxtikan', 'laxtikan'],
	"necesariamente": ['ihuanikan', 'nenekikan'],
	"necesitadamente":'nenekikan',
	"neciamente": ['apochtikan', 'tzontetekan'],
	"negadamente":'amotikan',
	"negramente":'tliltikan',
	"negrosamente":'tliltikan',
	"nerviosamente": ['makaukan', 'amomantzinkan'],
	"ninguna":'amakin',
	"ninguno":'amakin',
	"nombradamente":'tokakan',
	"nuevamente":'yankuikan',
	"nunca":['aikan', 'aik'],
	"náufragamente":'akamopoloki',
	"obligadamente": ['chiutikan', 'uihkilikan'],
	"observadamente":'tlachiakan',
	"obtenidamente":'tlaniakan',
	"ocasionalmente":'kemaniantikan',
	"ocupadamente":'ipantekitikan',
	"odiadamente":'onamonekikan',
	"odiosamente":'kuehzolikan',
	"ofensivamente":'achikuepalikan',
	"olvidadamente": ['iktlapaukan', 'ilkaukan'],
	"omitidamente":'tzikuinikan',
	"ondeadamente":'koloakan',
	"onduladamente":'koloakan',
	"opacamente":'pinixtikan',
	"optadamente":'pehpenakan',
	"opuestamente":'ixkokan',
	"oratemente": ['kiuaxokokan', 'koaxokokan', 'kouaxokokan'],
	"ordenadamente":'nauatikan',
	"ordenatoriamente":'nauatikan',
	"organizadamente": ['nepanpatichiuakan', 'nepanpatikan'],
	"organizatoriamente": ['nepanpatichiuakan', 'nepanpatikan'],
	"orgullosamente":'mauizokan',
	"orgullososamente":'mauizokan',
	"originalmente":['tlapeuhpan', 'tlapeuhko', 'tlapeuhkan'],
	"orinádamente":'axixiyokan',
	"osadamente": ['ipalixukan', 'ipalixuliztikan'],
	"osativamente":'ipalixuliztikan',
	"osatoriamente":'ipalixulizko',
	"oscuramente": ['yoyouhkan', 'yayauhkan'],
	"oteadamente":'itaazikan',
	"oteativamente":'itaaziliztikan',
	"otra vez":'okzepa',
	"otra":'okze',
	"otro":'okze',
	"palabradamente":'tlahtolkan',
	"parcialmente":'achitikan',
	"parecidamente":'neltokayokan',
	"paridamente":'ixuhkan',
	"pasadamente":'panokan',
	"pasivamente":'amochiuakan',
	"pasivosamente":'amochiuakan',
	"pasmadamente":'izakan',
	"pateadamente": ['ikxitzakan', 'teletzakan'],
	"pausadamente": ['kehtzakan', 'nakauakan', 'nekauakan'],
	"pausadosamente":'kehtzakan',
	"pausatoriamente": ['nakauakan', 'nekauakan'],
	"pedidamente":'ihtlaniakan',
	"pegadamente":'pehpechouakan',
	"peleadamente":'yaokan',
	"peleoneramente":'ixyaochiuakan',
	"peligrosamente":'uiyokan',
	"pelónamente":'amotzontlakan',
	"pensadamente":'tlalnamikikan',
	"peormente": ['amokualtikan', 'amokualyokan'],
	"pequeñamente":'pilli',
	"percatadamente": ['matkuikan', 'matkuitikan', 'matzaziuikan', 'matzaziuitikan'],
	"perdidamente":'poliuikan',
	"perduradamente": ['kehtzakan', 'kehtzauakan', 'totokakan'],
	"perezosamente": ['amoyoki', 'nekayoki'],
	"perfumadamente":'ahuikaukan',
	"perjudicadamente":'ihtlakokan',
	"permitidamente":'kauakan',
	"perseguidamente":'totokatekatl',
	"perseveradamente":'ontotokakan',
	"perseverantemente":'totokatikan',
	"persiguiente":'totokatokan',
	"persiguientemente":'totokatokan',
	"persistente":'amokauhtitokan',
	"persistentemente":'amokauhtitokan',
	"personalmente":'imatikan',
	"personalmente":'inochiinehuiyan',
	"perspicazmente":'azihtokan',
	"pertinentemente":'tekauatokan',
	"perversamente":'amokualtiki',
	"pesadamente":'etikan',
	"petulantemente": ['ixkotlachiki', 'mopatiyoki', 'nehueililki'],
	"picadamente": ['chilokan', 'chiuahtzotikan', 'uitzpaniakan'],
	"picudamente":'uitztikan',
	"pinchadamente":'uitziakan',
	"planificadamente":'nepanpatichiuakan',
	"planificatoriamente":'nepanpatichiuakan',
	"platicadamente":'nonotzakan',
	"platicatoriamente":'nonotzakan',
	"pobremente":'iknokan',
	"poderosamente":'uelikan',
	"ponderadamente":'teueliakan',
	"portadamente":'uihkakan',
	"posicionadamente":'kaniakan',
	"posteriormente":'niman',
	"preciosamente": ['yekyokan', 'yekyolikan', 'yekyoltzin', 'yekyotzin'],
	"precisamente": [' melauakan', 'melauakan'],
	"precisamentemente":'melauakan',
	"precisosamente":' melauakan',
	"predictivamente":'achtoilikan',
	"preferidamente": ['kuakan', 'pehpenayokan'],
	"preguntadamente":'tlahtlanikan',
	"prehispánicamente": ['achtokaxtilan', 'achtopanespañoltikan'],
	"preparadamente": ['moltiakan', 'yektlaliakan'],
	"preparatoriamente":'moltiakan',
	"preponderante":'ihuanikan',
	"preponderantemente":'ihuanikan',
	"preservadamente":'tlanemonyauzyokan',
	"presumidamente": ['ixkotlachiki', 'mopatiyoki', 'nehueililki'],
	"presuntuosamente": ['ixkotlachiki', 'mopatiyoki'],
	"prevenidamente":'achtoilitokan',
	"preventivamente":'achtoilikan',
	"principalmente":'okzenkan',
	"principalmentemente":'okzenka',
	"priorizadamente":'euakan',
	"probadamente": ['ipaliakan', 'itzminakan', 'tlapalokan'],
	"problemáticamente": ['ouihyotl', 'ouiyokan'],
	"programadamente": ['amatekitikan', 'amatekiyokan'],
	"progresadamente":'ahkuanakan',
	"prologadamente":'tlapeukan',
	"prologativamente":'tlapeualiztikan',
	"prologosamente":'tlapeutikan',
	"prontamente": ['azuhkan', 'ikiuh', 'ueliuikan'],
	"pronto": ['azuakan', 'ikiuh'],
	"pronto":'ikiuh',
	"propiamente": ['axka', 'axkauh', 'inochiinehuiyan'],
	"propiamente":'inochiinehuiyan',
	"propiamentemente":'inochiinehuiyan',
	"provocadamente": ['chiuiliakan', 'ikchiuakan'],
	"proyectadamente":'ititikan',
	"prudentemente": ['machiluaki', 'nechiuaki', 'nemachiliuaki'],
	"puenteadamente":'tzikuinikan',
	"punzadamente":'chiuahtzotikan',
	"punzante":'uitztikan',
	"punzantemente":'uitztikan',
	"puramente":'iztakan',
	"putrefactadamente":'amokualpalaxukan',
	"pálidamente":'iztaktikan',
	"pésimamente":'amomiak kualtikan',
	"públicamente":'mazeualixpan',
#	"que": ['ma', 'tlen'],
	"quebradamente": ['tzomonikan', 'tzomonitikan'],
	"quebradizamente":'tzomonikan',
	"quedadamente":'kehtzakan',
	"quejadamente":'kokoiliakan',
	"quemadamente":'tlatiakan',
	"queridamente":'nekiyokan',
	"quien":'akin',
	"quitadamente":'kuitiakan',
	"quizá":'ueliz',
	"quizás":'ueliz',
	"quién":'akin',
	"quiénes":'akin',
	"rascadamente":'xexelokan',
	"rasgadamente":'pantekikan',
	"ratificadamente": ['itachiyakan', 'itachiyokan'],
	"realmente": ['melakan', 'melauakan', 'nelyokan'],
	"rebajadamente": ['tziniakan', 'tzitziniakan', 'tzitziniatikan'],
	"rebasadamente":'ueyikchiuakan',
	"recibidamente":'tlakuikan',
	"recientemente":'yankuikan',
	"reconstruidamente":'onchiuayokan',
	"recordadamente":'ilnamikikan',
	"rectamente":'melaki',
	"rectificadamente": ['mekrectificikan', 'melakiakan'],
	"recuperadamente":'ontlakuikan',
	"recuperatoriamente":'ontlakuikan',
	"rededor":'ixkan',
	"rededormente":'ixkan',
	"redimidamente":'makixtiakan',
	"redondeadamente": ['maliakan', 'maliatikan'],
	"reelaboradamente":'onchiuakan',
	"referidamente":'tlailiakan',
	"regaladamente": ['makakan', 'makatikan'],
	"regañadamente":'ahuakan',
	"regañonamente":'ahuanki',
	"regañón":'ahualki',
	"regañónmente":'ahualki',
	"rehechamente": ['onchiuayokan', 'onixmatiyokan'],
	"reidamente":'uetzkakan',
	"reivindicadamente":'ontlapatiyokan',
	"relacionadamente": ['iktlapaukan', 'mekakan', 'mekauakan', 'mekrelacionikan'],
	"relajádamente":'auikan',
	"relevadamente":'notzokan',
	"relevatoriamente":'notzokan',
	"remembradamente": ['ilnamikikan', 'onilnamikikan'],
	"remitidamente":'titlaniyokan',
	"remojadamente":'apachokan',
	"remplazadamente": ['onnekikan', 'panpalakan'],
	"repartidamente":'nepanpatiyokan',
	"repentemente":'imanikan',
	"repentinamente":'imanikan',
	"repentinamente":'izamikan',
	"repetidamente":'teneuakan',
	"repitidamente":'putzhuiayokan',
	"reprochadamente":'amonamilikan',
	"resbaladamente": ['alauakan', 'alaualiztikan'],
	"resbalosamente":'alaxtikan',
	"resguardadamente":'koiakan',
	"resistentemente":'chikauakan',
	"resistidamente":'kehtzayokan',
	"respecto":'achtok',
	"respecto":'iktlapa',
	"respetadamente": ['tzinikan', 'tzinitikan'],
	"respetuosamente":'tzinyokan',
	"respetuososamente":'tzinyokan',
	"respiradamente": ['ehekaihiyotiukan', 'ehekaihyotiukan', 'ihiyotiakan', 'ihiyotiatikan', 'ihiyotikan', 'ihtlanikan', 'ihtlanitikan'],
	"respondidamente":'nankiliakan',
	"retádamente":'chikauilikan',
	"reventadamente":'kueponiakan',
	"reverenciadamente": ['tlalpalokan', 'tzinikan', 'tzinitikan'],
	"ricamente":'achtikan',
	"riegadamente":'apantitlazakan',
	"robadamente":'ixtekikan',
	"rociádamente": ['apantitlazakan', 'auachtikan'],
	"rojamente":'chiltikan',
	"rojas":'chiltikan',
	"rojosamente":'chiltikan',
	"rosamente": ['tlapaltikan', 'xokoxochitl'],
	"rotamente":'tzomonikan',
	"rubiamente":'iztakan',
	"rubias":'iztakan',
	"rubiosamente":'iztakan',
	"rápidamente":'ueliuikan',
	"sabiamente":'tlamatiki',
	"sabiosamente":'tlamatiki',
	"sacadamente": ['kilikan', 'kizakan', 'kizakuikan'],
	"salidamente":'kizakan',
	"salpicádamente":'atlatzinkuiniakan',
	"saltadamente":'tzikuinikan',
	"saludadamente":'tlahpalokan',
	"salvadamente":'makixtiakan',
	"secadamente": ['uahkiakan', 'uahkiatikan'],
	"sedentariamente":'pepechouakan',
	"sedientamente":'amiktokan',
	"seducidamente":'ixkuepakan',
	"seguidamente":'totokakan',
	"seguramente":'chimalikan',
	"segúnmente":'ixmatipan',
	"sembradamente":'tokakan',
	"semejantemente":'neneuakan',
	"sencillamente":'ayouikan',
	"sendamente":'ohtli',
	"sensitivamente":'tekochmamatikan',
	"sentidamente":'tekochmamakan',
	"separadamente": ['tekikan', 'tzokan', 'tzotikan', 'zezekikan'],
	"serenamente":'mantikan',
	"servidamente":'tekitiyokan',
	"señaladamente": ['axiltiakan', 'kilikan', 'kimahpiliuiakan'],
	"señalizadamente":'axiltiayotikan',
	"si":'intla',
	"siempre":'nochipa',
	"significadamente":'machiliakan',
	"significativamente":'ihuanikan',
	"siguientemente":'totokakan',
	"simplemente": ['amotekitikan', 'amoyouikan', 'ayotikan', 'ayouikan'],
	"sobradamente":'panuia',
	"sobrepasadamente":'chimeuakan',
	"sobrepasosamente":'chimeuatikan',
	"sobresalientemente":'ihuantokan',
	"sobresaltadamente": ['ahkomanakan', 'ahkomanatikan'],
	"socavadamente":'achikuepalakan',
	"socavativamente":'achikuepalaliztikan',
	"solamente":'izelpan',
	"solamente":'izelpan',
	"solamentemente":'izelpan',
	"solitamente":'izel',
	"solo":'izel',
	"soltadamente":'kauiliakan',
	"sombramente":'zeualli',
	"sonadamente":'tzilinikan',
	"sonreidamente": ['ixuetzkakan', 'uetzkakan'],
	"sonrojádamente":'chichileuakan',
	"sopesadamente":'eheukan',
	"sopladamente":'ilpitzakan',
	"soportadamente": ['chikoukan', 'mamauakan', 'mamauatikan'],
	"soportamente":'chikoukan',
	"sorprendidamente":'izakan',
	"sorpresamente": ['ayeulli', 'izalli'],
	"sorpresivamente":'izatikan',
	"soñadamente":'kochikan',
	"suave": ['amotlaueltikan', 'amoueltikan', 'ilitikan', 'papatztikan', 'tzinyokan'],
	"suavemente": ['amotlaueltikan', 'amoueltikan', 'ilitikan', 'papatztikan', 'tzinyokan'],
	"suavizádamente":'auaxpeuikan',
	"subidamente":'euakan',
	"submarinamente": ['atlantemokakan', 'atlantzinkakan'],
	"succionádamente":'chichinakan',
	"sucedidamente":'panoyokan',
	"suciamente": ['makauakan', 'makauitl', 'makaukan', 'tzokan', 'tzoktli'],
	"suficiente":'temtikan',
	"suficientemente":'temtikan',
	"sufragadamente":'kuikan',
	"sufridamente":'kokolikan',
	"sugeridamente":'izpanotzakan',
	"sujetadamente": ['kuchokan', 'kuikan'],
	"sumadamente":'iuanyokan',
	"sumergidamente":'akalakiakan',
	"super": ['achtokan', 'ueyikchiuakan'],
	"superadamente":'ueyikchiuakan',
	"superativamente":'ueyikchiutikan',
	"superior": ['achtokan', 'achton'],
	"superiormente": ['achtokan', 'achton'],
	"supermente": ['achtokan', 'ueyikchiuakan'],
	"supuestamente":'neltokan',
	"suspicaz":'amoneltokatokan',
	"suspicazmente":'amoneltokatokan',
	"sustancial":'ihuanikan',
	"sustancialmente":'ihuanikan',
	"sustituidamente":'onchiuayokan',
	"susurradamente":'ixtlakatlatlapouakan',
	"sí":'kemakan',
	"sólidamente":'teyokan',
	"sólo":'izel',
	"sónicamente":'tzilinitikan',
	"tal":'ihkin',
	"taladamente":'kuautekikan',
	"también":'noihki',
	"también":'noihki',
	"tampoco":'amonoihki',
	"tanta":'kexki',
	"tanto":'kexki',
	"tapadamente":'tlapakan',
	"tardadamente":'tlahkakan',
	"tarde":'tlahkan',
	"tardíamente":'tlahpakan',
	"temerosamente":'maohtiki',
	"temiblemente":'maohueltikan',
	"temidamente":'mautiakan',
	"templadamente":'yamantikan',
	"temporalmente": ['imanpan', 'imantzinko', 'manikan'],
	"temporalmente":'imanpan',
	"temporalmentemente":'imanpan',
	"temporareamente": ['imantikan', 'kauikan', 'kautikan'],
	"tempranamente":'kualkan',
	"temprano":'kualkan',
	"tenaz":'amokauhtiyokan',
	"tenazmente":'amokauhtiyokan',
	"tercamente": ['amokauhtiyokan', 'tzontetekan'],
	"terminadamente": ['tlamiakan', 'tlamikan'],
	"terminantemente":'tlamikan',
	"testarudamente": ['amokimatlahtokan', 'amotemahmatikan', 'tzontetekan'],
	"testificadamente":'ixkouakan',
	"testificatoriamente":'ixkouakan',
	"timbradamente":'pipitzkakan',
	"tiradamente":'tlazakan',
	"tiritadamente":'motoliniakan',
	"tiritatoriamente":'motoliniakan',
	"tocadamente":'ixpankuikan',
	"toda":'nochi',
	"todavía":'amoye',
	"todavía":'mazki',
	"toleradamente": ['mamauakan', 'mamauatikan'],
	"tolerantemente":'mamautokan',
	"tomadamente":'kuikan',
	"tontamente": ['koaxokokan', 'kouaxokokan', 'tzontekontlauanki'],
	"torcidamente":'koliuhkikan',
	"torpemente":'yeyetehtikan',
	"torpes":'yeyetehtikan',
	"toscamente": ['tzapaltikan', 'tzatzapaltikan'],
	"totalmente":'nochikan',
	"trabajadamente":'tekitikan',
	"traducidamente":'tlahtolpalayokan',
	"tragadamente":'kuakan',
	"traidamente":'tlauihkokan',
	"tranquilamente":'mantikan',
	"transformadamente": ['itztlakoliuikan', 'xolokan'],
	"transmitidamente":'titlaniyokan',
	"transmutadamente":'itztlakoliuakan',
	"transparenciamente":'chipauakyokan',
	"transparente": ['aiztatokan', 'chipauakan', 'chipauatokan', 'iztakan'],
	"transparentemente": ['aiztatokan', 'chipauakan', 'chipauatokan', 'iztakan'],
	"transpiradamente": ['ihitonyokan', 'ihitonyotikan'],
	"traseramente":'kuitlapan',
	"trasladadamente": ['mamayauikan', 'mamayauitikan', 'olikan', 'olitikan'],
	"trece":'mahtlak uan eyi',
	"trecemente":'mahtlak uan eyi',
	"tremente":'eyi',
	"tres":'eyi',
	"trescientosamente":'mahtlak uan kaxtolpoual',
	"triste": ['amopahpakikan', 'amopakiliztikan'],
	"tristeadamente":'amopahpakikan',
	"tristemente": ['amopahpakikan', 'amopakiliztikan'],
	"trocadamente":'namakakan',
	"trocatoriamente":'namakakan',
	"tronadamente": ['kueponiakan', 'tlapetlaniakan'],
	"trotadamente":'chocholotiukan',
	"truenadamente":'tlapetlaniakan',
	"tumbadamente": ['kantlazakan', 'kotlazakan'],
	"términadamente":'tlamikan',
	"túmente": ['tehua', 'tehuatl'],
	"ubicadamente":'kaniakan',
	"ungidamente":'achtoutikan',
	"unidamente":'uaniakan',
	"untadamente": ['achtoutikan', 'ixpanmoliakan'],
	"ustedemente":'anmeh',
	"vacíamente": ['amo onkakan', 'amokatikan', 'amoonkakan'],
	"valiosamente":'patiyokan',
	"valuadamente":'patiyokan',
	"variablemente":'xolotikan',
	"variadamente":'xolokan',
	"veladamente":'amokochiuakan',
	"velocidadamente":'olikan',
	"velocidatoriamente":'olikan',
	"velozmente":'olikan',
	"venidamente":'ualakan',
	"verdad":'melauak',
	"verdaderamente":'melauakan',
	"verificadamente": ['itachiuakan', 'itachiyokan', 'ni itakan'],
	"verificamente": ['itachiuakan', 'itachiyokan', 'ni itakan'],
	"verificativamente":'onitaliztikan',
	"verificatoriamente":'onitaliztikan',
	"verázmente":'melauakan',
	"vestidamente": ['kemitikan', 'tlakemikan'],
	"viajadamente":'ohtotokakan',
	"viajatoriamente":'ohtotokakan',
	"vibrablemente":'olinikan',
	"vibradamente":'nmooliniakan',
	"vibrativamente":'nmoolinializtikan',
	"vibratoriamente":'moolinializtikan',
	"viciosamente":'makaukan',
	"vigiladamente":'kuitlauiakan',
	"vigilosamente":'kuitlauiatikan',
	"vinculadamente": ['mekauatikan', 'mekakan', 'mekatikan', 'mekauakan'],
	"violadamente":'ihuiyaukan',
	"violentadamente":'ihuiyaukan',
	"violentamente":'ihuiyaukan',
	"virtualmente":'amonelikan',
	"visiblemente":'itayokan',
	"visiblemente":'itayopan',
	"vislumbradamente":'itaazikan',
	"vislumbrativamente":'itaaziliztikan',
	"vistamente":'itayotl',
	"vivamente": ['nemitokan', 'nemiyokan'],
	"vividamente":'nemikan',
	"voladamente":'patlanikan',
	"voltedamente":'kuepayotikan',
	"votadamente":'kuikan',
	"vívidamente": ['nemikan', 'nemitikan'],
	"ya":'ye',
	"ásperamente":'teteltikan',
	"únicamente":'zekan',
#	"mientras":'ipan kauitl',
	"vulgarmente":'amouelueyikan'
}