# -*- coding: utf-8 -*-
"""
© Roberto Spíndola Barrón, 2026.
Todos los derechos reservados.

Sistema estructural de análisis lingüístico Náhuatl ↔ Español.
Módulo: [MODIFIERS]
Versión: v1.0
Fecha: [23-05-2026]

Prohibida la reproducción, redistribución, extracción estructural,
ingeniería inversa, entrenamiento de modelos de inteligencia artificial
o reutilización no autorizada.
"""

MODIFIERS= {
	" melauak":'precisa',
	" melauak":'preciso',
	" melauak":'precisos',
	"(|O) (O) | •":'126',
	"(|O) (O) | ••":'127',
	"(|O) (O) | •••":'128',
	"(|O) (O) | ••••":'129',
	"(|O) (O) |":'125',
	"(|O) (O) || •":'131',
	"(|O) (O) || ••":'132',
	"(|O) (O) || •••":'133',
	"(|O) (O) || ••••":'134',
	"(|O) (O) ||":'130',
	"(|O) (O) ||| •":'136',
	"(|O) (O) ||| ••":'137',
	"(|O) (O) ||| •••":'138',
	"(|O) (O) ||| ••••":'139',
	"(|O) (O) |||":'135',
	"(|O) (O) •":'121',
	"(|O) (O) ••":'122',
	"(|O) (O) •••":'123',
	"(|O) (O) ••••":'124',
	"(|O) (••O) | •":'146',
	"(|O) (••O) | ••":'147',
	"(|O) (••O) | •••":'148',
	"(|O) (••O) | ••••":'149',
	"(|O) (••O) |":'145',
	"(|O) (••O) || •":'151',
	"(|O) (••O) || ••":'152',
	"(|O) (••O) || •••":'153',
	"(|O) (••O) || ••••":'154',
	"(|O) (••O) ||":'150',
	"(|O) (••O) ||| •":'156',
	"(|O) (••O) ||| ••":'157',
	"(|O) (••O) ||| •••":'158',
	"(|O) (••O) ||| ••••":'159',
	"(|O) (••O) |||":'155',
	"(|O) (••O) •":'141',
	"(|O) (••O) ••":'142',
	"(|O) (••O) •••":'143',
	"(|O) (••O) ••••":'144',
	"(|O) (•••O) | •":'166',
	"(|O) (•••O) | ••":'167',
	"(|O) (•••O) | •••":'168',
	"(|O) (•••O) | ••••":'169',
	"(|O) (•••O) |":'165',
	"(|O) (•••O) || •":'171',
	"(|O) (•••O) || ••":'172',
	"(|O) (•••O) || •••":'173',
	"(|O) (•••O) || ••••":'174',
	"(|O) (•••O) ||":'160',
	"(|O) (•••O) ||":'170',
	"(|O) (•••O) ||| •":'176',
	"(|O) (•••O) ||| ••":'177',
	"(|O) (•••O) ||| •••":'178',
	"(|O) (•••O) ||| ••••":'179',
	"(|O) (•••O) |||":'175',
	"(|O) (•••O) •":'161',
	"(|O) (•••O) ••":'162',
	"(|O) (•••O) •••":'163',
	"(|O) (•••O) ••••":'164',
	"(|O) (••••O) | •":'186',
	"(|O) (••••O) | ••":'187',
	"(|O) (••••O) | •••":'188',
	"(|O) (••••O) | ••••":'189',
	"(|O) (••••O) |":'185',
	"(|O) (••••O) || •":'191',
	"(|O) (••••O) || ••":'192',
	"(|O) (••••O) || •••":'193',
	"(|O) (••••O) || ••••":'194',
	"(|O) (••••O) ||":'190',
	"(|O) (••••O) ||| •":'196',
	"(|O) (••••O) ||| ••":'197',
	"(|O) (••••O) ||| •••":'198',
	"(|O) (••••O) ||| ••••":'199',
	"(|O) (••••O) |||":'195',
	"(|O) (••••O) •":'181',
	"(|O) (••••O) ••":'182',
	"(|O) (••••O) •••":'183',
	"(|O) (••••O) ••••":'184',
	"(|O) (••••O)":'180',
	"(|O) | •":'106',
	"(|O) | ••":'107',
	"(|O) | •••":'108',
	"(|O) | ••••":'109',
	"(|O) |":'105',
	"(|O) || •":'111',
	"(|O) || ••":'112',
	"(|O) || •••":'113',
	"(|O) || ••••":'114',
	"(|O) ||":'110',
	"(|O) ||| •":'116',
	"(|O) ||| ••":'117',
	"(|O) ||| •••":'118',
	"(|O) ||| ••••":'119',
	"(|O) |||":'115',
	"(|O) •":'101',
	"(|O) •O":'120',
	"(|O) ••":'102',
	"(|O) ••O":'140',
	"(|O) •••":'103',
	"(|O) ••••":'104',
	"(|O)":'100',
	"(||O) (O) | •":'226',
	"(||O) (O) | ••":'227',
	"(||O) (O) | •••":'228',
	"(||O) (O) | ••••":'229',
	"(||O) (O) |":'225',
	"(||O) (O) || •":'231',
	"(||O) (O) || ••":'232',
	"(||O) (O) || •••":'233',
	"(||O) (O) || ••••":'234',
	"(||O) (O) ||":'230',
	"(||O) (O) ||| •":'236',
	"(||O) (O) ||| ••":'237',
	"(||O) (O) ||| •••":'238',
	"(||O) (O) ||| ••••":'239',
	"(||O) (O) |||":'235',
	"(||O) (O) •":'221',
	"(||O) (O) ••":'222',
	"(||O) (O) •••":'223',
	"(||O) (O) ••••":'224',
	"(||O) (••O) | •":'246',
	"(||O) (••O) | ••":'247',
	"(||O) (••O) | •••":'248',
	"(||O) (••O) | ••••":'249',
	"(||O) (••O) |":'245',
	"(||O) (••O) || •":'251',
	"(||O) (••O) || ••":'252',
	"(||O) (••O) || •••":'253',
	"(||O) (••O) || ••••":'254',
	"(||O) (••O) ||":'250',
	"(||O) (••O) ||| •":'256',
	"(||O) (••O) ||| ••":'257',
	"(||O) (••O) ||| •••":'258',
	"(||O) (••O) ||| ••••":'259',
	"(||O) (••O) |||":'255',
	"(||O) (••O) •":'241',
	"(||O) (••O) ••":'242',
	"(||O) (••O) •••":'243',
	"(||O) (••O) ••••":'244',
	"(||O) (•••O) | •":'266',
	"(||O) (•••O) | ••":'267',
	"(||O) (•••O) | •••":'268',
	"(||O) (•••O) | ••••":'269',
	"(||O) (•••O) |":'265',
	"(||O) (•••O) || •":'271',
	"(||O) (•••O) || ••":'272',
	"(||O) (•••O) || •••":'273',
	"(||O) (•••O) || ••••":'274',
	"(||O) (•••O) ||":'260',
	"(||O) (•••O) ||":'270',
	"(||O) (•••O) ||| •":'276',
	"(||O) (•••O) ||| ••":'277',
	"(||O) (•••O) ||| •••":'278',
	"(||O) (•••O) ||| ••••":'279',
	"(||O) (•••O) |||":'275',
	"(||O) (•••O) •":'261',
	"(||O) (•••O) ••":'262',
	"(||O) (•••O) •••":'263',
	"(||O) (•••O) ••••":'264',
	"(||O) (••••O) | •":'286',
	"(||O) (••••O) | ••":'287',
	"(||O) (••••O) | •••":'288',
	"(||O) (••••O) | ••••":'289',
	"(||O) (••••O) |":'285',
	"(||O) (••••O) || •":'291',
	"(||O) (••••O) || ••":'292',
	"(||O) (••••O) || •••":'293',
	"(||O) (••••O) || ••••":'294',
	"(||O) (••••O) ||":'290',
	"(||O) (••••O) ||| •":'296',
	"(||O) (••••O) ||| ••":'297',
	"(||O) (••••O) ||| •••":'298',
	"(||O) (••••O) ||| ••••":'299',
	"(||O) (••••O) |||":'295',
	"(||O) (••••O) •":'281',
	"(||O) (••••O) ••":'282',
	"(||O) (••••O) •••":'283',
	"(||O) (••••O) ••••":'284',
	"(||O) (••••O)":'280',
	"(||O) | •":'206',
	"(||O) | ••":'207',
	"(||O) | •••":'208',
	"(||O) | ••••":'209',
	"(||O) |":'205',
	"(||O) || •":'211',
	"(||O) || ••":'212',
	"(||O) || •••":'213',
	"(||O) || ••••":'214',
	"(||O) ||":'210',
	"(||O) ||| •":'216',
	"(||O) ||| ••":'217',
	"(||O) ||| •••":'218',
	"(||O) ||| ••••":'219',
	"(||O) |||":'215',
	"(||O) •":'201',
	"(||O) •O":'220',
	"(||O) ••":'202',
	"(||O) ••O":'240',
	"(||O) •••":'203',
	"(||O) ••••":'204',
	"(||O)":'200',
	"(|||O) (O) | •":'326',
	"(|||O) (O) | ••":'327',
	"(|||O) (O) | •••":'328',
	"(|||O) (O) | ••••":'329',
	"(|||O) (O) |":'325',
	"(|||O) (O) || •":'331',
	"(|||O) (O) || ••":'332',
	"(|||O) (O) || •••":'333',
	"(|||O) (O) || ••••":'334',
	"(|||O) (O) ||":'330',
	"(|||O) (O) ||| •":'336',
	"(|||O) (O) ||| ••":'337',
	"(|||O) (O) ||| •••":'338',
	"(|||O) (O) ||| ••••":'339',
	"(|||O) (O) |||":'335',
	"(|||O) (O) •":'321',
	"(|||O) (O) ••":'322',
	"(|||O) (O) •••":'323',
	"(|||O) (O) ••••":'324',
	"(|||O) (••O) | •":'346',
	"(|||O) (••O) | ••":'347',
	"(|||O) (••O) | •••":'348',
	"(|||O) (••O) | ••••":'349',
	"(|||O) (••O) |":'345',
	"(|||O) (••O) || •":'351',
	"(|||O) (••O) || ••":'352',
	"(|||O) (••O) || •••":'353',
	"(|||O) (••O) || ••••":'354',
	"(|||O) (••O) ||":'350',
	"(|||O) (••O) ||| •":'356',
	"(|||O) (••O) ||| ••":'357',
	"(|||O) (••O) ||| •••":'358',
	"(|||O) (••O) ||| ••••":'359',
	"(|||O) (••O) |||":'355',
	"(|||O) (••O) •":'341',
	"(|||O) (••O) ••":'342',
	"(|||O) (••O) •••":'343',
	"(|||O) (••O) ••••":'344',
	"(|||O) (•••O) | •":'366',
	"(|||O) (•••O) | ••":'367',
	"(|||O) (•••O) | •••":'368',
	"(|||O) (•••O) | ••••":'369',
	"(|||O) (•••O) |":'365',
	"(|||O) (•••O) || •":'371',
	"(|||O) (•••O) || ••":'372',
	"(|||O) (•••O) || •••":'373',
	"(|||O) (•••O) || ••••":'374',
	"(|||O) (•••O) ||":'360',
	"(|||O) (•••O) ||":'370',
	"(|||O) (•••O) ||| •":'376',
	"(|||O) (•••O) ||| ••":'377',
	"(|||O) (•••O) ||| •••":'378',
	"(|||O) (•••O) ||| ••••":'379',
	"(|||O) (•••O) |||":'375',
	"(|||O) (•••O) •":'361',
	"(|||O) (•••O) ••":'362',
	"(|||O) (•••O) •••":'363',
	"(|||O) (•••O) ••••":'364',
	"(|||O) (••••O) | •":'386',
	"(|||O) (••••O) | ••":'387',
	"(|||O) (••••O) | •••":'388',
	"(|||O) (••••O) | ••••":'389',
	"(|||O) (••••O) |":'385',
	"(|||O) (••••O) || •":'391',
	"(|||O) (••••O) || ••":'392',
	"(|||O) (••••O) || •••":'393',
	"(|||O) (••••O) || ••••":'394',
	"(|||O) (••••O) ||":'390',
	"(|||O) (••••O) ||| •":'396',
	"(|||O) (••••O) ||| ••":'397',
	"(|||O) (••••O) ||| •••":'398',
	"(|||O) (••••O) ||| ••••":'399',
	"(|||O) (••••O) |||":'395',
	"(|||O) (••••O) •":'381',
	"(|||O) (••••O) ••":'382',
	"(|||O) (••••O) •••":'383',
	"(|||O) (••••O) ••••":'384',
	"(|||O) (••••O)":'380',
	"(|||O) | •":'306',
	"(|||O) | •":'66',
	"(|||O) | ••":'307',
	"(|||O) | ••":'67',
	"(|||O) | •••":'308',
	"(|||O) | •••":'68',
	"(|||O) | ••••":'309',
	"(|||O) | ••••":'69',
	"(|||O) |":'305',
	"(|||O) |":'65',
	"(|||O) || •":'311',
	"(|||O) || •":'71',
	"(|||O) || ••":'312',
	"(|||O) || ••":'72',
	"(|||O) || •••":'313',
	"(|||O) || •••":'73',
	"(|||O) || ••••":'314',
	"(|||O) || ••••":'74',
	"(|||O) ||":'310',
	"(|||O) ||":'70',
	"(|||O) ||| •":'316',
	"(|||O) ||| •":'76',
	"(|||O) ||| ••":'317',
	"(|||O) ||| ••":'77',
	"(|||O) ||| •••":'318',
	"(|||O) ||| •••":'78',
	"(|||O) ||| ••••":'319',
	"(|||O) ||| ••••":'79',
	"(|||O) |||":'315',
	"(|||O) |||":'75',
	"(|||O) •":'301',
	"(|||O) •":'61',
	"(|||O) •O":'320',
	"(|||O) ••":'302',
	"(|||O) ••":'62',
	"(|||O) ••O":'340',
	"(|||O) •••":'303',
	"(|||O) •••":'63',
	"(|||O) ••••":'304',
	"(|||O) ••••":'64',
	"(|||O)":'300',
	"(|||O)":'60',
	"(ʎ) (O) | •":'426',
	"(ʎ) (O) | ••":'427',
	"(ʎ) (O) | •••":'428',
	"(ʎ) (O) | ••••":'429',
	"(ʎ) (O) |":'425',
	"(ʎ) (O) || •":'431',
	"(ʎ) (O) || ••":'432',
	"(ʎ) (O) || •••":'433',
	"(ʎ) (O) || ••••":'434',
	"(ʎ) (O) ||":'430',
	"(ʎ) (O) ||| •":'436',
	"(ʎ) (O) ||| ••":'437',
	"(ʎ) (O) ||| •••":'438',
	"(ʎ) (O) ||| ••••":'439',
	"(ʎ) (O) |||":'435',
	"(ʎ) (O) •":'421',
	"(ʎ) (O) ••":'422',
	"(ʎ) (O) •••":'423',
	"(ʎ) (O) ••••":'424',
	"(ʎ) (••O) | •":'446',
	"(ʎ) (••O) | ••":'447',
	"(ʎ) (••O) | •••":'448',
	"(ʎ) (••O) | ••••":'449',
	"(ʎ) (••O) |":'445',
	"(ʎ) (••O) || •":'451',
	"(ʎ) (••O) || ••":'452',
	"(ʎ) (••O) || •••":'453',
	"(ʎ) (••O) || ••••":'454',
	"(ʎ) (••O) ||":'450',
	"(ʎ) (••O) ||| •":'456',
	"(ʎ) (••O) ||| ••":'457',
	"(ʎ) (••O) ||| •••":'458',
	"(ʎ) (••O) ||| ••••":'459',
	"(ʎ) (••O) |||":'455',
	"(ʎ) (••O) •":'441',
	"(ʎ) (••O) ••":'442',
	"(ʎ) (••O) •••":'443',
	"(ʎ) (••O) ••••":'444',
	"(ʎ) (•••O) | •":'466',
	"(ʎ) (•••O) | ••":'467',
	"(ʎ) (•••O) | •••":'468',
	"(ʎ) (•••O) | ••••":'469',
	"(ʎ) (•••O) |":'465',
	"(ʎ) (•••O) || •":'471',
	"(ʎ) (•••O) || ••":'472',
	"(ʎ) (•••O) || •••":'473',
	"(ʎ) (•••O) || ••••":'474',
	"(ʎ) (•••O) ||":'460',
	"(ʎ) (•••O) ||":'470',
	"(ʎ) (•••O) ||| •":'476',
	"(ʎ) (•••O) ||| ••":'477',
	"(ʎ) (•••O) ||| •••":'478',
	"(ʎ) (•••O) ||| ••••":'479',
	"(ʎ) (•••O) |||":'475',
	"(ʎ) (•••O) •":'461',
	"(ʎ) (•••O) ••":'462',
	"(ʎ) (•••O) •••":'463',
	"(ʎ) (•••O) ••••":'464',
	"(ʎ) (••••O) | •":'486',
	"(ʎ) (••••O) | ••":'487',
	"(ʎ) (••••O) | •••":'488',
	"(ʎ) (••••O) | ••••":'489',
	"(ʎ) (••••O) |":'485',
	"(ʎ) (••••O) || •":'491',
	"(ʎ) (••••O) || ••":'492',
	"(ʎ) (••••O) || •••":'493',
	"(ʎ) (••••O) || ••••":'494',
	"(ʎ) (••••O) ||":'490',
	"(ʎ) (••••O) ||| •":'496',
	"(ʎ) (••••O) ||| ••":'497',
	"(ʎ) (••••O) ||| •••":'498',
	"(ʎ) (••••O) ||| ••••":'499',
	"(ʎ) (••••O) |||":'495',
	"(ʎ) (••••O) •":'481',
	"(ʎ) (••••O) ••":'482',
	"(ʎ) (••••O) •••":'483',
	"(ʎ) (••••O) ••••":'484',
	"(ʎ) (••••O)":'480',
	"(ʎ) | •":'406',
	"(ʎ) | ••":'407',
	"(ʎ) | •••":'408',
	"(ʎ) | ••••":'409',
	"(ʎ) |":'405',
	"(ʎ) || •":'411',
	"(ʎ) || ••":'412',
	"(ʎ) || •••":'413',
	"(ʎ) || ••••":'414',
	"(ʎ) ||":'410',
	"(ʎ) ||| •":'416',
	"(ʎ) ||| ••":'417',
	"(ʎ) ||| •••":'418',
	"(ʎ) ||| ••••":'419',
	"(ʎ) |||":'415',
	"(ʎ) •":'401',
	"(ʎ) •O":'420',
	"(ʎ) ••":'402',
	"(ʎ) ••O":'440',
	"(ʎ) •••":'403',
	"(ʎ) ••••":'404',
	"(••O) | •":'46',
	"(••O) | ••":'47',
	"(••O) | •••":'48',
	"(••O) | ••••":'49',
	"(••O) |":'45',
	"(••O) || •":'51',
	"(••O) || ••":'52',
	"(••O) || •••":'53',
	"(••O) || ••••":'54',
	"(••O) ||":'50',
	"(••O) ||| •":'56',
	"(••O) ||| ••":'57',
	"(••O) ||| •••":'58',
	"(••O) ||| ••••":'59',
	"(••O) |||":'55',
	"(••O) •":'41',
	"(••O) ••":'42',
	"(••O) •••":'43',
	"(••O) ••••":'44',
	"(••O)":'40',
	"(••••O) | •":'86',
	"(••••O) | ••":'87',
	"(••••O) | •••":'88',
	"(••••O) | ••••":'89',
	"(••••O) |":'85',
	"(••••O) || •":'91',
	"(••••O) || ••":'92',
	"(••••O) || •••":'93',
	"(••••O) || ••••":'94',
	"(••••O) ||":'90',
	"(••••O) ||| •":'96',
	"(••••O) ||| ••":'97',
	"(••••O) ||| •••":'98',
	"(••••O) ||| ••••":'99',
	"(••••O) |||":'95',
	"(••••O) •":'81',
	"(••••O) ••":'82',
	"(••••O) •••":'83',
	"(••••O) ••••":'84',
	"(••••O)":'80',
	"aayok":'jugoso',
	"achihko":'estrecha',
	"achihko":'estrecho',
	"achik":'breve',
	"achik":'corta',
	"achik":'corto',
	"achik":'poco',
	"achikopalatik":'acongojada',
	"achikopalatik":'acongojado',
	"achikualtik":'mejor',
	"achikuepalaliztik":'socavativa',
	"achikuepalaliztik":'socavativo',
	"achikuepalik":'ofensiva',
	"achikuepalik":'ofensivo',
	"achikuepaltik":'irrespetuoso',
	"achitik":'aguañoso',
	"achiutetemotok":'escurrida',
	"achiutetemotok":'escurrido',
	"achokzepak":'dramática',
	"achokzepak":'dramático',
	"achpaniliztik":'abundativa',
	"achpaniliztik":'abundativo',
	"achpaniliztik":'acumulativa',
	"achpaniliztik":'acumulativo',
	"achpaniliztik":'acumulatoria',
	"achpaniliztik":'acumulatorio',
	"achpanitik":'abusiva',
	"achpanitik":'abusivo',
	"achpanitik":'anticipativa',
	"achpanitik":'anticipativo',
	"achtik":'rica',
	"achtik":'rico',
	"achto":'antes',
	"achtoilik":'predictiva',
	"achtoilik":'predictivo',
	"achtoilik":'preventiva',
	"achtoilik":'preventivo',
	"achtoilitok":'prevenida',
	"achtoilitok":'prevenido',
	"achtok":'respecto',
	"achtok":'super',
	"achtok":'superior',
	"achtokan":'superior',
	"achtokaxtilan":'prehispánica',
	"achtokaxtilan":'prehispánico',
	"achtokchiutik":'anticipativa',
	"achtokchiutik":'anticipativo',
	"achtokzepalatik":'exajerada',
	"achtokzepalatik":'exajerado',
	"achton":'superior',
	"achtopak":'antigua',
	"achtopak":'antiguo',
	"achtopanespañoltik":'prehispánica',
	"achtopanespañoltik":'prehispánico',
	"achtoutik":'ungida',
	"achtoutik":'ungido',
	"achtoutik":'untada',
	"achtoutik":'untado',
	"acostada":'tekak',
	"acostado":'tekak',
	"ahkolkuk":'encorbado',
	"ahkomanatik":'sobresaltada',
	"ahkomanatik":'sobresaltado',
	"ahkopatiyotl":'caro',
	"ahkuanatik":'progresado',
	"ahuak":'regañado',
	"ahualki":'regañón',
	"ahuanki":'regañona',
	"ahuikauatik":'perfumado',
	"ahuikauliztik":'aromática',
	"ahuikauliztik":'aromático',
	"ahuiniliztik":'exhortada',
	"ahuiniliztik":'exhortado',
	"ahxiltik":'puntero',
	"aik":'jamás',
	"aik":'nunca',
	"aiztatok":'transparente',
	"akalakiak":'hundida',
	"akalakiak":'hundido',
	"akalakiak":'sumergida',
	"akalakiak":'sumergido',
	"akaleuyotik":'fletación',
	"akalkoyotik":'embarcada',
	"akalkoyotik":'embarcado',
	"akamopoloki":'náufraga',
	"akamopoloki":'náufrago',
	"akauiliztik":'adulterada',
	"akauiliztik":'adulterado',
	"akauitik":'desvirtuado',
	"akin":'quien',
	"akin":'quién',
	"akin":'quiénes',
	"alauahtik":'flemosa',
	"alauahtik":'flemoso',
	"alauak":'flemosa',
	"alauak":'flemoso',
	"alauak":'mocoso',
	"alaualiztik":'extornudada',
	"alaualiztik":'extornudado',
	"alaualiztik":'resbalada',
	"alaualiztik":'resbalado',
	"alauatik":'mocoso',
	"alauayotik":'deslizada',
	"alauayotik":'deslizado',
	"alaxtik":'lisa',
	"alaxtik":'liso',
	"alaxtik":'naranja',
	"alaxtik":'resbalosa',
	"alaxtik":'resbaloso',
	"altik":'bañada',
	"altik":'bañado',
	"amakin":'ninguna',
	"amakin":'ninguno',
	"amanak":'hervida',
	"amanak":'hervido',
	"amatekitik":'programada',
	"amatekitik":'programado',
	"amatzomayotik":'encuadernada',
	"amatzomayotik":'encuadernado',
	"amiktok":'sedienta',
	"amiktok":'sediento',
	"amikyotik":'ahogada',
	"amikyotik":'ahogado',
	"amiminatik":'colada',
	"amiminatik":'colado',
	"amiminatik":'filtrada',
	"amiminatik":'filtrado',
	"amitla":'nada',
	"amo onkak":'vacía',
	"amo onkak":'vacío',
	"amo yolpachok":'inquieta',
	"amo yolpachok":'inquieto',
	"amo":'no',
	"amochikualli":'ilícita',
	"amochikualli":'ilícito',
	"amochimalik":'insegura',
	"amochimalik":'inseguro',
	"amochiuak":'pasiva',
	"amochiuak":'pasivas',
	"amochiuak":'pasivo',
	"amochiuak":'pasivos',
	"amochiualiz":'ilícita',
	"amochiualiz":'ilícito',
	"amochiualoki":'ilícita',
	"amochiualoki":'ilícito',
	"amoetik":'ligera',
	"amoetik":'ligero',
	"amoihuanik":'innecesaria',
	"amoihuanik":'innecesario',
	"amoihuanik":'irrelevante',
	"amoixmatiki":'ignorante',
	"amoixmatiuak":'confundida',
	"amoixmatiuak":'confundido',
	"amok":'nulo',
	"amokatik":'inestable',
	"amokatik":'vacía',
	"amokatik":'vacío',
	"amokauak":'cohibida',
	"amokauak":'cohibido',
	"amokauak":'impedida',
	"amokauak":'impedido',
	"amokaualtik":'bloqueada',
	"amokaualtik":'bloqueado',
	"amokauatik":'limitada',
	"amokauatik":'limitado',
	"amokauhtitok":'persistente',
	"amokauhtiyok":'tenaz',
	"amokauhtiyok":'terca',
	"amokauhtiyok":'terco',
	"amokauik":'inquieto',
	"amokauik":'nervioso',
	"amoketzalyotl":'horrible',
	"amokimatlahtok":'testaruda',
	"amokimatlahtok":'testarudo',
	"amokual ahuiak":'apestosa',
	"amokual ahuiak":'apestoso',
	"amokual omochiuk":'malhecho',
	"amokual teilchiuak":'maldecido',
	"amokual tlachiualli":'malhecho',
	"amokual tzinkayoki":'irrespetuoso',
	"amokualli":'mal',
	"amokualli":'mala',
	"amokualli":'malo',
	"amokualteilchiuatik":'abominada',
	"amokualteilchiuatik":'abominado',
	"amokualteilchiuk":'abominada',
	"amokualteilchiuk":'abominado',
	"amokualtik":'inadecuada',
	"amokualtik":'inadecuado',
	"amokualtik":'peor',
	"amokualtiki":'maldito',
	"amokualtiki":'perversa',
	"amokualtiki":'perverso',
	"amokualtlamik":'inexacta',
	"amokualtlamik":'inexacto',
	"amokualtlamik":'inexactos',
	"amokualtzaihtoka":'intrigosa',
	"amokualtzaihtoka":'intrigoso',
	"amokualtzailihka":'intrigosa',
	"amokualtzailihka":'intrigoso',
	"amokualtzin":'desagradable',
	"amokualtzin":'fea',
	"amokualtzin":'feo',
	"amokualyok":'peor',
	"amokueltikyotl":'debilidad',
	"amomelauak":'imprecisa',
	"amomelauak":'impreciso',
	"amomelauak":'imprecisos',
	"amomelauak":'incorrecta',
	"amomelauak":'incorrecto',
	"amomiak kualtik":'pésima',
	"amomiak kualtik":'pésimo',
	"amonamiktiak":'diferida',
	"amonamiktiak":'diferido',
	"amonelihtoki":'mentiroso',
	"amonelik":'aparente',
	"amonelik":'virtual',
	"amoneltok":'aparente',
	"amoneltokatok":'suspicaz',
	"amonepanpatik":'indisponible',
	"amonoihki":'tampoco',
	"amoonkak":'vacía',
	"amoonkak":'vacío',
	"amopahpakik":'triste',
	"amopakiliztik":'triste',
	"amopatiyok":'barata',
	"amopatiyok":'barato',
	"amopatiyotik":'barata',
	"amopatiyotik":'barato',
	"amopoualyotl":'infinita',
	"amopoualyotl":'infinito',
	"amote yayauaktik":'clara',
	"amote yayauaktik":'claro',
	"amotekitik":'simple',
	"amotemahmatik":'testaruda',
	"amotemahmatik":'testarudo',
	"amotemik":'incompleta',
	"amotemik":'incompleto',
	"amotetlamatiki":'ingenua',
	"amotetlamatiki":'ingenuas',
	"amotetlamatiki":'ingenuo',
	"amotetlamatiki":'ingenuos',
	"amoteyauaktik":'clara',
	"amotla":'sin',
	"amotlamatiki":'ignorante',
	"amotlamatiki":'ignorantes',
	"amotlamikyan":'infinita',
	"amotlamikyan":'infinito',
	"amotlamyotl":'infinita',
	"amotlamyotl":'infinito',
	"amotlaolli":'reposo',
	"amotlaolyotl":'reposo',
	"amotlaueltik":'suave',
	"amotzalik":'inútil',
	"amotzatzalik":'inútil',
	"amotzinyok":'descorteses',
	"amotzinyok":'descortés',
	"amotzinyok":'irrespetuosa',
	"amotzinyok":'irrespetuoso',
	"amotzinyok":'irrespetuosos',
	"amotzontlak":'pelona',
	"amotzontlak":'pelón',
	"amoueltik":'incapaces',
	"amoueltik":'incapaz',
	"amoueltik":'suave',
	"amouelueyik":'vulgar',
	"amoye":'todavía',
	"amoyoki":'apática',
	"amoyoki":'apático',
	"amoyoki":'perezosa',
	"amoyoki":'perezoso',
	"amoyouik":'simple',
	"amoyouitiyotl":'facilitación',
	"aolinik":'hidráulica',
	"aolinik":'hidráulico',
	"apachiuaki":'húmeda',
	"apachiuaki":'húmedo',
	"apochtik":'necia',
	"apochtik":'necio',
	"atiak":'humeda',
	"atiak":'humedo',
	"atik":'acuosa',
	"atik":'acuoso',
	"atik":'acuática',
	"atik":'acuático',
	"atl olinik":'hidráulica',
	"atl olinik":'hidráulico',
	"atlantemokak":'submarina',
	"atlantemokak":'submarino',
	"atlantzinkak":'submarina',
	"atlantzinkak":'submarino',
	"auak":'derretida',
	"auak":'derretido',
	"auaxpeuik":'diluida',
	"auaxpeuik":'diluido',
	"auiltiak":'divertida',
	"auiltiak":'divertido',
	"auipaloliak":'distribuida',
	"auipaloliak":'distribuido',
	"axiltiayotik":'señalizada',
	"axiltiayotik":'señalizado',
	"axiltiayotl":'apuntada',
	"axiltiayotl":'apuntado',
	"axka":'propia',
	"axka":'propio',
	"axkan":'hoy',
	"axkantik":'moderna',
	"axkantik":'moderno',
	"axkauh":'propia',
	"axkauh":'propio',
	"axolohtiak":'derretida',
	"axolohtiak":'derretido',
	"ayak":'nadie',
	"ayeulli":'sorpresa',
	"ayok":'acuosa',
	"ayok":'acuoso',
	"ayolotl":'debilidad',
	"ayotik":'simple',
	"ayouik":'fácil',
	"ayouik":'fáciles',
	"ayouik":'sencillas',
	"ayouik":'sencillo',
	"ayouik":'sencillos',
	"ayouik":'simple',
	"azihtekatl":'aproximador',
	"azihtok":'alcanzante',
	"azihtok":'aproximante',
	"azihtok":'perspicaz',
	"azuhkan":'pronta',
	"azuhkan":'pronto',
	"chapotik":'negro',
	"chauaki":'celoso',
	"chautilki":'egoísta',
	"chichiuayok":'constituida',
	"chichiuayok":'constituido',
	"chikaua":'forzar',
	"chikauak":'dura',
	"chikauak":'duro',
	"chikauak":'firme',
	"chikauak":'fuerte',
	"chikauak":'resistente',
	"chikauak":'rígido',
	"chikauakan":'fuertemente',
	"chikauaktli":'fuerza',
	"chikauayotl":'fortaleza',
	"chikipilli":'8000',
	"chikipiluako":'1/400',
	"chiknauiko":'1/9',
	"chiknautetl":'9°',
	"chikoazentetl":'6°',
	"chikoazentetl":'sexto',
	"chikoazeuako":'1/6',
	"chikoeytetl":'8°',
	"chikoeyuako":'1/8',
	"chikome":'siete',
	"chikomkan":'1/7',
	"chikomtetl":'7°',
	"chikomtetl":'séptimo',
	"chikouk":'aguanta',
	"chikouk":'aguanto',
	"chikouk":'soporta',
	"chikouk":'soporto',
	"chilok":'pica',
	"chilok":'pico',
	"chiltik":'picoso',
	"chiltik":'roja',
	"chiltik":'rojas',
	"chiltik":'rojo',
	"chiltik":'rojos',
	"chimalik":'segura',
	"chimalik":'seguro',
	"chimeuatik":'sobrepasosa',
	"chimeuatik":'sobrepasoso',
	"chipauak":'clara',
	"chipauak":'claro',
	"chipauak":'inmaculada',
	"chipauak":'inmaculado',
	"chipauak":'transparente',
	"chipauakyok":'transparencia',
	"chipauatik":'aclarosa',
	"chipauatik":'aclaroso',
	"chipauatok":'transparente',
	"chiuak":'activa',
	"chiuak":'activas',
	"chiuak":'activo',
	"chiuak":'activos',
	"chiuatik":'ejecutosa',
	"chiuatik":'ejecutoso',
	"chiuayo":'hecho',
	"chiuayotl":'hecha',
	"chiuiko":'chueco',
	"chiuiliak":'insinuada',
	"chiuiliak":'insinuado',
	"chiuiliak":'provocada',
	"chiuiliak":'provocado',
	"choloeuak":'galopatoria',
	"choloeuak":'galopatorio',
	"chopitik":'picudo',
	"chopitik":'puntiagudo',
	"chotik":'barata',
	"chotik":'barato',
	"chupitik":'chupeteada',
	"chupitik":'chupeteado',
	"chupitok":'chupante',
	"ehekatik":'airoso',
	"ehkotik":'llegada',
	"ehkotik":'llegado',
	"ekehtzatik":'electrónica',
	"ekehtzatik":'electrónico',
	"etik":'pesada',
	"etik":'pesado',
	"etiktlahtolik":'grosero',
	"etiyok":'másico',
	"euak":'erigida',
	"euak":'erigido',
	"euak":'priorizada',
	"euak":'priorizado',
	"euak":'subida',
	"euak":'subido',
	"eyi":'tres',
	"eyichikipiluako":'1/1200',
	"eyiuakan":'triángulo',
	"eyiuako":'1/3',
	"halik":'cremoso',
	"i":'sus',
	"ihitonyotik":'transpirada',
	"ihitonyotik":'transpirado',
	"ihiyotiatik":'respirada',
	"ihiyotiatik":'respirado',
	"ihiyotik":'respirada',
	"ihiyotik":'respirado',
	"ihkampa":'atrás',
	"ihkin":'así',
	"ihkin":'tal',
	"ihtlaniak":'pedida',
	"ihtlaniak":'pedido',
	"ihtlanik":'cobrada',
	"ihtlanik":'cobrado',
	"ihtlanitik":'respirada',
	"ihtlanitik":'respirado',
	"ihtok":'dicha',
	"ihtok":'dicho',
	"ihtok":'expresada',
	"ihtok":'expresado',
	"ihtoki":'expresante',
	"ihtoltik":'idiomática',
	"ihtoltik":'idiomático',
	"ihtotik":'bailable',
	"ihtotik":'bailada',
	"ihtotik":'bailado',
	"ihtotik":'danzada',
	"ihtotik":'danzado',
	"ihtotik":'expresada',
	"ihtotik":'expresado',
	"ihtotik":'manifestada',
	"ihtotik":'manifestado',
	"ihtotitik":'bailada',
	"ihtotitik":'bailado',
	"ihtotitik":'danzada',
	"ihtotitik":'danzado',
	"ihuanik":'importante',
	"ihuanik":'necesaria',
	"ihuanik":'necesario',
	"ihuanik":'preponderante',
	"ihuanik":'significativa',
	"ihuanik":'significativo',
	"ihuanik":'sustancial',
	"ihuantok":'sobresaliente',
	"ihuiyauk":'violada',
	"ihuiyauk":'violado',
	"ihuiyauk":'violenta',
	"ihuiyauk":'violento',
	"ihyak":'apestosa',
	"ihyak":'apestoso',
	"ihyaktik":'apestosa',
	"ihyaktik":'apestoso',
	"ik tlamakaki":'dadivoso',
	"ik":'por',
	"ikamakixtiatik":'consolada',
	"ikamakixtiatik":'consolado',
	"ikauak":'espaciada',
	"ikauak":'espaciado',
	"ikchiuak":'causada',
	"ikchiuak":'causado',
	"ikchiuak":'desbocada',
	"ikchiuak":'desbocado',
	"ikchiuak":'provocada',
	"ikchiuak":'provocado',
	"ikiuh":'pronta',
	"ikiuh":'pronto',
	"ikniuhtik":'amable',
	"ikniuhtik":'amables',
	"iknok":'pobre',
	"iknotekatik":'humilde',
	"iknotekatik":'humildes',
	"ikopiak":'guiñada',
	"ikopiak":'guiñado',
	"ikoxik":'madura',
	"ikoxik":'maduro',
	"ikpaleuik":'consolada',
	"ikpaleuik":'consolado',
	"ikpanchiuak":'desenbocada',
	"ikpanchiuak":'desenbocado',
	"ikpapayotl":'reboso',
	"iktlapa":'respecto',
	"iktlapauk":'olvidada',
	"iktlapauk":'olvidado',
	"iktlapauk":'relacionada',
	"iktlapauk":'relacionado',
	"ikuak":'entonces',
	"ikxitzak":'pateada',
	"ikxitzak":'pateado',
	"ikzitok":'maduro',
	"ilama":'vieja',
	"ilamak":'vieja',
	"ilhuik":'festejatoria',
	"ilhuik":'festejatorio',
	"iliayok":'decisiva',
	"iliayok":'decisivo',
	"ilitik":'suave',
	"ilitik":'tierno',
	"ilkauak":'descuidada',
	"ilkauak":'descuidado',
	"ilnamikik":'recordada',
	"ilnamikik":'recordado',
	"ilpitzak":'soplada',
	"ilpitzak":'soplado',
	"imanik":'repente',
	"imanpan":'temporalmente',
	"imantik":'temporarea',
	"imantik":'temporareo',
	"imantzinko":'breve',
	"imantzinko":'temporal',
	"in ayak":'sin',
	"inayaki":'carente',
	"inayatok":'carente',
	"inik":'entonces',
	"inochiinehuiyan":'propiamente',
	"intla":'si',
	"ipal":'a través de',
	"ipal":'por medio de',
	"ipal":'por medio del',
	"ipaliak":'probada',
	"ipaliak":'probado',
	"ipalik":'atravesada',
	"ipalik":'atravesado',
	"ipalik":'cruzada',
	"ipalik":'cruzado',
	"ipalik":'mediada',
	"ipalik":'mediado',
	"ipalixulizko":'osatoria',
	"ipalixulizko":'osatorio',
	"ipalixuliztik":'osada',
	"ipalixuliztik":'osado',
	"ipalixuliztik":'osativa',
	"ipalixuliztik":'osativo',
	"ipalli":'a través de',
	"ipalli":'a través del',
	"ipalli":'por medio de',
	"ipalli":'por medio del',
	"ipan":'sobre',
	"ipantekitik":'ocupada',
	"ipantekitik":'ocupado',
	"itaaziliztik":'oteativa',
	"itaaziliztik":'oteativo',
	"itaaziliztik":'vislumbrativa',
	"itaaziliztik":'vislumbrativo',
	"itachiuak":'comproba',
	"itachiuak":'comprobo',
	"itachiuak":'verifica',
	"itachiuak":'verificada',
	"itachiuak":'verificado',
	"itachiuak":'verifico',
	"itachiyak":'ratificada',
	"itachiyak":'ratificado',
	"itachiyok":'ratificada',
	"itachiyok":'ratificado',
	"itachiyok":'verificada',
	"itachiyok":'verificado',
	"itatok":'visto',
	"itayotl":'vista',
	"itek":'dentro',
	"itekiak":'adentra',
	"itekiak":'adentro',
	"itekiak":'entra',
	"itekiak":'entraña',
	"itekiak":'entraño',
	"itekiak":'entro',
	"itekializtik":'adentrativa',
	"itekializtik":'adentrativo',
	"itekializtik":'entrativa',
	"itekializtik":'entrativo',
	"itekializtik":'entrañativa',
	"itekializtik":'entrañativo',
	"iteknehnemik":'invadida',
	"iteknehnemik":'invadido',
	"ititik":'exhibida',
	"ititik":'exhibido',
	"ititik":'mostrada',
	"ititik":'mostrodo',
	"ititik":'proyectada',
	"ititik":'proyectodo',
	"itlakuik":'determinada',
	"itlakuik":'determinado',
	"itzminak":'calada',
	"itzminak":'calodo',
	"itzminak":'probada',
	"itzminak":'probodo',
	"itztik":'frío',
	"itztlakoliuak":'desdoblada',
	"itztlakoliuak":'desdoblodo',
	"itztlakoliuak":'transmutada',
	"itztlakoliuak":'transmutodo',
	"itztlakoliuik":'metamorfoseada',
	"itztlakoliuik":'metamorfoseado',
	"itztlakoliuik":'transformada',
	"itztlakoliuik":'transformado',
	"itztlakoliuk":'engañada',
	"itztlakoliuk":'engañado',
	"itztlakoliuyok":'mentirosa',
	"itztlakoliuyok":'mentiroso',
	"iuanyok":'adicionada',
	"iuanyok":'adicionado',
	"iuanyok":'incrementada',
	"iuanyok":'incrementado',
	"iuanyok":'sumada',
	"iuanyok":'sumado',
	"iuanyouak":'incrementada',
	"iuanyouak":'incrementado',
	"iuhkayotik":'característica',
	"iuhkayotik":'característico',
	"iuhki":'casi',
	"iuhpantik":'igual',
	"iuhpechtik":'igual',
	"ixchiuak":'causada',
	"ixchiuak":'causado',
	"ixchiuak":'enfrentada',
	"ixchiuak":'enfrentado',
	"ixiuiliak":'desafiada',
	"ixiuiliak":'desafiado',
	"ixkaltiak":'agrandada',
	"ixkaltiak":'agrandado',
	"ixkaltiak":'aumentada',
	"ixkaltiak":'aumentado',
	"ixkaltiak":'incrementada',
	"ixkaltiak":'incrementado',
	"ixkan":'rededor',
	"ixkikan":'hacia',
	"ixkikan":'hasta',
	"ixkipa":'desde',
	"ixkohyauaki":'irrespetuoso',
	"ixkok":'opuesta',
	"ixkok":'opuesto',
	"ixkotlachiki":'petulante',
	"ixkotlachiki":'presumida',
	"ixkotlachiki":'presumido',
	"ixkotlachiki":'presuntuosa',
	"ixkotlachiki":'presuntuoso',
	"ixkouak":'testificatoria',
	"ixkouak":'testificatorio',
	"ixkuepak":'seducida',
	"ixkuepak":'seducido',
	"ixmatipan":'acuerdo',
	"ixmatipan":'conforme',
	"ixmatipan":'según',
	"ixmatitemoaki":'científico',
	"ixpan":'frente',
	"ixpankuik":'agrandada',
	"ixpankuik":'agrandado',
	"ixpankuik":'aumentada',
	"ixpankuik":'aumentado',
	"ixpankuik":'tocada',
	"ixpankuik":'tocado',
	"ixpanmoliak":'embarrada',
	"ixpanmoliak":'embarrado',
	"ixpanmoliak":'untada',
	"ixpanmoliak":'untado',
	"ixpopoyok":'cegada',
	"ixpopoyok":'cegado',
	"ixtekik":'robada',
	"ixtekik":'robado',
	"ixtetlapouak":'cuchicheada',
	"ixtetlapouak":'cuchicheado',
	"ixtlakatlatlapouak":'susurrada',
	"ixtlakatlatlapouak":'susurrado',
	"ixuak":'nacida',
	"ixuak":'nacido',
	"ixuetzkak":'sonreida',
	"ixuetzkak":'sonreido',
	"ixuhtok":'naciente',
	"ixyaochiuak":'peleonera',
	"ixyaochiuak":'peleonero',
	"ixyauik":'avanzada',
	"ixyauik":'avanzado',
	"izak":'asombrada',
	"izak":'asombrado',
	"izak":'despertada',
	"izak":'despertado',
	"izak":'pasmada',
	"izak":'pasmado',
	"izak":'sorprendida',
	"izak":'sorprendido',
	"izalli":'sorpresa',
	"izatik":'asombroso',
	"izatik":'pasmoso',
	"izatik":'sorpresiva',
	"izatik":'sorpresivo',
	"izel":'solita',
	"izel":'solito',
	"izel":'solo',
	"izel":'sólo',
	"izelpan":'solamente',
	"izkaliak":'agrandada',
	"izkaliak":'agrandado',
	"izkaltiak":'agrandada',
	"izkaltiak":'agrandado',
	"izkaltiak":'aumentada',
	"izkaltiak":'aumentado',
	"izkaltiak":'incrementada',
	"izkaltiak":'incrementado',
	"izpanilyok":'ideada',
	"izpanilyok":'ideado',
	"izpanilyok":'imaginada',
	"izpanilyok":'imaginado',
	"izpanotzak":'incitada',
	"izpanotzak":'incitado',
	"izpanotzak":'invitada',
	"izpanotzak":'invitado',
	"izpanotzak":'sugerida',
	"izpanotzak":'sugerido',
	"iztak":'blanca',
	"iztak":'blanco',
	"iztak":'clara',
	"iztak":'claro',
	"iztak":'inmaculada',
	"iztak":'inmaculado',
	"iztak":'pura',
	"iztak":'puro',
	"iztak":'rubia',
	"iztak":'rubias',
	"iztak":'rubio',
	"iztak":'rubios',
	"iztak":'transparente',
	"iztaktik":'pálida',
	"iztlaka":'mentiroso',
	"kahkayauak":'engañada',
	"kahkayauak":'engañado',
	"kak":'existida',
	"kak":'existido',
	"kalakiak":'adentrada',
	"kalakiak":'adentrado',
	"kalakiak":'encajada',
	"kalakiak":'encajado',
	"kalakiak":'entrada',
	"kalakiak":'entrado',
	"kalakiak":'incorporada',
	"kalakiak":'incorporado',
	"kalakiayok":'introducva',
	"kalakiayok":'introducvo',
	"kamanak":'burlada',
	"kamanak":'burlado',
	"kamapitok":'grosera',
	"kamapitok":'grosero',
	"kamapitok":'groseros',
	"kaniak":'colocada',
	"kaniak":'colocado',
	"kaniak":'posicionada',
	"kaniak":'posicionado',
	"kaniak":'ubicada',
	"kaniak":'ubicado',
	"kankuik":'involucrada',
	"kankuik":'involucrado',
	"kantlazak":'derribada',
	"kantlazak":'derribado',
	"kantlazak":'tumbada',
	"kantlazak":'tumbado',
	"katik":'estable',
	"katik":'estática',
	"katik":'estáticas',
	"katik":'estático',
	"katik":'estáticos',
	"katzalli":'hermosa',
	"katzalli":'hermoso',
	"kauak":'abandonada',
	"kauak":'abandonado',
	"kauak":'dejada',
	"kauak":'dejado',
	"kauak":'desistida',
	"kauak":'desistido',
	"kauak":'permitida',
	"kauak":'permitido',
	"kauik":'temporarea',
	"kauik":'temporareo',
	"kauiliak":'soltada',
	"kauiliak":'soltado',
	"kautik":'temporarea',
	"kautik":'temporareo',
	"kaxtoltetl":'15°',
	"kaxtoluanautetl":'19°',
	"kaxtoluanometetl":'17°',
	"kaxtoluanyetetl":'18°',
	"kaxtoluanzentetl":'16°',
	"kayotl":'equilibrio',
	"kayotl":'estabilidad',
	"kayotl":'estabilización',
	"kayotok":'congruente',
	"kehtzak":'bloqueada',
	"kehtzak":'bloqueado',
	"kehtzak":'frenada',
	"kehtzak":'frenado',
	"kehtzak":'interrumpida',
	"kehtzak":'interrumpido',
	"kehtzak":'parada',
	"kehtzak":'parado',
	"kehtzak":'pausada',
	"kehtzak":'pausadas',
	"kehtzak":'pausado',
	"kehtzak":'pausados',
	"kehtzak":'pausads',
	"kehtzak":'perdurada',
	"kehtzak":'perdurado',
	"kehtzak":'quedada',
	"kehtzak":'quedado',
	"kehtzauak":'perdurada',
	"kehtzauak":'perdurado',
	"kehtzayok":'resistida',
	"kehtzayok":'resistido',
	"kemak":'sí',
	"kemaniantik":'ocasional',
	"kemaniantik":'ocasionales',
	"kematiak":'afirmada',
	"kematiak":'afirmado',
	"kemihtok":'afirmada',
	"kemihtok":'afirmado',
	"kemiliak":'afirmada',
	"kemiliak":'afirmado',
	"kemitik":'vestida',
	"kemiyoak":'consentida',
	"kemiyoak":'consentido',
	"ketzalik":'hermosa',
	"ketzalik":'hermoso',
	"ketzalli":'hermosa',
	"ketzalli":'hermoso',
	"ketzaltzin":'hermosa',
	"ketzaltzin":'hermoso',
	"ketzauek":'manipulable',
	"kexki":'tanta',
	"kexki":'tanto',
	"kexkiak":'costada',
	"kexkiak":'costado',
	"kiliak":'adeudada',
	"kiliak":'adeudado',
	"kimahpiliuiak":'señalada',
	"kimahpiliuiak":'señalado',
	"kiuaxoko":'idiota',
	"kiuaxoko":'lunático',
	"kiuaxoko":'maniática',
	"kiuaxoko":'maníaca',
	"kiuaxoko":'orate',
	"kixtiak":'copiada',
	"kixtiak":'copiado',
	"kizak":'sacada',
	"kizak":'sacado',
	"kizak":'salida',
	"kizak":'salido',
	"kizkuik":'sacada',
	"kizkuik":'sacado',
	"kizoliuik":'escapada',
	"kizoliuik":'escapado',
	"kizoliuik":'huida',
	"kizoliuik":'huido',
	"koaxoko":'idiota',
	"koaxoko":'lunática',
	"koaxoko":'lunático',
	"koaxoko":'maniática',
	"koaxoko":'maniático',
	"koaxoko":'maníaca',
	"koaxoko":'maníaco',
	"koaxoko":'orate',
	"koaxoko":'tonta',
	"koaxoko":'tonto',
	"kochik":'dormida',
	"kochik":'dormido',
	"kochik":'soñada',
	"kochik":'soñado',
	"koiak":'resguardada',
	"koiak":'resguardado',
	"kokoiliak":'enfermada',
	"kokoiliak":'enfermado',
	"kokoiliak":'quejada',
	"kokoiliak":'quejado',
	"kokolik":'sufrida',
	"kokolik":'sufrido',
	"kokotik":'cilíndrica',
	"kokotik":'cilíndrico',
	"kokouhkuik":'enganchada',
	"kokouhkuik":'enganchado',
	"koliak":'curvada',
	"koliak":'curvado',
	"koliuhki":'torcida',
	"koliuhki":'torcido',
	"koliuik":'doblada',
	"koliuik":'doblado',
	"koloak":'ondeada',
	"koloak":'ondeado',
	"koloak":'ondulada',
	"koloak":'ondulado',
	"koniak":'bebida',
	"koniak":'bebido',
	"kopeuik":'despegada',
	"kopeuik":'despegado',
	"kotlazak":'derribada',
	"kotlazak":'derribado',
	"kotlazak":'tumbada',
	"kotlazak":'tumbado',
	"kouak":'comprada',
	"kouak":'comprado',
	"kouaxoko":'idiota',
	"kouaxoko":'lunática',
	"kouaxoko":'lunático',
	"kouaxoko":'maniático',
	"kouaxoko":'maníaco',
	"kouaxoko":'orate',
	"kouaxoko":'tonta',
	"kouaxoko":'tonto',
	"kouitik":'comprada',
	"kouitik":'comprado',
	"koyolik":'esférica',
	"koyolik":'esférico',
	"kuak":'entonces',
	"kuak":'preferida',
	"kuak":'preferido',
	"kuak":'tragada',
	"kuak":'tragado',
	"kualchiuak":'perfecta',
	"kualchiuak":'perfecto',
	"kualkan":'temprana',
	"kualkan":'temprano',
	"kualli":'bien',
	"kualli":'buena',
	"kualli":'bueno',
	"kualtik":'adecuada',
	"kualtik":'adecuado',
	"kualtik":'adhecuada',
	"kualtik":'adhecuado',
	"kualtiyok":'bondadosa',
	"kualtiyok":'bondadoso',
	"kualtlamik":'exacta',
	"kualtlamik":'exacto',
	"kualtlamik":'exactos',
	"kualtzin":'agradable',
	"kualtzin":'bonita',
	"kualtzin":'bonito',
	"kuauhkuik":'enganchada',
	"kuauhkuik":'enganchado',
	"kuautekik":'talada',
	"kuautekik":'talado',
	"kuayamanki":'lista',
	"kuayamanki":'listas',
	"kuayamanki":'listo',
	"kuayamanki":'listos',
	"kuchok":'sujetada',
	"kuchok":'sujetado',
	"kuechauak":'lenta',
	"kuechauak":'lento',
	"kuehtziak":'molestada',
	"kuehtziak":'molestado',
	"kuehzolik":'odiosa',
	"kuehzolik":'odioso',
	"kuekuetlaxtik":'biscosa',
	"kuekuetlaxtik":'biscoso',
	"kuekuetlaxtik":'elástica',
	"kuekuetlaxtik":'elástico',
	"kuekuetlaxtik":'gomoso',
	"kuenchiuak":'imprimida',
	"kuenchiuak":'imprimido',
	"kuenkauak":'imprimida',
	"kuenkauak":'imprimido',
	"kuepayotik":'volteda',
	"kuepayotik":'voltedo',
	"kueponiak":'brotada',
	"kueponiak":'brotado',
	"kueponiak":'reventada',
	"kueponiak":'reventado',
	"kueponiak":'tronada',
	"kueponiak":'tronado',
	"kuetekuani":'oso',
	"kuetziak":'fastidiada',
	"kuetziak":'fastidiado',
	"kuetziak":'hostigada',
	"kuetziak":'hostigado',
	"kuetziak":'molestada',
	"kuetziak":'molestado',
	"kuik":'agarrada',
	"kuik":'agarrado',
	"kuik":'asida',
	"kuik":'asido',
	"kuik":'sufragada',
	"kuik":'sufragado',
	"kuik":'sujetada',
	"kuik":'sujetado',
	"kuik":'tomada',
	"kuik":'tomado',
	"kuik":'votada',
	"kuik":'votado',
	"kuikak":'cantada',
	"kuikak":'cantado',
	"kuitiak":'quitada',
	"kuitiak":'quitado',
	"kuitlapa":'detrás',
	"kuitlapan":'trasera',
	"kuitlapan":'trasero',
	"kuitlapiluak":'coleada',
	"kuitlapiluak":'coleado',
	"kuitlauiatik":'vigilosa',
	"kuitlauiatik":'vigiloso',
	"kuitlauik":'cagada',
	"kuitlauik":'cagado',
	"kuitlauik":'defecada',
	"kuitlauik":'defecado',
	"laxtik":'naranja',
	"ma kixtik":'libre',
	"ma":'que',
	"machiliak":'definida',
	"machiliak":'definido',
	"machiliak":'significada',
	"machiliak":'significado',
	"machiliatik":'enseñada',
	"machiliatik":'enseñado',
	"machiluaki":'prudente',
	"machtiak":'instruida',
	"machtiak":'instruido',
	"machtiatik":'enseñada',
	"machtiatik":'enseñado',
	"mahkuiluako":'1/5',
	"mahkuiluanomeuako":'1/7',
	"mahkuiluanzeuako":'1/6',
	"mahtlak uan eyi":'trece',
	"mahtlak uan kaxtolpoual":'trescientos',
	"mahtlak uan nautetl":'14°',
	"mahtlak uan omtetl":'12°',
	"mahtlak uan yetetl":'13°',
	"mahtlak uan zentetl":'11°',
	"mahtlaktetl":'10°',
	"mahtlakuankaxtolpoualuako":'1/300',
	"mahtlakuanomezempoualuanmahtlakchikipiluako":'1/100000',
	"mahtlauako":'1/10',
	"mahtlauako":'10°',
	"makatik":'dada',
	"makatik":'dado',
	"makatik":'dosa',
	"makatik":'doso',
	"makatik":'regalada',
	"makatik":'regalado',
	"makauak":'sucia',
	"makauak":'sucio',
	"makauik":'adulterada',
	"makauik":'adulterado',
	"makauik":'alterado',
	"makauik":'contaminada',
	"makauik":'contaminado',
	"makauik":'descompuesta',
	"makauik":'descompuesto',
	"makauitl":'sucia',
	"makauitl":'sucio',
	"makauk":'alterada',
	"makauk":'alterado',
	"makauk":'inquieta',
	"makauk":'inquieto',
	"makauk":'nerviosa',
	"makauk":'nervioso',
	"makauk":'sucia',
	"makauk":'sucio',
	"makauk":'viciosa',
	"makauk":'vicioso',
	"makix":'expedita',
	"makix":'expedito',
	"makixtiak":'liberada',
	"makixtiak":'liberado',
	"makixtiak":'librada',
	"makixtiak":'librado',
	"makixtiak":'redimida',
	"makixtiak":'redimido',
	"makixtiak":'salvada',
	"makixtiak":'salvado',
	"makixtik":'libre',
	"makixtilli":'expedita',
	"makixtilli":'expedito',
	"makuilzempoualuako":'1/100',
	"maliatik":'circulada',
	"maliatik":'circulado',
	"maliatik":'girada',
	"maliatik":'girado',
	"maliatik":'redondeada',
	"maliatik":'redondeado',
	"maltik":'bañada',
	"maltik":'bañado',
	"mamahtok":'cargante',
	"mamauatik":'apoyada',
	"mamauatik":'apoyado',
	"mamauatik":'cargada',
	"mamauatik":'cargado',
	"mamauatik":'soportada',
	"mamauatik":'soportado',
	"mamauatik":'tolerada',
	"mamauatik":'tolerado',
	"mamautok":'tolerante',
	"mamayauitik":'llevada',
	"mamayauitik":'llevado',
	"mamayauitik":'trasladada',
	"mamayauitik":'trasladado',
	"mamazkauak":'descargada',
	"mamazkauak":'descargado',
	"manailhuak":'defendida',
	"manailhuak":'defendido',
	"manelotik":'nadada',
	"manelotik":'nadado',
	"manik":'temporal',
	"mantik":'calmada',
	"mantik":'calmado',
	"mantik":'serena',
	"mantik":'sereno',
	"mantik":'tranquila',
	"mantik":'tranquilo',
	"maohtiki":'temerosa',
	"maohtiki":'temeroso',
	"maohueltik":'temible',
	"matiazik":'astuta',
	"matiazik":'astuto',
	"matiazik":'astutos',
	"matichiuatik":'acostumbrada',
	"matichiuatik":'acostumbrado',
	"matichiuatik":'adaptada',
	"matichiuatik":'adaptado',
	"matichiuatik":'habituada',
	"matichiuatik":'habituado',
	"matizmakak":'advertida',
	"matizmakak":'advertido',
	"matizmakatik":'informada',
	"matizmakatik":'informado',
	"matkuitik":'percatada',
	"matkuitik":'percatado',
	"matzaziuitik":'percatada',
	"matzaziuitik":'percatado',
	"mauhtik":'tenebroso',
	"mauhtiki":'miedoso',
	"mauizok":'orgullosa',
	"mauizok":'orgulloso',
	"mauizok":'orgullosos',
	"mauizoki":'honrroso',
	"mauizokuitlatik":'deshonrada',
	"mauizokuitlatik":'deshonrado',
	"mauizotik":'encantada',
	"mauizotik":'encantado',
	"mauizotik":'fascinada',
	"mauizotik":'fascinado',
	"mauizotik":'honrada',
	"mauizotik":'honrado',
	"mauizotik":'maravillada',
	"mauizotik":'maravillado',
	"mautiak":'temida',
	"mautiak":'temido',
	"maxiuik":'parida',
	"maxiuik":'parido',
	"mayanak":'carente',
	"mayekpa":'derecha',
	"mazatl":'cierva',
	"mazatl":'ciervo',
	"mazeualixpan":'públicamente',
	"mazeuik":'merecida',
	"mazeuik":'merecido',
	"mekajustik":'ajustada',
	"mekajustik":'ajustado',
	"mekatik":'asociada',
	"mekatik":'asociado',
	"mekatik":'atada',
	"mekatik":'atado',
	"mekatik":'concatenada',
	"mekatik":'concatenado',
	"mekatik":'enlazada',
	"mekatik":'enlazado',
	"mekatik":'vinculada',
	"mekatik":'vinculado',
	"mekauatik":'asociada',
	"mekauatik":'asociado',
	"mekauatik":'atada',
	"mekauatik":'atado',
	"mekauatik":'concatenada',
	"mekauatik":'concatenado',
	"mekauatik":'enlazada',
	"mekauatik":'enlazado',
	"mekauatik":'vinculada',
	"mekauatik":'vinculado',
	"mekconectik":'conectada',
	"mekconectik":'conectado',
	"mekenderezik":'enderezada',
	"mekenderezik":'enderezado',
	"mekestructurik":'estructurada',
	"mekestructurik":'estructurado',
	"mekrectificik":'rectificada',
	"mekrectificik":'rectificado',
	"mekrelacionik":'relacionada',
	"mekrelacionik":'relacionado',
	"mela":'cierta',
	"mela":'cierto',
	"melak":'cierta',
	"melak":'cierto',
	"melak":'real',
	"melaki":'recta',
	"melaki":'recto',
	"melakiyok":'compuesta',
	"melakiyok":'compuesto',
	"melauak":'cierta',
	"melauak":'cierto',
	"melauak":'correcta',
	"melauak":'correcto',
	"melauak":'efectiva',
	"melauak":'efectivo',
	"melauak":'real',
	"melauak":'verdadera',
	"melauak":'verdadero',
	"melauak":'veráz',
	"melauakan":'justamente',
	"melauakan":'precisamente',
	"melauakzeliltik":'jurídica',
	"melauakzeliltik":'jurídico',
	"melauayok":'jurídico',
	"melauilyo":'jurídico',
	"melazeliltik":'jurídica',
	"melazeliltik":'jurídico',
	"melli":'cierta',
	"melli":'cierto',
	"miak kualtik":'excelente',
	"miak":'mucho',
	"miakamoketzalli":'horrible',
	"miakkualtik":'excelente',
	"mikiyok":'moribundo',
	"mikiyok":'mortal',
	"mikpahtiak":'envenenatoria',
	"mikpahtiak":'envenenatorio',
	"miktik":'asesinatoria',
	"miktik":'asesinatorio',
	"miktik":'mortoria',
	"miktik":'mortorio',
	"mimilkonik":'cilíndrica',
	"mimilkonik":'cilíndrico',
	"miminak":'colatoria',
	"miminak":'colatorio',
	"mkan":'1/2',
	"mochikauak":'esmeratoria',
	"mochikauak":'esmeratorio',
	"mokuitiliak":'confesatoria',
	"mokuitiliak":'confesatorio',
	"moleuak":'despegatoria',
	"moleuak":'despegatorio',
	"moltiak":'entrenaratoria',
	"moltiak":'entrenaratorio',
	"moltiak":'preparatoria',
	"moltiak":'preparatorio',
	"momoak":'copiatoria',
	"momoak":'copiatorio',
	"momochkak":'brillatoria',
	"momochkak":'brillatorio',
	"moolinializtik":'vibratoria',
	"moolinializtik":'vibratorio',
	"mopatiyoki":'petulante',
	"mopatiyoki":'presumida',
	"mopatiyoki":'presumido',
	"mopatiyoki":'presuntuosa',
	"mopatiyoki":'presuntuoso',
	"motlanextik":'brillante',
	"motlanextik":'brillosa',
	"motlanextik":'brilloso',
	"motlapozauhtik":'esponjoso',
	"motoliniak":'tiritatoria',
	"motoliniak":'tiritatorio',
	"moztla":'mañana',
	"nakauak":'cesatoria',
	"nakauak":'cesatorio',
	"nakauak":'pausatoria',
	"nakauak":'pausatorio',
	"nakauayok":'interrumpida',
	"nakauayok":'interrumpido',
	"namakak":'trocatoria',
	"namakak":'trocatorio',
	"namakok":'comerciatoria',
	"namakok":'comerciatorio',
	"namakok":'mercadeatoria',
	"namakok":'mercadeatorio',
	"namik":'esposo',
	"namikiatik":'encontrada',
	"namikiatik":'encontrado',
	"nankiliak":'contestatoria',
	"nankiliak":'contestatorio',
	"nankiliak":'respondida',
	"nankiliak":'respondido',
	"nauak":'cerca',
	"nauako":'1/4',
	"nauatik":'comandatoria',
	"nauatik":'comandatorio',
	"nauatik":'ordenatoria',
	"nauatik":'ordenatorio',
	"nauhkampak":'encuadratoria',
	"nauhkampak":'encuadratorio',
	"naupoualuanmahtlakchikipiluako":'1/20000',
	"nautetl":'4°',
	"nechiuaki":'prudente',
	"nechtiayok":'descubierta',
	"nechtiayok":'descubierto',
	"nehnemik":'avanzada',
	"nehnemik":'avanzado',
	"nehnemik":'camina',
	"nehnemik":'camino',
	"nehueililki":'petulante',
	"nehueililki":'presumida',
	"nehueililki":'presumido',
	"nehueililki":'presuntuoso',
	"nekauak":'cesatoria',
	"nekauak":'cesatorio',
	"nekauak":'paratoria',
	"nekauak":'paratorio',
	"nekauak":'pausatoria',
	"nekauak":'pausatorio',
	"nekayoki":'apática',
	"nekayoki":'apático',
	"nekayoki":'perezosa',
	"nekayoki":'perezoso',
	"nekiyok":'querida',
	"nekiyok":'querido',
	"nelli":'cierta',
	"nelli":'cierto',
	"neltok":'supuesta',
	"neltok":'supuesto',
	"neltokachiuak":'convencida',
	"neltokachiuak":'convencido',
	"neltokaihtok":'afirmatoria',
	"neltokaihtok":'afirmatorio',
	"neltokayok":'creida',
	"neltokayok":'creido',
	"neltokayok":'deductiva',
	"neltokayok":'deductivo',
	"neltokayok":'inferente',
	"neltokayok":'parecida',
	"neltokayok":'parecido',
	"neltokaztepitik":'esperanzada',
	"neltokaztepitik":'esperanzado',
	"nelyanak":'dudatoria',
	"nelyanak":'dudatorio',
	"nelyok":'real',
	"nemachiliuaki":'prudente',
	"nemik":'vivida',
	"nemik":'vivido',
	"nemik":'vívida',
	"nemik":'vívido',
	"nemiliztik":'animatoria',
	"nemiliztik":'animatorio',
	"nemitik":'animada',
	"nemitik":'animado',
	"nemitik":'vívida',
	"nemitik":'vívido',
	"nemitok":'viva',
	"nemitok":'vivo',
	"nemiyok":'viva',
	"nemiyok":'vivo',
	"nenekik":'necesitatoria',
	"nenekik":'necesitatorio',
	"nenelouayok":'descubierta',
	"nenelouayok":'descubierto',
	"neneuak":'asemejatoria',
	"neneuak":'asemejatorio',
	"neneuak":'semejatoria',
	"neneuak":'semejatorio',
	"neneuaki":'igual',
	"neneuakiak":'igualatoria',
	"neneuakiak":'igualatorio',
	"neneuhtlachiak":'comparatoria',
	"neneuhtlachiak":'comparatorio',
	"neneuihkiayok":'medida',
	"neneuihkiayok":'medido',
	"neneutik":'identica',
	"neneutik":'identico',
	"nenkan":'menos',
	"nepanpatichiuak":'organizatoria',
	"nepanpatichiuak":'organizatorio',
	"nepanpatichiuak":'planificatoria',
	"nepanpatichiuak":'planificatorio',
	"nepanpatik":'acomodatoria',
	"nepanpatik":'acomodatorio',
	"nepanpatik":'administratoria',
	"nepanpatik":'administratorio',
	"nepanpatik":'disponible',
	"nepanpatik":'organizatoria',
	"nepanpatik":'organizatorio',
	"nepanpatiyok":'repartida',
	"nepanpatiyok":'repartido',
	"nepantla":'en medio de',
	"nepantla":'entre',
	"nezik":'atisbatoria',
	"nezik":'atisbatorio',
	"nezik":'avistatoria',
	"nezik":'avistatorio',
	"nezik":'avizoratoria',
	"nezik":'avizoratorio',
	"ni kan":'aquí',
	"nikan":'aquí',
	"niman":'después',
	"niman":'posterior',
	"nmoolinializtik":'vibrativa',
	"nmoolinializtik":'vibrativo',
	"nochi":'toda',
	"nochi":'todo',
	"nochik":'total',
	"nochipa":'siempre',
	"nochipak":'eterna',
	"nochipak":'eterno',
	"noihki":'también',
	"nonotzak":'charlatoria',
	"nonotzak":'charlatorio',
	"nonotzak":'conversatoria',
	"nonotzak":'conversatorio',
	"nonotzak":'platicatoria',
	"nonotzak":'platicatorio',
	"notzak":'avisatoria',
	"notzak":'avisatorio',
	"notzak":'exhortatoria',
	"notzak":'exhortatorio',
	"notzak":'llamatoria',
	"notzak":'llamatorio',
	"notzak":'manifestatoria',
	"notzak":'manifestatorio',
	"notzok":'disyuntatoria',
	"notzok":'disyuntatorio',
	"notzok":'relevatoria',
	"notzok":'relevatorio',
	"notzoyok":'deponida',
	"notzoyok":'deponido',
	"notzoyok":'desunida',
	"notzoyok":'desunido',
	"O •":'21',
	"O ••":'22',
	"O •••":'23',
	"O ••••":'24',
	"O":'20',
	"ohtli":'camino',
	"ohtli":'rastro',
	"ohtli":'senda',
	"ohtli":'sendero',
	"ohtli":'vereda',
	"ohtotokak":'viajatoria',
	"ohtotokak":'viajatorio',
	"okze":'otra',
	"okze":'otro',
	"okzenehnemkuik":'desviatoria',
	"okzenehnemkuik":'desviatorio',
	"okzenka":'mayoritariamente',
	"okzenka":'mayormente',
	"okzenka":'principalmente',
	"okzepa":'de nuevo',
	"okzepa":'otra vez',
	"olik":'desplazatoria',
	"olik":'desplazatorio',
	"olik":'velocidatoria',
	"olik":'velocidatorio',
	"olik":'veloz',
	"olinik":'dinámica',
	"olinik":'dinámicas',
	"olinik":'dinámico',
	"olinik":'dinámicos',
	"olinik":'vibrable',
	"olinxihtiak":'equilibrada',
	"olinxihtiak":'equilibrado',
	"olinyolok":'equilibrada',
	"olinyolok":'equilibrado',
	"olitik":'trasladada',
	"olitik":'trasladado',
	"oltik":'movible',
	"olyok":'acelerada',
	"olyok":'acelerado',
	"olyotik":'acelerado',
	"ompa":'allá',
	"ompa":'allí',
	"onamonekik":'odiada',
	"onamonekik":'odiado',
	"onchiuak":'reelaborada',
	"onchiuak":'reelaborado',
	"onchiuayok":'reconstruida',
	"onchiuayok":'reconstruido',
	"onchiuayok":'rehecha',
	"onchiuayok":'rehecho',
	"onchiuayok":'sustituida',
	"onchiuayok":'sustituido',
	"onilnamikik":'remembrada',
	"onilnamikik":'remembrado',
	"onitaliztik":'verificativa',
	"onitaliztik":'verificativo',
	"onitaliztik":'verificatoria',
	"onitaliztik":'verificatorio',
	"onixmatiyok":'rehecha',
	"onixmatiyok":'rehecho',
	"onkayotok":'habiente',
	"onnekik":'deseada',
	"onnekik":'deseado',
	"onnekik":'remplazada',
	"onnekik":'remplazado',
	"ontemik":'inútil',
	"ontlakuik":'recuperatoria',
	"ontlakuik":'recuperatorio',
	"ontlamatik":'asimilada',
	"ontlamatik":'asimilado',
	"ontlamatiyok":'conocida',
	"ontlamatiyok":'conocido',
	"ontlapatiyok":'reivindicada',
	"ontlapatiyok":'reivindicado',
	"ontotokak":'perseverada',
	"ontotokak":'perseverado',
	"ouihyotl":'problemática',
	"ouihyotl":'problemático',
	"ouilyok":'equivocada',
	"ouilyok":'equivocado',
	"ouilyok":'errada',
	"ouilyok":'errado',
	"ouiyoihtok":'amenazada',
	"ouiyoihtok":'amenazado',
	"ouiyok":'conflictiva',
	"ouiyok":'conflictivo',
	"ouiyok":'equivocada',
	"ouiyok":'equivocado',
	"ouiyok":'errónea',
	"ouiyok":'erróneo',
	"ouiyok":'problemática',
	"ouiyok":'problemático',
	"O| •":'26',
	"O| ••":'27',
	"O| •••":'28',
	"O| ••••":'29',
	"O|":'25',
	"O|| •":'31',
	"O|| ••":'32',
	"O|| •••":'33',
	"O|| ••••":'34',
	"O||":'30',
	"O||| •":'36',
	"O||| ••":'37',
	"O||| •••":'38',
	"O||| ••••":'39',
	"O|||":'35',
	"pachoatik":'abrazada',
	"pachoatik":'abrazado',
	"pachok":'abarcada',
	"pachok":'abarcado',
	"pachok":'abrazada',
	"pachok":'abrazado',
	"pachok":'acaparada',
	"pachok":'acaparado',
	"pachokalakiak":'incrustada',
	"pachokalakiak":'incrustado',
	"pachokuik":'atrapada',
	"pachokuik":'atrapado',
	"pachoyok":'cubrida',
	"pachoyok":'cubrido',
	"pakik":'gustada',
	"pakik":'gustado',
	"pakiliztik":'contenta',
	"pakiliztik":'contento',
	"pakiliztik":'feliz',
	"pakitik":'gustosa',
	"pakitik":'gustoso',
	"palak":'cambiada',
	"palak":'cambiado',
	"palanki":'podrido',
	"paleuik":'auxiliada',
	"paleuik":'auxiliado',
	"paleuik":'ayudada',
	"paleuik":'ayudado',
	"palkuik":'desviada',
	"palkuik":'desviado',
	"pampa":'porque',
	"paniak":'aplicada',
	"paniak":'aplicado',
	"panok":'pasada',
	"panok":'pasado',
	"panotik":'pasajosa',
	"panotik":'pasajoso',
	"panoyok":'acontecida',
	"panoyok":'acontecido',
	"panoyok":'sucedida',
	"panoyok":'sucedido',
	"panpalak":'remplazada',
	"panpalak":'remplazado',
	"panpalayok":'adertiva',
	"panpalayok":'adertivo',
	"panpalayok":'destituya',
	"panpalayok":'destituyo',
	"pantekik":'rasgada',
	"pantekik":'rasgado',
	"papachok":'apretada',
	"papachok":'apretado',
	"papachok":'estrujada',
	"papachok":'estrujado',
	"papatztik":'suave',
	"patiyok":'evaluada',
	"patiyok":'evaluado',
	"patiyok":'valiosa',
	"patiyok":'valioso',
	"patiyok":'valuada',
	"patiyok":'valuado',
	"patiyotik":'cara',
	"patiyotik":'caro',
	"patlanik":'volada',
	"patlanik":'volado',
	"patlauak":'ancha',
	"patlauak":'ancho',
	"pehpechik":'cogida',
	"pehpechik":'cogido',
	"pehpechik":'copulada',
	"pehpechik":'copulado',
	"pehpechik":'emprenda',
	"pehpechik":'emprendo',
	"pehpechouak":'fijada',
	"pehpechouak":'fijado',
	"pehpechouak":'pegada',
	"pehpechouak":'pegado',
	"pehpenak":'optada',
	"pehpenak":'optado',
	"pehpenayok":'electa',
	"pehpenayok":'electo',
	"pehpenayok":'escogida',
	"pehpenayok":'escogido',
	"pehpenayok":'preferida',
	"pehpenayok":'preferido',
	"pepechouak":'sedentaria',
	"pepechouak":'sedentario',
	"petlanik":'brillada',
	"petlanik":'brillado',
	"petlanik":'brillante',
	"petlanik":'brillosa',
	"petlanik":'brilloso',
	"peuak":'arrancada',
	"peuak":'arrancado',
	"peuak":'comenzada',
	"peuak":'comenzado',
	"peuak":'iniciada',
	"peuak":'iniciado',
	"pilli":'pequeña',
	"pilli":'pequeño',
	"piltik":'pequeño',
	"piluak":'coleada',
	"piluak":'coleado',
	"pinixtik":'opaca',
	"pinixtik":'opaco',
	"pipitzkak":'timbrada',
	"pipitzkak":'timbrado',
	"pitzauak":'delgada',
	"pitzauak":'delgado',
	"pitzauak":'fina',
	"pitzauak":'fino',
	"poliuik":'ausentada',
	"poliuik":'ausentado',
	"poliuik":'desaparecida',
	"poliuik":'desaparecido',
	"poliuik":'perdida',
	"poliuik":'perdido',
	"popolok":'borrada',
	"popolok":'borrado',
	"pouak":'contada',
	"pouak":'contado',
	"poualmachiyouak":'enumerada',
	"poualmachiyouak":'enumerado',
	"pouatik":'contada',
	"pouatik":'contado',
	"poxkauik":'mohoso',
	"putzhuiayok":'repitida',
	"putzhuiayok":'repitido',
	"teamoneloak":'mentirosa',
	"teamoneloak":'mentiroso',
	"teamoneloak":'mentirosos',
	"tech":'nos',
	"teiliak":'demandada',
	"teiliak":'demandado',
	"teiliak":'interpelada',
	"teiliak":'interpelado',
	"teiliayok":'exigida',
	"teiliayok":'exigido',
	"tek":'alguien',
	"tekak":'inclinada',
	"tekak":'inclinado',
	"tekauatok":'pertinente',
	"tekik":'cortada',
	"tekik":'cortado',
	"tekik":'disyuntada',
	"tekik":'disyuntado',
	"tekik":'separada',
	"tekik":'separado',
	"tekitik":'funcionada',
	"tekitik":'funcionado',
	"tekitik":'trabajada',
	"tekitik":'trabajado',
	"tekitiyok":'servida',
	"tekitiyok":'servido',
	"tekochmamak":'sentida',
	"tekochmamak":'sentido',
	"tekochmamatik":'sensitiva',
	"tekochmamatik":'sensitivo',
	"tekpanak":'golpeada',
	"tekpanak":'golpeado',
	"tekuanik":'encabronada',
	"tekuanik":'encabronado',
	"tekuanik":'enfurecida',
	"tekuanik":'enfurecido',
	"tekuanik":'enojada',
	"tekuanik":'enojado',
	"tekuanik":'guíada',
	"tekuanik":'guíado',
	"tekuaniliayok":'discutida',
	"tekuaniliayok":'discutido',
	"tekuantik":'enojada',
	"tekuantik":'enojado',
	"tekuhuayok":'dirigida',
	"tekuhuayok":'dirigido',
	"teletzak":'pateada',
	"teletzak":'pateado',
	"telpochtik":'joven',
	"temachiltik":'educada',
	"temachiltik":'educado',
	"temachiltik":'educados',
	"temelauak":'honesta',
	"temelauak":'honesto',
	"temelauak":'honestos',
	"temik":'complementada',
	"temik":'complementaria',
	"temik":'completa',
	"temik":'completada',
	"temik":'completado',
	"temik":'completo',
	"temik":'llena',
	"temik":'lleno',
	"temoak":'buscada',
	"temoak":'buscaria',
	"temok":'averiguatoria',
	"temok":'averiguatorio',
	"temok":'bajada',
	"temok":'bajaria',
	"temok":'descendida',
	"temok":'descendido',
	"temtik":'suficiente',
	"teneuak":'repetida',
	"teneuak":'repetido',
	"tepiltilanak":'masturbada',
	"tepiltilanak":'masturbado',
	"tepitik":'esperada',
	"tepitik":'esperado',
	"teponiak":'engranada',
	"teponiak":'engranado',
	"tetekik":'labrada',
	"tetekik":'labrado',
	"tetekik":'labratoria',
	"tetekik":'labratorio',
	"tetelti":'ásperok',
	"tetlakolchiuak":'culpada',
	"tetlakolchiuak":'culpado',
	"teueliak":'ponderada',
	"teueliak":'ponderado',
	"teyok":'sólida',
	"teyok":'sólido',
	"tilantik":'jalada',
	"tilantik":'jalado',
	"titlanik":'enviada',
	"titlanik":'enviado',
	"titlaniyok":'expidida',
	"titlaniyok":'expidido',
	"titlaniyok":'remitida',
	"titlaniyok":'remitido',
	"titlaniyok":'transmitida',
	"titlaniyok":'transmitido',
	"tla":'cosa',
	"tlachiak":'observada',
	"tlachiak":'observado',
	"tlachiuhyotik":'específica',
	"tlachiuhyotik":'específico',
	"tlahkak":'tardada',
	"tlahkak":'tardado',
	"tlahpak":'tardía',
	"tlahpak":'tardío',
	"tlahpalok":'saludada',
	"tlahpalok":'saludado',
	"tlahtlanik":'preguntada',
	"tlahtlanik":'preguntado',
	"tlahtok":'hablada',
	"tlahtok":'hablado',
	"tlahtolli":'palabra',
	"tlahtolpalayok":'traducida',
	"tlahtolpalayok":'traducido',
	"tlailiak":'referida',
	"tlailiak":'referido',
	"tlain":'qué',
	"tlakapexik":'autodestruida',
	"tlakapexik":'autodestruido',
	"tlakemiak":'atuendada',
	"tlakemiak":'atuendado',
	"tlakemik":'vestida',
	"tlakemik":'vestido',
	"tlakolok":'entristecida',
	"tlakolok":'entristecido',
	"tlakpak":'arriba',
	"tlakuak":'alimentada',
	"tlakuak":'alimentado',
	"tlakuak":'comada',
	"tlakuak":'comado',
	"tlakuak":'comida',
	"tlakuak":'comido',
	"tlakuak":'ingerida',
	"tlakuak":'ingerido',
	"tlakuepa":'devolver',
	"tlakuepaihtok":'conspirada',
	"tlakuepaihtok":'conspirado',
	"tlakuepayo":'devolutivo',
	"tlakuepayotl":'devolutiva',
	"tlakuepayotl":'devuelta',
	"tlakuik":'recibida',
	"tlakuik":'recibido',
	"tlaliak":'asentada',
	"tlaliak":'asentado',
	"tlaliak":'aterrizada',
	"tlaliak":'aterrizado',
	"tlaliak":'establecida',
	"tlaliak":'establecido',
	"tlalnamikik":'ideada',
	"tlalnamikik":'ideado',
	"tlalnamikik":'ingeniada',
	"tlalnamikik":'ingeniado',
	"tlalnamikik":'mentalizada',
	"tlalnamikik":'mentalizado',
	"tlalnamikik":'pensada',
	"tlalnamikik":'pensado',
	"tlalnamikyopalak":'interpretada',
	"tlalnamikyopalak":'interpretado',
	"tlalpalok":'reverenciada',
	"tlalpalok":'reverenciado',
	"tlalpolok":'confundida',
	"tlalpolok":'confundido',
	"tlamachiliak":'definida',
	"tlamachiliak":'definido',
	"tlamachiliak":'explicada',
	"tlamachiliak":'explicado',
	"tlamachiliyok":'explicativa',
	"tlamachiliyok":'explicativo',
	"tlamatiki":'inteligente',
	"tlamatiki":'inteligentes',
	"tlamatiki":'sabia',
	"tlamatiki":'sabio',
	"tlamatiki":'sabios',
	"tlamiak":'finalizada',
	"tlamiak":'finalizado',
	"tlamiak":'finiquitada',
	"tlamiak":'finiquitado',
	"tlamiak":'terminada',
	"tlamiak":'terminado',
	"tlamik":'finalizada',
	"tlamik":'finalizado',
	"tlamik":'finiquitada',
	"tlamik":'finiquitado',
	"tlamik":'terminada',
	"tlamik":'terminado',
	"tlamik":'términada',
	"tlamik":'términado',
	"tlanemonyauzyok":'preservada',
	"tlanemonyauzyok":'preservado',
	"tlanezik":'iluminada',
	"tlanezik":'iluminado',
	"tlanezik":'luminosa',
	"tlanezik":'luminoso',
	"tlanezik":'lumínica',
	"tlanezik":'lumínico',
	"tlaniak":'adquirida',
	"tlaniak":'adquirido',
	"tlaniak":'ardida',
	"tlaniak":'ardido',
	"tlaniak":'conseguida',
	"tlaniak":'conseguido',
	"tlaniak":'ganada',
	"tlaniak":'ganado',
	"tlaniak":'meritada',
	"tlaniak":'meritado',
	"tlaniak":'obtenida',
	"tlaniak":'obtenido',
	"tlapak":'tapada',
	"tlapak":'tapado',
	"tlapakak":'lavada',
	"tlapakak":'lavado',
	"tlapaliak":'coloreada',
	"tlapaliak":'coloreado',
	"tlapalok":'probada',
	"tlapalok":'probado',
	"tlapaltik":'rosa',
	"tlapetlaniak":'tronada',
	"tlapetlaniak":'tronado',
	"tlapeualiztik":'prologativa',
	"tlapeualiztik":'prologativo',
	"tlapeutik":'prologosa',
	"tlapeutik":'prologoso',
	"tlapok":'abierta',
	"tlapok":'abierto',
	"tlapok":'destapada',
	"tlapok":'destapado',
	"tlapolok":'confundida',
	"tlapolok":'confundido',
	"tlatiak":'guardada',
	"tlatiak":'guardado',
	"tlatiak":'quemada',
	"tlatiak":'quemado',
	"tlatlachiak":'leida',
	"tlatlachiak":'leido',
	"tlatlauhki":'ardiente',
	"tlauehkak":'alejada',
	"tlauehkak":'alejado',
	"tlauehkak":'distanciada',
	"tlauehkak":'distanciado',
	"tlauehkan":'lejos',
	"tlaueliak":'activada',
	"tlaueliak":'activado',
	"tlaueliak":'energizada',
	"tlaueliak":'energizado',
	"tlauelik":'iluminada',
	"tlauelik":'iluminado',
	"tlauihkak":'llevada',
	"tlauihkak":'llevado',
	"tlauihkok":'traida',
	"tlauihkok":'traido',
	"tlaxtlaxkalouayok":'aplausiva',
	"tlaxtlaxkalouayok":'aplausivo',
	"tlayouak":'oscura',
	"tlayouak":'oscuro',
	"tlazak":'aventada',
	"tlazak":'aventado',
	"tlazak":'lanzada',
	"tlazak":'lanzado',
	"tlazak":'tirada',
	"tlazak":'tirado',
	"tlazohtiak":'amada',
	"tlazohtiak":'amado',
	"tlein":'qué',
	"tlen":'que',
	"tlen":'qué',
	"tliltik":'negra',
	"tliltik":'negras',
	"tliltik":'negro',
	"tliltik":'negros',
	"tokak":'configurada',
	"tokak":'configurado',
	"tokak":'establecida',
	"tokak":'establecido',
	"tokak":'nombrada',
	"tokak":'nombrado',
	"tokak":'sembrada',
	"tokak":'sembrado',
	"tomauak":'ancho',
	"tomauak":'gruesa',
	"tomauak":'grueso',
	"tonak":'acalorada',
	"tonak":'acalorado',
	"tonak":'caliente',
	"tonak":'calorada',
	"tonak":'calorado',
	"totokak":'constante',
	"totokak":'constantes',
	"totokak":'perdurada',
	"totokak":'perdurado',
	"totokak":'seguida',
	"totokak":'seguido',
	"totokak":'siguiente',
	"totokatekatl":'perseguidor',
	"totokatik":'constante',
	"totokatik":'frecuente',
	"totokatik":'frecuentes',
	"totokatik":'perseverante',
	"totokatok":'persiguiente',
	"tzakualtik":'cerrada',
	"tzakualtik":'cerrado',
	"tzakuatik":'cerrada',
	"tzakuatik":'cerrado',
	"tzalok":'aprendida',
	"tzalok":'aprendido',
	"tzapaltik":'tosca',
	"tzapaltik":'tosco',
	"tzatepa":'posterior',
	"tzatepa":'posteriormente',
	"tzatik":'cerrada',
	"tzatik":'cerrado',
	"tzatzapaltik":'tosca',
	"tzatzapaltik":'tosco',
	"tzikuinik":'brincada',
	"tzikuinik":'brincado',
	"tzikuinik":'evitada',
	"tzikuinik":'evitado',
	"tzikuinik":'ignorada',
	"tzikuinik":'ignorado',
	"tzikuinik":'omitida',
	"tzikuinik":'omitido',
	"tzikuinik":'puenteada',
	"tzikuinik":'puenteado',
	"tzikuinik":'saltada',
	"tzikuinik":'saltado',
	"tzikuinitok":'brincante',
	"tzikuintok":'brincante',
	"tzilinitik":'sónica',
	"tzilinitik":'sónico',
	"tziniak":'aminorada',
	"tziniak":'aminorado',
	"tziniak":'degradada',
	"tziniak":'degradado',
	"tziniak":'rebajada',
	"tziniak":'rebajado',
	"tzinitik":'respetada',
	"tzinitik":'respetado',
	"tzinitik":'revernciada',
	"tzinitik":'revernciado',
	"tzinkapa":'baja',
	"tzinkapa":'bajo',
	"tzinik":'venerable',
	"tzintik":'respetable',
	"tzinuak":'empequeñecida',
	"tzinuak":'empequeñecido',
	"tzinuatik":'achicada',
	"tzinuatik":'achicado',
	"tzinuatik":'aminorada',
	"tzinuatik":'aminorado',
	"tzinuatik":'degradada',
	"tzinuatik":'degradado',
	"tzinuhtik":'despacio',
	"tzinuhtik":'lenta',
	"tzinuhtik":'lento',
	"tzinuik":'encogida',
	"tzinuik":'encogido',
	"tzinyok":'poquito',
	"tzinyok":'respetuosa',
	"tzinyok":'respetuoso',
	"tzinyok":'respetuosos',
	"tzinyok":'suave',
	"tzitziniak":'diludida',
	"tzitziniak":'diludido',
	"tzitziniatik":'aminorada',
	"tzitziniatik":'aminorado',
	"tzitziniatik":'degradada',
	"tzitziniatik":'degradado',
	"tzitziniatik":'rebajada',
	"tzitziniatik":'rebajado',
	"tziuhtik":'lento',
	"tzo":'o',
	"tzok":'mugroso',
	"tzok":'sucia',
	"tzok":'sucio',
	"tzoktli":'mugroso',
	"tzoktli":'sucia',
	"tzoktli":'sucio',
	"tzolyak":'apestosa',
	"tzolyak":'apestoso',
	"tzolyaktik":'apestosa',
	"tzolyaktik":'apestoso',
	"tzominiak":'destruida',
	"tzominiak":'destruido',
	"tzomonik":'frágil',
	"tzomonik":'quebradiza',
	"tzomonik":'quebradizo',
	"tzomonik":'rota',
	"tzomonik":'roto',
	"tzomonitik":'fracturada',
	"tzomonitik":'fracturado',
	"tzomonitik":'quebrada',
	"tzomonitik":'quebrado',
	"tzontekontekik":'decapitada',
	"tzontekontekik":'decapitado',
	"tzontekontlauanki":'tonta',
	"tzontekontlauanki":'tonto',
	"tzontetek":'necia',
	"tzontetek":'necio',
	"tzontetek":'terca',
	"tzontetek":'terco',
	"tzontetek":'testaruda',
	"tzontetek":'testarudo',
	"tzotik":'separada',
	"tzotik":'separado',
	"tzotzoka":'ambicioso',
	"tzotzoka":'avaricioso',
	"tzotzokatl":'ambicioso',
	"tzoyok":'raro',
	"tzoyonki":'frito',
	"tzoyotik":'ensuciada',
	"tzoyotik":'ensuciado',
	"uahkiatik":'secada',
	"uahkiatik":'secado',
	"ualak":'venida',
	"ualak":'venido',
	"uaniak":'acumulada',
	"uaniak":'acumulado',
	"uaniak":'integrada',
	"uaniak":'integrado',
	"uaniak":'juntada',
	"uaniak":'juntado',
	"uaniak":'unida',
	"uaniak":'unido',
	"uehka":'distante',
	"uehka":'lejano',
	"uehka":'lejos',
	"uehkak":'alejada',
	"uehkak":'alejado',
	"uehkak":'distanciada',
	"uehkak":'distanciado',
	"uehkapa":'alta',
	"uehkapa":'alto',
	"uehkatlahtoki":'teléfono',
	"uelik":'poderosa',
	"uelik":'poderoso',
	"ueliuik":'pronta',
	"ueliuik":'pronto',
	"ueliuik":'rápida',
	"ueliuik":'rápido',
	"ueliz":'quizá',
	"ueliz":'quizás',
	"ueliz":'tal vez',
	"ueltik":'capaces',
	"ueltik":'capaz',
	"uelueyik":'elegante',
	"uetzkak":'caida',
	"uetzkak":'caido',
	"uetzkak":'desplomada',
	"uetzkak":'desplomado',
	"uetzkak":'reida',
	"uetzkak":'reido',
	"uetzkak":'sonreida',
	"uetzkak":'sonreido',
	"uetzkatok":'caído',
	"uey":'gran',
	"ueyak":'larga',
	"ueyak":'largo',
	"ueyik":'grande',
	"ueyikchiuak":'agrandada',
	"ueyikchiuak":'agrandado',
	"ueyikchiuak":'super',
	"ueyikchiualiztik":'exajerativa',
	"ueyikchiualiztik":'exajerativo',
	"ueyikchiutik":'exajerada',
	"ueyikchiutik":'exajerado',
	"ueyikchiutik":'superativa',
	"ueyikchiutik":'superativo',
	"uihkak":'llevada',
	"uihkak":'llevado',
	"uihkak":'portada',
	"uihkak":'portado',
	"uihkilitik":'adeudada',
	"uihkilitik":'adeudado',
	"uihtik":'seca',
	"uihtik":'seco',
	"uipil":'vestido',
	"uitziak":'espinada',
	"uitziak":'espinado',
	"uitziak":'pinchada',
	"uitziak":'pinchado',
	"uitzpaniak":'espinada',
	"uitzpaniak":'espinado',
	"uitzpaniak":'picada',
	"uitzpaniak":'picado',
	"uitztik":'picuda',
	"uitztik":'picudo',
	"uitztik":'punzante',
	"uiyok":'peligrosa',
	"uiyok":'peligroso',
	"xexelok":'escarbada',
	"xexelok":'escarbado',
	"xexelok":'rascada',
	"xexelok":'rascado',
	"xihiak":'acertada',
	"xihiak":'acertado',
	"xihiak":'atinada',
	"xihiak":'atinado',
	"xihmakak":'acertada',
	"xihmakak":'acertado',
	"xikaltok":'calvo',
	"xiuhtik":'azul',
	"xiuitl":'año',
	"xokok":'agriada',
	"xokok":'agriado',
	"xokoxochitl":'rosa',
	"xolok":'transformada',
	"xolok":'transformado',
	"xolok":'variada',
	"xolok":'variado',
	"xolopihki":'mentiroso',
	"xolotik":'variable',
	"xolotik":'variables',
	"yalhua":'ayer',
	"yamantik":'templada',
	"yamantik":'templado',
	"yankuik":'nueva',
	"yankuik":'nuevo',
	"yankuik":'reciente',
	"yaok":'atacada',
	"yaok":'atacado',
	"yaok":'peleada',
	"yaok":'peleado',
	"yaolizko":'confrontatoria',
	"yaolizko":'confrontatorio',
	"yaoliztik":'enfrentativa',
	"yaoliztik":'enfrentativo',
	"yauk":'ida',
	"yauk":'ido',
	"yayauhtik":'intensa',
	"yayauhtik":'intenso',
	"yek":'derecha',
	"yek":'derecho',
	"yekamik":'derecha',
	"yekmachiliak":'capacitada',
	"yekmachiliak":'capacitado',
	"yektlaliak":'acondicionada',
	"yektlaliak":'acondicionado',
	"yektlaliak":'preparada',
	"yektlaliak":'preparado',
	"yekuakzeliltik":'jurídica',
	"yekuakzeliltik":'jurídico',
	"yekuayok":'jurídico',
	"yekuilyo":'jurídico',
	"yekyoik":'bonito',
	"yekyok":'bonita',
	"yekyok":'bonito',
	"yekyok":'preciosa',
	"yekyok":'precioso',
	"yekyoktzin":'bonito',
	"yekyolik":'bonito',
	"yekyolik":'preciosa',
	"yekyolik":'precioso',
	"yekyolli":'bonito',
	"yekyoltzin":'bonita',
	"yekyoltzin":'bonito',
	"yekyoltzin":'preciosa',
	"yekyoltzin":'precioso',
	"yekyotzin":'bonita',
	"yekyotzin":'bonito',
	"yekyotzin":'preciosa',
	"yekyotzin":'precioso',
	"yekzeliltik":'jurídica',
	"yekzeliltik":'jurídico',
	"yeyetehtik":'torpe',
	"yeyetehtik":'torpes',
	"yo":'esencia',
	"yolchiuiliak":'coqueteada',
	"yolchiuiliak":'coqueteado',
	"yolnekik":'deseada',
	"yolnekik":'deseado',
	"yolnotzak":'inspirada',
	"yolnotzak":'inspirado',
	"yolotik":'cardiaco',
	"yolpachok":'asimilada',
	"yolpachok":'asimilado',
	"yolpachok":'consolada',
	"yolpachok":'consolado',
	"youiak":'dificultada',
	"youiak":'dificultado',
	"youik":'compleja',
	"youik":'complejas',
	"youik":'complejo',
	"youik":'complejos',
	"youik":'confusa',
	"youik":'confusas',
	"youik":'confuso',
	"youik":'confusos',
	"youik":'difícil',
	"youik":'difíciles',
	"zauik":'cansada',
	"zauik":'cansado',
	"ze":'una',
	"ze":'un',
	"ze":'uno',
	"zeixtelolotzak":'guiñada',
	"zeixtelolotzak":'guiñado',
	"zekuik":'congelada',
	"zekuik":'congelado',
	"zekuik":'enfriada',
	"zekuik":'enfriado',
	"zeliak":'aceptada',
	"zeliak":'aceptado',
	"zeliak":'admitida',
	"zeliak":'admitido',
	"zelik":'tierno',
	"zempoualuanmakuilchikipiluako":'1/10000',
	"zen":'solo',
	"zeualli":'sombra',
	"zeuik":'descansada',
	"zeuik":'descansado',
	"zezek":'fría',
	"zezek":'frío',
	"zezekiak":'diferida',
	"zezekiak":'diferido',
	"zezekiak":'dividida',
	"zezekiak":'dividido',
	"zezekik":'separada',
	"zezekik":'separado',
	"zezeltlachiak":'comparada',
	"zezeltlachiak":'comparado',
	"ziuhtik":'lenta',
	"zolik":'vieja',
	"zolik":'viejo',
	"| ʎ":'2000',
	"| • ʎ":'2400',
	"| •":'6',
	"| •• ʎ":'2800',
	"| ••":'7',
	"| ••• ʎ":'3200',
	"| •••":'8',
	"| •••• ʎ":'3600',
	"| ••••":'9',
	"|":'5',
	"|| ʎ":'4000',
	"|| • ʎ":'4400',
	"|| •":'11',
	"|| •• ʎ":'4800',
	"|| ••":'12',
	"|| ••• ʎ":'5200',
	"|| •••":'13',
	"|| •••• ʎ":'5600',
	"|| ••••":'14',
	"||":'10',
	"||| ʎ":'6000',
	"||| • ʎ":'6400',
	"||| •":'16',
	"||| •• ʎ":'6800',
	"||| ••":'17',
	"||| ••• ʎ":'7200',
	"||| •••":'18',
	"||| •••• ʎ":'7600',
	"||| ••••":'19',
	"|||":'15',
	"υ":'8000',
	"•":'1',
	"•ʎ":'400',
	"•• ʎ":'800',
	"••":'2',
	"••• ʎ":'1200',
	"•••":'3',
	"•••• ʎ":'1600',
	"••••":'4',

# Reflexivos
	"nehuatl nimo":'yo mismo',
	"nimo":'yo mismo',
	"tehuatl timo":'tú mismo',
	"timo":'tú mismo',
	"yehuatl mo":['ella misma, él mismo, se'],
	"mo":['ella misma, él mismo, se'],
	"tehuan timo":['nosotras mismas, nosotros mismos, nos'], # Este elemento requiere de una terminación plural del verbo si se quiere que el reflexivo sea plural.
	"timo":['nosotras mismas, nosotros mismos, nos'], # Este elemento requiere de una terminación plural del verbo si se quiere que el reflexivo sea plural.
	"anmehuan anmo":['vosotras mismas, vosotros mismos, les'], # Este elemento requiere de una terminación plural del verbo si se quiere que el reflexivo sea plural.
	"anmo":['vosotras mismas, vosotros mismos, les'], # Este elemento requiere de una terminación plural del verbo si se quiere que el reflexivo sea plural.
	"kinmo":['a ellas, a ellos, les'], # Este elemento requiere de una terminación plural del verbo si se quiere que el reflexivo sea plural.
	"inmo":['a ellas, a ellos, les'], # Este elemento requiere de una terminación plural del verbo si se quiere que el reflexivo sea plural.

# acusativos
	"nech":'a mí',
	"nech":'mí',
	"mitz":'ti',
	"ki":['a ella, a él, lo'],
	"tech":['a nosotras, a nosotros, nos'],
	"anmech":['a vosotras, a vosotros, vos, a ustedes'],
	"kin":['a ellas, a ellos, les']
}