# -*- coding: utf-8 -*-
"""
© Roberto Spíndola Barrón, 2026.
Todos los derechos reservados.

Sistema estructural de análisis lingüístico Náhuatl ↔ Español.
Módulo: [MODIFIERS_SP_NTL]
Versión: v1.0
Fecha: [23-05-2026]

Prohibida la reproducción, redistribución, extracción estructural,
ingeniería inversa, entrenamiento de modelos de inteligencia artificial
o reutilización no autorizada.
"""

MODIFIERS= {
	"1":'•',
	"1/10":'mahtlauako',
	"1/100":'makuilzempoualuako',
	"1/10000":'zempoualuanmakuilchikipiluako',
	"1/100000":'mahtlakuanomezempoualuanmahtlakchikipiluako',
	"1/1200":'eyichikipiluako',
	"1/2":'mkan',
	"1/20000":'naupoualuanmahtlakchikipiluako',
	"1/3":'eyiuako',
	"1/300":'mahtlakuankaxtolpoualuako',
	"1/4":'nauako',
	"1/400":'chikipiluako',
	"1/5":'mahkuiluako',
	"1/6":'chikoazeuako',
	"1/6":'mahkuiluanzeuako',
	"1/7":'chikomkan',
	"1/7":'mahkuiluanomeuako',
	"1/8":'chikoeyuako',
	"1/9":'chiknauiko',
	"10":'||',
	"81":'(••••O) •',
	"82":'(••••O) ••',
	"83":'(••••O) •••',
	"84":'(••••O) ••••',
	"85":'(••••O) |',
	"86":'(••••O) | •',
	"87":'(••••O) | ••',
	"88":'(••••O) | •••',
	"89":'(••••O) | ••••',
	"90":'(••••O) ||',
	"91":'(••••O) || •',
	"92":'(••••O) || ••',
	"93":'(••••O) || •••',
	"94":'(••••O) || ••••',
	"95":'(••••O) |||',
	"96":'(••••O) ||| •',
	"97":'(••••O) ||| ••',
	"98":'(••••O) ||| •••',
	"99":'(••••O) ||| ••••',
	"100":'(|O)',
	"101":'(|O) •',
	"102":'(|O) ••',
	"103":'(|O) •••',
	"104":'(|O) ••••',
	"105":'(|O) |',
	"106":'(|O) | •',
	"107":'(|O) | ••',
	"108":'(|O) | •••',
	"109":'(|O) | ••••',
	"10°":'mahtlaktetl',
	"10°":'mahtlauako',
	"11":'|| •',
	"110":'(|O) ||',
	"111":'(|O) || •',
	"112":'(|O) || ••',
	"113":'(|O) || •••',
	"114":'(|O) || ••••',
	"115":'(|O) |||',
	"116":'(|O) ||| •',
	"117":'(|O) ||| ••',
	"118":'(|O) ||| •••',
	"119":'(|O) ||| ••••',
	"11°":'mahtlak uan zentetl',
	"12":'|| ••',
	"120":'(|O) •O',
	"1200":'••• ʎ',
	"121":'(|O) (O) •',
	"122":'(|O) (O) ••',
	"123":'(|O) (O) •••',
	"124":'(|O) (O) ••••',
	"125":'(|O) (O) |',
	"126":'(|O) (O) | •',
	"127":'(|O) (O) | ••',
	"128":'(|O) (O) | •••',
	"129":'(|O) (O) | ••••',
	"12°":'mahtlak uan omtetl',
	"13":'|| •••',
	"130":'(|O) (O) ||',
	"131":'(|O) (O) || •',
	"132":'(|O) (O) || ••',
	"133":'(|O) (O) || •••',
	"134":'(|O) (O) || ••••',
	"135":'(|O) (O) |||',
	"136":'(|O) (O) ||| •',
	"137":'(|O) (O) ||| ••',
	"138":'(|O) (O) ||| •••',
	"139":'(|O) (O) ||| ••••',
	"13°":'mahtlak uan yetetl',
	"14":'|| ••••',
	"140":'(|O) ••O',
	"141":'(|O) (••O) •',
	"142":'(|O) (••O) ••',
	"143":'(|O) (••O) •••',
	"144":'(|O) (••O) ••••',
	"145":'(|O) (••O) |',
	"146":'(|O) (••O) | •',
	"147":'(|O) (••O) | ••',
	"148":'(|O) (••O) | •••',
	"149":'(|O) (••O) | ••••',
	"14°":'mahtlak uan nautetl',
	"15":'|||',
	"150":'(|O) (••O) ||',
	"151":'(|O) (••O) || •',
	"152":'(|O) (••O) || ••',
	"153":'(|O) (••O) || •••',
	"154":'(|O) (••O) || ••••',
	"155":'(|O) (••O) |||',
	"156":'(|O) (••O) ||| •',
	"157":'(|O) (••O) ||| ••',
	"158":'(|O) (••O) ||| •••',
	"159":'(|O) (••O) ||| ••••',
	"15°":'kaxtoltetl',
	"16":'||| •',
	"160":'(|O) (•••O) ||',
	"1600":'•••• ʎ',
	"161":'(|O) (•••O) •',
	"162":'(|O) (•••O) ••',
	"163":'(|O) (•••O) •••',
	"164":'(|O) (•••O) ••••',
	"165":'(|O) (•••O) |',
	"166":'(|O) (•••O) | •',
	"167":'(|O) (•••O) | ••',
	"168":'(|O) (•••O) | •••',
	"169":'(|O) (•••O) | ••••',
	"16°":'kaxtoluanzentetl',
	"17":'||| ••',
	"170":'(|O) (•••O) ||',
	"171":'(|O) (•••O) || •',
	"172":'(|O) (•••O) || ••',
	"173":'(|O) (•••O) || •••',
	"174":'(|O) (•••O) || ••••',
	"175":'(|O) (•••O) |||',
	"176":'(|O) (•••O) ||| •',
	"177":'(|O) (•••O) ||| ••',
	"178":'(|O) (•••O) ||| •••',
	"179":'(|O) (•••O) ||| ••••',
	"17°":'kaxtoluanometetl',
	"18":'||| •••',
	"180":'(|O) (••••O)',
	"181":'(|O) (••••O) •',
	"182":'(|O) (••••O) ••',
	"183":'(|O) (••••O) •••',
	"184":'(|O) (••••O) ••••',
	"185":'(|O) (••••O) |',
	"186":'(|O) (••••O) | •',
	"187":'(|O) (••••O) | ••',
	"188":'(|O) (••••O) | •••',
	"189":'(|O) (••••O) | ••••',
	"18°":'kaxtoluanyetetl',
	"19":'||| ••••',
	"190":'(|O) (••••O) ||',
	"191":'(|O) (••••O) || •',
	"192":'(|O) (••••O) || ••',
	"193":'(|O) (••••O) || •••',
	"194":'(|O) (••••O) || ••••',
	"195":'(|O) (••••O) |||',
	"196":'(|O) (••••O) ||| •',
	"197":'(|O) (••••O) ||| ••',
	"198":'(|O) (••••O) ||| •••',
	"199":'(|O) (••••O) ||| ••••',
	"19°":'kaxtoluanautetl',
	"2":'••',
	"20":'O',
	"200":'(||O)',
	"2000":'| ʎ',
	"201":'(||O) •',
	"202":'(||O) ••',
	"203":'(||O) •••',
	"204":'(||O) ••••',
	"205":'(||O) |',
	"206":'(||O) | •',
	"207":'(||O) | ••',
	"208":'(||O) | •••',
	"209":'(||O) | ••••',
	"21":'O •',
	"210":'(||O) ||',
	"211":'(||O) || •',
	"212":'(||O) || ••',
	"213":'(||O) || •••',
	"214":'(||O) || ••••',
	"215":'(||O) |||',
	"216":'(||O) ||| •',
	"217":'(||O) ||| ••',
	"218":'(||O) ||| •••',
	"219":'(||O) ||| ••••',
	"22":'O ••',
	"220":'(||O) •O',
	"221":'(||O) (O) •',
	"222":'(||O) (O) ••',
	"223":'(||O) (O) •••',
	"224":'(||O) (O) ••••',
	"225":'(||O) (O) |',
	"226":'(||O) (O) | •',
	"227":'(||O) (O) | ••',
	"228":'(||O) (O) | •••',
	"229":'(||O) (O) | ••••',
	"23":'O •••',
	"230":'(||O) (O) ||',
	"231":'(||O) (O) || •',
	"232":'(||O) (O) || ••',
	"233":'(||O) (O) || •••',
	"234":'(||O) (O) || ••••',
	"235":'(||O) (O) |||',
	"236":'(||O) (O) ||| •',
	"237":'(||O) (O) ||| ••',
	"238":'(||O) (O) ||| •••',
	"239":'(||O) (O) ||| ••••',
	"24":'O ••••',
	"240":'(||O) ••O',
	"2400":'| • ʎ',
	"241":'(||O) (••O) •',
	"242":'(||O) (••O) ••',
	"243":'(||O) (••O) •••',
	"244":'(||O) (••O) ••••',
	"245":'(||O) (••O) |',
	"246":'(||O) (••O) | •',
	"247":'(||O) (••O) | ••',
	"248":'(||O) (••O) | •••',
	"249":'(||O) (••O) | ••••',
	"25":'O|',
	"250":'(||O) (••O) ||',
	"251":'(||O) (••O) || •',
	"252":'(||O) (••O) || ••',
	"253":'(||O) (••O) || •••',
	"254":'(||O) (••O) || ••••',
	"255":'(||O) (••O) |||',
	"256":'(||O) (••O) ||| •',
	"257":'(||O) (••O) ||| ••',
	"258":'(||O) (••O) ||| •••',
	"259":'(||O) (••O) ||| ••••',
	"26":'O| •',
	"260":'(||O) (•••O) ||',
	"261":'(||O) (•••O) •',
	"262":'(||O) (•••O) ••',
	"263":'(||O) (•••O) •••',
	"264":'(||O) (•••O) ••••',
	"265":'(||O) (•••O) |',
	"266":'(||O) (•••O) | •',
	"267":'(||O) (•••O) | ••',
	"268":'(||O) (•••O) | •••',
	"269":'(||O) (•••O) | ••••',
	"27":'O| ••',
	"270":'(||O) (•••O) ||',
	"271":'(||O) (•••O) || •',
	"272":'(||O) (•••O) || ••',
	"273":'(||O) (•••O) || •••',
	"274":'(||O) (•••O) || ••••',
	"275":'(||O) (•••O) |||',
	"276":'(||O) (•••O) ||| •',
	"277":'(||O) (•••O) ||| ••',
	"278":'(||O) (•••O) ||| •••',
	"279":'(||O) (•••O) ||| ••••',
	"28":'O| •••',
	"280":'(||O) (••••O)',
	"2800":'| •• ʎ',
	"281":'(||O) (••••O) •',
	"282":'(||O) (••••O) ••',
	"283":'(||O) (••••O) •••',
	"284":'(||O) (••••O) ••••',
	"285":'(||O) (••••O) |',
	"286":'(||O) (••••O) | •',
	"287":'(||O) (••••O) | ••',
	"288":'(||O) (••••O) | •••',
	"289":'(||O) (••••O) | ••••',
	"29":'O| ••••',
	"290":'(||O) (••••O) ||',
	"291":'(||O) (••••O) || •',
	"292":'(||O) (••••O) || ••',
	"293":'(||O) (••••O) || •••',
	"294":'(||O) (••••O) || ••••',
	"295":'(||O) (••••O) |||',
	"296":'(||O) (••••O) ||| •',
	"297":'(||O) (••••O) ||| ••',
	"298":'(||O) (••••O) ||| •••',
	"299":'(||O) (••••O) ||| ••••',
	"3":'•••',
	"30":'O||',
	"300":'(|||O)',
	"301":'(|||O) •',
	"302":'(|||O) ••',
	"303":'(|||O) •••',
	"304":'(|||O) ••••',
	"305":'(|||O) |',
	"306":'(|||O) | •',
	"307":'(|||O) | ••',
	"308":'(|||O) | •••',
	"309":'(|||O) | ••••',
	"31":'O|| •',
	"310":'(|||O) ||',
	"311":'(|||O) || •',
	"312":'(|||O) || ••',
	"313":'(|||O) || •••',
	"314":'(|||O) || ••••',
	"315":'(|||O) |||',
	"316":'(|||O) ||| •',
	"317":'(|||O) ||| ••',
	"318":'(|||O) ||| •••',
	"319":'(|||O) ||| ••••',
	"32":'O|| ••',
	"320":'(|||O) •O',
	"3200":'| ••• ʎ',
	"321":'(|||O) (O) •',
	"322":'(|||O) (O) ••',
	"323":'(|||O) (O) •••',
	"324":'(|||O) (O) ••••',
	"325":'(|||O) (O) |',
	"326":'(|||O) (O) | •',
	"327":'(|||O) (O) | ••',
	"328":'(|||O) (O) | •••',
	"329":'(|||O) (O) | ••••',
	"33":'O|| •••',
	"330":'(|||O) (O) ||',
	"331":'(|||O) (O) || •',
	"332":'(|||O) (O) || ••',
	"333":'(|||O) (O) || •••',
	"334":'(|||O) (O) || ••••',
	"335":'(|||O) (O) |||',
	"336":'(|||O) (O) ||| •',
	"337":'(|||O) (O) ||| ••',
	"338":'(|||O) (O) ||| •••',
	"339":'(|||O) (O) ||| ••••',
	"34":'O|| ••••',
	"340":'(|||O) ••O',
	"341":'(|||O) (••O) •',
	"342":'(|||O) (••O) ••',
	"343":'(|||O) (••O) •••',
	"344":'(|||O) (••O) ••••',
	"345":'(|||O) (••O) |',
	"346":'(|||O) (••O) | •',
	"347":'(|||O) (••O) | ••',
	"348":'(|||O) (••O) | •••',
	"349":'(|||O) (••O) | ••••',
	"35":'O|||',
	"350":'(|||O) (••O) ||',
	"351":'(|||O) (••O) || •',
	"352":'(|||O) (••O) || ••',
	"353":'(|||O) (••O) || •••',
	"354":'(|||O) (••O) || ••••',
	"355":'(|||O) (••O) |||',
	"356":'(|||O) (••O) ||| •',
	"357":'(|||O) (••O) ||| ••',
	"358":'(|||O) (••O) ||| •••',
	"359":'(|||O) (••O) ||| ••••',
	"36":'O||| •',
	"360":'(|||O) (•••O) ||',
	"3600":'| •••• ʎ',
	"361":'(|||O) (•••O) •',
	"362":'(|||O) (•••O) ••',
	"363":'(|||O) (•••O) •••',
	"364":'(|||O) (•••O) ••••',
	"365":'(|||O) (•••O) |',
	"366":'(|||O) (•••O) | •',
	"367":'(|||O) (•••O) | ••',
	"368":'(|||O) (•••O) | •••',
	"369":'(|||O) (•••O) | ••••',
	"37":'O||| ••',
	"370":'(|||O) (•••O) ||',
	"371":'(|||O) (•••O) || •',
	"372":'(|||O) (•••O) || ••',
	"373":'(|||O) (•••O) || •••',
	"374":'(|||O) (•••O) || ••••',
	"375":'(|||O) (•••O) |||',
	"376":'(|||O) (•••O) ||| •',
	"377":'(|||O) (•••O) ||| ••',
	"378":'(|||O) (•••O) ||| •••',
	"379":'(|||O) (•••O) ||| ••••',
	"38":'O||| •••',
	"380":'(|||O) (••••O)',
	"381":'(|||O) (••••O) •',
	"382":'(|||O) (••••O) ••',
	"383":'(|||O) (••••O) •••',
	"384":'(|||O) (••••O) ••••',
	"385":'(|||O) (••••O) |',
	"386":'(|||O) (••••O) | •',
	"387":'(|||O) (••••O) | ••',
	"388":'(|||O) (••••O) | •••',
	"389":'(|||O) (••••O) | ••••',
	"39":'O||| ••••',
	"390":'(|||O) (••••O) ||',
	"391":'(|||O) (••••O) || •',
	"392":'(|||O) (••••O) || ••',
	"393":'(|||O) (••••O) || •••',
	"394":'(|||O) (••••O) || ••••',
	"395":'(|||O) (••••O) |||',
	"396":'(|||O) (••••O) ||| •',
	"397":'(|||O) (••••O) ||| ••',
	"398":'(|||O) (••••O) ||| •••',
	"399":'(|||O) (••••O) ||| ••••',
	"4":'••••',
	"40":'(••O)',
	"400":'•ʎ',
	"4000":'|| ʎ',
	"401":'(ʎ) •',
	"402":'(ʎ) ••',
	"403":'(ʎ) •••',
	"404":'(ʎ) ••••',
	"405":'(ʎ) |',
	"406":'(ʎ) | •',
	"407":'(ʎ) | ••',
	"408":'(ʎ) | •••',
	"409":'(ʎ) | ••••',
	"41":'(••O) •',
	"410":'(ʎ) ||',
	"411":'(ʎ) || •',
	"412":'(ʎ) || ••',
	"413":'(ʎ) || •••',
	"414":'(ʎ) || ••••',
	"415":'(ʎ) |||',
	"416":'(ʎ) ||| •',
	"417":'(ʎ) ||| ••',
	"418":'(ʎ) ||| •••',
	"419":'(ʎ) ||| ••••',
	"42":'(••O) ••',
	"420":'(ʎ) •O',
	"421":'(ʎ) (O) •',
	"422":'(ʎ) (O) ••',
	"423":'(ʎ) (O) •••',
	"424":'(ʎ) (O) ••••',
	"425":'(ʎ) (O) |',
	"426":'(ʎ) (O) | •',
	"427":'(ʎ) (O) | ••',
	"428":'(ʎ) (O) | •••',
	"429":'(ʎ) (O) | ••••',
	"43":'(••O) •••',
	"430":'(ʎ) (O) ||',
	"431":'(ʎ) (O) || •',
	"432":'(ʎ) (O) || ••',
	"433":'(ʎ) (O) || •••',
	"434":'(ʎ) (O) || ••••',
	"435":'(ʎ) (O) |||',
	"436":'(ʎ) (O) ||| •',
	"437":'(ʎ) (O) ||| ••',
	"438":'(ʎ) (O) ||| •••',
	"439":'(ʎ) (O) ||| ••••',
	"44":'(••O) ••••',
	"440":'(ʎ) ••O',
	"4400":'|| • ʎ',
	"441":'(ʎ) (••O) •',
	"442":'(ʎ) (••O) ••',
	"443":'(ʎ) (••O) •••',
	"444":'(ʎ) (••O) ••••',
	"445":'(ʎ) (••O) |',
	"446":'(ʎ) (••O) | •',
	"447":'(ʎ) (••O) | ••',
	"448":'(ʎ) (••O) | •••',
	"449":'(ʎ) (••O) | ••••',
	"45":'(••O) |',
	"450":'(ʎ) (••O) ||',
	"451":'(ʎ) (••O) || •',
	"452":'(ʎ) (••O) || ••',
	"453":'(ʎ) (••O) || •••',
	"454":'(ʎ) (••O) || ••••',
	"455":'(ʎ) (••O) |||',
	"456":'(ʎ) (••O) ||| •',
	"457":'(ʎ) (••O) ||| ••',
	"458":'(ʎ) (••O) ||| •••',
	"459":'(ʎ) (••O) ||| ••••',
	"46":'(••O) | •',
	"460":'(ʎ) (•••O) ||',
	"461":'(ʎ) (•••O) •',
	"462":'(ʎ) (•••O) ••',
	"463":'(ʎ) (•••O) •••',
	"464":'(ʎ) (•••O) ••••',
	"465":'(ʎ) (•••O) |',
	"466":'(ʎ) (•••O) | •',
	"467":'(ʎ) (•••O) | ••',
	"468":'(ʎ) (•••O) | •••',
	"469":'(ʎ) (•••O) | ••••',
	"47":'(••O) | ••',
	"470":'(ʎ) (•••O) ||',
	"471":'(ʎ) (•••O) || •',
	"472":'(ʎ) (•••O) || ••',
	"473":'(ʎ) (•••O) || •••',
	"474":'(ʎ) (•••O) || ••••',
	"475":'(ʎ) (•••O) |||',
	"476":'(ʎ) (•••O) ||| •',
	"477":'(ʎ) (•••O) ||| ••',
	"478":'(ʎ) (•••O) ||| •••',
	"479":'(ʎ) (•••O) ||| ••••',
	"48":'(••O) | •••',
	"480":'(ʎ) (••••O)',
	"4800":'|| •• ʎ',
	"481":'(ʎ) (••••O) •',
	"482":'(ʎ) (••••O) ••',
	"483":'(ʎ) (••••O) •••',
	"484":'(ʎ) (••••O) ••••',
	"485":'(ʎ) (••••O) |',
	"486":'(ʎ) (••••O) | •',
	"487":'(ʎ) (••••O) | ••',
	"488":'(ʎ) (••••O) | •••',
	"489":'(ʎ) (••••O) | ••••',
	"49":'(••O) | ••••',
	"490":'(ʎ) (••••O) ||',
	"491":'(ʎ) (••••O) || •',
	"492":'(ʎ) (••••O) || ••',
	"493":'(ʎ) (••••O) || •••',
	"494":'(ʎ) (••••O) || ••••',
	"495":'(ʎ) (••••O) |||',
	"496":'(ʎ) (••••O) ||| •',
	"497":'(ʎ) (••••O) ||| ••',
	"498":'(ʎ) (••••O) ||| •••',
	"499":'(ʎ) (••••O) ||| ••••',
	"4°":'nautetl',
	"5":'|',
	"50":'(••O) ||',
	"51":'(••O) || •',
	"52":'(••O) || ••',
	"5200":'|| ••• ʎ',
	"53":'(••O) || •••',
	"54":'(••O) || ••••',
	"55":'(••O) |||',
	"56":'(••O) ||| •',
	"5600":'|| •••• ʎ',
	"57":'(••O) ||| ••',
	"58":'(••O) ||| •••',
	"59":'(••O) ||| ••••',
	"6":'| •',
	"60":'(|||O)',
	"6000":'||| ʎ',
	"61":'(|||O) •',
	"62":'(|||O) ••',
	"63":'(|||O) •••',
	"64":'(|||O) ••••',
	"6400":'||| • ʎ',
	"65":'(|||O) |',
	"66":'(|||O) | •',
	"67":'(|||O) | ••',
	"68":'(|||O) | •••',
	"6800":'||| •• ʎ',
	"69":'(|||O) | ••••',
	"6°":'chikoazentetl',
	"7":'| ••',
	"70":'(|||O) ||',
	"71":'(|||O) || •',
	"72":'(|||O) || ••',
	"7200":'||| ••• ʎ',
	"73":'(|||O) || •••',
	"74":'(|||O) || ••••',
	"75":'(|||O) |||',
	"76":'(|||O) ||| •',
	"7600":'||| •••• ʎ',
	"77":'(|||O) ||| ••',
	"78":'(|||O) ||| •••',
	"79":'(|||O) ||| ••••',
	"7°":'chikomtetl',
	"8":'| •••',
	"80":'(••••O)',
	"800":'•• ʎ',
	"8000":'chikipilli',
	"8000":'υ',
	"8°":'chikoeytetl',
	"9":'| ••••',
	
	"9°":'chiknautetl',
	"a través de":'ipal',
	"a través de":'ipalli',
	"a través del":'ipalli',
	"abajo":'tzintlan',
	"abandonada":'kauak',
	"abandonado":'kauak',
	"abarcada":'pachok',
	"abarcado":'pachok',
	"abierta":'tlapok',
	"abierto":'tlapok',
	"abominable":'amokualtik',
	"abominables":'amokualtikuan',
	"abominada":'amokualteilchiuatik',
	"abominada":'amokualteilchiuk',
	"abominado":'amokualteilchiuatik',
	"abominado":'amokualteilchiuk',
	"abrazada":'pachoatik',
	"abrazada":'pachok',
	"abrazado":'pachoatik',
	"abrazado":'pachok',
	"abundante":'achpantok',
	"abundantes":'achpanikuan',
	"abundativa":'achpaniliztik',
	"abundativo":'achpaniliztik',
	"abusiva":'achpanitik',
	"abusivo":'achpanitik',
	"acalorada":'tonak',
	"acalorado":'tonak',
	"acaparada":'pachok',
	"acaparado":'pachok',
	"acaso":'koch',
	"acaudalante":'axuahtok',
	"acelerada":'olyok',
	"acelerado":'olyok',
	"acelerado":'olyotik',
	"aceptada":'zeliak',
	"aceptado":'zeliak',
	"acertada":'xihiak',
	"acertada":'xihmakak',
	"acertado":'xihiak',
	"acertado":'xihmakak',
	"achicada":'tzinuatik',
	"achicado":'tzinuatik',
	"aclarosa":'chipauatik',
	"aclaroso":'chipauatik',
	"acomodatoria":'nepanpatik',
	"acomodatorio":'nepanpatik',
	"acondicionada":'yektlaliak',
	"acondicionado":'yektlaliak',
	"acongojada":'achikopalatik',
	"acongojado":'achikopalatik',
	"acontecida":'panoyok',
	"acontecido":'panoyok',
	"acostumbrada":'matichiuatik',
	"acostumbrado":'matichiuatik',
	"activa":'chiuak',
	"activada":'tlaueliak',
	"activado":'tlaueliak',
	"activas":'chiuak',
	"activo":'chiuak',
	"activos":'chiuak',
	"actualizada":'axkapanik',
	"actualizado":'axkapanik',
	"acuerdo":'ixmatipan',
	"acumulada":'uaniak',
	"acumulado":'uaniak',
	"acumulativa":'achpanik',
	"acumulativa":'achpaniliztik',
	"acumulativas":'achpanikuan',
	"acumulativo":'achpanik',
	"acumulativo":'achpaniliztik',
	"acumulativos":'achpanikuan',
	"acumulatoria":'achpaniliztik',
	"acumulatorio":'achpaniliztik',
	"acuosa":'atik',
	"acuosa":'ayok',
	"acuosas":'atikuan',
	"acuoso":'atik',
	"acuoso":'ayok',
	"acuosos":'atikuan',
	"acusativa":'axkauaki',
	"acusativas":'axkauakiuan',
	"acusativo":'axkauaki',
	"acusativos":'axkauakiuan',
	"acuática":'atik',
	"acuático":'atik',
	"adaptada":'matichiuatik',
	"adaptado":'matichiuatik',
	"adecuada":'kualtik',
	"adecuado":'kualtik',
	"adelante":'ixkan',
	"adelante":'ixko',
	"adelante":'ixman',
	"adelante":'ixpan',
	"además":'achiokze',
	"adentra":'itekiak',
	"adentrada":'kalakiak',
	"adentrado":'kalakiak',
	"adentrativa":'itekializtik',
	"adentrativo":'itekializtik',
	"adentro":'itek',
	"adentro":'itekiak',
	"adentro":'itik',
	"adentros":'itekuan',
	"adentros":'itikuan',
	"adertiva":'panpalayok',
	"adertivo":'panpalayok',
	"adeudada":'kiliak',
	"adeudada":'uihkilitik',
	"adeudado":'kiliak',
	"adeudado":'uihkilitik',
	"adhecuada":'kualtik',
	"adhecuado":'kualtik',
	"adicionada":'iuanyok',
	"adicionado":'iuanyok',
	"adicional":'achtlanik',
	"adicionales":'achtlanuan',
	"administratoria":'nepanpatik',
	"administratorio":'nepanpatik',
	"admitida":'zeliak',
	"admitido":'zeliak',
	"adolorimientos":'amo yolotzinyouan',
	"adquirida":'tlaniak',
	"adquirido":'tlaniak',
	"adrede":'ik',
	"adrede":'ipampa',
	"adulterada":'akauiliztik',
	"adulterada":'makauik',
	"adulterado":'akauiliztik',
	"adulterado":'makauik',
	"advertida":'matizmakak',
	"advertido":'matizmakak',
	"adúltero":'makauki',
	"adúlteros":'makauan',
	"afirmada":'kematiak',
	"afirmada":'kemihtok',
	"afirmada":'kemiliak',
	"afirmado":'kematiak',
	"afirmado":'kemihtok',
	"afirmado":'kemiliak',
	"afirmativa":'kemak',
	"afirmativa":'kemiyok',
	"afirmativas":'kemiyokuan',
	"afirmativo":'kemak',
	"afirmativo":'kemiyok',
	"afirmativos":'kemiyokuan',
	"afirmatoria":'neltokaihtok',
	"afirmatorio":'neltokaihtok',
	"afuera":'kiauak',
	"agarrada":'kuik',
	"agarrado":'kuik',
	"agnado":'apaltik',
	"agnados":'apaltikuan',
	"agradable":'kualtzin',
	"agrandada":'ixkaltiak',
	"agrandada":'ixpankuik',
	"agrandada":'izkaliak',
	"agrandada":'izkaltiak',
	"agrandada":'ueyikchiuak',
	"agrandado":'ixkaltiak',
	"agrandado":'ixpankuik',
	"agrandado":'izkaliak',
	"agrandado":'izkaltiak',
	"agrandado":'ueyikchiuak',
	"agriada":'xokok',
	"agriado":'xokok',
	"aguacatal":'auakatitlan',
	"aguado":'ayotik',
	"aguanta":'chikouk',
	"aguanto":'chikouk',
	"aguañoso":'achitik',
	"aguda":'chopitik',
	"agudo":'chopitik',
	"ahogada":'amikyotik',
	"ahogado":'amikyotik',
	"airoso":'ehekatik',
	"ajustada":'mekajustik',
	"ajustado":'mekajustik',
	"al":'inin',
	"alcanzante":'azihtok',
	"aleatoria":'aiuhyotl',
	"aleatoria":'ayotik',
	"aleatoria":'ayotl',
	"aleatorio":'aiuhyotl',
	"aleatorio":'ayotik',
	"aleatorio":'ayotl',
	"alejada":'tlauehkak',
	"alejada":'uehkak',
	"alejado":'tlauehkak',
	"alejado":'uehkak',
	"algo":'tla',
	"algo":'tlaitl',
	"alguien": ['tekan', 'te'],
	"alguien":'te',
	"alguien":'teitl',
	"aliento":'ihyotl',
	"alimentada":'tlakuak',
	"alimentado":'tlakuak',
	"alisante":'neneuatok',
	"allá":'ompa',
	"allí":'ompa',
	"alta":'uehkapa',
	"alterada":'makauk',
	"alterado":'makauik',
	"alto":'uehkapa',
	"alzante":'ehkotok',
	"amable":'ikniuhtik',
	"amables":'ikniuhtik',
	"amada":'tlazohtiak',
	"amado":'tlazohtiak',
	"ambiciosa":'tzotzoka',
	"ambiciosa":'tzotzokaitl',
	"ambicioso":'tzotzoka',
	"ambicioso":'tzotzokatl',
	"amenazada":'ouiyoihtok',
	"amenazado":'ouiyoihtok',
	"amenazante":'uiyoihtok',
	"aminorada":'tziniak',
	"aminorada":'tzinuatik',
	"aminorada":'tzitziniatik',
	"aminorado":'tziniak',
	"aminorado":'tzinuatik',
	"aminorado":'tzitziniatik',
	"amorable":'ueltlazohtik',
	"amortiguante":'auaxpeutok',
	"ancha":'patlauak',
	"ancho":'tomauak',
	"animada":'nemitik',
	"animado":'nemitik',
	"animatoria":'nemiliztik',
	"animatorio":'nemiliztik',
	"antes":'achto',
	"anticipativa":'achpanitik',
	"anticipativa":'achtokchiutik',
	"anticipativo":'achpanitik',
	"anticipativo":'achtokchiutik',
	"antigua":'achtopak',
	"antiguo":'achtopak',
	"aparente":'amonelik',
	"aparente":'amoneltok',
	"apestosa":'amokual ahuiak',
	"apestosa":'ihyak',
	"apestosa":'ihyaktik',
	"apestosa":'tzolyak',
	"apestosa":'tzolyaktik',
	"apestoso":'amokualahuiak',
	"apestoso":'ihyak',
	"apestoso":'ihyaktik',
	"apestoso":'tzolyak',
	"apestoso":'tzolyaktik',
	"aplausiva":'tlaxtlaxkalouayok',
	"aplicada":'paniak',
	"apoyada":'mamauatik',
	"apoyado":'mamauatik',
	"aprendida":'tzalok',
	"aprendido":'tzalok',
	"apretada":'papachok',
	"apretado":'papachok',
	"aproximador":'azihtekatl',
	"aproximante":'azihtok',
	"apuntada":'axiltiayotl',
	"apuntado":'axiltiayotl',
	"apática":'amoyoki',
	"apática":'nekayoki',
	"apático":'amoyoki',
	"apático":'nekayoki',
	"aquí":'ni kan',
	"aquí":'nikan',
	"araucaria":'alaya',
	"araucaria":'alaykan',
	"ardida":'tletletiak',
	"ardido":'tletletiak',
	"ardiente":'tlatlauhki',
	"aromatizante":'ahuiakatl',
	"aromática":'ahuikauliztik',
	"aromático":'ahuikauliztik',
	"arrancada":'peuak',
	"arrancado":'peuak',
	"arriba":'tlakpak',
	"arrogante":'chehke',
	"arrogante":'chehkeitl',
	"arrogante":'nehueililki',
	"artificial":'kehtzayotl',
	"asemejatoria":'neneuak',
	"asemejatorio":'neneuak',
	"asentada":'tlaliak',
	"asentado":'tlaliak',
	"asesinatoria":'miktik',
	"asesinatorio":'miktik',
	"asida":'kuik',
	"asido":'kuik',
	"asimilada":'ontlamatik',
	"asimilada":'yolpachok',
	"asimilado":'ontlamatik',
	"asimilado":'yolpachok',
	"asociada":'mekatik',
	"asociada":'mekauatik',
	"asociado":'mekatik',
	"asociado":'mekauatik',
	"asombrada":'izak',
	"asombrado":'izak',
	"asombroso":'izatik',
	"astuta":'matiazik',
	"astuto":'matiazik',
	"astutos":'matiazik',
	"así":'ihkin',
	"atacada":'yaok',
	"atacado":'yaok',
	"atada":'mekatik',
	"atada":'mekauatik',
	"atado":'akatl',
	"atado":'mekatik',
	"atado":'mekauatik',
	"aterrizada":'tlaliak',
	"aterrizado":'tlaliak',
	"atinada":'xihiak',
	"atinado":'xihiak',
	"atisbatoria":'nezik',
	"atisbatorio":'nezik',
	"atlántico":'atlantiko',
	"atolero":'atolchiuaki',
	"atrapada":'pachokuik',
	"atrapado":'pachokuik',
	"atravesada":'ipalik',
	"atravesado":'ipalik',
	"atrevido":'ixkimauaki',
	"atrevido":'ixkochiuaki',
	"atrevido":'ixkopalolki',
	"atrevido":'kekexkik',
	"atrás":'ihkampa',
	"atuendada":'tlakemiak',
	"atuendado":'tlakemiak',
	"aumentada":'ixkaltiak',
	"aumentada":'ixpankuik',
	"aumentada":'izkaltiak',
	"aumentado":'ixkaltiak',
	"aumentado":'ixpankuik',
	"aumentado":'izkaltiak',
	"ausentada":'poliuik',
	"ausentado":'poliuik',
	"ausente":'amouaki',
	"autodestructivo":'tlakapex',
	"autodestructivo":'tlakapexitl',
	"autodestruida":'tlakapexik',
	"autodestruido":'tlakapexik',
	"auxiliada":'paleuik',
	"auxiliado":'paleuik',
	"avanzada":'ixyauik',
	"avanzada":'nehnemik',
	"avanzado":'ixyauik',
	"avanzado":'nehnemik',
	"avaricioso":'tzotzoka',
	"aventada":'tlazak',
	"aventado":'tlazak',
	"averiguatoria":'temok',
	"averiguatorio":'temok',
	"avisatoria":'notzak',
	"avisatorio":'notzak',
	"avistatoria":'nezik',
	"avistatorio":'nezik',
	"avizoratoria":'nezik',
	"avizoratorio":'nezik',
	"ayer":'yalhua',
	"ayudada":'paleuik',
	"ayudado":'paleuik',
	"azul":'xiuhtik',
	"año":'xiuitl',
	"bailable":'ihtotik',
	"bailada":'ihtotik',
	"bailada":'ihtotitik',
	"bailado":'ihtotik',
	"bailado":'ihtotitik',
	"baja":'tzinkapa',
	"bajada":'temok',
	"bajaria":'temok',
	"bajo":'tzinkapa',
	"barata":'amopatiyok',
	"barata":'amopatiyotik',
	"barata":'chotik',
	"barato":'amopatiyok',
	"barato":'amopatiyotik',
	"barato":'chotik',
	"bastante":'miak',
	"bastantes":'miak',
	"bañada":'altik',
	"bañada":'maltik',
	"bañado":'altik',
	"bañado":'maltik',
	"bebida":'koniak',
	"bebido":'koniak',
	"bien":'kualli',
	"biscosa":'kuekuetlaxtik',
	"biscoso":'kuekuetlaxtik',
	"blanca":'iztak',
	"blanco":'iztak',
	"bloqueada":'amokaualtik',
	"bloqueada":'kehtzak',
	"bloqueado":'amokaualtik',
	"bloqueado":'kehtzak',
	"bondadosa":'kualtiyok',
	"bondadoso":'kualtiyok',
	"bonita":'kualtzin',
	"bonita":'yekyok',
	"bonita":'yekyoltzin',
	"bonita":'yekyotzin',
	"bonito":'kualtzin',
	"bonito":'yekyoik',
	"bonito":'yekyok',
	"bonito":'yekyoktzin',
	"bonito":'yekyolik',
	"bonito":'yekyolli',
	"bonito":'yekyoltzin',
	"bonito":'yekyotzin',
	"borrada":'popolok',
	"borrado":'popolok',
	"breve":'achik',
	"breve":'imantzinko',
	"brillada":'petlanik',
	"brillado":'petlanik',
	"brillante":'motlanextik',
	"brillante":'petlanik',
	"brillatoria":'momochkak',
	"brillatorio":'momochkak',
	"brillosa":'motlanextik',
	"brillosa":'petlanik',
	"brilloso":'motlanextik',
	"brilloso":'petlanik',
	"brincada":'tzikuinik',
	"brincado":'tzikuinik',
	"brincante":'tzikuinitok',
	"brincante":'tzikuintok',
	"brincantes":'tzikuinitouan',
	"brincantes":'tzikuintouan',
	"brotada":'kueponiak',
	"brotado":'kueponiak',
	"buen":'kualli',
	"buena":'kualli',
	"bueno":'kualli',
	"burlada":'kamanak',
	"burlado":'kamanak',
	"buscada":'temoak',
	"buscaria":'temoak',
	"cabrestante":'malakatl',
	"cagada":'kuitlauik',
	"cagado":'kuitlauik',
	"calada":'itzminak',
	"caliente":'tonak',
	"calmada":'mantik',
	"calmado":'mantik',
	"calodo":'itzminak',
	"calorada":'tonak',
	"calorado":'tonak',
	"calvo":'xikaltok',
	"camarada":'koach',
	"camarada":'koachi',
	"camarada":'koachitl',
	"cambiada":'palak',
	"cambiado":'palak',
	"camina":'nehnemik',
	"camino":'nehnemik',
	"cansada":'zauik',
	"cansado":'zauik',
	"cantada":'kuikak',
	"cantado":'kuikak',
	"capaces":'ueltik',
	"capacitada":'yekmachiliak',
	"capacitado":'yekmachiliak',
	"capaz":'ueltik',
	"característica":'iuhkayotik',
	"característico":'iuhkayotik',
	"cardiaco":'yolotik',
	"carente":'inayaki',
	"carente":'inayatok',
	"carente":'mayanak',
	"cargada":'mamauatik',
	"cargado":'mamauatik',
	"cargante":'mamahtok',
	"caro":'ahkopatiyotl',
	"caro":'patiyotik',
	"carril":'kuentli',
	"casi":'iuhki',
	"causada":'ikchiuak',
	"causada":'ixchiuak',
	"causado":'ikchiuak',
	"causado":'ixchiuak',
	"caída":'uetzkak',
	"caído":'uetzkak',
	"caído":'uetzkatok',
	"cañada":'kuentli',
	"cebada":'azezen',
	"cegada":'ixpopoyok',
	"cegado":'ixpopoyok',
	"celoso":'chauaki',
	"cerca":'nauak',
	"cerrada":'tzakualtik',
	"cerrada":'tzakuatik',
	"cerrada":'tzatik',
	"cerrado":'tzakualtik',
	"cerrado":'tzakuatik',
	"cerrado":'tzatik',
	"certero":'ahxiltik',
	"cesatoria":'nakauak',
	"cesatoria":'nekauak',
	"cesatorio":'nakauak',
	"cesatorio":'nekauak',
	"charlatoria":'nonotzak',
	"charlatorio":'nonotzak',
	"chiflada":'kiuaxoko',
	"chiflada":'koaxoko',
	"chiflada":'kouaxoko',
	"chiflado":'kiuaxoko',
	"chiflado":'koaxoko',
	"chiflado":'kouaxoko',
	"chueco":'chiuiko',
	"chupante":'chupitok',
	"chupeteada":'chupitik',
	"chupeteada":'chupitk',
	"chupeteado":'chupitik',
	"chupeteado":'chupitk',
	"cienmil":'mahtlak uanome zempoualtin uanmahtlak zentzontin',
	"científico":'ixmatitemoaki',
	"cierta":'mela',
	"cierta":'melak',
	"cierta":'melauak',
	"cierta":'melli',
	"cierta":'nelli',
	"cierto":'mela',
	"cierto":'melak',
	"cierto":'melauak',
	"cierto":'melli',
	"cierto":'nelli',
	"cierva":'mazatl',
	"ciervo":'mazatl',
	"cilíndrica":'kokotik',
	"cilíndrica":'mimilkonik',
	"cilíndrico":'kokotik',
	"cilíndrico":'mimilkonik',
	"circulada":'maliatik',
	"circulado":'maliatik',
	"circunstancial":'ik tlaiuakan',
	"clara":'amote yayauaktik',
	"clara":'amoteyauaktik',
	"clara":'chipauak',
	"clara":'iztak',
	"claro":'amoteyayauaktik',
	"claro":'chipauak',
	"claro":'iztak',
	"coartada":'amokauak',
	"cobrada":'ihtlanik',
	"cobrado":'ihtlanik',
	"cogida":'pehpechik',
	"cogido":'pehpechik',
	"cohibida":'amokauak',
	"cohibido":'amokauak',
	"colada":'amiminatik',
	"colado":'amiminatik',
	"colatoria":'miminak',
	"colatorio":'miminak',
	"coleada":'kuitlapiluak',
	"coleada":'piluak',
	"coleado":'kuitlapiluak',
	"coleado":'piluak',
	"colocada":'kaniak',
	"colocado":'kaniak',
	"coloreada":'tlapaliak',
	"coloreado":'tlapaliak',
	"comada":'tlakuak',
	"comado":'tlakuak',
	"comal":'komalli',
	"comandatoria":'nauatik',
	"comandatorio":'nauatik',
	"combustible":'chiuahtli',
	"comenzada":'peuak',
	"comenzado":'peuak',
	"comerciatoria":'namakok',
	"comerciatorio":'namakok',
	"comparada":'zezeltlachiak',
	"comparado":'zezeltlachiak',
	"comparatoria":'neneuhtlachiak',
	"comparatorio":'neneuhtlachiak',
	"compañero":'koachitl',
	"compleja":'youik',
	"complejas":'youik',
	"complejo":'youik',
	"complejos":'youik',
	"complementada":'temik',
	"complementaria":'temik',
	"completa":'temik',
	"completada":'temik',
	"completado":'temik',
	"completo":'temik',
	"componente":'melauahko',
	"comprada":'kouak',
	"comprada":'kouitik',
	"comprado":'kouak',
	"comprado":'kouitik',
	"comproba":'itachiuak',
	"comprobo":'itachiuak',
	"compuesta":'melakiyok',
	"compuesto":'melakiyok',
	"comunitaria":'altepehua',
	"comunitaria":'altepeka',
	"comunitarias":'altepehuan',
	"comunitarias":'altepekameh',
	"comunitarias":'altepekatin',
	"comunitarias":'altepekauan',
	"comunitarias":'altepekauantzin',
	"comunitario":'altepehua',
	"comunitario":'altepeka',
	"comunitarios":'altepehuan',
	"comunitarios":'altepekameh',
	"comunitarios":'altepekatin',
	"comunitarios":'altepekauan',
	"comunitarios":'altepekauantzin',
	"concatenada":'mekatik',
	"concatenada":'mekauatik',
	"concatenado":'mekatik',
	"concatenado":'mekauatik',
	"condicionante":'ik tlaiuakan',
	"condicionante":'makauhtok',
	"conectada":'mekconectik',
	"conectado":'mekconectik',
	"confederado":'altepetzakok',
	"confesatoria":'mokuitiliak',
	"confesatorio":'mokuitiliak',
	"configurada":'tokak',
	"configurado":'tokak',
	"conflictiva":'ouiyok',
	"conflictivo":'ouiyok',
	"conforme":'ixmatipan',
	"confrontatoria":'yaolizko',
	"confrontatorio":'yaolizko',
	"confundida":'amoixmatiuak',
	"confundida":'tlalpolok',
	"confundida":'tlapolok',
	"confundido":'amoixmatiuak',
	"confundido":'tlalpolok',
	"confundido":'tlapolok',
	"confusa":'youik',
	"confusas":'youik',
	"confuso":'youik',
	"confusos":'youik',
	"congelada":'zekuik',
	"congelado":'zekuik',
	"congruente":'kayotok',
	"conocida":'ixmatik',
	"conocida":'ontlamatik',
	"conocida":'ontlamatiyok',
	"conocido":'ixmatik',
	"conocido":'ontlamatik',
	"conocido":'ontlamatiyok',
	"consciente":'machiluaki',
	"consciente":'moixtematitok',
	"consciente":'moixtematiyok',
	"consciente":'nechiuaki',
	"consciente":'nemachiliuaki',
	"consciente":'yolixtik',
	"conseguida":'tlaniak',
	"conseguido":'tlaniak',
	"consentida":'kemiyoak',
	"consentido":'kemiyoak',
	"consentido":'kemiyouak',
	"conservada":'tlatiak',
	"conservado":'tlatiak',
	"considerable":'ihuanik',
	"consistente":'amotlazezel',
	"consolada":'ikamakixtiatik',
	"consolada":'ikpaleuik',
	"consolada":'yolpachok',
	"consolado":'ikamakixtiatik',
	"consolado":'ikpaleuik',
	"consolado":'yolpachok',
	"conspirada":'tlakuepaihtok',
	"conspirado":'tlakuepaihtok',
	"constante":'totokak',
	"constante":'totokatik',
	"constantes":'totokak',
	"constituida":'chichiuayok',
	"constituido":'chichiuayok',
	"contada":'pouak',
	"contada":'pouatik',
	"contado":'pouak',
	"contado":'pouatik',
	"contaminada":'makauik',
	"contaminado":'makauik',
	"contenedor colgante":'tetzikouahkok',
	"contenta":'pakiliztik',
	"contento":'pakiliztik',
	"contestatoria":'nankiliak',
	"contestatorio":'nankiliak',
	"contigo":'mouan',
	"contraria":'yaok',
	"contrincante":'ixkok',
	"contrincante":'yaotok',
	"controlable":'ketzauek',
	"contundente":'achtokmelauak',
	"contundente":'achtomelauak',
	"contundente":'ipanmelauak',
	"contundente":'ipantlamik',
	"contundente":'melauak',
	"contundente":'melauaktli',
	"convencida":'neltokachiuak',
	"convencido":'neltokachiuak',
	"convenenciera":'mopaleuiatok',
	"convenenciero":'mopaleuiatok',
	"conversatoria":'nonotzak',
	"conversatorio":'nonotzak',
	"convincente":'tlahtolpaleuiatok',
	"convocatoria":'nonotzayotl',
	"coordenada":'iuhkanin',
	"copiada":'kixtiak',
	"copiado":'kixtiak',
	"copiatoria":'momoak',
	"copiatorio":'momoak',
	"copulada":'pehpechik',
	"copulado":'pehpechik',
	"coqueteada":'yolchiuiliak',
	"coqueteado":'yolchiuiliak',
	"coral":'atekolli',
	"correcta":'melauak',
	"correcto":'melauak',
	"corriente":'cholli',
	"corriente":'nochipak',
	"corta":'achik',
	"cortada":'tekik',
	"cortado":'tekik',
	"corto":'achik',
	"cosa":'tla',
	"cosas":'tlameh',
	"costada":'kexkiak',
	"costado":'kexkiak',
	"costado":'nakazkan',
	"creida":'neltokayok',
	"creido":'neltokayok',
	"cremoso":'halik',
	"creyente":'neltok',
	"crucial":'ihuanik',
	"cruzada":'ipalik',
	"cruzado":'ipalik',
	"crónica":'nemipantlahtolli',
	"cualquiera":'azonakin',
	"cuanto":'kexki',
	"cuantos":'kexki',
	"cubierta":'pachoyok',
	"cubierto":'pachoyok',
	"cuchicheada":'ixtetlapouak',
	"cuchicheado":'ixtetlapouak',
	"culpada":'tetlakolchiuak',
	"culpado":'tetlakolchiuak',
	"culpante":'tetlakokolchiuahtok',
	"curvada":'koliak',
	"curvado":'koliak',
	"cuñada":'iueh',
	"cuñada":'iuehtlipolli',
	"cuñada":'iuez',
	"cuñado":'iueh',
	"cuñado":'iuehpolli',
	"cuñado":'iuehtlipolli',
	"dada":'makak',
	"dada":'makatik',
	"dadivoso":'ik tlamakaki',
	"dado":'makatik',
	"danzada":'ihtotik',
	"danzada":'ihtotitik',
	"danzado":'ihtotik',
	"danzado":'ihtotitik',
	"danzante":'ihtotiki',
	"de ellas":'anmo',
	"de ellos":'anmo',
	"de nuevo":'okzepa',
	"de ustedes":'anmo',
	"de ustedes":'anmoaxka',
	"debido":'ipampa',
	"debilidad":'amokueltikyotl',
	"debilidad":'ayolotl',
	"decapitada":'tzontekontekik',
	"decapitado":'tzontekontekik',
	"decidido":'ilkuak',
	"decidido":'ilnenehkauak',
	"decisiva":'iliayok',
	"decisivo":'iliayok',
	"deductiva":'neltokayok',
	"deductivo":'neltokayok',
	"defecada":'kuitlauik',
	"defecado":'kuitlauik',
	"defendida":'manailhuak',
	"defendido":'manailhuak',
	"definida":'machiliak',
	"definida":'tlamachiliak',
	"definido":'machiliak',
	"definido":'tlamachiliak',
	"degradada":'tziniak',
	"degradada":'tzinuatik',
	"degradada":'tzitziniatik',
	"degradado":'tziniak',
	"degradado":'tzinuatik',
	"degradado":'tzitziniatik',
	"dejada":'kauak',
	"dejado":'kauak',
	"delgada":'pitzauak',
	"delgado":'pitzauak',
	"demandada":'teiliak',
	"demandado":'teiliak',
	"dentro":'itek',
	"deponida":'notzoyok',
	"deponido":'notzoyok',
	"derecha":'mayekpa',
	"derecha":'yek',
	"derecha":'yekamik',
	"derecho":'yek',
	"derretida":'auak',
	"derretida":'axolohtiak',
	"derretido":'auak',
	"derretido":'axolohtiak',
	"derribada":'kantlazak',
	"derribada":'kotlazak',
	"derribado":'kantlazak',
	"derribado":'kotlazak',
	"desafiada":'ixiuiliak',
	"desafiado":'ixiuiliak',
	"desafiante":'ixiuiltok',
	"desagradable":'amokualtzin',
	"desaparecida":'poliuik',
	"desaparecido":'poliuik',
	"desbocada":'ikchiuak',
	"desbocado":'ikchiuak',
	"descansada":'zeuik',
	"descansado":'zeuik',
	"descargada":'mamazkauak',
	"descargado":'mamazkauak',
	"descendida":'temok',
	"descendido":'temok',
	"descompuesta":'makauik',
	"descompuesto":'makauik',
	"desconfiante":'amoneltokatok',
	"descorteses":'amotzinyok',
	"descortés":'amotzinyok',
	"descubierta":'nechtiayok',
	"descubierta":'nenelouayok',
	"descubierto":'nechtiayok',
	"descubierto":'nenelouayok',
	"descuidada":'ilkauak',
	"descuidado":'ilkauak',
	"desde":'ixkipa',
	"desdoblada":'itztlakoliuak',
	"desdoblodo":'itztlakoliuak',
	"deseada":'onnekik',
	"deseada":'yolnekik',
	"deseado":'onnekik',
	"deseado":'yolnekik',
	"desenbocada":'ikpanchiuak',
	"desenbocado":'ikpanchiuak',
	"desequilibrada":'koaxoko',
	"desequilibrada":'kouaxoko',
	"desequilibrado":'kiuaxoko',
	"desequilibrado":'koaxoko',
	"desequilibrado":'kouaxoko',
	"deshonrada":'mauizokuitlatik',
	"deshonrado":'mauizokuitlatik',
	"desistida":'kauak',
	"desistido":'kauak',
	"deslizada":'alauayotik',
	"deslizado":'alauayotik',
	"deslizante":'alaxtok',
	"desodorante":'kualahuiatok',
	"despacio":'tzinuhtik',
	"despegada":'kopeuik',
	"despegado":'kopeuik',
	"despegatoria":'moleuak',
	"despegatorio":'moleuak',
	"despertada":'izak',
	"despertado":'izak',
	"desplazatoria":'olik',
	"desplazatorio":'olik',
	"desplomada":'uetzkak',
	"desplomado":'uetzkak',
	"después":'tzatepa',
	"después":'niman',
	"destapada":'tlapok',
	"destapado":'tlapok',
	"destituya":'panpalayok',
	"destituyo":'panpalayok',
	"destruida":'tzominiak',
	"destruido":'tzominiak',
	"desunida":'notzoyok',
	"desunido":'notzoyok',
	"desviada":'palkuik',
	"desviado":'palkuik',
	"desviatoria":'okzenehnemkuik',
	"desviatorio":'okzenehnemkuik',
	"desvirtuado":'akauitik',
	"determinada":'itlakuik',
	"determinado":'itlakuik',
	"detestable":'amokualtik',
	"detrás":'kuitlapa',
	"devolutiva":'tlakuepayotl',
	"devolutivo":'tlakuepayo',
	"devolver":'tlakuepa',
	"devuelta":'tlakuepayotl',
	"dicha":'ihtok',
	"dicho":'ihtok',
	"diferida":'amonamiktiak',
	"diferida":'zezekiak',
	"diferido":'amonamiktiak',
	"diferido":'amonamiktik',
	"diferido":'zezekiak',
	"dificultada":'youiak',
	"dificultado":'youiak',
	"difícil":'youik',
	"difíciles":'youik',
	"diludida":'tzitziniak',
	"diludido":'tzitziniak',
	"diluida":'auaxpeuik',
	"diluido":'auaxpeuik',
	"dinámica":'olinik',
	"dinámicas":'olinik',
	"dinámico":'olinik',
	"dinámicos":'olinik',
	"dirigida":'tekuhuayok',
	"dirigido":'tekuhuayok',
	"discutida":'tekuaniliayok',
	"discutido":'tekuaniliayok',
	"disolvente":'neneloki',
	"disponible":'nepanpatik',
	"dispositivo":'az',
	"distanciada":'tlauehkak',
	"distanciada":'uehkak',
	"distanciado":'tlauehkak',
	"distanciado":'uehkak',
	"distante":'uehka',
	"distribuida":'auipaloliak',
	"distribuido":'auipaloliak',
	"disyuntada":'tekik',
	"disyuntado":'tekik',
	"disyuntatoria":'notzok',
	"disyuntatorio":'notzok',
	"disyuntiva":'nozok',
	"disyuntivo":'nozok',
	"divertida":'auiltiak',
	"divertido":'auiltiak',
	"dividida":'zezekiak',
	"dividido":'zezekiak',
	"doblada":'koliuik',
	"doblado":'koliuik',
	"documentos":'amameh',
	"documentos":'amatin',
	"documentos":'amauan',
	"dorada":'koztik',
	"doradas":'koztik',
	"dorado":'koztik petahtik',
	"dorado":'koztik',
	"dorados":'koztik',
	"dormida":'kochik',
	"dormido":'kochik',
	"dosa":'makatik',
	"doso":'makatik',
	"dramática":'achokzepak',
	"dramático":'achokzepak',
	"duda":'nelyanalli',
	"dudatoria":'nelyanak',
	"dudatorio":'nelyanak',
	"dura":'chikauak',
	"durable":'amokauhtiyok',
	"durada":'kehtzak',
	"duradero":'amokauhtiyok',
	"durmido":'kochik',
	"duro":'chikauak',
	"editorial":'amoxtitlan',
	"editorial":'amoxtitlantli',
	"educada":'temachiltik',
	"educado":'temachiltik',
	"educados":'temachiltik',
	"efectiva":'melauak',
	"efectivo":'melauak',
	"efímero":'achikkaua',
	"efímero":'panok',
	"efímero":'panotik',
	"egoísta":'chautilki',
	"ejecutosa":'chiuatik',
	"ejecutoso":'chiuatik',
	"electa":'pehpenayok',
	"electo":'pehpenayok',
	"electrónica":'ekehtzatik',
	"electrónico":'ekehtzatik',
	"elegante":'uelueyik',
	"ella":'yehua',
	"ellas":'yehuan',
	"ellos":'yehuan',
	"elocuente":'kualtlahtok',
	"elástica":'kuekuetlaxtik',
	"elástico":'kuekuetlaxtik',
	"email":'epainaki',
	"embarcada":'akalkoyotik',
	"embarcado":'akalkoyotik',
	"embarrada":'ixpanmoliak',
	"embarrado":'ixpanmoliak',
	"empequeñecida":'tzinuak',
	"empequeñecido":'tzinuak',
	"emprenda":'pehpechik',
	"emprendo":'pehpechik',
	"en medio de":'nepantla',
	"encabronada":'tekuanik',
	"encabronado":'tekuanik',
	"encajada":'kalakiak',
	"encajado":'kalakiak',
	"encantada":'mauizotik',
	"encantado":'mauizotik',
	"encogida":'tzinuik',
	"encogido":'tzinuik',
	"encontrada":'namikiatik',
	"encontrado":'namikiatik',
	"encorbado":'ahkolkuk',
	"encuadernada":'amatzomayotik',
	"encuadernado":'amatzomayotik',
	"encuadratoria":'nauhkampak',
	"encuadratorio":'nauhkampak',
	"enderezada":'mekenderezik',
	"enderezado":'mekenderezik',
	"energizada":'tlaueliak',
	"energizado":'tlaueliak',
	"enfermada":'kokoiliak',
	"enfermado":'kokoiliak',
	"enfrentada":'ixchiuak',
	"enfrentado":'ixchiuak',
	"enfrentativa":'yaoliztik',
	"enfrentativo":'yaoliztik',
	"enfriada":'zekuik',
	"enfriado":'zekuik',
	"enfurecida":'tekuanik',
	"enfurecido":'tekuanik',
	"enganchada":'kokouhkuik',
	"enganchada":'kuauhkuik',
	"enganchado":'kokouhkuik',
	"enganchado":'kuauhkuik',
	"engañada":'itztlakoliuk',
	"engañada":'kahkayauak',
	"engañado":'itztlakoliuk',
	"engañado":'kahkayauak',
	"engranada":'teponiak',
	"engranado":'teponiak',
	"enlazada":'mekatik',
	"enlazada":'mekauatik',
	"enlazado":'mekatik',
	"enlazado":'mekauatik',
	"enojada":'tekuanik',
	"enojada":'tekuantik',
	"enojado":'tekuanik',
	"enojado":'tekuantik',
	"enseñada":'machiliatik',
	"enseñada":'machtiatik',
	"enseñado":'machiliatik',
	"enseñado":'machtiatik',
	"ensuciada":'tzoyotik',
	"ensuciado":'tzoyotik',
	"entonces":'ikuak',
	"entonces":'inik',
	"entonces":'kuak',
	"entra":'itekiak',
	"entrada":'kalakiak',
	"entrado":'kalakiak',
	"entrativa":'itekializtik',
	"entrativo":'itekializtik',
	"entrañativa":'itekializtik',
	"entrañativo":'itekializtik',
	"entraño":'itekiak',
	"entre":'nepantla',
	"entrenaratoria":'moltiak',
	"entrenaratorio":'moltiak',
	"entristecida":'tlakolok',
	"entristecido":'tlakolok',
	"entro":'itekiak',
	"enturbiado":'akauik',
	"enumerada":'poualmachiyouak',
	"enumerado":'poualmachiyouak',
	"envenenatoria":'mikpahtiak',
	"envenenatorio":'mikpahtiak',
	"enviada":'titlanik',
	"enviado":'titlanik',
	"equilibrada":'olinxihtiak',
	"equilibrada":'olinyolok',
	"equilibrado":'olinxihtiak',
	"equilibrado":'olinyolok',
	"equilibrio":'kayotl',
	"equivocada":'ouilyok',
	"equivocada":'ouiyok',
	"equivocado":'ouilyok',
	"equivocado":'ouiyok',
	"erigida":'euak',
	"erigido":'euak',
	"errada":'ouilyok',
	"errado":'ouilyok',
	"errónea":'ouiyok',
	"erróneo":'ouiyok',
	"escapada":'kizoliuik',
	"escapado":'kizoliuik',
	"escarbada":'xexelok',
	"escarbado":'xexelok',
	"escogida":'kuik',
	"escogida":'pehpenayok',
	"escogido":'kuik',
	"escogido":'pehpenayok',
	"escondida":'amoixtlaka',
	"escondido":'amoixtlaka',
	"escritorio":'tekititlapech',
	"escualido":'mimiak pitzauaki',
	"escuchada":'nkak',
	"escuchado":'nkak',
	"escurrida":'achiutetemotok',
	"escurrido":'achiutetemotok',
	"esencial":'iuhyotl',
	"esférica":'koyolik',
	"esférico":'koyolik',
	"esmerada":'mochikauak',
	"esmerado":'mochikauak',
	"espaciada":'ikauak',
	"espaciado":'ikauak',
	"específica":'tlachiuahyok',
	"específica":'tlachiuhyotik',
	"específico":'tlachiuahyok',
	"específico":'tlachiuhyotik',
	"esperada":'chiak',
	"esperada":'tepitik',
	"esperado":'chiak',
	"esperado":'tepitik',
	"esperanzada":'neltokaztepitik',
	"esperanzado":'neltokaztepitik',
	"espinada":'uitziak',
	"espinada":'uitzpaniak',
	"espinado":'uitziak',
	"espinado":'uitzpaniak',
	"esponjoso":'motlapozauhtik',
	"estable":'katik',
	"estable":'kayok',
	"establecida":'tlaliak',
	"establecida":'tokak',
	"establecido":'tlaliak',
	"establecido":'tokak',
	"estrecha":'achihko',
	"estrecho":'achihko',
	"estructurada":'mekestructurik',
	"estructurado":'mekestructurik',
	"estrujada":'papachok',
	"estrujado":'papachok',
	"estática":'katik',
	"estáticas":'katik',
	"estático":'katik',
	"estáticos":'katik',
	"eterna":'nochipak',
	"eterno":'nochipak',
	"evaluada":'patiyok',
	"evaluado":'patiyok',
	"evidente":'itatok',
	"evidente":'itayok',
	"evitada":'tzikuinik',
	"evitado":'tzikuinik',
	"exacta":'kualtlamik',
	"exacto":'kualtlamik',
	"exactos":'kualtlamik',
	"exajerada":'achtokzepalatik',
	"exajerada":'ueyikchiutik',
	"exajerado":'achtokzepalatik',
	"exajerado":'ueyikchiutik',
	"exajerativa":'ueyikchiualiztik',
	"exajerativo":'ueyikchiualiztik',
	"excelente":'miak kualtik',
	"excelente":'miakkualtik',
	"exhibida":'ititik',
	"exhibido":'ititik',
	"exhibido":'ititk',
	"exhortada":'ahuiniliztik',
	"exhortado":'ahuiniliztik',
	"exhortatoria":'notzak',
	"exhortatorio":'notzak',
	"exigida":'teiliayok',
	"exigido":'teiliayok',
	"existida":'kak',
	"existido":'itempk',
	"existido":'kak',
	"expedita":'makix',
	"expedita":'makixtilli',
	"expedito":'makix',
	"expedito":'makixtilli',
	"expidida":'titlaniyok',
	"expidido":'titlaniyok',
	"explicada":'tlamachiliak',
	"explicado":'tlamachiliak',
	"explicativa":'tlamachiliyok',
	"explicativo":'tlamachiliyok',
	"expresada":'ihtok',
	"expresada":'ihtotik',
	"expresado":'ihtok',
	"expresado":'ihtotik',
	"expresante":'ihtoki',
	"extendido":'achtokixtek',
	"extendido":'ixpantek',
	"extornudada":'alaualiztik',
	"extornudado":'alaualiztik',
	"extraido":'kizanktli',
	"extranjero":'amixmachtli',
	"facilitación":'amoyouitiyotl',
	"faltante":'mayanak',
	"fascinada":'mauizotik',
	"fascinado":'mauizotik',
	"fastidiada":'kuetziak',
	"fastidiado":'kuetziak',
	"favorable":'kema nektik',
	"favorable":'kemanektik',
	"fea":'amokualtzin',
	"federal":'altepetzak',
	"feliz":'pakiliztik',
	"feo":'amokualtzin',
	"festejatoria":'ilhuik',
	"festejatorio":'ilhuik',
	"fiera":'tekuan',
	"fijada":'pehpechouak',
	"fijada":'pepechouak',
	"fijado":'mopepechouak',
	"fijado":'pehpechouak',
	"fijado":'pepechouak',
	"filtrada":'amiminatik',
	"filtrada":'mihminik',
	"filtrado":'amiminatik',
	"filtrado":'mihminik',
	"fina":'pitzauak',
	"final":'tlamik',
	"finalizada":'tlamiak',
	"finalizada":'tlamik',
	"finalizado":'tlamiak',
	"finalizado":'tlamik',
	"finiquitada":'tlamiak',
	"finiquitada":'tlamik',
	"finiquitado":'tlamiak',
	"finiquitado":'tlamik',
	"fino":'pitzauak',
	"firme":'chikauak',
	"flemosa":'alauahtik',
	"flemosa":'alauak',
	"flemoso":'alauahtik',
	"flemoso":'alauak',
	"flexible":'kuekuetlaxtik',
	"forzar":'chikaua',
	"fracturada":'tzomonitik',
	"fracturado":'tzomonitik',
	"fragante":'kualahuiak',
	"fraternada":'ikniuak',
	"fraternado":'ikniuak',
	"frecuente":'totokatik',
	"frecuentes":'totokatik',
	"frenada":'kehtzak',
	"frenado":'kehtzak',
	"frente":'ixko',
	"frente":'ixpan',
	"frente":'ixtli',
	"frito":'tzoyonki',
	"frontal":'ixkok',
	"frontal":'ixtik',
	"frágil":'tzomonik',
	"fría":'zezek',
	"frío":'itztik',
	"frío":'zezek',
	"fuera":'kiauak',
	"fuerte":'chikauak',
	"fuertemente":'chikauakan',
	"funcionada":'tekitik',
	"funcionado":'tekitik',
	"fábrica":'chiuakan',
	"fácil":'ayouik',
	"fáciles":'ayouik',
	"fútil":'amotzatzalik',
	"galopatoria":'choloeuak',
	"galopatorio":'choloeuak',
	"ganada":'tlaniak',
	"ganado":'tlaniak',
	"gente":'mazeualli',
	"girada":'kuepak',
	"girada":'maliatik',
	"girado":'kuepak',
	"girado":'maliatik',
	"golpeada":'mahmak',
	"golpeada":'tekpanak',
	"golpeado":'mahmak',
	"golpeado":'tekpanak',
	"gomoso":'kuekuetlaxtik',
	"gran":'uey',
	"grande":'ueyik',
	"grosera":'kamapitok',
	"grosero":'amokualtlahtoki',
	"grosero":'etiktlahtolik',
	"grosero":'kamapitok',
	"groseros":'kamapitok',
	"gruesa":'tomauak',
	"grueso":'tomauak',
	"guardada":'tlatiak',
	"guardado":'tlatiak',
	"guiñada":'ikopiak',
	"guiñada":'zeixtelolotzak',
	"guiñado":'ikopiak',
	"guiñado":'zeixtelolotzak',
	"gustada":'pakik',
	"gustado":'pakik',
	"gustosa":'pakitik',
	"gustoso":'pakitik',
	"guíada":'tekuanik',
	"guíado":'tekuanik',
	"güera":'iztak',
	"güero":'amoteyayauaktik',
	"güero":'amoteyayauhtik',
	"güero":'iztak',
	"habiente":'onkayotok',
	"habituada":'matichiuatik',
	"habituado":'matichiuatik',
	"hablada":'tlahtok',
	"hablado":'tlahtok',
	"hacia":'ixkikan',
	"hambiente":'iuakizaliz',
	"hambreada":'apizmik',
	"hambreado":'apizmik',
	"hambrienta":'apiztik',
	"hambrienta":'apiztikan',
	"hambriento":'apiztik',
	"hambriento":'mayana',
	"hasta":'ixkikan',
	"hecha":'chiuayotl',
	"hecho":'chiuayo',
	"heredada":'axkayo-otlakauak',
	"heredado":'axkayo-otlakauak',
	"hermosa":'ketzaltzin',
	"hermosa":'katzalli',
	"hermosa":'ketzalik',
	"hermosa":'ketzalli',
	"hermoso":'ketzaltzin',
	"hermoso":'ketzalik',
	"hermoso":'ketzalli',
	"herramienta":'az',
	"hervida":'amanak',
	"hervido":'amanak',
	"hervido":'amank',
	"hidráulica":'aolinik',
	"hidráulica":'atl olinik',
	"hidráulico":'aolinik',
	"hidráulico":'atl olinik',
	"holgada":'auik',
	"holgado":'auik',
	"honesta":'temelauak',
	"honesto":'temelauak',
	"honestos":'temelauak',
	"honrada":'mauizotik',
	"honrado":'mauizotik',
	"honrroso":'mauizoki',
	"hormiguero":'atzkiko',
	"horrible":'amoketzalyotl',
	"horrible":'miakamoketzalli',
	"hostigada":'kuetziak',
	"hostigado":'kuetziak',
	"hoy":'axkan',
	"huida":'kizoliuik',
	"huido":'kizoliuik',
	"humeda":'atiak',
	"humedo":'atiak',
	"humilde":'iknotekatik',
	"humildes":'iknotekatik',
	"hundida":'akalakiak',
	"hundido":'akalakiak',
	"hábil":'chiuelki',
	"hábil":'ixmatchiuaki',
	"hábil":'ixtlamatchiuaki',
	"hígado":'eltlapach',
	"húmeda":'apachiuaki',
	"húmedo":'apachiuaki',
	"ida":'yauk',
	"ideada":'izpanilyok',
	"ideada":'izpantlailik',
	"ideada":'izpantlailyok',
	"ideada":'izpantlalnamikilik',
	"ideada":'tlalnamikik',
	"ideado":'izpanilyok',
	"ideado":'izpantlailik',
	"ideado":'izpantlailyok',
	"ideado":'izpantlalnamikilik',
	"ideado":'tlalnamikik',
	"identica":'neneutik',
	"identico":'neneutik',
	"idiomática":'ihtoltik',
	"idiomático":'ihtoltik',
	"idiota":'kiuaxoko',
	"idiota":'koaxoko',
	"idiota":'kouaxoko',
	"ido":'yauk',
	"ignorada":'tzikuinik',
	"ignorado":'tzikuinik',
	"ignorante":'amitlamatiki',
	"ignorante":'amoixmatiki',
	"ignorante":'amotlamatiki',
	"ignorantes":'amotlamatiki',
	"igual":'iuhpantik',
	"igual":'iuhpechtik',
	"igual":'neneuaki',
	"igualatoria":'neneuakiak',
	"igualatorio":'neneuakiak',
	"iluminada":'tlanezik',
	"iluminada":'tlauelik',
	"iluminado":'tlanezik',
	"iluminado":'tlauelik',
	"ilícita":'amochikualli',
	"ilícita":'amochiualiz',
	"ilícita":'amochiualoki',
	"ilícito":'amochikualli',
	"ilícito":'amochiualiz',
	"ilícito":'amochiualoki',
	"imaginada":'izpanilyok',
	"imaginado":'izpanilyok',
	"impactante":'ayeltik',
	"impactante":'izamik',
	"impedida":'amokauak',
	"impedido":'amokauak',
	"impertinente":'amoixtlatzinuihki',
	"impertinente":'amotekauaki',
	"importante":'achipatiyo',
	"importante":'achipatiyok',
	"importante":'ihuanik',
	"importante":'ikhuanik',
	"imposible":'amotlauelik',
	"imposible":'amotlaueltik',
	"imposible":'amouel',
	"imposible":'amouelik',
	"imposible":'amoueltik',
	"imposible":'auelik',
	"impracticable":'auelik',
	"imprecisa":'amomelauak',
	"impreciso":'amomelauak',
	"imprecisos":'amomelauak',
	"imprimida":'kuenchiuak',
	"imprimida":'kuenkauak',
	"imprimido":'kuenchiuak',
	"imprimido":'kuenkauak',
	"improbable":'amoueltik',
	"inadecuada":'amokualtik',
	"inadecuado":'amokualtik',
	"inalcanzable":'auelik',
	"inasequible":'auelik',
	"incapaces":'amoueltik',
	"incapaz":'amoueltik',
	"incensario":'kopalli',
	"incensario":'popochkopalli',
	"incitada":'izpanotzak',
	"incitado":'izpanotzak',
	"inclinada":'tekak',
	"inclinado":'tekak',
	"incompleta":'amotemik',
	"incompleto":'amotemik',
	"inconversable":'amotla tlahtok',
	"inconversable":'amotlahtok',
	"incorporada":'kalakiak',
	"incorporado":'kalakiak',
	"incorrecta":'amomelauak',
	"incorrecto":'amomelauak',
	"increible":'amoneltokatik',
	"incrementada":'iuanyok',
	"incrementada":'iuanyouak',
	"incrementada":'ixkaltiak',
	"incrementada":'izkaltiak',
	"incrementado":'iuanyok',
	"incrementado":'iuanyouak',
	"incrementado":'ixkaltiak',
	"incrementado":'izkaltiak',
	"incrustada":'pachokalakiak',
	"incrustado":'pachokalakiak',
	"indiferente":'amoyoki',
	"indiferente":'nekayoki',
	"indiferente":'zenkaualizki',
	"indisponible":'amonepanpatik',
	"indolente":'amoyoki',
	"indolente":'nekayoki',
	"indolente":'zenkaualizki',
	"inesperado":'amotepitikpan',
	"inestable":'amokatik',
	"inexacta":'amokualtlamik',
	"inexacto":'amokualtlamik',
	"inexactos":'amokualtlamik',
	"inexistente":'amouaki',
	"inferente":'neltokayok',
	"infinita":'amopoualyotl',
	"infinita":'amotlamikyan',
	"infinita":'amotlamyotl',
	"infinito":'amopoualyotl',
	"infinito":'amotlamikyan',
	"infinito":'amotlamyotl',
	"informada":'matizmakatik',
	"informado":'matizmakatik',
	"ingeniada":'tlalnamikik',
	"ingeniado":'tlalnamikik',
	"ingenua":'amotetlamatiki',
	"ingenuas":'amotetlamatiki',
	"ingenuo":'amotetlamatiki',
	"ingenuos":'amotetlamatiki',
	"ingerida":'tlakuak',
	"ingerido":'tlakuak',
	"iniciada":'peuak',
	"iniciado":'peuak',
	"inmaculada":'chipauak',
	"inmaculada":'iztak',
	"inmaculado":'chipauak',
	"inmaculado":'iztak',
	"inminente":'panotok',
	"inminente":'panozik',
	"innecesaria":'amoihuanik',
	"innecesario":'amoihuanik',
	"innecesario":'amonenekik',
	"inocente":'amotlachiuamokualki',
	"inocente":'amotlapolki',
	"inocente":'iknolik',
	"inquieta":'amo yolpachok',
	"inquieta":'makauk',
	"inquieto":'amo yolpachok',
	"inquieto":'amokauik',
	"inquieto":'makauk',
	"insegura":'amochimalik',
	"inseguro":'amochimalik',
	"insignificante":'amokanuatik',
	"insignificante":'amokanyeuatik',
	"insignificante":'tzintok',
	"insinuada":'chiuiliak',
	"insinuado":'chiuiliak',
	"insistente":'amokauhtiyok',
	"insolente":'achikuepaltik',
	"insolente":'amokual tzinkayoki',
	"insolente":'ixkohyauaki',
	"inspirada":'yolnotzak',
	"inspirado":'yolnotzak',
	"instruida":'machtiak',
	"instruido":'machtiak',
	"instruido":'machtik',
	"instrumentada":'aztik',
	"instrumentado":'aztik',
	"insuficiente":'amokanuatik',
	"insuficiente":'amokanyeuatik',
	"insufrible":'amota kokolik',
	"insufrible":'ayak kokolik',
	"insultada":'amokualtzin-otlahtok',
	"insultado":'amokualtzin-otlahtok',
	"insípido":'amotzopelik',
	"insípido":'kuantik',
	"integrada":'nepanpatichiuak',
	"integrada":'uaniak',
	"integrado":'nepanpatichiuak',
	"integrado":'uaniak',
	"inteligente":'ixtematiyok',
	"inteligente":'tlamatiki',
	"inteligentes":'tlamatiki',
	"intensa":'yayauhtik',
	"intenso":'yayauhtik',
	"intento":'chiuahpeua',
	"intento":'ipalli',
	"interpelada":'teiliak',
	"interpelado":'teiliak',
	"interpretada":'tlalnamikyopalak',
	"interpretado":'tlalnamikyopalak',
	"interrogante":'nelyanalli',
	"interrumpida":'kehtzak',
	"interrumpida":'nakauayok',
	"interrumpido":'kehtzak',
	"interrumpido":'nakauayok',
	"intrigosa":'amokualtzaihtoka',
	"intrigosa":'amokualtzailihka',
	"intrigoso":'amokualtzaihtoka',
	"intrigoso":'amokualtzailihka',
	"intrincada":'ipanitek',
	"intrincado":'ipanitek',
	"introductiva":'kalakiayok',
	"introductivo":'kalakiayok',
	"invadida":'iteknehnemik',
	"invadido":'iteknehnemik',
	"inverosímil":'amoneltokatik',
	"inviable":'auelik',
	"invidente":'ixtelopoloteka',
	"invitada":'izpanotzak',
	"invitado":'izpanotzak',
	"involucrada":'kankuik',
	"involucrado":'kankuik',
	"inútil":'amotzalik',
	"inútil":'amotzatzalik',
	"inútil":'ontemik',
	"irrealizable":'auelik',
	"irrelevante":'amoihuanik',
	"irrespetuosa":'amotzinyok',
	"irrespetuoso":'achikuepaltik',
	"irrespetuoso":'amokual tzinkayoki',
	"irrespetuoso":'amotzinyok',
	"irrespetuoso":'ixkohyauaki',
	"irrespetuosos":'amotzinyok',
	"irreverente":'amokualtlahtoki',
	"irrigada":'ahuilik',
	"irrigado":'ahuilik',
	"irrigante":'ahuil',
	"itinerario":'amatek',
	"jalada":'tilantik',
	"jalado":'tilantik',
	"jamás":'aik',
	"joven":'telpochtik',
	"jugada":'auiltik',
	"jugado":'auiltik',
	"jugoso":'aayok',
	"juntada":'uaniak',
	"juntado":'uaniak',
	"jurídica":'melauakzeliltik',
	"jurídica":'melazeliltik',
	"jurídica":'yekuakzeliltik',
	"jurídica":'yekzeliltik',
	"jurídico":'melauakzeliltik',
	"jurídico":'melauayok',
	"jurídico":'melauilyo',
	"jurídico":'melazeliltik',
	"jurídico":'yekuakzeliltik',
	"jurídico":'yekuayok',
	"jurídico":'yekuilyo',
	"jurídico":'yekzeliltik',
	"justamente":'melauakan',
	"labrada":'tetekik',
	"labrado":'tetekik',
	"labratoria":'tetekik',
	"labratorio":'tetekik',
	"lado":'itlak',
	"lado":'iuhkanin',
	"lado":'motlak',
	"lado":'nakaz',
	"lanzada":'tlazak',
	"lanzado":'tlazak',
	"larga":'ueyak',
	"largo":'ueyak',
	"lastrada":'akaltetemok',
	"lastrado":'akaltetemok',
	"lavada":'tlapakak',
	"lavado":'tlapakak',
	"le":'ki',
	"leida":'tlatlachiak',
	"leido":'tlatlachiak',
	"lejano":'uehka',
	"lejos":'uehka',
	"lenta":'kuechauak',
	"lenta":'tzinuhtik',
	"lenta":'ziuhtik',
	"lento":'kuechauak',
	"lento":'tzinuhtik',
	"lento":'tziuhtik',
	"les":'an mo',
	"les":'anmech',
	"les":'anmo',
	"les":'in',
	"les":'inmo',
	"les":'kin',
	"liberada":'makixtiak',
	"liberada":'makixtik',
	"liberado":'makixtiak',
	"liberado":'makixtik',
	"librada":'makixtiak',
	"librado":'makixtiak',
	"libre":'ma kixtik',
	"libre":'makixtik',
	"ligera":'ahkokan',
	"ligera":'amoetik',
	"ligera":'amotla etik',
	"ligera":'etikkuitlak',
	"ligero":'ahkokan',
	"ligero":'amoetik',
	"ligero":'amotla etik',
	"ligero":'etikkuitlak',
	"limitada":'amokauak',
	"limitada":'amokauatik',
	"limitado":'amokauak',
	"limitado":'amokauatik',
	"limpiada":'iztauak',
	"limpiado":'iztauak',
	"lisa":'alaxtik',
	"liso":'alaxtik',
	"lista":'kuayamanki',
	"listas":'kuayamanki',
	"listo":'kuayamanki',
	"listos":'kuayamanki',
	"llamatoria":'notzak',
	"llamatorio":'notzak',
	"llegada":'ehkotik',
	"llegado":'ehkotik',
	"llena":'temik',
	"lleno":'temik',
	"llevada":'mamayauitik',
	"llevada":'tlauihkak',
	"llevada":'uihkak',
	"llevado":'mamayauitik',
	"llevado":'tlauihkak',
	"llevado":'uihkak',
	"lo":'i',
	"luminosa":'tlanezik',
	"luminoso":'tlanezik',
	"lumínica":'tlanezik',
	"lumínico":'tlanezik',
	"lunática":'koaxoko',
	"lunática":'kouaxoko',
	"lunático":'kiuaxoko',
	"lunático":'koaxoko',
	"lunático":'kouaxoko',
	"líquido":'ayotl',
	"madera":'kuau',
	"madura":'ikoxik',
	"maduro":'ikoxik',
	"maduro":'ikzitok',
	"mal":'amokualli',
	"mala":'amokualli',
	"maldecido":'amokual teilchiuak',
	"maldito":'amokualtiki',
	"malhecho":'amokual omochiuk',
	"malhecho":'amokual tlachiualli',
	"malintencionado":'amokualtiki',
	"malo":'amokualli',
	"malvado":'amokualtiki',
	"manantial":'amanalli',
	"manantial":'ameyalli',
	"manejable":'ketzauek',
	"manera":'ikinyo',
	"manguera":'kuitlakolli',
	"manifestada":'ihtotik',
	"manifestado":'ihtotik',
	"manifestatoria":'notzak',
	"manifestatorio":'notzak',
	"manipulable":'ketzauek',
	"maniática":'kiuaxoko',
	"maniática":'koaxoko',
	"maniático":'koaxoko',
	"maniático":'kouaxoko',
	"maníaca":'kiuaxoko',
	"maníaca":'koaxoko',
	"maníaco":'koaxoko',
	"maníaco":'kouaxoko',
	"maravillada":'mauizotik',
	"maravillado":'mauizotik',
	"marido":'namik',
	"marinero":'akalmotlauiki',
	"masturbada":'tepiltilanak',
	"masturbado":'tepiltilanak',
	"material":'etihketl',
	"matizada":'auaxpeuak',
	"matizado":'auaxpeuak',
	"mayoritariamente":'okzenka',
	"mayormente":'okzenka',
	"mañana":'moztla',
	"me":'nech',
	"me":'nimo',
	"mediada":'ipalik',
	"mediado":'ipalik',
	"medida":'neneuihkiayok',
	"medido":'neneuihkiayok',
	"medio ambiente":'iuakizaliz',
	"mejor":'achik',
	"mejor":'achikualtik',
	"mejor":'achkualli',
	"mejor":'kualyok',
	"mejor":'kualyotik',
	"memorizada":'ilkehtzayok',
	"memorizado":'ilkehtzayok',
	"menos":'nenkan',
	"mensajero":'ipanaki',
	"mensajero":'mamayauatok',
	"mentalizada":'tlalnamikik',
	"mentalizado":'tlalnamikik',
	"mentirosa":'itztlakoliuyok',
	"mentirosa":'teamoneloak',
	"mentiroso":'amonelihtoki',
	"mentiroso":'itztlakoliuyok',
	"mentiroso":'iztlaka',
	"mentiroso":'teamoneloak',
	"mentiroso":'xolopihki',
	"mentirosos":'teamoneloak',
	"mercadeatoria":'namakok',
	"mercadeatorio":'namakok',
	"merecida":'mazeuik',
	"merecido":'mazeuik',
	"meritada":'iktlapatiyok',
	"meritada":'tlaniak',
	"meritado":'iktlapatiyok',
	"meritado":'tlaniak',
	"mesoamérica":'ahkoanauak',
	"metamorfoseada":'itztlakoliuik',
	"metamorfoseado":'itztlakoliuik',
	"metálica":'tepoztik',
	"metálico":'tepoztik',
	"mi":'no',
	"miedoso":'mauhtiki',
	"mildoscientos":'eyi zentzon',
	"mineral":'tekonyotl',
	"mis":'no',
	"mismo":'mo',
	"mismos":'mo',
	"mocoso":'alauak',
	"mocoso":'alauatik',
	"moderna":'axkantik',
	"moderno":'axkantik',
	"mohoso":'poxkauik',
	"molestada":'kuehtziak',
	"molestada":'kuetziak',
	"molestado":'kuehtziak',
	"molestado":'kuetziak',
	"mollera":'iyatl',
	"morada":'kamohtik',
	"moradas":'kamohtik',
	"morado":'kamohtik',
	"morados":'kamohtik',
	"moribundo":'mikiyok',
	"mortal":'mikiyok',
	"mortoria":'miktik',
	"mortorio":'miktik',
	"mostrada":'ititik',
	"mostrodo":'ititik',
	"motivo":'ipampa',
	"movible":'ltik',
	"movible":'oltik',
	"mucho":'miak',
	"mugroso":'tzok',
	"mugroso":'tzoktli',
	"mutante":'itztlakoliuhtok',
	"másico":'etiyok',
	"mástil":'akalpankuau',
	"México":'mexihko',
	"mí":'nech',
	"mía":'noaxka',
	"mías":'noaxka',
	"mío":'noaxka',
	"míos":'noaxka',
	"música":'tzotzoniliztli',
	"nacida":'ixuak',
	"nacido":'ixuak',
	"naciente":'ixuhtok',
	"nada":'amitla',
	"nadada":'manelotik',
	"nadado":'manelotik',
	"nadie":'ayak',
	"naranja":'alaxtik',
	"naranja":'laxtik',
	"naufragada":'akalmopolok',
	"naufragado":'akalmopolok',
	"necesaria":'ihuanik',
	"necesario":'ihuanik',
	"necesitatoria":'nenekik',
	"necesitatorio":'nenekik',
	"necia":'apochtik',
	"necia":'tzontetek',
	"necio":'apochtik',
	"necio":'tzontetek',
	"negligente":'ilkauaki',
	"negligente":'ilkauatok',
	"negociada":'namakouak',
	"negociado":'namakouak',
	"negociante":'namakotok',
	"negra":'chapotik',
	"negra":'tliltik',
	"negras":'tliltik',
	"negro":'chapotik',
	"negro":'tliltik',
	"negros":'tliltik',
	"nerviosa":'makauk',
	"nervioso":'amokauik',
	"nervioso":'makauk',
	"ninguna":'amakin',
	"ninguno":'amakin',
	"no":'amo',
	"nombrada":'tokak',
	"nombrado":'tokak',
	"normal":'mantik',
	"nos":'tech',
	"nos":'timo',
	"nos":'to',
	"nosotras":'tech',
	"nosotros":'tech',
	"nudo":'akatl',
	"nuestra":'to',
	"nuestras":'to',
	"nuestro":'to',	
	"nuestros":'to',
	"nueva":'yankuik',
	"nuevo":'yankuik',
	"nulo":'amok',
	"nunca":'aik',
	"náufraga":'akamopoloki',
	"náufrago":'akamopoloki',
	"nómada":'lpan',
	"o":'tzo',
	"objetivo":'azitlampan',
	"objetivo":'iuhik',
	"objetivo":'iuhiktli',
	"obligatoria":'chiuayok',
	"obligatoria":'ikpantlalchiuayok',
	"obligatoria":'melaualchiualli',
	"obligatorio":'chiuayok',
	"obligatorio":'ikpantlalchiuayok',
	"obligatorio":'melaualchiualli',
	"observada":'tlachiak',
	"observado":'tlachiak',
	"obtenida":'tlaniak',
	"obtenido":'tlaniak',
	"ocasional":'kemaniantik',
	"ocasionales":'kemaniantik',
	"ocupada":'ipantekitik',
	"ocupado":'ipantekitik',
	"odiada":'onamonekik',
	"odiado":'onamonekik',
	"odiosa":'kuehzolik',
	"odioso":'kuehzolik',
	"ofensiva":'achikuepalik',
	"ofensiva":'achikuepaltik',
	"ofensiva":'amokualtlahtoki',
	"ofensiva":'chunkak',
	"ofensivo":'achikuepalik',
	"ofensivo":'achikuepaltik',
	"ofensivo":'amokualtlahtoki',
	"ofensivo":'chunkak',
	"oficiante":'achkauah',
	"oficiante":'achkauhtli',
	"oida":'onkak',
	"oido":'onkak',
	"olvidada":'iktlapauk',
	"olvidado":'iktlapauk',
	"omitida":'tzikuinik',
	"omitido":'tzikuinik',
	"ondeada":'koloak',
	"ondeado":'koloak',
	"ondulada":'koloak',
	"ondulado":'koloak',
	"opaca":'pinixtik',
	"opaco":'pinixtik',
	"operario":'chiteka',
	"optada":'kuik',
	"optada":'pehpenak',
	"optado":'kuik',
	"optado":'pehpenak',
	"opuesta":'ixkok',
	"opuesto":'ixkok',
	"orate":'kiuaxoko',
	"orate":'koaxoko',
	"orate":'kouaxoko',
	"ordenatoria":'nauatik',
	"ordenatorio":'nauatik',
	"organizatoria":'nepanpatichiuak',
	"organizatoria":'nepanpatik',
	"organizatorio":'nepanpatichiuak',
	"organizatorio":'nepanpatik',
	"orgullosa":'mauizok',
	"orgulloso":'mauizok',
	"orgullosos":'mauizok',
	"oriente":'tonalkizayan',
	"original":'axkauhyo',
	"original":'axkauhyotl',
	"osada":'ipalixuliztik',
	"osado":'ipalixuliztik',
	"osativa":'ipalixuliztik',
	"osativo":'ipalixuliztik',
	"osatoria":'ipalixulizko',
	"osatorio":'ipalixulizko',
	"oscura":'tlayouak',
	"oscuro":'tlayouak',
	"oso":'kuetekuani',
	"oso":'kuetekuanitl',
	"oteativa":'itaaziliztik',
	"oteativo":'itaaziliztik',
	"otra vez":'okzepa',
	"otra":'okze',
	"otro":'okze',
	"padecido":'kokok',
	"palabra":'tlahtolli',
	"pantallada":'italonik',
	"pantallado":'italonik',
	"papelera":'amateka',
	"papelero":'amateka',
	"para":'inik',
	"parada":'kehtzak',
	"parada":'nekauak',
	"parado":'kehtzak',
	"parado":'nekauak',
	"paratoria":'nekauak',
	"paratorio":'nekauak',
	"parcial":'achitik',
	"parecida":'neltokayok',
	"parecido":'neltokayok',
	"parecido":'neneuak',
	"parida":'maxiuik',
	"parido":'maxiuik',
	"pariente":'apaltik',
	"pariente":'chantekatl',
	"pariente":'chantik',
	"pariente":'ikniuhtzin',
	"parientes":'iknimeh',
	"parientes":'iknitin',
	"parientes":'ikniuan',
	"parientes":'ikniuhmeh',
	"parientes":'ikniuhtin',
	"parientes":'ikniuhuan',
	"pasada":'panok',
	"pasado":'panok',
	"pasajero":'achik kaua',
	"pasajosa":'panotik',
	"pasajoso":'panotik',
	"pasiva":'amochiuak',
	"pasivas":'amochiuak',
	"pasivo":'amochiuak',
	"pasivos":'amochiuak',
	"pasmada":'izak',
	"pasmado":'izak',
	"pasmoso":'izatik',
	"pateada":'ikxitzak',
	"pateada":'teletzak',
	"pateado":'ikxitzak',
	"pateado":'teletzak',
	"pausada":'kehtzak',
	"pausadas":'kehtzak',
	"pausado":'kehtzak',
	"pausados":'kehtzak',
	"pausads":'kehtzak',
	"pausatoria":'nakauak',
	"pausatoria":'nekauak',
	"pausatorio":'nakauak',
	"pausatorio":'nekauak',
	"pecunaria":'tekomyo',
	"pecunario":'tekomyo',
	"pedida":'ihtlaniak',
	"pedido":'ihtlaniak',
	"pegada":'pehpechouak',
	"pegado":'pehpechouak',
	"peleada":'yaok',
	"peleado":'yaok',
	"peleonera":'ixyaochiuak',
	"peleonero":'ixyaochiuak',
	"peligrosa":'uiyok',
	"peligroso":'uiyok',
	"pelona":'amotzontlak',
	"pelón":'amotzontlak',
	"pensada":'tlalnamikik',
	"pensado":'tlalnamikik',
	"peor":'amokualik',
	"peor":'amokualtik',
	"peor":'amokualyok',
	"peor":'amokualyotik',
	"peor":'amouelkualik',
	"peor":'amouelkualli',
	"pequeña":'pilli',
	"pequeño":'pilli',
	"pequeño":'piltik',
	"percatada":'matkuitik',
	"percatada":'matzaziuitik',
	"percatado":'matkuitik',
	"percatado":'matzaziuitik',
	"perdida":'poliuik',
	"perdido":'poliuik',
	"perdurada":'kehtzak',
	"perdurada":'kehtzauak',
	"perdurada":'totokak',
	"perdurado":'kehtzak',
	"perdurado":'kehtzauak',
	"perdurado":'totokak',
	"perezosa":'amoyoki',
	"perezosa":'nekayoki',
	"perezoso":'amoyoki',
	"perezoso":'nekayoki',
	"perfecta":'kualchiuak',
	"perfecto":'kualchiuak',
	"perfil":'ikinyo',
	"perfil":'itayo',
	"perfumado":'ahuikauatik',
	"permitida":'kauak',
	"permitido":'kauak',
	"perseguidor":'totokatekatl',
	"perseverada":'ontotokak',
	"perseverado":'ontotokak',
	"perseverante":'totokatik',
	"persiguiente":'totokatok',
	"persistente":'amokauhtitok',
	"perspectiva":'ixkoyotl',
	"perspicaz":'azihtok',
	"pertinente":'tekauatok',
	"perversa":'amokualtiki',
	"perverso":'amokualtiki',
	"pesada":'etik',
	"pesado":'etik',
	"petulante":'ixkotlachiki',
	"petulante":'mopatiyoki',
	"petulante":'nehueililki',
	"pica":'chilok',
	"picada":'uitzpaniak',
	"picado":'uitzpaniak',
	"picante":'chil',
	"pico":'aua',
	"pico":'chilok',
	"pico":'itzt',
	"pico":'izt',
	"pico":'mim',
	"pico":'yakaz',
	"picoso":'chiltik',
	"picuda":'uitztik',
	"picudo":'chopitik',
	"picudo":'uitztik',
	"pinchada":'uitziak',
	"pinchado":'uitziak',
	"planificatoria":'nepanpatichiuak',
	"planificatorio":'nepanpatichiuak',
	"plateada":'petahtik',
	"plateado":'iztak petahtik',
	"plateado":'petahtik',
	"platicatoria":'nonotzak',
	"platicatorio":'nonotzak',
	"playera":'koton',
	"plástico":'iuhkayotl',
	"plática":'nonotzayo',
	"poblado":'altepeuak',
	"pobre":'iknok',
	"poco":'achik',
	"poderosa":'uelik',
	"poderoso":'uelik',
	"podrido":'palanki',
	"ponderada":'teueliak',
	"ponderado":'teueliak',
	"poniente":'kalakiyan',
	"poniente":'tonalkalakiyan',
	"poniente":'ziuatlampa',
	"poquito":'tzinyok',
	"por medio de":'ipalli',
	"por medio del":'ipalli',
	"por":'ik',
	"porque":'pampa',
	"portada":'uihkak',
	"portado":'uihkak',
	"portátil":'itakatl',
	"posicionada":'kaniak',
	"posicionado":'kaniak',
	"posterior":'niman',
	"preciosa":'yekyok',
	"preciosa":'yekyolik',
	"preciosa":'yekyoltik',
	"preciosa":'yekyoltzin',
	"preciosa":'yekyotzin',
	"precioso":'yekyoik',
	"precioso":'yekyok',
	"precioso":'yekyolik',
	"precioso":'yekyolli',
	"precioso":'yekyoltzin',
	"precioso":'yekyotzin',
	"precisa":' melauak',
	"precisamente":'melauakan',
	"preciso":' melauak',
	"precisos":' melauak',
	"predictiva":'achtoilik',
	"predictivo":'achtoilik',
	"preferida":'kuak',
	"preferida":'pehpenayok',
	"preferido":'kuak',
	"preferido":'pehpenayok',
	"preguntada":'tlahtlanik',
	"preguntado":'tlahtlanik',
	"prehispánica":'achtokaxtilan',
	"prehispánica":'achtopanespañoltik',
	"prehispánico":'achtokaxtilan',
	"prehispánico":'achtopanespañoltik',
	"preparada":'yektlaliak',
	"preparado":'yektlaliak',
	"preparatoria":'moltiak',
	"preparatorio":'moltiak',
	"preponderante":'ihuanik',
	"preservada":'tlanemonyauzyok',
	"preservado":'tlanemonyauzyok',
	"presumida":'ixkotlachiki',
	"presumida":'mopatiyoki',
	"presumida":'nehueililki',
	"presumido":'ixkotlachiki',
	"presumido":'mopatiyoki',
	"presumido":'nehueililki',
	"presuntuosa":'ixkotlachiki',
	"presuntuosa":'mopatiyoki',
	"presuntuosa":'nehueililki',
	"presuntuoso":'ixkotlachiki',
	"presuntuoso":'mopatiyoki',
	"presuntuoso":'nehueililki',
	"prevenida":'achtoilitok',
	"prevenido":'achtoilitok',
	"preventiva":'achtoilik',
	"preventivo":'achtoilik',
	"principalmente":'okzenka',
	"priorizada":'euak',
	"priorizado":'euak',
	"probada":'ipaliak',
	"probada":'itzminak',
	"probada":'tlapalok',
	"probado":'ipaliak',
	"probado":'itzminak',
	"probado":'tlapalok',
	"problemática":'ouihyotl',
	"problemática":'ouiyok',
	"problemático":'ouihyotl',
	"problemático":'ouiyok',
	"programada":'amatekitik',
	"programado":'amatekitik',
	"progresado":'ahkuanatik',
	"prologativa":'tlapeualiztik',
	"prologativo":'tlapeualiztik',
	"prologosa":'tlapeutik',
	"prologoso":'tlapeutik',
	"pronta":'azuhkan',
	"pronta":'ikiuh',
	"pronta":'ueliuik',
	"pronto":'azuhkan',
	"pronto":'ikiuh',
	"pronto":'ueliuik',
	"propia":'axka',
	"propia":'axkauah',
	"propia":'axkauh',
	"propiamente":'inochiinehuiyan',
	"propio":'axka',
	"propio":'axkauah',
	"propio":'axkauh',
	"provocada":'chiuiliak',
	"provocada":'ikchiuak',
	"provocado":'chiuiliak',
	"provocado":'ikchiuak',
	"proyectada":'ititik',
	"proyectodo":'ititik',
	"prudente":'machiluaki',
	"prudente":'nechiuaki',
	"prudente":'nemachiliuaki',
	"práctica":'tlakuepayotl',
	"puenteada":'tzikuinik',
	"puenteado":'tzikuinik',
	"puntero":'ahxiltik',
	"puntiagudo":'chopitik',
	"punzante":'uitztik',
	"pura":'iztak',
	"puro":'chipauak',
	"puro":'iztak',
	"pálida":'iztaktik',
	"pálido":'iztaktik',
	"pálido":'iztayoki',
	"pésima":'amomiak kualtik',
	"pésimo":'amomiak kualtik',
	"públicamente":'mazeualixpan',
	"que":'ma',
	"que":'tlen',
	"quebrada":'tzomonitik',
	"quebradiza":'tzomonik',
	"quebradizo":'tzomonik',
	"quebrado":'tzomonitik',
	"quedada":'kehtzak',
	"quedado":'kehtzak',
	"quejada":'kokoiliak',
	"quejado":'kokoiliak',
	"quemada":'tlatiak',
	"quemado":'tlatiak',
	"querida":'nekiyok',
	"querido":'nekiyok',
	"quien":'akin',
	"quitada":'kuitiak',
	"quitado":'kuitiak',
	"quizá":'ueliz',
	"quizás":'ueliz',
	"quién":'akin',
	"quiénes":'akin',
	"qué":'tlain',
	"qué":'tlein',
	"qué":'tlen',
	"raro":'tzoyok',
	"rascada":'xexelok',
	"rascado":'xexelok',
	"rasgada":'pantekik',
	"rasgado":'pantekik',
	"rastro":'ohtli',
	"ratero":'ixteki',
	"ratificada":'itachiyok',
	"ratificado":'itachiyok',
	"real":'mel',
	"real":'mela',
	"real":'melak',
	"real":'melauak',
	"real":'nelyok',
	"rebajada":'tziniak',
	"rebajada":'tzitziniatik',
	"rebajado":'tziniak',
	"rebajado":'tzitziniatik',
	"reboso":'ikpapayo',
	"reboso":'ikpapayotl',
	"recibida":'tlakuik',
	"recibido":'tlakuik',
	"reciente":'yankuik',
	"recipiente":'komitl',
	"reconstruida":'onchiuayok',
	"reconstruido":'onchiuayok',
	"recordada":'ilnamikik',
	"recordado":'ilnamikik',
	"recorrido":'nehnemiyotl',
	"recta":'melaki',
	"rectificada":'mekrectificik',
	"rectificado":'mekrectificik',
	"recto":'melaki',
	"recuperatoria":'ontlakuik',
	"recuperatorio":'ontlakuik',
	"rededor":'ixkan',
	"redimida":'makixtiak',
	"redimido":'makixtiak',
	"redondeada":'maliatik',
	"redondeado":'maliatik',
	"reelaborada":'onchiuak',
	"reelaborado":'onchiuak',
	"referida":'tlailiak',
	"referido":'tlailiak',
	"regalada":'makatik',
	"regalado":'makatik',
	"regañado":'ahuak',
	"regañona":'ahuanki',
	"regañón":'ahualki',
	"regente":'tekuh',
	"rehecha":'onchiuayok',
	"rehecha":'onixmatiyok',
	"rehecho":'onchiuayok',
	"rehecho":'onixmatiyok',
	"reida":'uetzkak',
	"reido":'uetzkak',
	"reivindicada":'ontlapatiyok',
	"reivindicado":'ontlapatiyok',
	"relacionada":'iktlapauk',
	"relacionada":'mekrelacionik',
	"relacionado":'iktlapauk',
	"relacionado":'mekrelacionik',
	"relevatoria":'notzok',
	"relevatorio":'notzok',
	"remembrada":'onilnamikik',
	"remembrado":'onilnamikik',
	"remitida":'titlaniyok',
	"remitido":'titlaniyok',
	"remplazada":'onnekik',
	"remplazada":'panpalak',
	"remplazado":'onnekik',
	"remplazado":'panpalak',
	"repartida":'nepanpatiyok',
	"repartido":'nepanpatiyok',
	"repente":'imanik',
	"repente":'izamik',
	"repetida":'teneuak',
	"repetido":'teneuak',
	"repitida":'putzhuiayok',
	"repitido":'putzhuiayok',
	"reposo":'amolli',
	"reposo":'amotlaolli',
	"reposo":'amotlaolyo',
	"reposo":'amotlaolyotl',
	"resbalada":'alaualiztik',
	"resbalado":'alaualiztik',
	"resbalosa":'alaxtik',
	"resbaloso":'alaxtik',
	"resguardada":'koiak',
	"resguardado":'koiak',
	"resistente":'chikauak',
	"resistida":'kehtzayok',
	"resistido":'kehtzayok',
	"respecto":'achtok',
	"respecto":'iktlapa',
	"respetable":'tzintik',
	"respetada":'tzinitik',
	"respetado":'tzinitik',
	"respetuosa":'tzinyok',
	"respetuoso":'tzinyok',
	"respetuosos":'tzinyok',
	"respirada":'ihiyotiatik',
	"respirada":'ihiyotik',
	"respirada":'ihtlanitik',
	"respirado":'ihiyotiatik',
	"respirado":'ihiyotik',
	"respirado":'ihtlanitik',
	"respondida":'nankiliak',
	"respondido":'nankiliak',
	"reventada":'kueponiak',
	"reventado":'kueponiak',
	"reverenciada":'tlalpalok',
	"reverenciado":'tlalpalok',
	"revernciada":'tzinitik',
	"revernciado":'tzinitik',
	"rica":'achtik',
	"rico":'achtik',
	"robada":'ixtekik',
	"robado":'ixtekik',
	"roja":'chichiltik',
	"roja":'chiltik',
	"rojas":'chichiltik',
	"rojas":'chiltik',
	"rojo":'chichiltik',
	"rojo":'chiltik',
	"rojos":'chichiltik',
	"rojos":'chiltik',
	"rosa":'tlapaltik',
	"rosa":'xokoxochitl',
	"rota":'tzomonik',
	"roto":'tzomonik',
	"rubia":'iztak',
	"rubias":'iztak',
	"rubio":'amoteyayauaktik',
	"rubio":'iztak',
	"rubios":'amoteyayauaktik',
	"rubios":'iztak',
	"rápida":'ueliuik',
	"rápido":'ueliuik',
	"rígido":'chikauak',
	"sabia":'tlamatiki',
	"sabio":'tlamatiki',
	"sabios":'tlamatiki',
	"sacada":'kizak',
	"sacada":'kizkuik',
	"sacado":'kizak',
	"sacado":'kizkuik',
	"sal":'izta',
	"salida":'kizak',
	"salido":'kizak',
	"saliva":'achihchalli',
	"saliva":'chihchalli',
	"saliva":'kualak',
	"saltada":'tzikuinik',
	"saltado":'tzikuinik',
	"saludada":'tlahpalok',
	"saludado":'tlahpalok',
	"salvada":'makixtiak',
	"salvado":'makixtiak',
	"sarpullido":'auamikiliz',
	"sarpullido":'auamikiliztli',
	"se":'mo',
	"seca":'uihtik',
	"secada":'uahkiatik',
	"secado":'uahkiatik',
	"seco":'uihtik',
	"sedentaria":'pepechouak',
	"sedentario":'pepechouak',
	"sedentario":'pepechouaktli',
	"sedienta":'amiktok',
	"sediento":'amikki',
	"sediento":'amiktok',
	"seducida":'ixkuepak',
	"seducido":'ixkuepak',
	"seguida":'totokak',
	"seguido":'totokak',
	"segura":'chimalik',
	"seguro":'chimalik',
	"según":'ixmatipan',
	"sembrada":'tokak',
	"sembrado":'tokak',
	"semejante":'ikniuhtli',
	"semejatoria":'neneuak',
	"semejatorio":'neneuak',
	"sencilla":'ayouik',
	"sencillas":'ayouik',
	"sencillo":'ayouik',
	"sencillos":'ayouik',
	"senda":'ohtli',
	"sendero":'ohtli',
	"sensitiva":'tekochmamatik',
	"sensitivo":'tekochmamatik',
	"sentida":'tekochmamak',
	"sentido":'tekochmamak',
	"separada":'tekik',
	"separada":'tzotik',
	"separada":'zezekik',
	"separado":'tekik',
	"separado":'tzotik',
	"separado":'zezekik',
	"serena":'mantik',
	"sereno":'mantik',
	"serpiente":'koatl',
	"servida":'tekitiyok',
	"servido":'tekitiyok',
	"sexto":'chikoazentetl',
	"señal":'koluhyotl',
	"señalada":'kimahpiliuiak',
	"señalado":'kimahpiliuiak',
	"señalizada":'axiltiayotik',
	"señalizado":'axiltiayotik',
	"si":'intla',
	"siempre":'nochipa',
	"siete":'chikome',
	"significada":'machiliak',
	"significado":'machiliak',
	"significativa":'ihuanik',
	"significativo":'ihuanik',
	"siguiente":'totokak',
	"simple":'amotekitik',
	"simple":'amoyouik',
	"simple":'ayotik',
	"simple":'ayouik',
	"sin":'amotla',
	"sin":'in ayak',
	"sobre":'ipan',
	"sobrepasosa":'chimeuatik',
	"sobrepasoso":'chimeuatik',
	"sobresaliente":'ihuantok',
	"sobresaltada":'ahkomanatik',
	"sobresaltado":'ahkomanatik',
	"socavativa":'achikuepalaliztik',
	"socavativo":'achikuepalaliztik',
	"sola":'izel',
	"solamente":'izelpan',
	"solita":'izel',
	"solito":'izel',
	"solo":'izel',
	"solo":'zenkan',
	"soltada":'kauiliak',
	"soltado":'kauiliak',
	"sombra":'zeualli',
	"sonreida":'ixuetzkak',
	"sonreida":'uetzkak',
	"sonreido":'ixuetzkak',
	"sonreido":'uetzkak',
	"soplada":'ilpitzak',
	"soplado":'ilpitzak',
	"soporta":'chikouk',
	"soportada":'mamauatik',
	"soportado":'mamauatik',
	"soporto":'chikouk',
	"sorprendida":'izak',
	"sorprendido":'izak',
	"sorpresa":'ayeulli',
	"sorpresa":'izalli',
	"sorpresiva":'izatik',
	"sorpresiva":'izatiktli',
	"sorpresivo":'izatik',
	"sorpresivo":'izatiktli',
	"soñada":'kochik',
	"soñado":'kochik',
	"su":'i',
	"suave":'amotlaueltik',
	"suave":'amoueltik',
	"suave":'ilitik',
	"suave":'papatztik',
	"suave":'tzinyok',
	"subida":'euak',
	"subido":'euak',
	"submarina":'atlantemokak',
	"submarina":'atlantzinkak',
	"submarino":'atlantemokak',
	"submarino":'atlantzinkak',
	"sucedida":'panoyok',
	"sucedido":'panoyok',
	"sucia":'makauak',
	"sucia":'makauitl',
	"sucia":'makauk',
	"sucia":'tzok',
	"sucia":'tzoktli',
	"sucio":'makauak',
	"sucio":'makauitl',
	"sucio":'makauk',
	"sucio":'tzok',
	"sucio":'tzoktli',
	"suficiente":'temtik',
	"sufragada":'kuik',
	"sufragado":'kuik',
	"sufrida":'kokolik',
	"sufrido":'kokolik',
	"sugerida":'izpanotzak',
	"sugerido":'izpanotzak',
	"sujetada":'kuchok',
	"sujetada":'kuik',
	"sujetado":'kuchok',
	"sujetado":'kuik',
	"sumada":'iuanyok',
	"sumado":'iuanyok',
	"sumergida":'akalakiak',
	"sumergido":'akalakiak',
	"sumidero":'atokolko',
	"super":'achtok',
	"super":'ueyikchiuak',
	"superativa":'ueyikchiutik',
	"superativo":'ueyikchiutik',
	"superior":'achtok',
	"superior":'achtokan',
	"superior":'achtokantli',
	"superior":'achton',
	"superior":'achtontli',
	"supuesta":'neltok',
	"supuesto":'neltok',
	"sus":'i',
	"suspicaz":'amoneltokatok',
	"sustancial":'ihuanik',
	"sustituida":'onchiuayok',
	"sustituido":'onchiuayok',
	"susurrada":'ixtlakatlatlapouak',
	"susurrado":'ixtlakatlatlapouak',
	"suya":'anmo',
	"suya":'iaxka',
	"suyas":'anmo',
	"suyas":'iaxka',
	"suyo":'anmo',
	"suyo":'iaxka',
	"suyo":'inaxka',
	"suyos":'anmo',
	"suyos":'iaxka',
	"suyos":'inaxka',
	"séptimo":'chikomtetl',
	"sí":'kemak',
	"sólida":'teyok',
	"sólido":'teyok',
	"sólo":'izel',
	"sólo":'zenkan',
	"sónica":'tzilinitik',
	"sónico":'tzilinitik',
	"tal vez":'ueliz',
	"tal":'ihkin',
	"tal":'ikin',
	"talada":'kuautekik',
	"talado":'kuautekik',
	"también":'noihki',
	"tampoco":'amonoihki',
	"tan":'kexki',
	"tanta":'kexki',
	"tanto":'kexki',
	"tapada":'tlapak',
	"tapado":'tlapak',
	"tardada":'tlahkak',
	"tardado":'tlahkak',
	"tardía":'tlahpak',
	"tardío":'tlahpak',
	"te":'mitz',
	"te":'timo',
	"teclado":'machiyokan',
	"tekak":'acostada',
	"tekak":'acostado',
	"teléfono":'uehkatlahtoki',
	"temerosa":'maohtiki',
	"temeroso":'maohtiki',
	"temible":'maohueltik',
	"temida":'mautiak',
	"temido":'mautiak',
	"templada":'yamantik',
	"templado":'yamantik',
	"temporada":'kauyan',
	"temporal":'iman',
	"temporal":'imantzinko',
	"temporal":'man',
	"temporal":'manik',
	"temporalmente":'imanpan',
	"temporarea":'imantik',
	"temporarea":'kauik',
	"temporarea":'kautik',
	"temporareo":'imantik',
	"temporareo":'kauik',
	"temporareo":'kautik',
	"temprana":'kualkan',
	"temprano":'kualkan',
	"tenaz":'amokauhtiyok',
	"tenebroso":'mauhtik',
	"terca":'amokauhtiyok',
	"terca":'tzontetek',
	"terco":'amokauhtiyok',
	"terco":'tzontetek',
	"terminada":'tlamiak',
	"terminada":'tlamik',
	"terminado":'tlamiak',
	"terminado":'tlamik',
	"testaruda":'amokimatlahto',
	"testaruda":'amokimatlahtok',
	"testaruda":'amotemahmatik',
	"testaruda":'tzontetek',
	"testarudo":'amokimatlahto',
	"testarudo":'amokimatlahtok',
	"testarudo":'amotemahmatik',
	"testarudo":'tzontetek',
	"testificatoria":'ixkouak',
	"testificatorio":'ixkouak',
	"ti":'mitz',
	"tierno":'ilitik',
	"tierno":'zelik',
	"timbrada":'pipitzkak',
	"timbrado":'pipitzkak',
	"tirada":'tlazak',
	"tirado":'tlazak',
	"tiritatoria":'motoliniak',
	"tiritatorio":'motoliniak',
	"tocada":'ixpankuik',
	"tocado":'ixpankuik',
	"toda":'nochi',
	"todavía":'amoye',
	"todo":'nochi',
	"tolerada":'mamauatik',
	"tolerado":'mamauatik',
	"tolerante":'mamauatok',
	"tolerante":'mamautok',
	"tomada":'kuik',
	"tomado":'kuik',
	"tonta":'koaxoko',
	"tonta":'kouaxoko',
	"tonta":'tzontekontlauanki',
	"tonto":'koaxoko',
	"tonto":'kouaxoko',
	"tonto":'tzontekontlauanki',
	"torcida":'koliuhki',
	"torcido":'koliuaki',
	"torcido":'koliuhki',
	"tormenta":'aueyieheka',
	"tornado":'ahkamalakan',
	"tornado":'ehekapopoh',
	"tornado":'ehekatlakomolko',
	"tornado":'komaltlamatolli',
	"torpe":'yeyetehtik',
	"torpes":'yeyetehtik',
	"tosca":'tzapaltik',
	"tosca":'tzatzapaltik',
	"tosco":'tzapaltik',
	"tosco":'tzatzapaltik',
	"total":'nochik',
	"total":'nochtetl',
	"trabajada":'tekitik',
	"trabajado":'tekitik',
	"traducida":'tlahtolpalayok',
	"traducido":'tlahtolpalayok',
	"tragada":'kuak',
	"tragado":'kuak',
	"traida":'tlauihkok',
	"traido":'tlauihkok',
	"tramposo":'amonelihtoki',
	"tranquila":'mantik',
	"tranquilo":'mantik',
	"transformada":'itztlakoliuik',
	"transformada":'xolok',
	"transformado":'itztlakoliuik',
	"transformado":'xolok',
	"transmitida":'titlaniyok',
	"transmitido":'titlaniyok',
	"transmutada":'itztlakoliuak',
	"transmutodo":'itztlakoliuak',
	"transparencia":'chipauakyok',
	"transparente":'aiztatok',
	"transparente":'chipauak',
	"transparente":'chipauatok',
	"transparente":'iztak',
	"transpirada":'ihitonyotik',
	"transpirado":'ihitonyotik',
	"trasera":'kuitlapan',
	"trasero":'kuitlapan',
	"trasladada":'mamayauitik',
	"trasladada":'olitik',
	"trasladado":'mamayauitik',
	"trasladado":'olitik',
	"trece":'mahtlak uan eyi',
	"tres":'eyi',
	"trescientos":'mahtlak uan kaxtolpoual',
	"triste":'amopahpakik',
	"triste":'amopakiliztik',
	"triángulo":'eyiuakan',
	"trocatoria":'namakak',
	"trocatorio":'namakak',
	"tronada":'kueponiak',
	"tronada":'tlapetlaniak',
	"tronado":'kueponiak',
	"tronado":'tlapetlaniak',
	"tráfico":'cholli',
	"tu":'mo',
	"tumbada":'kantlazak',
	"tumbada":'kotlazak',
	"tumbado":'kantlazak',
	"tumbado":'kotlazak',
	"tus":'mo',
	"tuya":'moaxka',
	"tuyas":'moaxka',
	"tuyo":'moaxka',
	"tuyos":'moaxka',
	"términada":'tlamik',
	"términado":'tlamik',
	"ubicada":'kaniak',
	"ubicado":'kaniak',
	"un":'ze',
	"una":'ze',
	"ungida":'achtoutik',
	"ungido":'achtoutik',
	"unida":'uaniak',
	"unido":'uaniak',
	"universal":'nochik',
	"uno":'ze',
	"untada":'achtoutik',
	"untada":'ixpanmoliak',
	"untado":'achtoutik',
	"untado":'ixpanmoliak',
	"urticaria":'atzintzikatl',
	"usable":'kehtzauelik',
	"ustedes":'anmech',
	"usuario":'kehuitl',
	"utópico":'auelik',
	"vacía":'amo onkak',
	"vacía":'amokatik',
	"vacía":'amoonkak',
	"vacío":'amo onkak',
	"vacío":'amokatik',
	"vacío":'amoonkak',
	"valiosa":'patiyok',
	"valioso":'patiyok',
	"valuada":'patiyok',
	"valuado":'patiyok',
	"variable":'xolotik',
	"variables":'xolotik',
	"variada":'xolok',
	"variado":'xolok',
	"varios":'miak',
	"varonil":'alik',
	"velocidatoria":'olik',
	"velocidatorio":'olik',
	"veloz":'olik',
	"venerable":'tzintik',
	"venida":'ualak',
	"venido":'ualak',
	"verdadera":'melauak',
	"verdadero":'melauak',
	"verde":'xohtik',
	"verdes":'xohtik',
	"vereda":'ohtli',
	"verifica":'itachiuak',
	"verificada":'itachiuak',
	"verificada":'itachiyok',
	"verificado":'itachiuak',
	"verificado":'itachiyok',
	"verificativa":'onitaliztik',
	"verificativo":'onitaliztik',
	"verificatoria":'onitaliztik',
	"verificatorio":'onitaliztik',
	"verifico":'itachiuak',
	"vertical":'melauipechtli',
	"vertiente":'atlapulko',
	"veráz":'melauak',
	"vestida":'kemitik',
	"vestida":'tlakemik',
	"vestido":'tlakemik',
	"vestido":'uipil',
	"vestido":'uipilli',
	"vestimenta":'kemitl',
	"vesánica":'koaxoko',
	"vesánica":'kouaxoko',
	"vesánico":'kiuaxoko',
	"vesánico":'koaxoko',
	"viajante":'ohtotokatok',
	"viajante":'ohtotokayautok',
	"viajatoria":'ohtotokak',
	"viajatorio":'ohtotokak',
	"viajero":'ohtotokatok',
	"vibrable":'olinik',
	"vibrativa":'nmoolinializtik',
	"vibrativo":'nmoolinializtik',
	"vibratoria":'moolinializtik',
	"vibratorio":'moolinializtik',
	"viciosa":'makaua',
	"viciosa":'makauitl',
	"viciosa":'makauk',
	"vicioso":'makaua',
	"vicioso":'makauitl',
	"vicioso":'makauk',
	"vida":'nemil',
	"vida":'nemilli',
	"vieja":'ilama',
	"vieja":'ilamak',
	"vieja":'zolik',
	"viejo":'zolik',
	"viento":'ehekatl',
	"vigilante":'kuitlauatok',
	"vigilosa":'kuitlauiatik',
	"vigiloso":'kuitlauiatik',
	"vinculada":'mekatik',
	"vinculada":'mekauatik',
	"vinculado":'mekatik',
	"vinculado":'mekauatik',
	"violada":'ihuiyauk',
	"violado":'ihuiyauk',
	"violenta":'ihuiyauk',
	"violento":'ihuiyauk',
	"virtual":'amonelik',
	"viscoso":'alaixtik',
	"visitante":'chantotokatok',
	"vislumbrativa":'itaaziliztik',
	"vislumbrativo":'itaaziliztik',
	"vista":'itayotl',
	"visto":'itatok',
	"viva":'nemitok',
	"viva":'nemiyok',
	"vivida":'nemik',
	"vivido":'nemik',
	"vivo":'nemitok',
	"vivo":'nemiyok',
	"volada":'patlanik',
	"volado":'patlanik',
	"volteda":'kuepayotik',
	"voltedo":'kuepayotik',
	"voludo":'koyolli',
	"votada":'kuik',
	"votado":'kuik',
	"vuestra":'anmo',
	"vuestra":'anmoaxka',
	"vuestras":'anmo',
	"vuestras":'anmoaxka',
	"vuestro":'anmo',
	"vuestro":'anmoaxka',
	"vuestros":'anmo',
	"vuestros":'anmoaxka',
	"vulgar":'amouelueyik',
	"vívida":'nemik',
	"vívida":'nemitik',
	"vívido":'nemik',
	"vívido":'nemitik',
	"áspero":'teteltik',
	"él":'yehua',
	"única":'izelli',
	# Acusativos
	# acusativos
	# Indefinidos:
	# Prefijos de pertenencia
	# Reflexivos
# PERTENENCIA
# REFLEXIVO
	"único":'izelli'
	}