# -*- coding: utf-8 -*-
"""
© Roberto Spíndola Barrón, 2026.
Todos los derechos reservados.

Sistema estructural de análisis lingüístico Náhuatl ↔ Español.
Módulo: [poualyotl]
Versión: v1.0
Fecha: [23-05-2026]

Prohibida la reproducción, redistribución, extracción estructural,
ingeniería inversa, entrenamiento de modelos de inteligencia artificial
o reutilización no autorizada.
"""
# Tkinter se importa únicamente al abrir la interfaz local.
# El módulo puede así importarse sin entorno gráfico (por ejemplo, en Railway).

#Este programa lleva a cabo conversión numérica entre "anAuak pouAlyotl" y el sistema numérico actual.

numeros = {
	8000: ["υ", "chikipil"],
	7600: ["|||•••• ʎ", "chikonaui zentzon"],
	7200: ["|||••• ʎ", "chikoeyi zentzon"],
	6800: ["|||•• ʎ", "kaxtol uan ome zentzon"],
	6400: ["|||• ʎ", "kaxtol uan ze zentzon"],
	6000: ["||| ʎ", "kaxtol zentzon"],
	5600: ["||•••• ʎ", "mahtlak uan naui zentzon"],
	5200: ["||••• ʎ", "mahtlak uan eyi zentzon"],
	4800: ["||•• ʎ", "mahtlak uan ome zentzon"],
	4400: ["||• ʎ", "mahtlak uan ze zentzon"],
	4000: ["|| ʎ", "mahtlak zentzon"],
	3600: ["|•••• ʎ", "chiknaui zentzon"],
	3200: ["|••• ʎ", "chikoeyi zentzon"],
	2800: ["|•• ʎ", "chikome zentzon"],
	2400: ["|• ʎ", "chikoaze zentzon"],
	2000: ["| ʎ", "makuil zentzon"],
	1600: ["•••• ʎ", "naui zentzon"],
	1200: ["••• ʎ", "eyi zentzon"],
	800: ["•• ʎ", "omzentzon"],
	499: ["(ʎ) (••••O) ||| ••••", "zentzon uan naupoual uan kaxtol uan naui"],
	498: ["(ʎ) (••••O) ||| •••", "zentzon uan naupoual uan kaxtol uan eyi"],
	497: ["(ʎ) (••••O) ||| ••", "zentzon uan naupoual uan kaxtol uan ome"],
	496: ["(ʎ) (••••O) ||| •", "zentzon uan naupoual uan kaxtol uan ze"],
	495: ["(ʎ) (••••O) |||", "zentzon uan naupoual uan kaxtol"],
	494: ["(ʎ) (••••O) || ••••", "zentzon uan naupoual uan mahtlak uan naui"],
	493: ["(ʎ) (••••O) || •••", "zentzon uan naupoual uan mahtlak uan eyi"],
	492: ["(ʎ) (••••O) || ••", "zentzon uan naupoual uan mahtlak uan ome"],
	491: ["(ʎ) (••••O) || •", "zentzon uan naupoual uan mahtlak uan ze"],
	490: ["(ʎ) (••••O) ||", "zentzon uan naupoual uan mahtlak"],
	489: ["(ʎ) (••••O) |••••", "zentzon uan naupoual uan chiknaui"],
	488: ["(ʎ) (••••O) |•••", "zentzon uan naupoual uan chikoeyi"],
	487: ["(ʎ) (••••O) |••", "zentzon uan naupoual uan chikome"],
	486: ["(ʎ) (••••O) |•", "zentzon uan naupoual uan chikoaze"],
	485: ["(ʎ) (••••O) |", "zentzon uan naupoual uan makuil"],
	484: ["(ʎ) (••••O) ••••", "zentzon uan naupoual uan naui"],
	483: ["(ʎ) (••••O) •••", "zentzon uan naupoual uan eyi"],
	482: ["(ʎ) (••••O) ••", "zentzon uan naupoual uan ome"],
	481: ["(ʎ) (••••O) •", "zentzon uan naupoual uan ze"],
	480: ["(ʎ) (••••O)", "zentzon uan naupoual"],
	479: ["(ʎ) (•••O) ||| ••••", "zentzon uan eypoual uan kaxtol uan naui"],
	478: ["(ʎ) (•••O) ||| •••", "zentzon uan eypoual uan kaxtol uan eyi"],
	477: ["(ʎ) (•••O) ||| ••", "zentzon uan eypoual uan kaxtol uan ome"],
	476: ["(ʎ) (•••O) ||| •", "zentzon uan eypoual uan kaxtol uan ze"],
	475: ["(ʎ) (•••O) |||", "zentzon uan eypoual uan kaxtol"],
	474: ["(ʎ) (•••O) || ••••", "zentzon uan eypoual uan mahtlak uan naui"],
	473: ["(ʎ) (•••O) || •••", "zentzon uan eypoual uan mahtlak uan eyi"],
	472: ["(ʎ) (•••O) || ••", "zentzon uan eypoual uan mahtlak uan ome"],
	471: ["(ʎ) (•••O) || •", "zentzon uan eypoual uan mahtlak uan ze"],
	470: ["(ʎ) (•••O) ||", "zentzon uan eypoual uan mahtlak"],
	469: ["(ʎ) (•••O) |••••", "zentzon uan eypoual uan chiknaui"],
	468: ["(ʎ) (•••O) |•••", "zentzon uan eypoual uan chikoeyi"],
	467: ["(ʎ) (•••O) |••", "zentzon uan eypoual uan chikome"],
	466: ["(ʎ) (•••O) |•", "zentzon uan eypoual uan chikoaze"],
	465: ["(ʎ) (•••O) |", "zentzon uan eypoual uan makuil"],
	464: ["(ʎ) (•••O) ••••", "zentzon uan eypoual uan naui"],
	463: ["(ʎ) (•••O) •••", "zentzon uan eypoual uan eyi"],
	462: ["(ʎ) (•••O) ••", "zentzon uan eypoual uan ome"],
	461: ["(ʎ) (•••O) •", "zentzon uan eypoual uan ze"],
	460: ["(ʎ) (•••O) ||", "zentzon uan eypoual uan mahtlak"],
	459: ["(ʎ) (••O) ||| ••••", "zentzon uan ompoual uan kaxtol uan naui"],
	458: ["(ʎ) (••O) ||| •••", "zentzon uan ompoual uan kaxtol uan eyi"],
	457: ["(ʎ) (••O) ||| ••", "zentzon uan ompoual uan kaxtol uan ome"],
	456: ["(ʎ) (••O) ||| •", "zentzon uan ompoual uan kaxtol uan ze"],
	455: ["(ʎ) (••O) |||", "zentzon uan ompoual uan kaxtol"],
	454: ["(ʎ) (••O) || ••••", "zentzon uan ompoual uan mahtlak uan naui"],
	453: ["(ʎ) (••O) || •••", "zentzon uan ompoual uan mahtlak uan eyi"],
	452: ["(ʎ) (••O) || ••", "zentzon uan ompoual uan mahtlak uan ome"],
	451: ["(ʎ) (••O) || •", "zentzon uan ompoual uan mahtlak uan ze"],
	450: ["(ʎ) (••O) ||", "zentzon uan ompoual uan mahtlak"],
	449: ["(ʎ) (••O) |••••", "zentzon uan ompoual uan chiknaui"],
	448: ["(ʎ) (••O) |•••", "zentzon uan ompoual uan chikoeyi"],
	447: ["(ʎ) (••O) |••", "zentzon uan ompoual uan chikome"],
	446: ["(ʎ) (••O) |•", "zentzon uan ompoual uan chikoaze"],
	445: ["(ʎ) (••O) |", "zentzon uan ompoual uan makuil"],
	444: ["(ʎ) (••O) ••••", "zentzon uan ompoual uan naui"],
	443: ["(ʎ) (••O) •••", "zentzon uan ompoual uan eyi"],
	442: ["(ʎ) (••O) ••", "zentzon uan ompoual uan ome"],
	441: ["(ʎ) (••O) •", "zentzon uan ompoual uan ze"],
	440: ["(ʎ) ••O", "zentzon uan ompoual"],
	439: ["(ʎ) (O) ||| ••••", "zentzon uan zempoual uan kaxtol uan naui"],
	438: ["(ʎ) (O) ||| •••", "zentzon uan zempoual uan kaxtol uan eyi"],
	437: ["(ʎ) (O) ||| ••", "zentzon uan zempoual uan kaxtol uan ome"],
	436: ["(ʎ) (O) ||| •", "zentzon uan zempoual uan kaxtol uan ze"],
	435: ["(ʎ) (O) |||", "zentzon uan zempoual uan kaxtol"],
	434: ["(ʎ) (O) || ••••", "zentzon uan zempoual uan mahtlak uan naui"],
	433: ["(ʎ) (O) || •••", "zentzon uan zempoual uan mahtlak uan eyi"],
	432: ["(ʎ) (O) || ••", "zentzon uan zempoual uan mahtlak uan ome"],
	431: ["(ʎ) (O) || •", "zentzon uan zempoual uan mahtlak uan ze"],
	430: ["(ʎ) (O) ||", "zentzon uan zempoual uan mahtlak"],
	429: ["(ʎ) (O) |••••", "zentzon uan zempoual uan chiknaui"],
	428: ["(ʎ) (O) |•••", "zentzon uan zempoual uan chikoeyi"],
	427: ["(ʎ) (O) |••", "zentzon uan zempoual uan chikome"],
	426: ["(ʎ) (O) |•", "zentzon uan zempoual uan chikoaze"],
	425: ["(ʎ) (O) |", "zentzon uan zempoual uan makuil"],
	424: ["(ʎ) (O) ••••", "zentzon uan zempoual uan naui"],
	423: ["(ʎ) (O) •••", "zentzon uan zempoual uan eyi"],
	422: ["(ʎ) (O) ••", "zentzon uan zempoual uan ome"],
	421: ["(ʎ) (O) •", "zentzon uan zempoual uan ze"],
	420: ["(ʎ) •O", "zentzon uan zempoual"],
	419: ["(ʎ) ||| ••••", "zentzon uan kaxtol uan naui"],
	418: ["(ʎ) ||| •••", "zentzon uan kaxtol uan eyi"],
	417: ["(ʎ) ||| ••", "zentzon uan kaxtol uan ome"],
	416: ["(ʎ) ||| •", "zentzon uan kaxtol uan ze"],
	415: ["(ʎ) |||", "zentzon uan kaxtol"],
	414: ["(ʎ) || ••••", "zentzon uan mahtlak uan naui"],
	413: ["(ʎ) || •••", "zentzon uan mahtlak uan eyi"],
	412: ["(ʎ) || ••", "zentzon uan mahtlak uan ome"],
	411: ["(ʎ) || •", "zentzon uan mahtlak uan ze"],
	410: ["(ʎ) ||", "zentzon uan mahtlak"],
	409: ["(ʎ) |••••", "zentzon uan chiknaui"],
	408: ["(ʎ) |•••", "zentzon uan chikoeyi"],
	407: ["(ʎ) |••", "zentzon uan chikome"],
	406: ["(ʎ) |•", "zentzon uan chikoaze"],
	405: ["(ʎ) |", "zentzon uan makuil"],
	404: ["(ʎ) ••••", "zentzon uan naui"],
	403: ["(ʎ) •••", "zentzon uan eyi"],
	402: ["(ʎ) ••", "zentzon uan ome"],
	401: ["(ʎ) •", "zentzon uan ze"],
	400: ["•ʎ", "zentzon"],
	399: ["(|||O) (••••O) ||| ••••", "kaxtol poual uan naupoual uan kaxtol uan naui"],
	398: ["(|||O) (••••O) ||| •••", "kaxtol poual uan naupoual uan kaxtol uan eyi"],
	397: ["(|||O) (••••O) ||| ••", "kaxtol poual uan naupoual uan kaxtol uan ome"],
	396: ["(|||O) (••••O) ||| •", "kaxtol poual uan naupoual uan kaxtol uan ze"],
	395: ["(|||O) (••••O) |||", "kaxtol poual uan naupoual uan kaxtol"],
	394: ["(|||O) (••••O) || ••••", "kaxtol poual uan naupoual uan mahtlak uan naui"],
	393: ["(|||O) (••••O) || •••", "kaxtol poual uan naupoual uan mahtlak uan eyi"],
	392: ["(|||O) (••••O) || ••", "kaxtol poual uan naupoual uan mahtlak uan ome"],
	391: ["(|||O) (••••O) || •", "kaxtol poual uan naupoual uan mahtlak uan ze"],
	390: ["(|||O) (••••O) ||", "kaxtol poual uan naupoual uan mahtlak"],
	389: ["(|||O) (••••O) |••••", "kaxtol poual uan naupoual uan chiknaui"],
	388: ["(|||O) (••••O) |•••", "kaxtol poual uan naupoual uan chikoeyi"],
	387: ["(|||O) (••••O) |••", "kaxtol poual uan naupoual uan chikome"],
	386: ["(|||O) (••••O) |•", "kaxtol poual uan naupoual uan chikoaze"],
	385: ["(|||O) (••••O) |", "kaxtol poual uan naupoual uan makuil"],
	384: ["(|||O) (••••O) ••••", "kaxtol poual uan naupoual uan naui"],
	383: ["(|||O) (••••O) •••", "kaxtol poual uan naupoual uan eyi"],
	382: ["(|||O) (••••O) ••", "kaxtol poual uan naupoual uan ome"],
	381: ["(|||O) (••••O) •", "kaxtol poual uan naupoual uan ze"],
	380: ["(|||O) (••••O)", "kaxtol poual uan naupoual"],
	379: ["(|||O) (•••O) ||| ••••", "kaxtol poual uan eypoual uan kaxtol uan naui"],
	378: ["(|||O) (•••O) ||| •••", "kaxtol poual uan eypoual uan kaxtol uan eyi"],
	377: ["(|||O) (•••O) ||| ••", "kaxtol poual uan eypoual uan kaxtol uan ome"],
	376: ["(|||O) (•••O) ||| •", "kaxtol poual uan eypoual uan kaxtol uan ze"],
	375: ["(|||O) (•••O) |||", "kaxtol poual uan eypoual uan kaxtol"],
	374: ["(|||O) (•••O) || ••••", "kaxtol poual uan eypoual uan mahtlak uan naui"],
	373: ["(|||O) (•••O) || •••", "kaxtol poual uan eypoual uan mahtlak uan eyi"],
	372: ["(|||O) (•••O) || ••", "kaxtol poual uan eypoual uan mahtlak uan ome"],
	371: ["(|||O) (•••O) || •", "kaxtol poual uan eypoual uan mahtlak uan ze"],
	370: ["(|||O) (•••O) ||", "kaxtol poual uan eypoual uan mahtlak"],
	369: ["(|||O) (•••O) |••••", "kaxtol poual uan eypoual uan chiknaui"],
	368: ["(|||O) (•••O) |•••", "kaxtol poual uan eypoual uan chikoeyi"],
	367: ["(|||O) (•••O) |••", "kaxtol poual uan eypoual uan chikome"],
	366: ["(|||O) (•••O) |•", "kaxtol poual uan eypoual uan chikoaze"],
	365: ["(|||O) (•••O) |", "kaxtol poual uan eypoual uan makuil"],
	364: ["(|||O) (•••O) ••••", "kaxtol poual uan eypoual uan naui"],
	363: ["(|||O) (•••O) •••", "kaxtol poual uan eypoual uan eyi"],
	362: ["(|||O) (•••O) ••", "kaxtol poual uan eypoual uan ome"],
	361: ["(|||O) (•••O) •", "kaxtol poual uan eypoual uan ze"],
	360: ["(|||O) (•••O) ||", "kaxtol poual uan eypoual uan mahtlak"],
	359: ["(|||O) (••O) ||| ••••", "kaxtol poual uan ompoual uan kaxtol uan naui"],
	358: ["(|||O) (••O) ||| •••", "kaxtol poual uan ompoual uan kaxtol uan eyi"],
	357: ["(|||O) (••O) ||| ••", "kaxtol poual uan ompoual uan kaxtol uan ome"],
	356: ["(|||O) (••O) ||| •", "kaxtol poual uan ompoual uan kaxtol uan ze"],
	355: ["(|||O) (••O) |||", "kaxtol poual uan ompoual uan kaxtol"],
	354: ["(|||O) (••O) || ••••", "kaxtol poual uan ompoual uan mahtlak uan naui"],
	353: ["(|||O) (••O) || •••", "kaxtol poual uan ompoual uan mahtlak uan eyi"],
	352: ["(|||O) (••O) || ••", "kaxtol poual uan ompoual uan mahtlak uan ome"],
	351: ["(|||O) (••O) || •", "kaxtol poual uan ompoual uan mahtlak uan ze"],
	350: ["(|||O) (••O) ||", "kaxtol poual uan ompoual uan mahtlak"],
	349: ["(|||O) (••O) |••••", "kaxtol poual uan ompoual uan chiknaui"],
	348: ["(|||O) (••O) |•••", "kaxtol poual uan ompoual uan chikoeyi"],
	347: ["(|||O) (••O) |••", "kaxtol poual uan ompoual uan chikome"],
	346: ["(|||O) (••O) |•", "kaxtol poual uan ompoual uan chikoaze"],
	345: ["(|||O) (••O) |", "kaxtol poual uan ompoual uan makuil"],
	344: ["(|||O) (••O) ••••", "kaxtol poual uan ompoual uan naui"],
	343: ["(|||O) (••O) •••", "kaxtol poual uan ompoual uan eyi"],
	342: ["(|||O) (••O) ••", "kaxtol poual uan ompoual uan ome"],
	341: ["(|||O) (••O) •", "kaxtol poual uan ompoual uan ze"],
	340: ["(|||O) ••O", "kaxtol poual uan ompoual"],
	339: ["(|||O) (O) ||| ••••", "kaxtol poual uan zempoual uan kaxtol uan naui"],
	338: ["(|||O) (O) ||| •••", "kaxtol poual uan zempoual uan kaxtol uan eyi"],
	337: ["(|||O) (O) ||| ••", "kaxtol poual uan zempoual uan kaxtol uan ome"],
	336: ["(|||O) (O) ||| •", "kaxtol poual uan zempoual uan kaxtol uan ze"],
	335: ["(|||O) (O) |||", "kaxtol poual uan zempoual uan kaxtol"],
	334: ["(|||O) (O) || ••••", "kaxtol poual uan zempoual uan mahtlak uan naui"],
	333: ["(|||O) (O) || •••", "kaxtol poual uan zempoual uan mahtlak uan eyi"],
	332: ["(|||O) (O) || ••", "kaxtol poual uan zempoual uan mahtlak uan ome"],
	331: ["(|||O) (O) || •", "kaxtol poual uan zempoual uan mahtlak uan ze"],
	330: ["(|||O) (O) ||", "kaxtol poual uan zempoual uan mahtlak"],
	329: ["(|||O) (O) |••••", "kaxtol poual uan zempoual uan chiknaui"],
	328: ["(|||O) (O) |•••", "kaxtol poual uan zempoual uan chikoeyi"],
	327: ["(|||O) (O) |••", "kaxtol poual uan zempoual uan chikome"],
	326: ["(|||O) (O) |•", "kaxtol poual uan zempoual uan chikoaze"],
	325: ["(|||O) (O) |", "kaxtol poual uan zempoual uan makuil"],
	324: ["(|||O) (O) ••••", "kaxtol poual uan zempoual uan naui"],
	323: ["(|||O) (O) •••", "kaxtol poual uan zempoual uan eyi"],
	322: ["(|||O) (O) ••", "kaxtol poual uan zempoual uan ome"],
	321: ["(|||O) (O) •", "kaxtol poual uan zempoual uan ze"],
	320: ["(|||O) •O", "kaxtol poual uan zempoual"],
	319: ["(|||O) ||| ••••", "kaxtol poual uan kaxtol uan naui"],
	318: ["(|||O) ||| •••", "kaxtol poual uan kaxtol uan eyi"],
	317: ["(|||O) ||| ••", "kaxtol poual uan kaxtol uan ome"],
	316: ["(|||O) ||| •", "kaxtol poual uan kaxtol uan ze"],
	315: ["(|||O) |||", "kaxtol poual uan kaxtol"],
	314: ["(|||O) || ••••", "kaxtol poual uan mahtlak uan naui"],
	313: ["(|||O) || •••", "kaxtol poual uan mahtlak uan eyi"],
	312: ["(|||O) || ••", "kaxtol poual uan mahtlak uan ome"],
	311: ["(|||O) || •", "kaxtol poual uan mahtlak uan ze"],
	310: ["(|||O) ||", "kaxtol poual uan mahtlak"],
	309: ["(|||O) |••••", "kaxtol poual uan chiknaui"],
	308: ["(|||O) |•••", "kaxtol poual uan chikoeyi"],
	307: ["(|||O) |••", "kaxtol poual uan chikome"],
	306: ["(|||O) |•", "kaxtol poual uan chikoaze"],
	305: ["(|||O) |", "kaxtol poual uan makuil"],
	304: ["(|||O) ••••", "kaxtol poual uan naui"],
	303: ["(|||O) •••", "kaxtol poual uan eyi"],
	302: ["(|||O) ••", "kaxtol poual uan ome"],
	301: ["(|||O) •", "kaxtol poual uan ze"],
	300: ["(|||O)", "kaxtol poual"],
	299: ["(||O) (••••O) ||| ••••", "mahtlak poual uan naupoual uan kaxtol uan naui"],
	298: ["(||O) (••••O) ||| •••", "mahtlak poual uan naupoual uan kaxtol uan eyi"],
	297: ["(||O) (••••O) ||| ••", "mahtlak poual uan naupoual uan kaxtol uan ome"],
	296: ["(||O) (••••O) ||| •", "mahtlak poual uan naupoual uan kaxtol uan ze"],
	295: ["(||O) (••••O) |||", "mahtlak poual uan naupoual uan kaxtol"],
	294: ["(||O) (••••O) || ••••", "mahtlak poual uan naupoual uan mahtlak uan naui"],
	293: ["(||O) (••••O) || •••", "mahtlak poual uan naupoual uan mahtlak uan eyi"],
	292: ["(||O) (••••O) || ••", "mahtlak poual uan naupoual uan mahtlak uan ome"],
	291: ["(||O) (••••O) || •", "mahtlak poual uan naupoual uan mahtlak uan ze"],
	290: ["(||O) (••••O) ||", "mahtlak poual uan naupoual uan mahtlak"],
	289: ["(||O) (••••O) |••••", "mahtlak poual uan naupoual uan chiknaui"],
	288: ["(||O) (••••O) |•••", "mahtlak poual uan naupoual uan chikoeyi"],
	287: ["(||O) (••••O) |••", "mahtlak poual uan naupoual uan chikome"],
	286: ["(||O) (••••O) |•", "mahtlak poual uan naupoual uan chikoaze"],
	285: ["(||O) (••••O) |", "mahtlak poual uan naupoual uan makuil"],
	284: ["(||O) (••••O) ••••", "mahtlak poual uan naupoual uan naui"],
	283: ["(||O) (••••O) •••", "mahtlak poual uan naupoual uan eyi"],
	282: ["(||O) (••••O) ••", "mahtlak poual uan naupoual uan ome"],
	281: ["(||O) (••••O) •", "mahtlak poual uan naupoual uan ze"],
	280: ["(||O) (••••O)", "mahtlak poual uan naupoual"],
	279: ["(||O) (•••O) ||| ••••", "mahtlak poual uan eypoual uan kaxtol uan naui"],
	278: ["(||O) (•••O) ||| •••", "mahtlak poual uan eypoual uan kaxtol uan eyi"],
	277: ["(||O) (•••O) ||| ••", "mahtlak poual uan eypoual uan kaxtol uan ome"],
	276: ["(||O) (•••O) ||| •", "mahtlak poual uan eypoual uan kaxtol uan ze"],
	275: ["(||O) (•••O) |||", "mahtlak poual uan eypoual uan kaxtol"],
	274: ["(||O) (•••O) || ••••", "mahtlak poual uan eypoual uan mahtlak uan naui"],
	273: ["(||O) (•••O) || •••", "mahtlak poual uan eypoual uan mahtlak uan eyi"],
	272: ["(||O) (•••O) || ••", "mahtlak poual uan eypoual uan mahtlak uan ome"],
	271: ["(||O) (•••O) || •", "mahtlak poual uan eypoual uan mahtlak uan ze"],
	270: ["(||O) (•••O) ||", "mahtlak poual uan eypoual uan mahtlak"],
	269: ["(||O) (•••O) |••••", "mahtlak poual uan eypoual uan chiknaui"],
	268: ["(||O) (•••O) |•••", "mahtlak poual uan eypoual uan chikoeyi"],
	267: ["(||O) (•••O) |••", "mahtlak poual uan eypoual uan chikome"],
	266: ["(||O) (•••O) |•", "mahtlak poual uan eypoual uan chikoaze"],
	265: ["(||O) (•••O) |", "mahtlak poual uan eypoual uan makuil"],
	264: ["(||O) (•••O) ••••", "mahtlak poual uan eypoual uan naui"],
	263: ["(||O) (•••O) •••", "mahtlak poual uan eypoual uan eyi"],
	262: ["(||O) (•••O) ••", "mahtlak poual uan eypoual uan ome"],
	261: ["(||O) (•••O) •", "mahtlak poual uan eypoual uan ze"],
	260: ["(||O) (•••O) ||", "mahtlak poual uan eypoual uan mahtlak"],
	259: ["(||O) (••O) ||| ••••", "mahtlak poual uan ompoual uan kaxtol uan naui"],
	258: ["(||O) (••O) ||| •••", "mahtlak poual uan ompoual uan kaxtol uan eyi"],
	257: ["(||O) (••O) ||| ••", "mahtlak poual uan ompoual uan kaxtol uan ome"],
	256: ["(||O) (••O) ||| •", "mahtlak poual uan ompoual uan kaxtol uan ze"],
	255: ["(||O) (••O) |||", "mahtlak poual uan ompoual uan kaxtol"],
	254: ["(||O) (••O) || ••••", "mahtlak poual uan ompoual uan mahtlak uan naui"],
	253: ["(||O) (••O) || •••", "mahtlak poual uan ompoual uan mahtlak uan eyi"],
	252: ["(||O) (••O) || ••", "mahtlak poual uan ompoual uan mahtlak uan ome"],
	251: ["(||O) (••O) || •", "mahtlak poual uan ompoual uan mahtlak uan ze"],
	250: ["(||O) (••O) ||", "mahtlak poual uan ompoual uan mahtlak"],
	249: ["(||O) (••O) |••••", "mahtlak poual uan ompoual uan chiknaui"],
	248: ["(||O) (••O) |•••", "mahtlak poual uan ompoual uan chikoeyi"],
	247: ["(||O) (••O) |••", "mahtlak poual uan ompoual uan chikome"],
	246: ["(||O) (••O) |•", "mahtlak poual uan ompoual uan chikoaze"],
	245: ["(||O) (••O) |", "mahtlak poual uan ompoual uan makuil"],
	244: ["(||O) (••O) ••••", "mahtlak poual uan ompoual uan naui"],
	243: ["(||O) (••O) •••", "mahtlak poual uan ompoual uan eyi"],
	242: ["(||O) (••O) ••", "mahtlak poual uan ompoual uan ome"],
	241: ["(||O) (••O) •", "mahtlak poual uan ompoual uan ze"],
	240: ["(||O) ••O", "mahtlak poual uan ompoual"],
	239: ["(||O) (O) ||| ••••", "mahtlak poual uan zempoual uan kaxtol uan naui"],
	238: ["(||O) (O) ||| •••", "mahtlak poual uan zempoual uan kaxtol uan eyi"],
	237: ["(||O) (O) ||| ••", "mahtlak poual uan zempoual uan kaxtol uan ome"],
	236: ["(||O) (O) ||| •", "mahtlak poual uan zempoual uan kaxtol uan ze"],
	235: ["(||O) (O) |||", "mahtlak poual uan zempoual uan kaxtol"],
	234: ["(||O) (O) || ••••", "mahtlak poual uan zempoual uan mahtlak uan naui"],
	233: ["(||O) (O) || •••", "mahtlak poual uan zempoual uan mahtlak uan eyi"],
	232: ["(||O) (O) || ••", "mahtlak poual uan zempoual uan mahtlak uan ome"],
	231: ["(||O) (O) || •", "mahtlak poual uan zempoual uan mahtlak uan ze"],
	230: ["(||O) (O) ||", "mahtlak poual uan zempoual uan mahtlak"],
	229: ["(||O) (O) |••••", "mahtlak poual uan zempoual uan chiknaui"],
	228: ["(||O) (O) |•••", "mahtlak poual uan zempoual uan chikoeyi"],
	227: ["(||O) (O) |••", "mahtlak poual uan zempoual uan chikome"],
	226: ["(||O) (O) |•", "mahtlak poual uan zempoual uan chikoaze"],
	225: ["(||O) (O) |", "mahtlak poual uan zempoual uan makuil"],
	224: ["(||O) (O) ••••", "mahtlak poual uan zempoual uan naui"],
	223: ["(||O) (O) •••", "mahtlak poual uan zempoual uan eyi"],
	222: ["(||O) (O) ••", "mahtlak poual uan zempoual uan ome"],
	221: ["(||O) (O) •", "mahtlak poual uan zempoual uan ze"],
	220: ["(||O) •O", "mahtlak poual uan zempoual"],
	219: ["(||O) ||| ••••", "mahtlak poual uan kaxtol uan naui"],
	218: ["(||O) ||| •••", "mahtlak poual uan kaxtol uan eyi"],
	217: ["(||O) ||| ••", "mahtlak poual uan kaxtol uan ome"],
	216: ["(||O) ||| •", "mahtlak poual uan kaxtol uan ze"],
	215: ["(||O) |||", "mahtlak poual uan kaxtol"],
	214: ["(||O) || ••••", "mahtlak poual uan mahtlak uan naui"],
	213: ["(||O) || •••", "mahtlak poual uan mahtlak uan eyi"],
	212: ["(||O) || ••", "mahtlak poual uan mahtlak uan ome"],
	211: ["(||O) || •", "mahtlak poual uan mahtlak uan ze"],
	210: ["(||O) ||", "mahtlak poual uan mahtlak"],
	209: ["(||O) |••••", "mahtlak poual uan chiknaui"],
	208: ["(||O) |•••", "mahtlak poual uan chikoeyi"],
	207: ["(||O) |••", "mahtlak poual uan chikome"],
	206: ["(||O) |•", "mahtlak poual uan chikoaze"],
	205: ["(||O) |", "mahtlak poual uan makuil"],
	204: ["(||O) ••••", "mahtlak poual uan naui"],
	203: ["(||O) •••", "mahtlak poual uan eyi"],
	202: ["(||O) ••", "mahtlak poual uan ome"],
	201: ["(||O) •", "mahtlak poual uan ze"],
	200: ["(||O)", "mahtlak poual"],
	199: ["(|O) (••••O) ||| ••••", "makuil poual uan naupoual uan kaxtol uan naui"],
	198: ["(|O) (••••O) ||| •••", "makuil poual uan naupoual uan kaxtol uan eyi"],
	197: ["(|O) (••••O) ||| ••", "makuil poual uan naupoual uan kaxtol uan ome"],
	196: ["(|O) (••••O) ||| •", "makuil poual uan naupoual uan kaxtol uan ze"],
	195: ["(|O) (••••O) |||", "makuil poual uan naupoual uan kaxtol"],
	194: ["(|O) (••••O) || ••••", "makuil poual uan naupoual uan mahtlak uan naui"],
	193: ["(|O) (••••O) || •••", "makuil poual uan naupoual uan mahtlak uan eyi"],
	192: ["(|O) (••••O) || ••", "makuil poual uan naupoual uan mahtlak uan ome"],
	191: ["(|O) (••••O) || •", "makuil poual uan naupoual uan mahtlak uan ze"],
	190: ["(|O) (••••O) ||", "makuil poual uan naupoual uan mahtlak"],
	189: ["(|O) (••••O) |••••", "makuil poual uan naupoual uan chiknaui"],
	188: ["(|O) (••••O) |•••", "makuil poual uan naupoual uan chikoeyi"],
	187: ["(|O) (••••O) |••", "makuil poual uan naupoual uan chikome"],
	186: ["(|O) (••••O) |•", "makuil poual uan naupoual uan chikoaze"],
	185: ["(|O) (••••O) |", "makuil poual uan naupoual uan makuil"],
	184: ["(|O) (••••O) ••••", "makuil poual uan naupoual uan naui"],
	183: ["(|O) (••••O) •••", "makuil poual uan naupoual uan eyi"],
	182: ["(|O) (••••O) ••", "makuil poual uan naupoual uan ome"],
	181: ["(|O) (••••O) •", "makuil poual uan naupoual uan ze"],
	180: ["(|O) (••••O)", "makuil poual uan naupoual"],
	179: ["(|O) (•••O) ||| ••••", "makuil poual uan eypoual uan kaxtol uan naui"],
	178: ["(|O) (•••O) ||| •••", "makuil poual uan eypoual uan kaxtol uan eyi"],
	177: ["(|O) (•••O) ||| ••", "makuil poual uan eypoual uan kaxtol uan ome"],
	176: ["(|O) (•••O) ||| •", "makuil poual uan eypoual uan kaxtol uan ze"],
	175: ["(|O) (•••O) |||", "makuil poual uan eypoual uan kaxtol"],
	174: ["(|O) (•••O) || ••••", "makuil poual uan eypoual uan mahtlak uan naui"],
	173: ["(|O) (•••O) || •••", "makuil poual uan eypoual uan mahtlak uan eyi"],
	172: ["(|O) (•••O) || ••", "makuil poual uan eypoual uan mahtlak uan ome"],
	171: ["(|O) (•••O) || •", "makuil poual uan eypoual uan mahtlak uan ze"],
	170: ["(|O) (•••O) ||", "makuil poual uan eypoual uan mahtlak"],
	169: ["(|O) (•••O) |••••", "makuil poual uan eypoual uan chiknaui"],
	168: ["(|O) (•••O) |•••", "makuil poual uan eypoual uan chikoeyi"],
	167: ["(|O) (•••O) |••", "makuil poual uan eypoual uan chikome"],
	166: ["(|O) (•••O) |•", "makuil poual uan eypoual uan chikoaze"],
	165: ["(|O) (•••O) |", "makuil poual uan eypoual uan makuil"],
	164: ["(|O) (•••O) ••••", "makuil poual uan eypoual uan naui"],
	163: ["(|O) (•••O) •••", "makuil poual uan eypoual uan eyi"],
	162: ["(|O) (•••O) ••", "makuil poual uan eypoual uan ome"],
	161: ["(|O) (•••O) •", "makuil poual uan eypoual uan ze"],
	160: ["(|O) (•••O) ||", "makuil poual uan eypoual uan mahtlak"],
	159: ["(|O) (••O) ||| ••••", "makuil poual uan ompoual uan kaxtol uan naui"],
	158: ["(|O) (••O) ||| •••", "makuil poual uan ompoual uan kaxtol uan eyi"],
	157: ["(|O) (••O) ||| ••", "makuil poual uan ompoual uan kaxtol uan ome"],
	156: ["(|O) (••O) ||| •", "makuil poual uan ompoual uan kaxtol uan ze"],
	155: ["(|O) (••O) |||", "makuil poual uan ompoual uan kaxtol"],
	154: ["(|O) (••O) || ••••", "makuil poual uan ompoual uan mahtlak uan naui"],
	153: ["(|O) (••O) || •••", "makuil poual uan ompoual uan mahtlak uan eyi"],
	152: ["(|O) (••O) || ••", "makuil poual uan ompoual uan mahtlak uan ome"],
	151: ["(|O) (••O) || •", "makuil poual uan ompoual uan mahtlak uan ze"],
	150: ["(|O) (••O) ||", "makuil poual uan ompoual uan mahtlak"],
	149: ["(|O) (••O) |••••", "makuil poual uan ompoual uan chiknaui"],
	148: ["(|O) (••O) |•••", "makuil poual uan ompoual uan chikoeyi"],
	147: ["(|O) (••O) |••", "makuil poual uan ompoual uan chikome"],
	146: ["(|O) (••O) |•", "makuil poual uan ompoual uan chikoaze"],
	145: ["(|O) (••O) |", "makuil poual uan ompoual uan makuil"],
	144: ["(|O) (••O) ••••", "makuil poual uan ompoual uan naui"],
	143: ["(|O) (••O) •••", "makuil poual uan ompoual uan eyi"],
	142: ["(|O) (••O) ••", "makuil poual uan ompoual uan ome"],
	141: ["(|O) (••O) •", "makuil poual uan ompoual uan ze"],
	140: ["(|O) ••O", "makuil poual uan ompoual"],
	139: ["(|O) (O) ||| ••••", "makuil poual uan zempoual uan kaxtol uan naui"],
	138: ["(|O) (O) ||| •••", "makuil poual uan zempoual uan kaxtol uan eyi"],
	137: ["(|O) (O) ||| ••", "makuil poual uan zempoual uan kaxtol uan ome"],
	136: ["(|O) (O) ||| •", "makuil poual uan zempoual uan kaxtol uan ze"],
	135: ["(|O) (O) |||", "makuil poual uan zempoual uan kaxtol"],
	134: ["(|O) (O) || ••••", "makuil poual uan zempoual uan mahtlak uan naui"],
	133: ["(|O) (O) || •••", "makuil poual uan zempoual uan mahtlak uan eyi"],
	132: ["(|O) (O) || ••", "makuil poual uan zempoual uan mahtlak uan ome"],
	131: ["(|O) (O) || •", "makuil poual uan zempoual uan mahtlak uan ze"],
	130: ["(|O) (O) ||", "makuil poual uan zempoual uan mahtlak"],
	129: ["(|O) (O) |••••", "makuil poual uan zempoual uan chiknaui"],
	128: ["(|O) (O) |•••", "makuil poual uan zempoual uan chikoeyi"],
	127: ["(|O) (O) |••", "makuil poual uan zempoual uan chikome"],
	126: ["(|O) (O) |•", "makuil poual uan zempoual uan chikoaze"],
	125: ["(|O) (O) |", "makuil poual uan zempoual uan makuil"],
	124: ["(|O) (O) ••••", "makuil poual uan zempoual uan naui"],
	123: ["(|O) (O) •••", "makuil poual uan zempoual uan eyi"],
	122: ["(|O) (O) ••", "makuil poual uan zempoual uan ome"],
	121: ["(|O) (O) •", "makuil poual uan zempoual uan ze"],
	120: ["(|O) •O", "makuil poual uan zempoual"],
	119: ["(|O) ||| ••••", "makuil poual uan kaxtol uan naui"],
	118: ["(|O) ||| •••", "makuil poual uan kaxtol uan eyi"],
	117: ["(|O) ||| ••", "makuil poual uan kaxtol uan ome"],
	116: ["(|O) ||| •", "makuil poual uan kaxtol uan ze"],
	115: ["(|O) |||", "makuil poual uan kaxtol"],
	114: ["(|O) || ••••", "makuil poual uan mahtlak uan naui"],
	113: ["(|O) || •••", "makuil poual uan mahtlak uan eyi"],
	112: ["(|O) || ••", "makuil poual uan mahtlak uan ome"],
	111: ["(|O) || •", "makuil poual uan mahtlak uan ze"],
	110: ["(|O) ||", "makuil poual uan mahtlak"],
	109: ["(|O) |••••", "makuil poual uan chiknaui"],
	108: ["(|O) |•••", "makuil poual uan chikoeyi"],
	107: ["(|O) |••", "makuil poual uan chikome"],
	106: ["(|O) |•", "makuil poual uan chikoaze"],
	105: ["(|O) |", "makuil poual uan makuil"],
	104: ["(|O) ••••", "makuil poual uan naui"],
	103: ["(|O) •••", "makuil poual uan eyi"],
	102: ["(|O) ••", "makuil poual uan ome"],
	101: ["(|O) •", "makuil poual uan ze"],
	100: ["(|O)", "makuil poual"],
	99: ["(••••O) ||| ••••", "naupoual uan kaxtol uan naui"],
	98: ["(••••O) ||| •••", "naupoual uan kaxtol uan eyi"],
	97: ["(••••O) ||| ••", "naupoual uan kaxtol uan ome"],
	96: ["(••••O) ||| •", "naupoual uan kaxtol uan ze"],
	95: ["(••••O) |||", "naupoual uan kaxtol"],
	94: ["(••••O) || ••••", "naupoual uan mahtlak uan naui"],
	93: ["(••••O) || •••", "naupoual uan mahtlak uan eyi"],
	92: ["(••••O) || ••", "naupoual uan mahtlak uan ome"],
	91: ["(••••O) || •", "naupoual uan mahtlak uan ze"],
	90: ["(••••O) ||", "naupoual uan mahtlak"],
	89: ["(••••O) |••••", "naupoual uan chiknaui"],
	88: ["(••••O) |•••", "naupoual uan chikoeyi"],
	87: ["(••••O) |••", "naupoual uan chikome"],
	86: ["(••••O) |•", "naupoual uan chikoaze"],
	85: ["(••••O) |", "naupoual uan makuil"],
	84: ["(••••O) ••••", "naupoual uan naui"],
	83: ["(••••O) •••", "naupoual uan eyi"],
	82: ["(••••O) ••", "naupoual uan ome"],
	81: ["(••••O) •", "naupoual uan ze"],
	80: ["(••••O)", "naupoual"],
	79: ["(|||O) ||| ••••", "kaxtol poual uan kaxtol uan naui"],
	78: ["(|||O) ||| •••", "kaxtol poual uan kaxtol uan eyi"],
	77: ["(|||O) ||| ••", "kaxtol poual uan kaxtol uan ome"],
	76: ["(|||O) ||| •", "kaxtol poual uan kaxtol uan ze"],
	75: ["(|||O) |||", "kaxtol poual uan kaxtol"],
	74: ["(|||O) || ••••", "kaxtol poual uan mahtlak uan naui"],
	73: ["(|||O) || •••", "kaxtol poual uan mahtlak uan eyi"],
	72: ["(|||O) || ••", "kaxtol poual uan mahtlak uan ome"],
	71: ["(|||O) || •", "kaxtol poual uan mahtlak uan ze"],
	70: ["(|||O) ||", "kaxtol poual uan mahtlak"],
	69: ["(|||O) |••••", "kaxtol poual uan chiknaui"],
	68: ["(|||O) |•••", "kaxtol poual uan chikoeyi"],
	67: ["(|||O) |••", "kaxtol poual uan chikome"],
	66: ["(|||O) |•", "kaxtol poual uan chikoaze"],
	65: ["(|||O) |", "kaxtol poual uan makuil"],
	64: ["(|||O) ••••", "kaxtol poual uan naui"],
	63: ["(|||O) •••", "kaxtol poual uan eyi"],
	62: ["(|||O) ••", "kaxtol poual uan ome"],
	61: ["(|||O) •", "kaxtol poual uan ze"],
	60: ["(|||O)", "kaxtol poual"],
	59: ["(••O) ||| ••••", "ompoual uan kaxtol uan naui"],
	58: ["(••O) ||| •••", "ompoual uan kaxtol uan eyi"],
	57: ["(••O) ||| ••", "ompoual uan kaxtol uan ome"],
	56: ["(••O) ||| •", "ompoual uan kaxtol uan ze"],
	55: ["(••O) |||", "ompoual uan kaxtol"],
	54: ["(••O) || ••••", "ompoual uan mahtlak uan naui"],
	53: ["(••O) || •••", "ompoual uan mahtlak uan eyi"],
	52: ["(••O) || ••", "ompoual uan mahtlak uan ome"],
	51: ["(••O) || •", "ompoual uan mahtlak uan ze"],
	50: ["(••O) ||", "ompoual uan mahtlak"],
	49: ["(••O) |••••", "ompoual uan chiknaui"],
	48: ["(••O) |•••", "ompoual uan chikoeyi"],
	47: ["(••O) |••", "ompoual uan chikome"],
	46: ["(••O) |•", "ompoual uan chikoaze"],
	45: ["(••O) |", "ompoual uan makuil"],
	44: ["(••O) ••••", "ompoual uan naui"],
	43: ["(••O) •••", "ompoual uan eyi"],
	42: ["(••O) ••", "ompoual uan ome"],
	41: ["(••O) •", "ompoual uan ze"],
	40: ["(••O)", "ompoual"],
	39: ["O ||| ••••", "zempoual uan kaxtol uan naui"],
	38: ["O ||| •••", "zempoual uan kaxtol uan eyi"],
	37: ["O ||| ••", "zempoual uan kaxtol uan ome"],
	36: ["O ||| •", "zempoual uan kaxtol uan ze"],
	35: ["O |||", "zempoual uan kaxtol"],
	34: ["O || ••••", "zempoual uan mahtlak uan naui"],
	33: ["O || •••", "zempoual uan mahtlak uan eyi"],
	32: ["O || ••", "zempoual uan mahtlak uan ome"],
	31: ["O || •", "zempoual uan mahtlak uan ze"],
	30: ["O ||", "zempoual uan mahtlak"],
	29: ["O |••••", "zempoual uan chiknaui"],
	28: ["O |•••", "zempoual uan chikoeyi"],
	27: ["O |••", "zempoual uan chikome"],
	26: ["O |•", "zempoual uan chikoaze"],
	25: ["O |", "zempoual uan makuil"],
	24: ["O ••••", "zempoual uan naui"],
	23: ["O •••", "zempoual uan eyi"],
	22: ["O ••", "zempoual uan ome"],
	21: ["O •", "zempoual uan ze"],
	20: ["O", "zempoual"],
	19: ["||| ••••", "kaxtol uan naui"],
	18: ["||| •••", "kaxtol uan eyi"],
	17: ["||| ••", "kaxtol uan ome"],
	16: ["||| •", "kaxtol uan ze"],
	15: ["|||", "kaxtol"],
	14: ["|| ••••", "mahtlak uan naui"],
	13: ["|| •••", "mahtlak uan eyi"],
	12: ["|| ••", "mahtlak uan ome"],
	11: ["|| •", "mahtlak uan ze"],
	10: ["||", "mahtlak"],
	9: ["|••••", "chiknaui"],
	8: ["|•••", "chikoeyi"],
	7: ["|••", "chikome"],
	6: ["|•", "chikoaze"],
	5: ["|", "mahkuil"],
	4: ["••••", "naui"],
	3: ["•••", "eyi"],
	2: ["••", "ome"],
	1: ["•", "ze"],
	0: ["nemankan", "nemankan"],
}

def descomponer_numero(numero):
	if numero in numeros:
		nombre, *texto_adicional = numeros[numero]
		return nombre, " ".join(texto_adicional)
	else:
		return "Número fuera de rango", ""

def iniciar_interfaz():
	import tkinter as tk

	frame = tk.Tk()
	frame.title("pOual tOkaitl")

	try:
		frame.iconbitmap("Opoch_tlAhtol_64px.ico")
	except Exception:
		pass

	frame.config(bg="beige")
	frame.config(bd="25")
	frame.config(relief="sunken")
	frame.config(
		bd=25,
		relief="sunken",
		highlightthickness=3,
		highlightbackground="green",
		highlightcolor="light blue",
	)

	etiqueta = tk.Label(frame, text="Ingrese un número:")
	etiqueta.pack()

	entrada = tk.Entry(frame)
	entrada.pack()

	resultado = tk.Label(frame, text="")
	resultado.pack()

	texto_adicional_label = tk.Label(frame, text="")
	texto_adicional_label.pack()

	def generar_respuesta_gui():
		numero_str = entrada.get()
		try:
			numero = int(numero_str)
			respuesta, texto_adicional = descomponer_numero(numero)
			resultado.config(text=respuesta)
			texto_adicional_label.config(text=texto_adicional)
		except ValueError:
			resultado.config(text="Error: Ingrese solo números enteros.")

	boton = tk.Button(
		frame,
		text="Generar Respuesta",
		command=generar_respuesta_gui,
	)
	boton.pack()

	frame.mainloop()


if __name__ == "__main__":
	iniciar_interfaz()
