# PROFESIONES Y OFICIOS:

# Agricultura, ganadería y actividades rurales:
	"agricultor":'tlaltekitikatl',
	"agricultora":'tlaltekitikatl',
	"campesino":'tlaltekititekatl',
	"campesina":'tlaltekititekatl',
	"labrador":'tekitikatl',
	"labradora":'tekitikatl',
	"jornalero":'tekitikatl',
	"jornalera":'tekitikatl',
	"horticultor":'',
	"horticultora":'',
	"floricultor":'xochitekikatl',
	"floricultora":'xochitekikatl',
	"fruticultor":'',
	"fruticultora":'',
	"viticultor":'',
	"viticultora":'',
	"apicultor":'',
	"apicultora":'',
	"ganadero":'yolkatekitikatl',
	"ganadera":'yolkatikitikatl',
	"pastor":'zakatekitikatl',
	"pastora":'zakatekitikatl',
	"vaquero":'kuenmazakatl',
	"vaquera":'kuenmazakatl',
	"caballerango":'tzonmazatekatl',
	"criador":'kuitlauitekatl',
	"criadora":'kuitlauitekatl',
	"ordeñador":'chichitilanakatl',
	"ordeñadora":'chichitlanakatl',
	"silvicultor":'',
	"silvicultora":'',
	"leñador":'kuaikatl',
	"leñadora":'kuauikatl',

Construcción y obra:
	"albañil":'kalchiuatekatl',
	"maestro de obra":'kalchiuakatl temachtiki',
	"peón":'',
	"constructor":'chichiuatekatl',
	"constructora":'chichiuatekatl',
	"arquitecto":'kalchiuatekatl',
	"arquitecta":'kalchiuatekatl',
	"ingeniero civil":'tlalnamikikatl',
	"ingeniera civil":'tlalnamikikatl',
	"topógrafo":'tlalmachiyokatl',
	"topógrafa":'tlalmachiyokatl',
	"urbanista":'altepekatl',
	"yesero":'tizakatl',
	"yesera":'tizakatl',
	"tablarroquero":'tetlapechkatl',
	"tablarroquera":'tetlapechkatl',
	"pintor":'tlakuilolkatl',
	"pintora":'tlakuilolkatl',
	"electricista":'tlauelkatl',
	"plomero":'kalmelkokatl',
	"plomera":'kalmelkokatl',
	"fontanero":'kalmelkokatl',
	"fontanera":'kalmelkokatl',
	"soldador":'zentilikatl',
	"soldadora":'zentilikatl',
	"herrero":'tepozkatl',
	"herrera":'tepozkatl',
	"carpintero":'kuaukatl',
	"carpintera":'kuaukatl',
	"ebanista":'kuaukatl',
	"vidriero":'teuilokatl',
	"vidriera":'teuilokatl',
	"cerrajero":'tzaaztli',
	"cerrajera":'tzaaztli',
	"techador":'tlapankatl',
	"techadora":'tlapankatl',
	"cantero":'',
	"cantera":'',
	"marmolista":'',
	"instalador":'tlaliakatl',
	"instaladora":'tlaliakatl',

Artesanías y manufactura:
	"artesano":'toltekatl',
	"artesana":'toltekatl',
	"alfarero":'',
	"alfarera":'',
	"ceramista":'',
	"tejedor":'temalakatl',
	"tejedora":'temalakatl',
	"bordador":'temekauakatl',
	"bordadora":'temekauakatl',
	"costurero":'temekauakatl',
	"costurera":'temekauakatl',
	"sastre":'',
	"modista":'',
	"zapatero":'',
	"zapatera":'',
	"talabartero":'',
	"talabartera":'',
	"curtidor":'',
	"curtidora":'',
	"joyero":'',
	"joyera":'',
	"orfebre":'',
	"platero":'',
	"platera":'',
	"grabador":'',
	"grabadora":'',
	"tallador":'',
	"talladora":'',
	"escultor":'',
	"escultora":'',
	"tornero":'',
	"tornera":'',
	"fundidor":'',
	"fundidora":'',
	"forjador":'',
	"forjadora":'',
	"ensamblador":'',
	"ensambladora":'',

# Industria y producción:
	"obrero":'',
	"obrera":'',
	"trabajador":'',
	"trabajadora":'',
	"operador":'',
	"operadora":'',
	"maquinista":'',
	"ensamblador":'',
	"ensambladora":'',
	"empacador":'',
	"empacadora":'',
	"envasador":'',
	"envasadora":'',
	"almacenista":'',
	"montacarguista":'',
	"supervisor":'',
	"supervisora":'',
	"inspector":'',
	"inspectora":'',
	"técnico industrial":'',
	"técnica industrial":'',
	"mecánico industrial":'',
	"mecánica industrial":'',
	"matricero":'',
	"matricera":'',
	"fresador":'',
	"fresadora":'',
	"soldador":'',
	"soldadora":'',

# Mecánica y transporte:
	"mecánico":'',
	"mecánica":'',
	"electromecánico":'',
	"electromecánica":'',
	"hojalatero":'',
	"hojalatera":'',
	"vulcanizador":'',
	"vulcanizadora":'',
	"conductor":'',
	"conductora":'',
	"chofer":'',
	"taxista":'',
	"camionero":'',
	"camionera":'',
	"trailero":'',
	"trailera":'',
	"motociclista":'',
	"ciclista":'',
	"repartidor":'',
	"repartidora":'',
	"mensajero":'',
	"mensajera":'',
	"piloto":'',
	"copiloto":'',
	"aviador":'',
	"aviadora":'',
	"sobrecargo":'',
	"marinero":'',
	"marinera":'',
	"capitán":'',
	"capitana":'',
	"ferroviario":'',
	"ferroviaria":'',
	"despachador":'',
	"despachadora":'',

# Comercio y ventas:
	"comerciante":'',
	"vendedor":'',
	"vendedora":'',
	"comprador":'',
	"compradora":'',
	"cajero":'',
	"cajera":'',
	"dependiente":'',
	"dependienta":'',
	"tendero":'',
	"tendera":'',
	"abarrotero":'',
	"abarrotera":'',
	"carnicero":'',
	"carnicera":'',
	"panadero":'',
	"panadera":'',
	"frutero":'',
	"frutera":'',
	"florista":'',
	"joyero":'',
	"joyera":'',
	"agente de ventas":'',
	"representante comercial":'',
	"promotor":'',
	"promotora":'',
	"corredor":'',
	"corredora":'',
	"subastador":'',
	"subastadora":'',

# Alimentos y gastronomía:
	"cocinera":'',
	"cocinero":'',
	"chef":'',
	"panadero":'',
	"panadera":'',
	"pastelero":'',
	"pastelera":'',
	"repostero":'',
	"repostera":'',
	"tortillero":'',
	"tortillera":'',
	"carnicero":'',
	"carnicera":'',
	"pescadero":'',
	"pescadera":'',
	"mesero":'',
	"mesera":'',
	"camarero":'',
	"camarera":'',
	"cantinero":'',
	"cantinera":'',
	"barista":'',
	"sommelier":'',
	"catador":'',
	"catadora":'',
	"chocolatero":'',
	"chocolatera":'',
	"quesero":'',
	"quesera":'',
	"molinero":'',
	"molinera":'',

# Salud:
	"médico":'',
	"médica":'',
	"doctor":'',
	"doctora":'',
	"cirujano":'',
	"cirujana":'',
	"enfermero":'',
	"enfermera":'',
	"dentista":'',
	"odontólogo":'',
	"odontóloga":'',
	"pediatra":'',
	"ginecólogo":'',
	"ginecóloga":'',
	"cardiólogo":'',
	"cardióloga":'',
	"dermatólogo":'',
	"dermatóloga":'',
	"oftalmólogo":'',
	"oftalmóloga":'',
	"optometrista":'',
	"anestesiólogo":'',
	"anestesióloga":'',
	"radiólogo":'',
	"radióloga":'',
	"psiquiatra":'',
	"psicólogo":'',
	"psicóloga":'',
	"terapeuta":'',
	"fisioterapeuta":'',
	"nutriólogo":'',
	"nutrióloga":'',
	"paramédico":'',
	"paramédica":'',
	"farmacéutico":'',
	"farmacéutica":'',
	"laboratorista":'',
	"epidemiólogo":'',
	"epidemióloga":'',
	"veterinario":'',
	"veterinaria":'',

# Ciencias:
	"científico":'',
	"científica":'',
	"investigador":'',
	"investigadora":'',
	"biólogo":'',
	"bióloga":'',
	"químico":'',
	"química":'',
	"físico":'',
	"física":'',
	"matemático":'',
	"matemática":'',
	"astrónomo":'',
	"astrónoma":'',
	"geólogo":'',
	"geóloga":'',
	"geógrafo":'',
	"geógrafa":'',
	"arqueólogo":'',
	"arqueóloga":'',
	"antropólogo":'',
	"antropóloga":'',
	"paleontólogo":'',
	"paleontóloga":'',
	"ecólogo":'',
	"ecóloga":'',
	"botánico":'',
	"botánica":'',
	"zoólogo":'',
	"zoóloga":'',
	"genetista":'',
	"microbiólogo":'',
	"microbióloga":'',
	"oceanógrafo":'',
	"oceanógrafa":'',
	"meteorólogo":'',
	"meteoróloga":'',

# Ingeniería y tecnología:
	"ingeniero":'',
	"ingeniera":'',
	"ingeniero mecánico":'',
	"ingeniera mecánica":'',
	"ingeniero eléctrico":'',
	"ingeniera eléctrica":'',
	"ingeniero electrónico":'',
	"ingeniera electrónica":'',
	"ingeniero químico":'',
	"ingeniera química":'',
	"ingeniero industrial":'',
	"ingeniera industrial":'',
	"ingeniero ambiental":'',
	"ingeniera ambiental":'',
	"ingeniero aeroespacial":'',
	"ingeniera aeroespacial":'',
	"ingeniero de software":'',
	"ingeniera de software":'',
	"programador":'',
	"programadora":'',
	"desarrollador":'',
	"desarrolladora":'',
	"analista de sistemas":'',
	"administrador de sistemas":'',
	"administradora de sistemas":'',
	"técnico":'',
	"técnica":'',
	"informático":'',
	"informática":'',
	"especialista en ciberseguridad":'',
	"administrador de redes":'',
	"administradora de redes":'',
	"científico de datos":'',
	"científica de datos":'',

# Educación:
	"maestro":'',
	"maestra":'',
	"profesor":'',
	"profesora":'',
	"docente":'',
	"educador":'',
	"educadora":'',
	"pedagogo":'',
	"pedagoga":'',
	"instructor":'',
	"instructora":'',
	"capacitador":'',
	"capacitadora":'',
	"tutor":'',
	"tutora":'',
	"orientador":'',
	"orientadora":'',
	"director escolar":'',
	"directora escolar":'',
	"bibliotecario":'',
	"bibliotecaria":'',
	"investigador":'',
	"investigadora":'',

# Lenguas y comunicación:
	"lingüista":'',
	"gramático":'',
	"gramática":'',
	"traductor":'',
	"traductora":'',
	"intérprete":'',
	"lexicógrafo":'',
	"lexicógrafa":'',
	"filólogo":'',
	"filóloga":'',
	"escritor":'',
	"escritora":'',
	"redactor":'',
	"redactora":'',
	"corrector":'',
	"correctora":'',
	"editor":'',
	"editora":'',
	"periodista":'',
	"reportero":'',
	"reportera":'',
	"corresponsal":'',
	"locutor":'',
	"locutora":'',
	"comunicador":'',
	"comunicadora":'',
	"presentador":'',
	"presentadora":'',

# Artes visuales y diseño:
	"artista":'',
	"pintor":'',
	"pintora":'',
	"dibujante":'',
	"ilustrador":'',
	"ilustradora":'',
	"diseñador":'',
	"diseñadora":'',
	"diseñador gráfico":'',
	"diseñadora gráfica":'',
	"diseñador industrial":'',
	"diseñadora industrial":'',
	"diseñador de modas":'',
	"diseñadora de modas":'',
	"fotógrafo":'',
	"fotógrafa":'',
	"camarógrafo":'',
	"camarógrafa":'',
	"escultor":'',
	"escultora":'',
	"muralista":'',
	"grabador":'',
	"grabadora":'',
	"animador":'',
	"animadora":'',
	"modelador":'',
	"modeladora":'',

# Música y artes escénicas:
	"músico":'',
	"música":'',
	"cantante":'',
	"compositor":'',
	"compositora":'',
	"intérprete":'',
	"guitarrista":'',
	"pianista":'',
	"violinista":'',
	"baterista":'',
	"trompetista":'',
	"flautista":'',
	"director de orquesta":'',
	"directora de orquesta":'',
	"actor":'',
	"actriz":'',
	"bailarín":'',
	"bailarina":'',
	"coreógrafo":'',
	"coreógrafa":'',
	"dramaturgo":'',
	"dramaturga":'',
	"escenógrafo":'',
	"escenógrafa":'',
	"productor":'',
	"productora":'',

# Cine, radio y televisión:
	"cineasta":'',
	"director":'',
	"directora":'',
	"productor":'',
	"productora":'',
	"guionista":'',
	"camarógrafo":'',
	"camarógrafa":'',
	"sonidista":'',
	"iluminador":'',
	"iluminadora":'',
	"editor de video":'',
	"editora de video":'',
	"montajista":'',
	"maquillista":'',
	"vestuarista":'',
	"conductor":'',
	"conductora":'',
	"locutor":'',
	"locutora":'',
	"fotógrafo":'',
	"fotógrafa":'',

# Administración, contabilidad y finanzas:
	"administrador":'',
	"administradora":'',
	"contador":'',
	"contadora":'',
	"economista":'',
	"actuario":'',
	"actuaria":'',
	"auditor":'',
	"auditora":'',
	"tesorero":'',
	"tesorera":'',
	"banquero":'',
	"banquera":'',
	"cajero":'',
	"cajera":'',
	"asesor financiero":'',
	"asesora financiera":'',
	"analista financiero":'',
	"analista contable":'',
	"ejecutivo":'',
	"ejecutiva":'',
	"gerente":'',
	"secretaria":'',
	"secretario":'',
	"recepcionista":'',
	"archivista":'',

# Derecho y justicia:
	"abogado":'',
	"abogada":'',
	"jurista":'',
	"juez":'',
	"jueza":'',
	"magistrado":'',
	"magistrada":'',
	"fiscal":'',
	"defensor":'',
	"defensora":'',
	"notario":'',
	"notaria":'',
	"procurador":'',
	"procuradora":'',
	"perito":'',
	"criminólogo":'',
	"criminóloga":'',
	"criminalista":'',
	"mediador":'',
	"mediadora":'',

# Servicios y mantenimiento:
	"limpiador":'',
	"limpiadora":'',
	"intendente":'',
	"conserje":'',
	"jardinero":'',
	"jardinera":'',
	"podador":'',
	"podadora":'',
	"fumigador":'',
	"fumigadora":'',
	"cuidador":'',
	"cuidadora":'',
	"velador":'',
	"vigilante":'',
	"guardia":'',
	"portero":'',
	"portera":'',
	"lavandero":'',
	"lavandera":'',
	"tintorero":'',
	"tintorera":'',
	"peluquero":'',
	"peluquera":'',
	"barbero":'',
	"estilista":'',
	"maquillista":'',
	"manicurista":'',

# Emergencias y protección civil:
	"bombero":'',
	"bombera":'',
	"paramédico":'',
	"paramédica":'',
	"rescatista":'',
	"socorrista":'',
	"salvavidas":'',
	"brigadista":'',
	"operador de emergencias":'',
	"operadora de emergencias":'',
# Turismo y hospedaje:
	"guía":'',
	"guía turístico":'',
	"guía turística":'',
	"agente de viajes":'',
	"recepcionista":'',
	"hotelero":'',
	"hotelera":'',
	"botones":'',
	"camarista":'',
	"concierge":'',
	"animador turístico":'',
	"animadora turística":'',

# Medio ambiente:
	"ambientalista":'',
	"ecólogo":'',
	"ecóloga":'',
	"guardabosques":'',
	"viverista":'',
	"arborista":'',
	"reciclador":'',
	"recicladora":'',
	"recolector":'',
	"recolectora":'',
	"conservacionista":'',
	"inspector ambiental":'',
	"inspectora ambiental":'',

# Deportes:
	"deportista":'',
	"atleta":'',
	"futbolista":'',
	"basquetbolista":'',
	"beisbolista":'',
	"boxeador":'',
	"boxeadora":'',
	"luchador":'',
	"luchadora":'',
	"nadador":'',
	"nadadora":'',
	"corredor":'',
	"corredora":'',
	"entrenador":'',
	"entrenadora":'',
	"árbitro":'',
	"árbitra":'',
	"preparador físico":'',
	"preparadora física":'',

# Trabajo intelectual y social:
	"historiador":'',
	"historiadora":'',
	"sociólogo":'',
	"socióloga":'',
	"filósofo":'',
	"filósofa":'',
	"politólogo":'',
	"politóloga":'',
	"demógrafo":'',
	"demógrafa":'',
	"trabajador social":'',
	"trabajadora social":'',
	"archivista":'',
	"museógrafo":'',
	"museógrafa":'',
	"curador":'',
	"curadora":'',
	"restaurador":'',
	"restauradora":'',

# Ocupaciones digitales contemporáneas:
	"desarrollador web":'',
	"desarrolladora web":'',
	"desarrollador móvil":'',
	"desarrolladora móvil":'',
	"diseñador web":'',
	"diseñadora web":'',
	"administrador web":'',
	"administradora web":'',
	"creador de contenido":'',
	"creadora de contenido":'',
	"editor digital":'',
	"editora digital":'',
	"diseñador de videojuegos":'',
	"diseñadora de videojuegos":'',
	"desarrollador de videojuegos":'',
	"desarrolladora de videojuegos":'',
	"administrador de bases de datos":'',
	"administradora de bases de datos":'',
	"analista de datos":'',
	"científico de datos":'',
	"científica de datos":'',
	"especialista en inteligencia artificial":'',
	"ingeniero de inteligencia artificial":'',
	"ingeniera de inteligencia artificial":'',