# PROFESIONES Y OFICIOS:

# Agricultura, ganadería y actividades rurales:
	"agricultor":'tekontlalkatl',
	"agricultora":'tekontlalkatl',
	"campesino":'tlaltekitikatl',
	"campesina":'tlaltekitikatl',
	"labrador":'tekitikatl',
	"labradora":'tekitikatl',
	"jornalero":'tekitikatl',
	"jornalera":'tekitikatl',
	"horticultor":'tlaltekikatl',
	"horticultora":'tlaltekikatl',
	"floricultor":'xochitekatl',
	"floricultora":'xochitekatl',
	"fruticultor":'tzapokatl',
	"fruticultora":'tzapokatl',
	"viticultor":'tlaltekitikatl',
	"viticultora":'tlaltekitikatl',
	"apicultor":'chipankatl',
	"apicultora":'chipankatl',
	"abejero":'chipantekatl',
	"abejera":'chipantekatl',
	"ganadero":'yolkatekatl',
	"ganadera":'yolkatekatl',
	"pastor":'zakatekitikatl',
	"pastora":'zakatekitikatl',
	"vaquero":'kuenyoltekatl',
	"vaquera":'kuenyoltekatl',
	"caballerango":'tzonmazatekatl',
	"criador":'kuitlauitekatl',
	"criadora":'kuitlauitekatl',
	"ordeñador":'chichitilanakatl',
	"ordeñadora":'chichitlanakatl',
	"silvicultor":'kuautekatl',
	"silvicultora":'kuautekatl',
	"leñador":'kuaukatl',
	"leñadora":'kuaukatl',

# Construcción y obra:
	"albañil":'kalchiuatekatl',
	"maestro de obra":'kalchiuatekuhtli',
	"peón":'tzintekitikatl',
	"constructor":'chichiuatekatl',
	"constructora":'chichiuatekatl',
	"arquitecto":'kalmachiyotekatl',
	"arquitecta":'kalmachiyotekatl',
	"ingeniero civil":'kaltlalnamikikatl',
	"ingeniera civil":'kaltlalnamikikatl',
	"topógrafo":'tlalmachiyokatl',
	"topógrafa":'tlalmachiyokatl',
	"urbanista":'altepekatl',
	"yesero":'tizakatl',
	"yesera":'tizakatl',
	"tablarroquero":'tetlapechkatl',
	"tablarroquera":'tetlapechkatl',
	"pintor":'tlakuilolkatl',
	"pintora":'tlakuilolkatl',
	"electricista":'tlauelkatl',
	"plomero":'kalmelkokatl',
	"plomera":'kalmelkokatl',
	"fontanero":'kalmelkokatl',
	"fontanera":'kalmelkokatl',
	"soldador":'zentilikatl',
	"soldadora":'zentilikatl',
	"herrera":'tepozkatl',
	"herrero":'tepozkatl',
	"carpintera":'kuaukatl',
	"carpintero":'kuaukatl',
	"ebanista":'kuaukatl',
	"vidriera":'teuilokatl',
	"vidriero":'teuilokatl',
	"cerrajera":'tzaaztli',
	"cerrajero":'tzaaztli',
	"techadora":'tlapankatl',
	"techador":'tlapankatl',
	"cantera":'tenkatl',
	"cantero":'tenkatl',
	"marmolista":'iztaktekatl',
	"instaladora":'tlaliakatl',
	"instalador":'tlaliakatl',

# Artesanías y manufactura:
	"artista":'toltekatl',
	"artesano":'toltekatl',
	"artesana":'toltekatl',
	"alfarera":'zokitekatl',
	"alfarero":'zokitekatl',
	"ceramista":'zokitekatl',
	"tejedora":'temalakatl',
	"tejedor":'temalakatl',
	"bordadora":'temekauakatl',
	"bordador":'temekauakatl',
	"costurera":'temekauakatl',
	"costurero":'temekauakatl',
	"sastre":'kemichiuakatl',
	"modista":'kemichiuakatl',
	"zapatera":'kexkikatl',
	"zapatero":'kexkikatl',
	"talabartera":'kuetlaxkatl',
	"talabartero":'kuetlaxkatl',
	"curtidor":'kuetlaxkatl',
	"curtidora":'kuetlaxkatl',
	"joyera":'petahkatl',
	"joyero":'petahkatl',
	"orfebre":'petahkatl',
	"platera":'petahkatl',
	"platero":'petahkatl',
	"grabadora":'kuenkatl',
	"grabadoro":'kuenkatl',
	"talladora":'kuenkatl',
	"talladoro":'kuenkatl',
	"escultora":'tekitekatl',
	"escultor":'tekitekatl',
	"tornera":'tepoztekikatl',
	"tornero":'tepoztekikatl',
	"fundidora":'tepoztekikatl',
	"fundidor":'tepoztekikatl',
	"forjadora":'tepoztekikatl',
	"forjador":'tepoztekikatl',
	"ensambladora":'uantekatl',
	"ensamblador":'uantekatl',

# Industria y producción:
	"obrera":'tekitikatl',
	"obrero":'tekitikatl',
	"trabajadora":'tekitikatl',
	"trabajador":'tekitikatl',
	"operadora":'kehuitl',
	"operador":'kehuitl',
	"maquinista":'teponaztekatl',
	"ensambladora":'uantekatl',
	"ensamblador":'uantekatl',
	"empacadora":'itakatekatl',
	"empacador":'itakatekatl',
	"envasadora":'itakatekatl',
	"envasador":'itakatekatl',
	"almacenista":'kotekatl',
	"montacarguista":'mamatekatl',
	"supervisora":'kuitlauatekatl',
	"supervisor":'kuitlauatekatl',
	"inspectora":'tlachitekatl',
	"inspector":'tlachitekatl',
	"técnica industrial":'chiuauelkatl',
	"técnico industrial":'chiuauelkatl',
	"mecánica industrial":'tepontekatl',
	"mecánico industrial":'tepontekatl',
	"matricera":'matlatekatl',
	"matricero":'matlatekatl',
	"fresadora":'kuentekatl',
	"fresador":'kuentekatl',
	"soldadora":'uentekatl',
	"soldador":'uentekatl',

# Mecánica y transporte:
	"mecánico":'tepontekatl',
	"mecánica":'tepontekatl',
	"electromecánico":'tlaueltepontekatl',
	"electromecánica":'tlaueltepontekatl',
	"hojalatera":'tepoz-ihuitekatl',
	"hojalatero":'tepoz-ihuitekatl',
	"vulcanizador":'ultlapatekatl',
	"vulcanizadora":'ultlapatekatl',
	"conductora":'tekuitekatl',
	"conductor":'tekuitekatl',
	"chofer":'telolopankatl',
	"taxista":'telolopankatl',
	"camionera":'ueyiktelolopankatl',
	"camionero":'ueyiktelolopankatl',
	"trailero":'ueyiktelolopankatl',
	"trailera":'ueyiktelolopankatl',
	"motociclista":'ometelolopankatl',
	"ciclista":'ometelolopankatl',
	"repartidora":'nepanpatikatl',
	"repartidor":'nepanpatikatl',
	"mensajera":'ipainatekatl',
	"mensajero":'ipainatekatl',
	"piloto":'tekuikatl',
	"copiloto":'tekuikatl',
	"aviadora":'tekuikatl',
	"aviador":'tekuikatl',
	"sobrecargo":'mamatekatl',
	"marinera":'atlantekatl',
	"marinero":'atlantekatl',
	"capitán":'atlantekuikatl',
	"capitana":'atlantekuikatl',
	"ferroviaria":'tepoztekuik',
	"ferroviario":'tepoztekuik',
	"despachadora":'kuitlatekatl',
	"despachador":'kuitlatekatl',

# Comercio y ventas:
	"comerciante":'kouayokatl',
	"vendedora":'kouayokatl',
	"vendedor":'kouayokatl',
	"compradora":'kouayokatl',
	"comprador":'kouayokatl',
	"cajera":'ihtlanikatl',
	"cajero":'ihtlanikatl',
	"dependienta":'tehuikatl',
	"dependiente":'tehuikatl',
	"tendera":'tehuikatl',
	"tendero":'tehuikatl',
	"abarrotera":'tehuikatl',
	"abarrotero":'tehuikatl',
	"carnicera":'nakakatl',
	"carnicero":'nakakatl',
	"panadera":'texkalkatl',
	"panadero":'texkalkatl',
	"frutera":'tzapokatl',
	"frutero":'tzapokatl',
	"florista":'xochikatl',
	"joyera":'petahkatl',
	"joyero":'petahkatl',
	"agente de ventas":'kouayokatl',
	"representante comercial":'kouayokatl',
	"promotora":'achtoolintekatl',
	"promotor":'achtoolintekatl',
	"corredora":'cholotekatl',
	"corredor":'cholotekatl',
	"subastadora":'namiktlakotekatl',
	"subastador":'namiktlakotekatl',

# Alimentos y gastronomía:
	"cocinera":'tizkalko',
	"cocinero":'tizkalko',
	"chef":'tizkalkokatl',
	"panadera":'texkalkatl',
	"panadero":'texkalkatl',
	"pastelera":'texkaltekatl',
	"pastelero":'texkaltekatl',
	"repostera":'texkaltekatl',
	"repostero":'texkaltekatl',
	"tortillera":'tlaxkaltekatl',
	"tortillero":'tlaxkaltekatl',
	"carnicera":'nakatekatl',
	"carnicero":'nakatekatl',
	"pescadora":'michkuitekatl',
	"pescador":'michkuitekatl',
	"mesera":'tlapechkatl',
	"mesero":'tlapechkatl',
	"camarera":'kaltekatl',
	"camarero":'kaltekatl',
	"cantinera":'konitekatl',
	"cantinero":'konitekatl',
	"barista":'konitekatl',
	"sommelier":'konitekatl',
	"catadora":'konitekatl',
	"catador":'konitekatl',
	"chocolatera":'xokotekatl',
	"chocolatero":'xokotekatl',
	"quesera":'kitzolkatl',
	"quesero":'kitzolkatl',
	"molinera":'molinilkatl',
	"molinero":'molinilkatl',

# Salud:
	"médica":'tizitl',
	"médico":'tizitl',
	"doctora":'tlamatepahtiki',
	"doctor":'tlamatepahtiki',
	"cirujana":'tekitlamatepahtiki',
	"cirujano":'tekitlamatepahtiki',
	"enfermera":'paleuitlamatepahtiki',
	"enfermero":'paleuitlamatepahtiki',
	"dentista":'tlantlamatepahtiki',
	"odontóloga":'tlantlamatepahtiki',
	"odontólogo":'tlantlamatepahtiki',
	"pediatra":'piltzintlamatepahtiki',
	"ginecóloga":'maxatepahtiki',
	"ginecólogo":'maxatepahtiki',
	"cardióloga":'yolotepahtiki',
	"cardiólogo":'yolotepahtiki',
	"dermatóloga":'euatepahtiki',
	"dermatólogo":'euatepahtiki',
	"oftalmóloga":'ixtelolotepahtiki',
	"oftalmólogo":'ixtelolotepahtiki',
	"optometrista":'ixtelolotekatl',
	"anestesióloga":'kokolkehtzatekatl',
	"anestesiólogo":'kokolkehtzatekatl',
	"radióloga":'tlauelpahtekatl',
	"radiólogo":'tlauelpahtekatl',
	"psiquiatra":'tlalnamikipahtekatl',
	"psicóloga":'tlalnamitepantiki',
	"psicólogo":'tlalnamitepantiki',
	"terapeuta":'kuitlauitekatl',
	"fisioterapeuta":'kuitlauitekatl',
	"nutrióloga":'tlakuatepantiki',
	"nutriólogo":'tlakuatepantiki',
	"paramédica":'paleuitepanteki',
	"paramédico":'paleuitepanteki',
	"farmacéutica":'paleuitepanteki',
	"farmacéutico":'paleuitepanteki',
	"laboratorista":'aztlauatekatl',
	"epidemióloga":'kokolpahtekatl',
	"epidemiólogo":'kokolpahtekatl',
	"veterinaria":'yolkapahtekatl',
	"veterinario":'yolkapahtekatl',

# Ciencias:
	"científica":'ontlamatikatl',
	"científico":'ontlamatikatl',
	"investigadora":'temomatikatl',
	"investigador":'temomatikatl',
	"bióloga":'nemikatl',
	"biólogo":'nemikatl',
	"química":'tlauhpalatekatl',
	"químico":'tlauhpalatekatl',
	"física":'oltlaiuhyokatl',
	"físico":'oltlaiuhyokatl',
	"matemática":'poualkatl',
	"matemático":'poualkatl',
	"astrónoma":'ilhuikatekatl',
	"astrónomo":'ilhuikatekatl',
	"geóloga":'tlaltikpakatl',
	"geólogo":'tlaltikpakatl',
	"geógrafa":'tlaltikpakatl',
	"geógrafo":'tlaltikpakatl',
	"arqueóloga":'otlapanokatl',
	"arqueólogo":'otlapanokatl',
	"antropóloga":'axkauhtekatl',
	"antropólogo":'axkauhtekatl',
	"paleontóloga":'achtonemtekatl',
	"paleontólogo":'achtonemtekatl',
	"ecóloga":'iuhkizatekatl',
	"ecólogo":'iuhkizatekatl',
	"botánica":'xochtekatl',
	"botánico":'xochtekatl',
	"zoóloga":'yolkatekatl',
	"zoólogo":'yolkatekatl',
	"genetista":'nemzekaniuakatl',
	"microbióloga":'pipilnemtekatl',
	"microbiólogo":'pipilnemtekatl',
	"oceanógrafa":'atlantlakuilokatl',
	"oceanógrafo":'atlantlakuilokatl',
	"meteoróloga":'ehekatekatl',
	"meteorólogo":'ehekatekatl',

# Ingeniería y tecnología:
	"ingeniera":'tlalnamikiztekatl',
	"ingeniero":'tlalnamikiztekatl',
	"ingeniera mecánica":'tepontlalnamikiztekatl',
	"ingeniero mecánico":'tepontlalnamikiztekatl',
	"ingeniera eléctrica":'tlaueltlalnamikiztekatl',
	"ingeniero eléctrico":'tlaueltlalnamikiztekatl',
	"ingeniera electrónica":'tlaueltlalnamikiztekatl',
	"ingeniero electrónico":'tlaueltlalnamikiztekatl',
	"ingeniera química":'tlauelpalatlalnamikiztekatl',
	"ingeniero químico":'tlauelpalatlalnamikiztekatl',
	"ingeniera industrial":'etiktlalnamikiztekatl',
	"ingeniero industrial":'etiktlalnamikiztekatl',
	"ingeniera ambiental":'kizatlalnamikiztekatl',
	"ingeniero ambiental":'kizatlalnamikiztekatl',
	"ingeniera aeroespacial":'ilhuikatlalnamiztekatl',
	"ingeniero aeroespacial":'ilhuikatlalnamiztekatl',
	"ingeniera de software":'tlalnamiztekatl',
	"ingeniero de software":'tlalnamiztekatl',
	"programadora":'nepapantekatl',
	"programador":'nepapantekatl',
	"desarrolladora":'nepapantekatl',
	"desarrollador":'nepapantekatl',
	"analista de sistemas":'tlalnamikiliztekatl',
	"administradora de sistemas":'tlalnamikiliztekatl',
	"administrador de sistemas":'tlalnamikiliztekatl',
	"técnica":'chiuatekititekatl',
	"técnico":'chiuatekititekatl',
	"informática":'machiyotik',
	"informático":'machiyotik',
	"especialista en ciberseguridad":'e-chimaltekatl',
	"administradora de redes":'matlanepanpatikatl',
	"administrador de redes":'matlanepanpatikatl',
	"científica de datos":'machiyotlamatik',
	"científico de datos":'machiyotlamatik',

# Educación:
	"maestra":'temachtiki',
	"maestro":'temachtiki',
	"profesora":'temachtiki',
	"profesor":'temachtiki',
	"docente":'temachtiki',
	"educadora":'temachtiki',
	"educador":'temachtiki',
	"pedagoga":'temachtiki',
	"pedagogo":'temachtiki',
	"instructora":'temachtiki',
	"instructor":'temachtiki',
	"capacitadora":'temachtiki',
	"capacitador":'temachtiki',
	"tutora":'temachtiki',
	"tutor":'temachtiki',
	"orientadora":'temachtiki',
	"orientador":'temachtiki',
	"directora escolar":'temachtitekuhtli',
	"director escolar":'temachtitekuhtli',
	"bibliotecaria":'amoxtekitiki',
	"bibliotecario":'amoxtekitiki',
	"investigadora":'temoaki',
	"investigador":'temoaki',

# Lenguas y comunicación:
	"lingüista":'tlahtolmatikatl',
	"gramática":'tokamatikatl',
	"gramático":'tokamatikatl',
	"traductora":'palatlahtolki',
	"traductor":'palatlahtolki',
	"intérprete":'palatlahtoki',
	"lexicógrafa":'amoxtokamatikatl',
	"lexicógrafo":'amoxtokamatikatl',
	"filóloga":'amoxtemotiki',
	"filólogo":'amoxtemotiki',
	"escritora":'atlantlakuilokatl',
	"escritor":'tlakuilokatl',
	"redactora":'tlakuilochiuaki',
	"redactor":'tlakuilochiuaki',
	"correctora":'melachiuaki',
	"corrector":'melachiuaki',
	"editora":'machiyoolintekatl',
	"editor":'machiyoolintekatl',
	"periodista":'nehnemokzepa',
	"reportera":'chiuanonotzaki',
	"reportero":'chiuanonotzaki',
	"corresponsal":'tlakuitekatl',
	"locutora":'tlahtolki',
	"locutor":'tlahtolki',
	"comunicadora":'tlahtolki',
	"comunicador":'tlahtolki',
	"comunicante":'tlahtltok',
	"presentadora":'ititiki',
	"presentador":'ititiki',

# Artes visuales y diseño:
	"artista":'toltekatl',
	"pintora":'tlakuilolki',
	"pintor":'tlakuilolki',
	"dibujante":'tlakuilolki',
	"ilustradora":'ixkopiki',
	"ilustrador":'ixkopiki',
	"diseñadora":'tlakuilolnamiki',
	"diseñador":'tlakuilolnamiki',
	"diseñadora gráfica":'tlakuilolnamiki',
	"diseñador gráfico":'tlakuilolnamiki',
	"diseñadora industrial":'tlakuilolnamiki',
	"diseñador industrial":'tlakuilolnamiki',
	"diseñadora de modas":'tlakuilolnamiki',
	"diseñador de modas":'tlakuilolnamiki',
	"fotógrafa":'ixiptekatl',
	"fotógrafo":'ixiptekatl',
	"camarógrafa":'ixiptekatl',
	"camarógrafo":'ixiptekatl',
	"escultora":'tetekitekatl',
	"escultor":'tetekitekatl',
	"muralista":'tepamtekatl',
	"grabadora":'momoxkatl',
	"grabador":'momoxkatl',
	"animadora":'pakilizkatl',
	"animador":'pakilizkatl',
	"modeladora":'tetekitekatl',
	"modelador":'tetekitekatl',

# Música y artes escénicas:
	"música":'tzontzonnilizki',
	"músico":'tzontzonnilizki',
	"cantante":'kuikatekatl',
	"compositora":'nepanpatekatl',
	"compositor":'nepanpatekatl',
	"intérprete":'ontlamatitlahtolki',
	"guitarrista":'tzontzonaztekatl',
	"pianista":'tzontzonaztekatl',
	"violinista":'tzontzonaztekatl',
	"baterista":'tzontzonaztekatl',
	"trompetista":'tzontzonaztekatl',
	"flautista":'tlapitzalaztli',
	"directora de orquesta":'tzontzontekuhtli',
	"director de orquesta":'tzontzontekuhtli',
	"actor":'chiuatekatl',
	"actriz":'chiuatekatl',
	"bailarina":'ihtotiki',
	"bailarín":'ihtotiki',
#	"coreógrafa":'',
#	"coreógrafo":'',
#	"dramaturga":'',
#	"dramaturgo":'',
#	"escenógrafa":'',
#	"escenógrafo":'',
#	"productora":'',
#	"productor":'',

# Cine, radio y televisión:
	"cineasta":'ixiptlaoltekatl',
	"directora":'tekuhtli',
	"director":'tekuhtli',
	"productora":'chiuatekatl',
	"productor":'chiuatekatl',
	"guionista":'tekuhtekatl',
	"camarógrafa":'ixiptekatl',
	"camarógrafo":'ixiptekatl',
	"sonidista":'nauatekatl',
	"iluminadora":'tlauelkatl',
	"iluminador":'tlauelkatl',
	"editor de video":'ixiptlaoltekatl',
	"editora de video":'ixiptlaoltekatl',
	"montajista":'kalnepanpatiki',
	"maquillista":'xayaktekatl',
	"vestuarista":'kemitekatl',
	"conductor":'tlakuikatl',
	"conductora":'tlakuikatl',
	"locutor":'tlahtolkatl',
	"locutora":'tlahtolkatl',
	"fotógrafo":'ixiptekatl',
	"fotógrafa":'ixiptekatl',

# Administración, contabilidad y finanzas:
	"administradora":'nepanpatikatl',
	"administrador":'nepanpatikatl',
	"contadora":'poualtekatl',
	"contador":'poualtekatl',
	"economista":'tekontlamatekatl',
	"actuaria":'chiuatekatl',
	"actuario":'chiuatekatl',
	"auditora":'kuitlauitekatl',
	"auditor":'kuitlauitekatl',
	"tesorera":'tekontekatl',
	"tesorero":'tekontekatl',
	"banquera":'tekonkokatl',
	"banquero":'tekonkokatl',
	"cajera":'tekonkaltekatl',
	"cajero":'tekonkaltekatl',
	"asesora financiera":'tekonpaleuikatl',
	"asesor financiero":'tekonpaleuikatl',
	"analista financiero":'tekontlalnamikilizkatl',
	"analista contable":'tekontlalnamikilizkatl',
	"ejecutiva":'tekuhtekatl',
	"ejecutivo":'tekuhtekatl',
	"gerente":'tekuhkatl',
	"secretario":'paleuitekatl',
	"secretaria":'paleuitekatl',
	"recepcionista":'tlakuitekatl',
	"archivista":'amatlatlaualizkatl',

# Derecho y justicia:
	"abogada":'melaktlahtoki',
	"abogado":'melaktlahtoki',
	"jurista":'melauaktekatl',
	"jueza":'tlakpaktekuhtli',
	"juez":'tlakpaktekuhtli',
	"magistrada":'tlakpaktekuhtli',
	"magistrado":'tlakpaktekuhtli',
	"fiscal":'chikiuikatl',
	"defensora":'makixtekuhtli',
	"defensor":'makixtekuhtli',
	"notaria":'tlakuilkatl',
	"notario":'tlakuilkatl',
	"procuradora":'paleuiltiki',
	"procurador":'paleuiltiki',
	"perita":'paleuikatl',
	"perito":'paleuikatl',
	"criminóloga":'ihtlakoltekatl',
	"criminólogo":'ihtlakoltekatl',
	"criminalista":'ihtlakoltekatl',
	"mediadora":'ipaltiki',
	"mediador":'ipaltiki',

# Servicios y mantenimiento:
	"limpiadora":'chipauatekatl',
	"limpiador":'chipauatekatl',
	"intendente":'chipauatekatl',
	"conserje":'kuitlauitekatl',
	"jardinera":'xochtlauakatl',
	"jardinero":'xochtlauakatl',
	"podadora":'zakatekatl',
	"podador":'zakatekatl',
	"fumigadora":'amotlakokokatl',
	"fumigador":'amotlakokokatl',
	"cuidadora":'kuitlauitekatl',
	"cuidador":'kuitlauitekatl',
	"veladora":'youalkuitlauikatl',
	"velador":'youalkuitlauikatl',
	"vigilante":'kuitlauikatl',
	"guardia":'kuitlauikatl',
	"portera":'tzakualoltekatl',
	"portero":'tzakualoltekatl',
	"lavandera":'tlapakatekatl',
	"lavandero":'tlapakatekatl',
	"tintorera":'tlapaltekatl',
	"tintorero":'tlapaltekatl',
	"peluquera":'tzontekontekatl',
	"peluquero":'tzontekontekatl',
	"barbera":'tentzontekatl',
	"barbero":'tentzontekatl',
	"estilista":'tzontekatl',
	"maquillista":'xayaktlapaltekatl',
	"manicurista":'xayaktlapaltekatl',

# Emergencias y protección civil:
	"bombera":'atl mamaztekatl',
	"bombero":'atl mamaztekatl',
	"paramédica":'makixtekatl',
	"paramédico":'makixtekatl',
	"socorrista":'makixtekatl',
	"brigadista":'makixtekatl',
	"operadora de emergencias":'makixtekatl',
	"operador de emergencias":'makixtekatl',
	"rescatista":'makixtekatl',
	"salvavidas":'makixtekatl',

# Turismo y hospedaje:
	"guía":'tekuhkatl',
	"guía turística":'tekuhkatl',
	"guía turístico":'tekuhkatl',
	"recepcionista":'mazeualkuikatl',

#	"agente de viajes":'',
#	"hotelera":'',
#	"hotelero":'',
#	"botones":'',
#	"camarista":'',
#	"concerge":'',

	"animadora":'nemitekatl',
	"animador":'nemitekatl',

# Medio ambiente:
	"ambientalista":'iuhkizaltekatl',
	"ecóloga":'iuhkizaltekatl',
	"ecólogo":'iuhkizaltekatl',
	"guardabosques":'kuaumakixtekatl',
	"viverista":'xoxomakixtekatl',
	"arborista":'xoxomakixtekatl',
	"recicladora":'yankuiltekatl',
	"reciclador":'yankuiltekatl',
	"recolectora":'zentiltekatl',
	"recolector":'zentiltekatl',
	"conservacionista":'xoxouatekatl',
	"inspectora ambiental":'iuhkizaliztemotekatl',
	"inspector ambiental":'iuhkizaliztemotekatl',

# Deportes:
	"deporte":'auiltikayotl',
	"deportista":'auiltikayotekatl',
	"atleta":'auiltikayotekatl',
	"futbolista":'auiltikayotekatl',
	"basquetbolista":'auiltikayotekatl',
	"beisbolista":'auiltikayotekatl',
	"boxeadora":'auiltikayotekatl',
	"boxeador":'auiltikayotekatl',
	"luchadora":'auiltikayotekatl',
	"luchador":'auiltikayotekatl',
	"nadadora":'auiltikayotekatl',
	"nadador":'auiltikayotekatl',
	"corredora":'auiltikayotekatl',
	"corredor":'auiltikayotekatl',
	"entrenadora":'auiltikayotekatl',
	"entrenador":'auiltikayotekatl',
	"árbitra":'auiltikayotekatl',
	"árbitro":'auiltikayotekatl',
	"preparadora física":'auiltikayotekatl',
	"preparador físico":'auiltikayotekatl',

# Trabajo intelectual y social:
	"historiadora":'nemyotekatl',
	"historiador":'nemyotekatl',
	"socióloga":'mazeualtekatl',
	"sociólogo":'mazeualtekatl',
	"filósofa":'tlalnamikiltekatl',
	"filósofo":'tlalnamikiltekatl',
	"politóloga":'ixkotlahtoltekatl',
	"politólogo":'ixkotlahtoltekatl',
	"demógrafa":'mazeualpoualtekatl',
	"demógrafo":'mazeualpoualtekatl',
	"trabajadora social":'mazeualtekitikatl',
	"trabajador social":'mazeualtekitikatl',
	"archivista":'amatlauatekatl',
	"museógrafa":'ititikaltlakuiltekatl',
	"museógrafo":'ititikaltlakuiltekatl',
	"curadora":'pahtekatl',
	"curador":'pahtekatl',
	"restauradora":'onchiuatekatl',
	"restaurador":'onchiuatekatl',

# Ocupaciones digitales contemporáneas:
	"desarrolladora web":'web chiuatekatl',
	"desarrollador web":'web chiuatekatl',
	"desarrolladora móvil":'olinikchiuatekatl',
	"desarrollador móvil":'olinikchiuatekatl',
	"diseñadora web":'web chiuatekatl',
	"diseñador web":'web chiuatekatl',
	"administradora web":'web nepanpatekatl',
	"administrador web":'web nepanpatekatl',
	"creadora de contenido":'itekyotl chiuakatl',
	"creador de contenido":'itekyotl chiuakatl',
	"editora digital":'e-olinkatl',
	"editor digital":'e-olinkatl',
	"diseñadora de videojuegos":'ixiptlaolchiuatekatl',
	"diseñador de videojuegos":'ixiptlaolchiuatekatl',
	"desarrolladora de videojuegos":'ixiptlaolchiuatekatl',
	"desarrollador de videojuegos":'ixiptlaolchiuatekatl',
	"administrador de bases de datos":'machiyotlapechtekatl',
	"administradora de bases de datos":'machiyotlapechtekatl',
	"administrador de bases de datos":'machiyonepanpatekatl',
	"analista de datos":'machiyotlalnamikiliztekatl',
	"científica de datos":'machiyomatiliztekatl',
	"científico de datos":'machiyomatiliztekatl',
	"especialista en inteligencia artificial":'AI ontlamatiliztli',
	"ingeniera de inteligencia artificial":'AI ontlamatiliztli',
	"ingeniero de inteligencia artificial":'AI ontlamatiliztli',