tlalkan_SP_NTL = {
	"Acajete":'akaxete',
	"Acapulco de Juárez":'akapulko de juárez',
	"Acateno":'akateno',
	"Acatepec":'akatepek',
	"Acatepec":'akatepek',
	"Acatlán de Pérez Figueroa":'Pérez Figueroa akatlan',
	"Acatlán":'akatlan',
	"Acatzingo":'akatzinko',
	"Acolman":'akolman',
	"Acteopan":'akteopan',
	"Acuamanala de Miguel Hidalgo":'Miguel Hidalgo akuamanala',
	"Aculco":'akulko',
	"Afganistán":'afgankan',
	"Ahuacatlán":'auakatlan',
	"Ahuacuotzingo":'auakuotzinko',
	"Ahuatlán":'auatlan',
	"Ahuazotepec":'auazotepek',
	"Ahuehuetitla":'aueuetitla',
	"Ajalpan":'axalpan',
	"Ajuchitlán del Progreso":'axuchitlan del progreso',
	"Albania":'albaniakan',
	"Albino Zertuche":'Albino Zertuche',
	"Alcozauca de Guerrero":'alkozauka de guerrero',
	"Alemania":'jermanikan',
	"Aljojuca":'alxoxuka',
	"Almoloya":'almoloya',
	"Alpoyeca":'alpoyeka',
	"Altepexi":'altepexi',
	"Amacuzac":'amakuzak',
	"Amanalco":'amanalko',
	"Amatepec":'amatepek',
	"Amaxac de Guerrero":'amaxak de guerrero',
	"Amecameca":'amekameka',
	"Amixtlán":'amixtlan',
	"Amozoc":'amozok',
	"Andorra":'andorrakan',
	"Angola":'angolakan',
	"Antigua y Barbuda":'antigua y barbuda',
	"Apaxco":'apaxko',
	"Apaxtla":'apaxtla',
	"Apetatitlán de Antonio Carvajal":'apetatitlan de Antonio Carvajal',
	"Apizaco":'apizako',
	"Aquixtla":'akixtla',
	"Arabia Saudita":'saudkan',
	"Arcelia":'arcelia',
	"Argelia":'anepantla',
	"Argentina":'argentumkan',
	"Armenia":'armeniakan',
	"Asunción Ixtaltepec":'Asunción ixtaltepek',
	"Asunción Nochixtlán":'Asunción nochixtlan',
	"Asunción Ocotlán":'Asunción okotlan',
	"Asunción Tlacolulita":'Asunción tlakololitla',
	"Atempan":'atempan',
	"Atenango del Río":'atenanko del río',
	"Atenco":'atenko',
	"Atexcal":'atexkal',
	"Atizapán":'atizapan',
	"Atlacomulco":'atlakomulko',
	"Atlamajalcingo del Monte":'atlamaxaltzinko del monte',
	"Atlangatepec":'atlangatepek',
	"Atlatlahucan":'atlatlaukan',
	"Atlautla":'atlautla',
	"Atlequizayan":'atlekizayan',
	"Atlixco":'atlixko',
	"Atlixtac":'atlixtak',
	"Atltzayanca":'atltzayanka',
	"Atoyac de Álvarez":'atoyak de álvarez',
	"Atoyatempan":'atoyatempan',
	"Atzala":'atzala',
	"Atzitzihuacán":'atzitziuakan',
	"Atzitzintla":'atzitzintla',
	"Australia":'uitzilkan',
	"Austria":'tonalkizayan-altepetl',
	"Axapusco":'axapusko',
	"Axochiapan":'axochiapan',
	"Axutla":'axutla',
	"Ayala":'ayala',
	"Ayapango":'ayapanko',
	"Ayotoxco de Guerrero":'yaotekatl ayotoxko',
	"Ayotzintepec":'ayotzintepek',
	"Ayutla de los Libres":'ayutla de los libres',
	"Azerbaiyán":'atropatezkan',
	"Azoyú":'azoyú',
	"Bahamas":'baamakan',
	"Bangladés":'bengalakan',
	"Barbados":'tzontenkouan',
	"Baréin":'omeatlan',
	"Belice":'belicekan',
	"Benito Juárez":'benito juárez',
	"Benito Juárez":'Benito Juárez',
	"Benín":'beninkan',
	"Bielorrusia":'rus-iztakan',
	"Birmania":'bamarkan',
	"Bolivia":'bolivarkan',
	"Bosnia y Herzegovina":'bosniduketlal',
	"Botsuana":'tzuanakan',
	"Brasil":'palobrazilkan',
	"Brunéi":'bruneikan',
	"Buenavista de Cuéllar":'buenavista de cuéllar',
	"Bulgaria":'bulgarokan',
	"Burkina Faso":'integrokan',
	"Burundi":'rundikan',
	"Bután":'butankan',
	"Bélgica":'belgakan',
	"Cabo Verde":'xoxohtikpak',
	"Calimaya":'kalimaya',
	"Calpan":'kalpan',
	"Calpulalpan":'kalpulalpan',
	"Caltepec":'kaltepek',
	"Camboya":'kambukan',
	"Camerún":'chakaatenko',
	"Camocuautla":'kamokuautla',
	"Canadá":'altepetl',
	"Capulhuac":'kapuluak',
	"Capulálpam de Méndez":'De Méndez kapulalpan',
	"Catar":'catarkan',
	"Caxhuacan":'kaxuakan',
	"Cañada Morelos":'cañada morelos',
	"Chad":'ako',
	"Chalchicomula de Sesma":'de Sesma chalchikomula',
	"Chalco":'chalko',
	"Chapulco":'chapulko',
	"Chapultepec":'chapultepek',
	"Chiautempan":'chiautempan',
	"Chiautla":'chiautla',
	"Chiautla":'chiautla',
	"Chiautzingo":'chiautzinko',
	"Chichiquila":'chichikila',
	"Chicoloapan":'chikoloapan',
	"Chiconcuac":'chikonkuak',
	"Chiconcuautla":'chikonkuautla',
	"Chietla":'chietla',
	"Chigmecatitlán":'chihmekatitlan',
	"Chignahuapan":'chihnauapan',
	"Chignautla":'chihnautla',
	"Chila de la Sal":'iztatl chila',
	"Chila":'chila',
	"Chilapa de Álvarez":'chilapa',
	"Chilchotla":'chilchotla',
	"Chile":'chilkan',
	"Chilpancingo de los Bravo":'chilpantzinko',
	"Chimalhuacán":'chimaluakan',
	"China":'kinkan',
	"Chinantla":'chinantla',
	"Chipre":'chiprekan',
	"Chiquihuitlán de Benito Juárez":'chikiuitlan de Benito Juárez',
	"Ciudad del Vaticano":'vaticanaltepetl',
	"Ciudad Ixtepec":'ixtepek altepetl',
	"Coacalco":'koakalko',
	"Coahuayutla de José María Izazaga":'koauayutla de josé María izazaga',
	"Coatecas Altas":'uehkapakoatekatl',
	"Coatepec":'koatepek',
	"Coatepec":'koatepek',
	"Coatetelco":'koatetelko',
	"Coatetelco":'koatetelko',
	"Coatlán del Río":'koatlan del río',
	"Coatzingo":'koatzinko',
	"Cochoapa el Grande":'ueyikkochoapa',
	"Cocotitlán":'kokotitlan',
	"Cocula":'kokula',
	"Cohetzala":'koetzala',
	"Cohuecan":'kouekan',
	"Colombia":'kolonkan',
	"Comoras":'metznepantlan',
	"Contla de Juan Cuamatzi":'kuamatzin kontla de Juan',
	"Copala":'kopala',
	"Copalillo":'kopalillo',
	"Copanatoyac":'kopanatoyak',
	"Corea del Norte":'miktlankuakualtzin',
	"Corea del Sur":'uitzilkuakualtzin',
	"Coronango":'koronanko',
	"Cosolapa":'kozolapa',
	"Cosoltepec":'kozoltepek',
	"Costa de Marfil":'tenomitl',
	"Costa Rica":'tenatlan',
	"Coxcatlán":'koxkatlan',
	"Coyomeapan":'koyomeapan',
	"Coyotepec":'koyotepek',
	"Coyotepec":'koyotepek',
	"Coyuca de Benítez":'koyuka de benítez',
	"Coyuca de Catalán":'koyuka de catalán',
	"Croacia":'kroatakan',
	"Cuajinicuilapa":'kuaxinikuilapa',
	"Cualác":'kualak',
	"Cuapiaxtla de Madero":'kuapiaxtla de Madero',
	"Cuapiaxtla":'kuapiaxtla',
	"Cuautempan":'kuautempan',
	"Cuautepec":'kuautepek',
	"Cuautinchán":'kuautinchan',
	"Cuautitlán Izcalli":'kuautitlan izkalli',
	"Cuautitlán":'kuautitlan',
	"Cuautla":'kuautla',
	"Cuautlancingo":'kuautlantzinko',
	"Cuaxomulco":'kuaxomulko',
	"Cuayuca de Andrade":'De Andrade kuayuka',
	"Cuba":'cubakan',
	"Cuernavaca":'kuernavaka',
	"Cuetzala del Progreso":'kuetzala',
	"Cuetzalan del Progreso":'kuetzalan',
	"Cuilápam de Guerrero":'yaotekatl kuilapan',
	"Cutzamala de Pinzón":'pinzón kutzamala',
	"Cuyoaco":'kuyoako',
	"Dinamarca":'danezkan',
	"Domingo Arenas":'xalli Domingo',
	"Dominica":'zepachikome',
	"Ecatepec":'ekatepek',
	"Ecatzingo":'ekatzinko',
	"Ecuador":'tlaltikpakxihko',
	"Egipto":'ptahkalkan',
	"El Carmen Tequexquitla":'El Carmen tekexkitla',
	"El Salvador":'makixtekatl',
	"Eloxochitlán de Flores Magón":'Flores Magón eloxochitlan',
	"Eloxochitlán":'eloxochitlan',
	"Emiliano Zapata":'emiliano zapata',
	"Emiliano Zapata":'Emiliano Zapata',
	"Emiratos Árabes Unidos":'emirkan',
	"Epatlán":'epatlan',
	"Eritrea":'rojokanatlan',
	"Eslovaquia":'tokauilkan',
	"Eslovenia":'tokaihtokan',
	"España":'kaxtilan',
	"Españita":'españita',
	"Esperanza":'chiayotl',
	"Estados Unidos":'miktlananauak',
	"Estonia":'estikan',
	"Esuatini":'suazikan',
	"Etiopía":'tlatlaxayakan',
	"Filipinas":'felipekan',
	"Finlandia":'fineskan',
	"Fiyi":'viti',
	"Florencio Villarreal":'florencio villarreal',
	"Francia":'francokan',
	"Francisco Z. Mena":'Francisco Z. Mena',
	"Gabón":'ueyikotontli',
	"Gambia":'gambiakan',
	"General Felipe Ángeles":'General Felipe Ángeles',
	"Georgia":'tlaltekitikan',
	"Ghana":'yaotekuhkan',
	"Granada":'granadakan',
	"Grecia":'melauakan',
	"Guadalupe Victoria":'Guadalupe Victoria',
	"Guadalupe":'Guadalupe',
	"Guatemala":'kuauhtemalan',
	"Guinea Ecuatorial":'xihtliltik',
	"Guinea":'tliltikan',
	"Guinea-Bisáu":'tliltik-bisaukan',
	"Guyana":'miak-akan',
	"Haití":'ueyiktepekan',
	"Hermenegildo Galeana":'Hermenegildo Galeana',
	"Honduras":'yayauhkan',
	"Honey":'Honey',
	"Huamantla":'uamantla',
	"Huamuxtitlán":'uamuxtitlan',
	"Huaquechula":'uakechula',
	"Huatlatlauca":'uatlatlauka',
	"Huauchinango":'uauchinanko',
	"Huautla de Jiménez":'uautla de Jiménez',
	"Huehuetla":'ueuetla',
	"Huehuetlán el Chico":'piltzin ueuetlan',
	"Huehuetlán el Grande":'ueyikueuetlan',
	"Huehuetoca":'ueuetoka',
	"Huejotzingo":'uexotzinko',
	"Hueyapan":'ueyapan',
	"Hueyapan":'ueyapan',
	"Hueyotlipan":'ueyotlipan',
	"Hueypoxtla":'ueypoxtla',
	"Hueytamalco":'ueytamalko',
	"Hueytlalpan":'ueytlalpan',
	"Huitzilac":'uitzilak',
	"Huitzilan de Serdán":' De Serdán uitzilan',
	"Huitziltepec":'uitziltepek',
	"Huitzuco de los Figueroa":'uitzuko',
	"HuixquiLucan":'uixkilukan',
	"Hungría":'mahtlakmazeualkan',
	"Igualapa":'iualapa',
	"Iliatenco":'iliatenko',
	"India":'atenkokan',
	"Indonesia":'anepantlalli',
	"Irak":'tzintlankan',
	"Irlanda":'eriutlalkan',
	"Irán":'ariotlalkan',
	"Islandia":'zezeknepanatlan',
	"Islas Marshall":'zezeknepantlanmarshallkan',
	"Islas Salomón":'zezeknepantlansalomónkan',
	"Israel":'tlanemonyauzkan',
	"Italia":'yolkakan',
	"Ixcamilpa de Guerrero":'Guerrero ixkamilpa',
	"Ixcaquixtla":'ixkakixtla',
	"Ixcateopan de Cuauhtémoc":'kuautemok ixkateopan',
	"Ixpantepec Nieves":'zezek ixpantepek',
	"Ixtacamaxtitlán":'ixtakamaxtitlan',
	"Ixtacuixtla de Mariano Matamoros":'Mariano Matamoros ixtakuixtla',
	"IxtapaLuca":'ixtapaluka',
	"Ixtapan":'ixtapan',
	"Ixtenco":'ixtenko',
	"Ixtepec":'ixtepek',
	"Ixtlahuaca":'ixtlauaka',
	"Ixtlán de Juárez":'Juárez ixtlan',
	"Izúcar de Matamoros":'Izúcar de Matamoros',
	"Jalpan":'xalpan',
	"Jaltenco":'xaltenko',
	"Jamaica":'akuaukan',
	"Jantetelco":'xantetelko',
	"Japón":'tonal-ixuhtzin',
	"Jilotepec":'xilotepek',
	"Jilotzingo":'xilotzinko',
	"Jiquipilco":'xikipilko',
	"Jiutepec":'xiutepek',
	"Jocotitlán":'xokotitlan',
	"Jojutla":'xoxutla',
	"Jolalpan":'xolalpan',
	"Jonacatepec de Leandro Valle":'xonakatepek de leandro valle',
	"Jonotla":'xonotla',
	"Jopala":'xopala',
	"Joquicingo":'xokitzinko',
	"Jordania":'acholkan',
	"Juan C. Bonilla":'Juan C. Bonilla',
	"Juan Galindo":'Juan Galindo',
	"Juan N. Méndez":'Juan N. Méndez',
	"Juan R. Escudero":'Juan R. chimaltekatl',
	"Juchitepec":'xuchitepek',
	"Juchitán":'iztakxochitlan',
	"Kazajistán":'nehemikan',
	"Kenia":'kenitepekan',
	"Kirguistán":'kirguistlalkan',
	"Kiribati":'hilberts',
	"Kuwait":'chikauapilko',
	"La Magdalena Tlaltelulco":'La Magdalena tlaltelulko',
	"La Magdalena Tlatlauquitepec":'tlatlaukitepek La Magdalena',
	"Lafragua":'Lafragua',
	"Laos":'laokan',
	"Leonardo Bravo":'Leonardo Bravo',
	"Lesoto":'sothokan',
	"Letonia":'letónkan',
	"Liberia":'makixkan',
	"Libia":'libukan',
	"Libres":'makixtik',
	"Liechtenstein":'liechtensteinkan',
	"Lituania":'lituaniakan',
	"Los Reyes de Juárez":'Los Reyes de Juárez',
	"Luxemburgo":'chikauapilkan',
	"Lázaro Cárdenas":'Lázaro Cárdenas',
	"Líbano":'iztak-kan',
	"Macedonia del Norte":'miktlanmacedoniakan',
	"Madagascar":'madagascartlalkan',
	"Magdalena Apasco":'Magdalena apazko',
	"Magdalena Jaltepec":'Magdalena xaltepek',
	"Magdalena Mixtepec":'Magdalena mixtepek',
	"Magdalena Ocotlán":'Magdalena okotlan',
	"Magdalena Teitipac":'Magdalena teitipak',
	"Magdalena Tequisistlán":'Magdalena tekizistlan',
	"Magdalena Tlacotepec":'Magdalena tlakotepek',
	"Malasia":'malayokan',
	"Malaui":'tlekan',
	"Maldivas":'maldivaskan',
	"Malinalco":'malinalko',
	"Malinaltepec":'malinaltepek',
	"Malta":'achkan',
	"Malí":'ueyikyolkan',
	"Marquelia":'marquelia',
	"Marruecos":'teotlalkan',
	"Mauricio":'tlilkan',
	"Mauritania":'tliltikan',
	"Mazapiltepec de Juárez":'mazapiltepek de Juárez',
	"Mazatecochco de José María Morelos":'José María Morelos mazatekochko',
	"Mazatepec":'mazatepek',
	"Mazatlán Villa de Flores":'xochtlauamazatlan',
	"Metepec":'metepek',
	"Metlatónoc":'metlatonok',
	"Mexicaltzingo":'mexikaltzinko',
	"Miacatlán":'miakatlan',
	"Miahuatlán de Porfirio Díaz":'Porfirio Díaz miauatlan',
	"Micronesia":'nepantlatlan',
	"Mixtla":'mixtla',
	"Mochitlán":'mochitlan',
	"Molcaxac":'molkaxak',
	"Moldavia":'tehkan',
	"Mongolia":'mongolkan',
	"Montenegro":'tliltiktepekan',
	"Mozambique":'kuikan',
	"Muñoz de Domingo Arenas":'Muñoz de Domingo Arenas',
	"Mártir de Cuilapan":'kuilapan',
	"Mártires de Tacubaya":'ixkouantlapakoyan',
	"México Tenochtitlán":'mexihko tenochtitlan',
	"México":'mexihko',
	"México-Tenochtitlán":'mexihko-tenochtitlan',
	"Mónaco":'kalkan',
	"Namibia":'atenkuikan',
	"Nanacamilpa de Mariano Arista":'Mariano Arista nanakamilpa',
	"Natívitas":'natívitas',
	"Naucalpan":'naukalpan',
	"Naupan":'naupan',
	"Nauru":'naurukan',
	"Nauzontla":'nauzontla',
	"Nealtican":'nealtikan',
	"Nejapa de Madero":'kuaunexapa',
	"Nepal":'nepalkan',
	"Nextlalpan":'nextlalpan',
	"Nezahualcóyotl":'nezaualkoyotl',
	"Nicaragua":'nikanauak',
	"Nicolás Bravo":'Nicolás Bravo',
	"Nigeria":'tlilkan',
	"Nopaltepec":'nopaltepek',
	"NopaLucan":'nopalukan',
	"Noruega":'miktlanohkan',
	"Nueva Zelanda":'zelandayankuikan',
	"Níger":'tliltiko',
	"Ocotepec":'okotepek',
	"Ocotlán de Morelos":'Morelos okotlan',
	"Ocoyoacac":'okoyoakak',
	"Ocoyucan":'okoyukan',
	"Ocuilan":'okuilan',
	"Ocuituco":'okuituko',
	"Olinalá":'olinala',
	"Olintla":'olintla',
	"Ometepec":'ometepek',
	"Omán":'omankan',
	"Oriental":'oriental',
	"Otumba":'otumba',
	"Otzoloapan":'otzoloapan',
	"Otzolotepec":'otzolotepek',
	"Ozumba":'ozumba',
	"Pahuatlán":'pauatlan',
	"Pakistán":'pakiskan',
	"Palaos":'belaukan',
	"Palestina":'filisteokan',
	"Palmar de Bravo":'Palmar de Bravo',
	"Panamá":'panamakan',
	"Panotla":'panotla',
	"Pantepec":'pantepek',
	"Papalotla de Xicohténcatl":'xikoténkatl papalotla',
	"Papalotla":'papalotla',
	"Papúa Nueva Guinea":'papúa yankuik guinea',
	"Paraguay":'atlan-ualakan',
	"Países Bajos":'tzintlalkan',
	"Pedro Ascencio Alquisiras":'Pedro Ascencio Alquisiras',
	"Perú":'birukan',
	"Petatlán":'petatlan',
	"Petlalcingo":'petlaltzinko',
	"Piaxtla":'piaxtla',
	"Pilcaya":'pilkaya',
	"Polonia":'tlauatekan',
	"Portugal":'atlamik',
	"Puebla":'puebla',
	"Puente de Ixtla":'puente de ixtla',
	"Pungarabato":'pungarabato',
	"Quecholac":'kecholak',
	"Quechultenango":'kechultenanko',
	"Quimixtlán":'kimixtlan',
	"Rafael Lara Grajales":'Rafael Lara Grajales',
	"Reino Unido":'tlalkan-uanik',
	"República Centroafricana":'africaxihkan',
	"República Checa":'checokan',
	"República del Congo":'kongokan',
	"República Democrática del Congo":'kongokan',
	"República Dominicana":'Santozeilhuitl',
	"Ruanda":'ruandakan',
	"Rumania":'romanokan',
	"Rusia":'ruskan',
	"Samoa":'samoakan',
	"San Agustín Amatengo":'San Agustín amatenko',
	"San Agustín Atenango":'San Agustín atenanko',
	"San Agustín Chayuco":'San Agustín chayuko',
	"San Agustín Etla":'San Agustín etla',
	"San Agustín Loxicha":'San Agustín loxicha',
	"San Andrés Cholula":'San Andrés cholula',
	"San Andrés Huaxpaltepec":'San Andrés uaxpaltepek',
	"San Andrés Ixtlahuaca":'San Andrés ixtlauaka',
	"San Andrés Teotilálpam":'San Andrés teotilalpan',
	"San Antonino Castillo Velasco":'San Antonino Castillo Velasco',
	"San Antonino el Alto":'San Antonino el Alto',
	"San Antonio Cañada":'San Antonio Cañada',
	"San Baltazar Chichicápam":'San Baltazar chichikapan',
	"San Bartolo Coyotepec":'San bartolo koyotepek',
	"San Bartolo Soyaltepec":'San bartolo zoyaltepek',
	"San Bernardo Mixtepec":'San bernardo mixtepek',
	"San Blas Atempa":'San blas atempa',
	"San Cristóbal Amatlán":'San cristóbal amatlan',
	"San Cristóbal Amoltepec":'San cristóbal amoltepek',
	"San Damián Texóloc":'San Damián texólok',
	"San Diego la Mesa Tochimiltzingo":'San Diego la Mesa tochimiltzinko',
	"San Dionisio Ocotepec":'San dionisio okotepek',
	"San Felipe Jalapa de Díaz":'San felipe xalapa de díaz',
	"San Felipe Tejalápam":'San felipe texalapan',
	"San Felipe Teotlalcingo":'San Felipe teotlaltzinko',
	"San Felipe Tepatlán":'San Felipe tepatlan',
	"San Francisco Cahuacuá":'San francisco kauakua',
	"San Francisco Huehuetlán":'San francisco ueuetlan',
	"San Francisco Ixhuatán":'San francisco ixuatan',
	"San Francisco Ozolotepec":'San francisco ozolotepek',
	"San Francisco Telixtlahuaca":'San francisco telixtlauaka',
	"San Francisco Tetlanohcan":'San Francisco tetlanohkan',
	"San Gabriel Chilac":'San Gabriel chilak',
	"San Gregorio Atzompa":'San Gregorio atzompa',
	"San Jerónimo Tecuanipan":'San Jerónimo tekuanipan',
	"San Jerónimo Tecóatl":'San jerónimo tekoatl',
	"San Jerónimo Tlacochahuaya":'San jerónimo tlakochauaya',
	"San Jerónimo Xayacatlán":'San Jerónimo xayakatlan',
	"San Jerónimo Zacualpan":'San Jerónimo zakualpan',
	"San José Chiapa":'San José chiapa',
	"San José Chiltepec":'San josé chiltepek',
	"San José Miahuatlán":'San José miauatlan',
	"San José Teacalco":'San José teakalko',
	"San José Tenango":'San josé tenanko',
	"San Juan Atenco":'San Juan atenko',
	"San Juan Atepec":'San Juan atepek',
	"San Juan Atzompa":'San Juan atzompa',
	"San Juan Bautista Atatlahuca":'San Juan Bautista atatlauka',
	"San Juan Bautista Coixtlahuaca":'San Juan Bautista koixtlauaka',
	"San Juan Bautista Cuicatlán":'San Juan Bautista kuikatlan',
	"San Juan Bautista Jayacatlán":'San Juan Bautista xayakatlan',
	"San Juan Bautista Tlachichilco":'San Juan Bautista tlachichilko',
	"San Juan Bautista Tuxtepec":'San Juan Bautista tuxtepek',
	"San Juan Chilateca":'San Juan chilateka',
	"San Juan Coatzóspam":'San Juan koatzospan',
	"San Juan Huactzinco":'San Juan uaktzinko',
	"San Juan Ihualtepec":'San Juan iualtepek',
	"San Juan Lachigalla":'San Juan lachigalla',
	"San Juan Mazatlán":'San Juan mazatlan',
	"San Juan Mixtepec":'San Juan mixtepek',
	"San Juan Ozolotepec":'San Juan ozolotepek',
	"San Juan Petlapa":'San Juan petlapa',
	"San Juan Teitipac":'San Juan teitipak',
	"San Juan Tepeuxila":'San Juan tepeuxila',
	"San Lorenzo Albarradas":'San Lorenzo albarradas',
	"San Lorenzo Axocomanitla":'San Lorenzo axokomanitla',
	"San Lorenzo Cacaotepec":'San Lorenzo kakaotepek',
	"San Lorenzo Texmelúcan":'San Lorenzo texmelukan',
	"San Lucas Ojitlán":'San Lucas oxitlan',
	"San Lucas Tecopilco":'San Lucas tekopilko',
	"San Lucas Zoquiápam":'San Lucas zokiapan',
	"San Marcos":'San Marcos',
	"San Marino":'marinuskan',
	"San Martín Huamelúlpam":'San Martín uamelulpan',
	"San Martín Itunyoso":'San Martín Itunyoso',
	"San Martín Lachilá":'San Martín Lachila',
	"San Martín TexmeLucan":'San Martín texmelukan',
	"San Martín Totoltepec":'San Martín totoltepek',
	"San Martín Toxpalan":'San Martín toxpalan',
	"San Mateo Etlatongo":'San Mateo etlatonko',
	"San Mateo Nejápam":'San Mateo nexapan',
	"San Mateo Peñasco":'San Mateo peñasco',
	"San Mateo Piñas":'San Mateo piñas',
	"San Mateo Yoloxochitlán":'San Mateo yoloxochitlan',
	"San Matías Tlalancaleca":'San Matías tlalankaleka',
	"San Miguel Amatitlán":'San Miguel amatitlan',
	"San Miguel Amatlán":'San Miguel amatlan',
	"San Miguel Coatlán":'San Miguel koatlan',
	"San Miguel Ejutla":'San Miguel exutla',
	"San Miguel Huautla":'San Miguel uautla',
	"San Miguel Ixitlán":'San Miguel ixitlan',
	"San Miguel Mixtepec":'San Miguel mixtepek',
	"San Miguel Panixtlahuaca":'San Miguel panixtlauaka',
	"San Miguel Quetzaltepec":'San Miguel ketzaltepek',
	"San Miguel Tecomatlán":'San Miguel tekomatlan',
	"San Miguel Tenango":'San Miguel tenanko',
	"San Miguel Tlacamama":'San Miguel tlakamama',
	"San Miguel Tlacotepec":'San Miguel tlakotepek',
	"San Miguel Totolapan":'totolapan',
	"San Miguel Xoxtla":'San Miguel xoxtla',
	"San Nicolás Buenos Aires":'San Nicolás kualehekatl',
	"San Nicolás de los Ranchos":'San Nicolás de los Ranchos',
	"San Nicolás":'San nicolás',
	"San Pablo Anicano":'San Pablo Anicano',
	"San Pablo Coatlán":'San Pablo koatlan',
	"San Pablo del Monte":'San Pablo del monte',
	"San Pablo Etla":'San Pablo etla',
	"San Pablo Huixtepec":'San Pablo uixtepek',
	"San Pablo Macuiltianguis":'San Pablo makuiltiankiz',
	"San Pedro Amuzgos":'San Pedro amuzgos',
	"San Pedro Apóstol":'San Pedro apóstol',
	"San Pedro Atoyac":'San Pedro atoyak',
	"San Pedro Cholula":'San Pedro cholula',
	"San Pedro Huamelula":'San Pedro uamelula',
	"San Pedro Ixcatlán":'San Pedro ixkatlan',
	"San Pedro Jicayán":'San Pedro xikayan',
	"San Pedro Mixtepec":'San Pedro mixtepek',
	"San Pedro Ocotepec":'San Pedro okotepek',
	"San Pedro Pochutla":'San Pedro pochutla',
	"San Pedro Teozacoalco":'San Pedro teozakoalko',
	"San Pedro Tidaá":'San Pedro tidaá',
	"San Pedro Totolápam":'San Pedro totolapan',
	"San Pedro y San Pablo Teposcolula":'San Pedro y San Pablo tepozkolula',
	"San Pedro Yeloixtlahuaca":'San Pedro yeloixtlauaka',
	"San Salvador el Seco":'San Salvador el Seco',
	"San Salvador el Verde":'San Salvador el Verde',
	"San Salvador Huixcolotla":'San Salvador uixkolotla',
	"San Sebastián Coatlán":'San Sebastián koatlan',
	"San Sebastián Tecomaxtlahuaca":'San Sebastián tekomaxtlauaka',
	"San Sebastián Tlacotepec":'San Sebastián tlakotepek',
	"Sanctórum de Lázaro Cárdenas":'Sanctórum de Lázaro Cárdenas',
	"Santa Ana Cuauhtémoc":'Santa Ana kuautémok',
	"Santa Ana NopaLucan":'Santa Ana nopalukan',
	"Santa Ana Tavela":'Santa Ana Tavela',
	"Santa Ana Tlapacoyan":'Santa Ana tlapakoyan',
	"Santa Apolonia Teacalco":'Santa Apolonia teakalko',
	"Santa Catarina Ayometla":'Santa Catarina ayometla',
	"Santa Catarina Cuixtla":'Santa Catarina kuixtla',
	"Santa Catarina Ixtepeji":'Santa Catarina ixtepexi',
	"Santa Catarina Juquila":'Santa Catarina xukila',
	"Santa Catarina Loxicha":'Santa Catarina loxicha',
	"Santa Catarina Mechoacán":'Santa Catarina mechoakan',
	"Santa Catarina Minas":'Santa Catarina minas',
	"Santa Catarina Quiané":'Santa Catarina kiané',
	"Santa Catarina Ticuá":'Santa Catarina tikua',
	"Santa Catarina Tlaltempan":'Santa Catarina tlaltempan',
	"Santa Cruz Acatepec":'Santa Cruz akatepek',
	"Santa Cruz Amilpas":'Santa Cruz amilpas',
	"Santa Cruz del Rincón":'Santa Cruz del Rincón',
	"Santa Cruz Mixtepec":'Santa Cruz mixtepek',
	"Santa Cruz Nundaco":'Santa Cruz nundako',
	"Santa Cruz Papalutla":'Santa Cruz papalutla',
	"Santa Cruz Quilehtla":'Santa Cruz kilehtla',
	"Santa Cruz Tacache de Mina":'Santa Cruz takache de mina',
	"Santa Cruz Tacahua":'Santa Cruz takaua',
	"Santa Cruz Tayata":'Santa Cruz tayata',
	"Santa Cruz Tlaxcala":'Santa Cruz tlaxkala',
	"Santa Cruz Xitla":'Santa Cruz xitla',
	"Santa Cruz Xoxocotlán":'Santa Cruz xoxokotlan',
	"Santa Gertrudis":'Santa gertrudis',
	"Santa Inés Ahuatempan":'Santa Inés auatempan',
	"Santa Inés del Monte":'Santa Inés del monte',
	"Santa Isabel Cholula":'Santa Isabel cholula',
	"Santa Isabel Xiloxoxtla":'Santa Isabel xiloxoxtla',
	"Santa Lucía del Camino":'Santa Lucía del Camino',
	"Santa Lucía Miahuatlán":'Santa Lucía miauatlan',
	"Santa María Apazco":'Santa María apazko',
	"Santa María Atzompa":'Santa María atzompa',
	"Santa María Chilchotla":'Santa María chilchotla',
	"Santa María Chimalapa":'Santa María chimalapa',
	"Santa María Colotepec":'Santa María kolotepek',
	"Santa María Ecatepec":'Santa María ekatepek',
	"Santa María Huatulco":'Santa María uatulko',
	"Santa María Huazolotitlán":'Santa María uazolotitlan',
	"Santa María Ixcatlán":'Santa María ixkatlan',
	"Santa María Mixtequilla":'Santa María mixtekilla',
	"Santa María Nativitas":'Santa María nativitas',
	"Santa María Ozolotepec":'Santa María ozolotepek',
	"Santa María Pápalo":'Santa María papalo',
	"Santa María Tecomavaca":'Santa María tekomavaka',
	"Santa María Temaxcalapa":'Santa María temaxkalapa',
	"Santa María Teopoxco":'Santa María teopoxko',
	"Santa María Tlalixtac":'Santa María tlalixtak',
	"Santa María Tonameca":'Santa María tonameka',
	"Santiago Amoltepec":'Santiago amoltepek',
	"Santiago Apoala":'Santiago apoala',
	"Santiago Atitlán":'Santiago atitlan',
	"Santiago Ayuquililla":'Santiago ayukililla',
	"Santiago Cacaloxtepec":'Santiago kakaloxtepek',
	"Santiago Chazumba":'Santiago chazumba',
	"Santiago Huajolotitlán":'Santiago uaxolotitlan',
	"Santiago Huauclilla":'Santiago uauklilla',
	"Santiago Ihuitlán Plumas":'Santiago iuitlan plumas',
	"Santiago Ixcuintepec":'Santiago ixkuintepek',
	"Santiago Jocotepec":'Santiago xokotepek',
	"Santiago Juxtlahuaca":'Santiago xuxtlauaka',
	"Santiago Lachiguiri":'Santiago lachiguiri',
	"Santiago Matatlán":'Santiago matatlan',
	"Santiago Miahuatlán":'Santiago miauatlan',
	"Santiago Nacaltepec":'Santiago nakaltepek',
	"Santiago Nejapilla":'Santiago nexapilla',
	"Santiago Pinotepa Nacional":'Santiago Pinotepa Nacional',
	"Santiago Suchilquitongo":'Santiago xochilkitonko',
	"Santiago Tamazola":'Santiago Tamazola',
	"Santiago Tenango":'Santiago tenanko',
	"Santiago Tepetlapa":'Santiago tepetlapa',
	"Santiago Tetepec":'Santiago tetepek',
	"Santiago Texcalcingo":'Santiago texkaltzinko',
	"Santiago Tilantongo":'Santiago tilantonko',
	"Santiago Xanica":'Santiago xanika',
	"Santo Domingo Chihuitán":'Santo Domingo chiuitan',
	"Santo Domingo Ixcatlán":'Santo Domingo ixkatlan',
	"Santo Domingo Nuxaá":'Santo Domingo nuxaá',
	"Santo Domingo Petapa":'Santo Domingo petapa',
	"Santo Domingo Tehuantepec":'Santo Domingo teuantepek',
	"Santo Domingo Tepuxtepec":'Santo Domingo tepuxtepek',
	"Santo Domingo Tlatayápam":'Santo Domingo tlatayapan',
	"Santo Domingo Tonaltepec":'Santo Domingo tonaltepek',
	"Santo Domingo Tonalá":'Santo Domingo tonala',
	"Santo Domingo Xagacía":'Santo Domingo xagacía',
	"Santo Domingo Yanhuitlán":'Santo Domingo yaniuitlan',
	"Santo Tomás Hueyotlipan":'Santo Tomás ueyotlipan',
	"Santo Tomás Jalieza":'Santo Tomás xalieza',
	"Santo Tomás Mazaltepec":'Santo Tomás mazaltepek',
	"Santos Reyes Nopala":'Santos Reyes nopala',
	"Senegal":'senegalkan',
	"Serbia":'serbiokan',
	"Seychelles":'sechelleskan',
	"Sierra Leona":'tzontekuanikan',
	"Silacayoápam":'zilakayoapan',
	"Singapur":'tzontekuanialtepetl',
	"Siria":'siriakan',
	"Soltepec":'zoltepek',
	"Somalia":'zomalikan',
	"Sri Lanka":'ketzalnepantla',
	"Sudáfrica":'uitztlampa-africa',
	"Sudán del Sur":'uitztlampakan',
	"Sudán":'tliltikkan',
	"Suecia":'suecokan',
	"Suiza":'schwyzkan',
	"Sultepec":'zultepek',
	"Surinam":'uitztlampankan',
	"Tailandia":'taikan',
	"Tanetze de Zaragoza":'Tanetze de Zaragoza',
	"Taxco de Alarcón":'tlachko',
	"Tecali de Herrera":'tekali',
	"Tecamachalco":'tekamachalko',
	"Tecoanapa":'tekoanapa',
	"Tecomatlán":'tekomatlan',
	"Tecámac":'tekamak',
	"Tehuacán":'teuakan',
	"Tehuitzingo":'teuitzinko',
	"Tejupilco":'tehupilko',
	"Teloloapan":'teloloapan',
	"Temamatla":'temamatla',
	"Temascalapa":'temazkalapa',
	"Temascalcingo":'temazkaltzinko',
	"Temascaltepec":'temazkaltepek', # Tierra de los matlatzinka
	"Temixco":'temixko',
	"Temoac":'temoak',
	"Tenampulco":'tenampulko',
	"Tenancingo":'tenantzinko',
	"Tenancingo":'tenantzinko',
	"Tenango":'tenanko',
	"Tenochtitlán":'tenochtitlan',
	"Teolocholco":'teolocholko',
	"Teoloyucan":'teoloyukan',
	"Teopantlán":'teopantlan',
	"Teotihuacán":'teotiuakan',
	"Teotitlán de Flores Magón":'Flores Magón teotitlan',
	"Teotitlán del Valle":'del Valle teotitlan',
	"Teotlalco":'teotlalko',
	"Teotongo":'teotonko',
	"Tepalcingo":'tepaltzinko',
	"Tepanco de López":'tepanko',
	"Tepango de Rodríguez":'tepanko',
	"Tepatlaxco de Hidalgo":'tepatlaxko',
	"Tepeaca":'tepeaka',
	"Tepecoacuilco de Trujano":'tepekoakuilko',
	"Tepelmeme Villa de Morelos":'Villa de Morelos tepelmeme',
	"Tepemaxalco":'tepemaxalko',
	"Tepeojuma":'tepeoxuma',
	"Tepetitla de Lardizábal":'Lardizábal tepetitla',
	"Tepetlaoxtoc":'tepetlaoxtok',
	"Tepetlixpa":'tepetlixpa',
	"Tepetzintla":'tepetzintla',
	"Tepexco":'tepexko',
	"Tepexi de Rodríguez":'tepexi',
	"Tepeyahualco de Cuauhtémoc":'kuauhtemok tepeyaualko',
	"Tepeyahualco":'tepeyaualko',
	"Tepeyanco":'tepeyanko',
	"Tepotzotlán":'tepotzotlan',
	"Tepoztlán":'tepoztlan',
	"Tequixquiac":'tekixkiak',
	"Terrenate":'terrenate',
	"Tetecala":'tetekala',
	"Tetela de Ocampo":'tetela de ocampo',
	"Tetela del Volcán":'tetela del volcán',
	"Teteles de Ávila Castillo":'teteles',
	"Tetipac":'tetipak',
	"Tetla de la Solidaridad":' De la solidaridad tetla',
	"Tetlatlahuca":'tetlatlauka',
	"Texcaltitlán":'texkaltitlan',
	"Texcalyacac":'texkalyakak',
	"Texcoco":'texkoko',
	"Teziutlán":'teziutlan',
	"Tezoatlán de Segura y Luna":'tezoatlan de segura y luna',
	"Tezoyuca":'tezoyuka',
	"Tianguismanalco":'tiankizmanalko',
	"Tianguistenco":'tiankiztenko',
	"Tilapa":'tilapa',
	"Timilpan":'timilpan',
	"Tixtla de Guerrero":'tixtla',
	"Tlachichuca":'tlachichuka',
	"Tlacoachistlahuaca":'tlakoachiztlauaka',
	"Tlacoapa":'tlakoapa',
	"Tlacolula de Matamoros":'tlakolula de Matamoros',
	"Tlacotepec de Benito Juárez":'tlakotepek',
	"Tlacuilotepec":'tlakuilotepek',
	"Tlahuapan":'tlauapan',
	"Tlalchapa":'tlalchapa',
	"Tlalixtac de Cabrera":'Cabrera tlalixtak',
	"Tlalixtaquilla de Maldonado":'tlalixtakilla',
	"Tlalmanalco":'tlalmanalko',
	"Tlalnepantla":'tlalnepantla',
	"Tlalnepantla":'tlalnepantla',
	"Tlaltenango":'tlaltenanko',
	"Tlaltizapán de Zapata":'tlaltizapan de zapata',
	"Tlanepantla":'tlanepantla',
	"Tlaola":'tlaola',
	"Tlapa de Comonfort":'tlapa',
	"Tlapacoya":'tlapakoya',
	"Tlapanalá":'tlapanala',
	"Tlapehuala":'tlapeuala',
	"Tlaquiltenango":'tlakiltenanko',
	"Tlatlauquitepec":'tlatlaukitepek',
	"Tlatlaya":'tlatlaya',
	"Tlaxcala":'tlaxkala',
	"Tlaxco":'tlaxko',
	"Tlaxco":'tlaxko',
	"Tlayacapan":'tlayakapan',
	"Tocatlán":'tokatlan',
	"Tochimilco":'tochimilko',
	"Tochtepec":'tochtepek',
	"Togo":'tenkotlakuitlapan',
	"ToLuca":'toluka',
	"Tonanitla":'tonanitla',
	"Tonatico":'tonatiko',
	"Tonga":'uitztlampan',
	"Totolac":'totolak',
	"Totolapan":'totolapan',
	"Totoltepec de Guerrero":'totoltepek',
	"Totontepec Villa de Morelos":'Villa de Morelos totontepek',
	"Tulcingo":'tultzinko',
	"Tultepec":'tultepek',
	"Tultitlán":'tultitlan',
	"Turquía":'turcokan',
	"Tuvalu":'chikoeyiuantiak',
	"Tuzamapan de Galeana":'tuzamapan de galeana',
	"Tzicatlacoyan":'tzikatlakoyan',
	"Tzompantepec":'tzompantepek',
	"Técpan de Galeana":'tekpan',
	"Ucrania":'tentlalkan',
	"Uganda":'bugandakan',
	"Uzbekistán":'uzbekokan',
	"Vanuatu":'nochipatotlalkan',
	"Venezuela":'veneciapil',
	"Vietnam":'vietkan',
	"Villa de Etla":'villa de etla',
	"Villa de Tamazulápam del Progreso":'Villa de tlamazulapan del Progreso',
	"Villa Tejúpam de la Unión":'Villa texupan de la Unión',
	"Xalatlaco":'xalatlako',
	"Xaloztoc":'xaloztok',
	"Xalpatláhuac":'xalpatlauak',
	"Xaltocan":'xaltokan',
	"Xayacatlán de Bravo":'xayakatlan',
	"Xicohtzinco":'xikotzinko',
	"Xicotepec":'xikotepek',
	"Xicotlán":'xikotlan',
	"Xiutetelco":'xiutetelko',
	"Xochiapulco":'xochiapulko',
	"Xochihuehuetlán":'xochiueuetlan',
	"Xochiltepec":'xochiltepek',
	"Xochistlahuaca":'xochiztlauaka',
	"Xochitepec":'xochitepek',
	"Xochitlán de Vicente Suárez":'xochitlan',
	"Xochitlán Todos Santos":'xochitlan',
	"Xonacatlán":'xonakatlan',
	"Xoxocotla":'xoxokotla',
	"Yaonáhuac":'yaonauak',
	"Yauhquemehcan":'yaukemehkan',
	"Yautepec":'yautepek',
	"Yecapixtla":'yekapixtla',
	"Yehualtepec":'yeualtepek',
	"Yemen":'yemenkan',
	"Yibuti":'yibutikan',
	"Yutanduchi de Guerrero":'Yutanduchi de Guerrero',
	"Zacapala":'zakapala',
	"Zacapoaxtla":'zakapoaxtla',
	"Zacatelco":'zakatelko',
	"Zacatepec":'zakatepek',
	"Zacatlán":'zakatlan',
	"Zacazonapan":'zakazonapan',
	"Zacualpan de Amilpas":'zakualpan de amilpas',
	"Zacualpan":'zakualpan',
	"Zambia":'zambezekan',
	"Zapotitlán de Méndez":'zapotitlan',
	"Zapotitlán Lagunas":'zapotitlan Lagunas',
	"Zapotitlán Palmas":'zapotitlan Palmas',
	"Zapotitlán Tablas":'zapotitlan',
	"Zapotitlán":'zapotitlan',
	"Zaragoza":'zaragoza',
	"Zautla":'zautla',
	"Zihuatanejo de Azueta":'ziuatlaneko',
	"Zihuateutla":'ziuateutla',
	"Zimatlán de Álvarez":'zimatlan de Álvarez',
	"Zimbabue":'tekaltin',
	"Zinacantepec":'zinakantepek',
	"Zinacatepec":'zinakatepek',
	"Zitlala":'zitlala',
	"Zitlaltepec de Trinidad Sánchez Santos":'Trinidad Sánchez Santos zitlaltepek',
	"Zongozotla":'zongozotla',
	"Zoquiapan":'zokiapan',
	"Zoquitlán":'zokitlan',
	"Zumpahuacán":'zumpauakan',
	"Zumpango":'zumpanko',
	"Ánimas Trujano":'Ánimas Trujano',
	"Ñuu Savi":'ñuu savi',
	"Anáhuac":'anauak',

	"oxtotilpan":'oxtotilpan'

#	"Eduardo Neri":'eduardo neri',
#	"General Canuto A. Neri":'general canuto a. neri',
#	"General Heliodoro Castillo":'general heliodoro castillo',
#	"Heroica Ciudad de Ejutla de Crespo":'heroica ciudad de exutla de crespo',
#	"Heroica Ciudad de Huajuapan de León":'heroica ciudad de uaxuapan de león',
#	"Heroica Ciudad de Juchitán de Zaragoza":'heroica ciudad de xuchitan de zaragoza',
#	"Heroica Ciudad de Tlaxiaco":'heroica ciudad de tlaxiako',
#	"Iguala de la Independencia":'iuala de la Independencia',
#	"José Joaquín de Herrera":'josé joaquín de herrera',
#	"La Unión de Isidoro Montes de Oca":'La unión de Isidoro Montes de Oca',
#	"Las Vigas":'las vigas',
#	"San Cristóbal y Nieves":'San cristóbal y nieves',
#	"San Luis Acatlán":'San Luis akatlan',
#	"San Vicente y las Granadinas":'San vicente y las granadinas',
#	"Santa Lucía":'Santa lucía',
#	"Santo Tomé y Príncipe":'Santo tomé y príncipe',
#	"Tanzania":'tanganica y zanzíbar',
#	"Tayikistán":'tayikokan',
#	"Timor Oriental":'oriente oriental',
#	"Trinidad y Tobago":'trinidad y tobago',
#	"Turkmenistán":'turcomanokan',
#	"Túnez":'túnezkan',
#	"Uruguay":'uruguaykan',
#	"Venustiano Carranza":'venustiano carranza',
#	"Vicente Guerrero":'vicente guerrero',
#	"Zirándaro":'zirándaro',
}