tlalkan_SP_NTL = {
	"achkan":'Malta',
	"acholkan":'Jordania',
	"afgankan":'Afganistán',
	"africaxihkan":'República Centroafricana',
	"ako":'Chad',
	"akuaukan":'Jamaica',
	"albaniakan":'Albania',
	"altepetl":'Canadá',
	"anauak":'Anáhuac',
	"andorrakan":'Andorra',
	"anepantla":'Argelia',
	"anepantlalli":'Indonesia',
	"angolakan":'Angola',
	"antigua y barbuda":'Antigua y Barbuda',
	"argentumkan":'Argentina',
	"ariotlalkan":'Irán',
	"armeniakan":'Armenia',
	"atenkokan":'India',
	"atenkuikan":'Namibia',
	"atlamik":'Portugal',
	"atlan-ualakan":'Paraguay',
	"atropatezkan":'Azerbaiyán',
	"baamakan":'Bahamas',
	"bamarkan":'Birmania',
	"belaukan":'Palaos',
	"belgakan":'Bélgica',
	"belicekan":'Belice',
	"bengalakan":'Bangladés',
	"beninkan":'Benín',
	"birukan":'Perú',
	"bolivarkan":'Bolivia',
	"bosniduketlal":'Bosnia y Herzegovina',
	"bruneikan":'Brunéi',
	"bugandakan":'Uganda',
	"bulgarokan":'Bulgaria',
	"butankan":'Bután',
	"catarkan":'Catar',
	"chakaatenko":'Camerún',
	"checokan":'República Checa',
	"chikauapilkan":'Luxemburgo',
	"chikauapilko":'Kuwait',
	"chikoeyiuantiak":'Tuvalu',
	"chilkan":'Chile',
	"chiprekan":'Chipre',
	"cubakan":'Cuba',
	"danezkan":'Dinamarca',
	"emirkan":'Emiratos Árabes Unidos',
	"eriutlalkan":'Irlanda',
	"estikan":'Estonia',
	"felipekan":'Filipinas',
	"filisteokan":'Palestina',
	"fineskan":'Finlandia',
	"francokan":'Francia',
	"gambiakan":'Gambia',
	"granadakan":'Granada',
	"hilberts":'Kiribati',
	"integrokan":'Burkina Faso',
	"iztak-kan":'Líbano',
	"jermanikan":'Alemania',
	"kalkan":'Mónaco',
	"kambukan":'Camboya',
	"kaxtilan":'España',
	"kenitepekan":'Kenia',
	"ketzalnepantla":'Sri Lanka',
	"kinkan":'China',
	"kirguistlalkan":'Kirguistán',
	"kolonkan":'Colombia',
	"kongokan":'República del Congo',
	"kongokan":'República Democrática del Congo',
	"kroatakan":'Croacia',
	"kuauhtemalan":'Guatemala',
	"kuikan":'Mozambique',
	"laokan":'Laos',
	"letónkan":'Letonia',
	"libukan":'Libia',
	"liechtensteinkan":'Liechtenstein',
	"lituaniakan":'Lituania',
	"madagascartlalkan":'Madagascar',
	"mahtlakmazeualkan":'Hungría',
	"makixkan":'Liberia',
	"makixtekatl":'El Salvador',
	"malayokan":'Malasia',
	"maldivaskan":'Maldivas',
	"marinuskan":'San Marino',
	"melauakan":'Grecia',
	"metznepantlan":'Comoras',
	"mexihko tenochtilan":'México Tenochtitlán',
	"mexihko":'México',
	"mexihko-tenochtilan":'México-Tenochtitlán',
	"miak-akan":'Guyana',
	"miktlananauak":'Estados Unidos',
	"miktlankuakualtzin":'Corea del Norte',
	"miktlanmacedoniakan":'Macedonia del Norte',
	"miktlanohkan":'Noruega',
	"mongolkan":'Mongolia',
	"naurukan":'Nauru',
	"nehemikan":'Kazajistán',
	"nepalkan":'Nepal',
	"nepantlatlan":'Micronesia',
	"nikanauak":'Nicaragua',
	"nochipatotlalkan":'Vanuatu',
	"omankan":'Omán',
	"omeatlan":'Baréin',
	"pakiskan":'Pakistán',
	"palobrazilkan":'Brasil',
	"panamakan":'Panamá',
	"papúa yankuik guinea":'Papúa Nueva Guinea',
	"ptahkalkan":'Egipto',
	"rojokanatlan":'Eritrea',
	"romanokan":'Rumania',
	"ruandakan":'Ruanda',
	"rundikan":'Burundi',
	"rus-iztakan":'Bielorrusia',
	"ruskan":'Rusia',
	"samoakan":'Samoa',
	"santozeilhuitl":'República Dominicana',
	"saudkan":'Arabia Saudita',
	"schwyzkan":'Suiza',
	"sechelleskan":'Seychelles',
	"senegalkan":'Senegal',
	"serbiokan":'Serbia',
	"siriakan":'Siria',
	"sothokan":'Lesoto',
	"suazikan":'Esuatini',
	"suecokan":'Suecia',
	"taikan":'Tailandia',
	"tehkan":'Moldavia',
	"tekalti":'Zimbabuen',
	"temazkaltepek":'Temazkaltépec',
	"tenatlan":'Costa Rica',
	"tenkotlakuitlapan":'Togo',
	"tenochtitlan":'Tenochtitlán',
	"tenomitl":'Costa de Marfil',
	"tentlalkan":'Ucrania',
	"teotlalkan":'Marruecos',
	"tlalkan-uanik":'Reino Unido',
	"tlaltekitikan":'Georgia',
	"tlaltikpakxihko":'Ecuador',
	"tlanemonyauzkan":'Israel',
	"tlatlaxayakan":'Etiopía',
	"tlauatekan":'Polonia',
	"tlekan":'Malaui',
	"tlilkan":'Mauricio',
	"tlilkan":'Nigeria',
	"tliltik-bisaukan":'Guinea-Bisáu',
	"tliltikan":'Guinea',
	"tliltikan":'Mauritania',
	"tliltikkan":'Sudán',
	"tliltiko":'Níger',
	"tliltiktepekan":'Montenegro',
	"tokaihtokan":'Eslovenia',
	"tokauilkan":'Eslovaquia',
	"tonal-ixuhtzin":'Japón',
	"tonalkizayan-altepetl":'Austria',
	"turcokan":'Turquía',
	"tzintlalkan":'Países Bajos',
	"tzintlankan":'Irak',
	"tzontekuanialtepetl":'Singapur',
	"tzontekuanikan":'Sierra Leona',
	"tzontenkouan":'Barbados',
	"tzuanakan":'Botsuana',
	"ueyikotontli":'Gabón',
	"ueyiktepekan":'Haití',
	"ueyikyolkan":'Malí',
	"uitzilkan":'Australia',
	"uitzilkuakualtzin":'Corea del Sur',
	"uitztlampa-africa":'Sudáfrica',
	"uitztlampakan":'Sudán del Sur',
	"uitztlampan":'Tonga',
	"uitztlampankan":'Surinam',
	"uzbekokan":'Uzbekistán',
	"vaticanaltepetl":'Ciudad del Vaticano',
	"veneciapil":'Venezuela',
	"vietkan":'Vietnam',
	"viti":'Fiyi',
	"xihtliltik":'Guinea Ecuatorial',
	"xoxohtikpak":'Cabo Verde',
	"yaotekuhkan":'Ghana',
	"yayauhkan":'Honduras',
	"yemenkan":'Yemen',
	"yibutikan":'Yibuti',
	"yolkakan":'Italia',
	"zambezekan":'Zambia',
	"zelandayankuikan":'Nueva Zelanda',
	"zepachikome":'Dominica',
	"zezeknepanatlan":'Islandia',
	"zezeknepantlanmarshallkan":'Islas Marshall',
	"zezeknepantlansalomónkan":'Islas Salomón',
	"zomalikan":'Somalia',
#	"oriente oriental":'Timor Oriental',
#	"san cristóbal y nieves":'San Cristóbal y Nieves',
#	"san vicente y las granadinas":'San Vicente y las Granadinas',
#	"santo tomé y príncipe":'Santo Tomé y Príncipe',
#	"tanganica y zanzíbar":'Tanzania',
#	"trinidad y tobago":'Trinidad y Tobago',
#	"tunezkan":'Túnez',
#	"turcomanokan":'Turkmenistán',
#	"uruguaykan":'Uruguay',
#	santa lucía":'Santa Lucía',
#	tayikokan":'Tayikistán',
}